<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="클로드">
<meta name="dcterms.date" content="2026-04-30">

<title>리뷰 ▷ D2GSL – 신록예찬’s Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5b48ee63c5e90d651e19f9ead4b448f1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">신록예찬’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DL2024/"> 
<span class="menu-text">DL2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/AP2023/"> 
<span class="menu-text">AP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/PP2024/"> 
<span class="menu-text">PP2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DV2023/"> 
<span class="menu-text">DV2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/MP2023/"> 
<span class="menu-text">MP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SC2024/"> 
<span class="menu-text">SC2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DS2022/"> 
<span class="menu-text">DS2022</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SP2023/"> 
<span class="menu-text">SP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/IR2021/"> 
<span class="menu-text">IR2021</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan/"> 
<span class="menu-text">yechan</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan2/"> 
<span class="menu-text">yechan2</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/miruetoto/yechan"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#d2gsl-self-supervised-dual-layer-structure-driven-graph-structure-learning" id="toc-d2gsl-self-supervised-dual-layer-structure-driven-graph-structure-learning" class="nav-link active" data-scroll-target="#d2gsl-self-supervised-dual-layer-structure-driven-graph-structure-learning">D2GSL: Self-supervised Dual-Layer Structure-Driven Graph Structure Learning</a>
  <ul class="collapse">
  <li><a href="#초록" id="toc-초록" class="nav-link" data-scroll-target="#초록">초록</a></li>
  <li><a href="#핵심어" id="toc-핵심어" class="nav-link" data-scroll-target="#핵심어">핵심어</a></li>
  </ul></li>
  <li><a href="#서론" id="toc-서론" class="nav-link" data-scroll-target="#서론">1 서론</a></li>
  <li><a href="#관련-연구" id="toc-관련-연구" class="nav-link" data-scroll-target="#관련-연구">2 관련 연구</a>
  <ul class="collapse">
  <li><a href="#그래프-신경망" id="toc-그래프-신경망" class="nav-link" data-scroll-target="#그래프-신경망">2.1 그래프 신경망</a></li>
  <li><a href="#그래프-구조-학습" id="toc-그래프-구조-학습" class="nav-link" data-scroll-target="#그래프-구조-학습">2.2 그래프 구조 학습</a></li>
  <li><a href="#그래프-대조-학습" id="toc-그래프-대조-학습" class="nav-link" data-scroll-target="#그래프-대조-학습">2.3 그래프 대조 학습</a></li>
  </ul></li>
  <li><a href="#문제-정의" id="toc-문제-정의" class="nav-link" data-scroll-target="#문제-정의">3 문제 정의</a></li>
  <li><a href="#방법론" id="toc-방법론" class="nav-link" data-scroll-target="#방법론">4 방법론</a>
  <ul class="collapse">
  <li><a href="#다중-채널-그래프-구조-학습" id="toc-다중-채널-그래프-구조-학습" class="nav-link" data-scroll-target="#다중-채널-그래프-구조-학습">4.1 다중 채널 그래프 구조 학습</a>
  <ul class="collapse">
  <li><a href="#의미-유사도-채널-그래프의-구성" id="toc-의미-유사도-채널-그래프의-구성" class="nav-link" data-scroll-target="#의미-유사도-채널-그래프의-구성">4.1.1 의미 유사도 채널 그래프의 구성</a></li>
  <li><a href="#스펙트럼-특징-채널-그래프의-구성" id="toc-스펙트럼-특징-채널-그래프의-구성" class="nav-link" data-scroll-target="#스펙트럼-특징-채널-그래프의-구성">4.1.2 스펙트럼 특징 채널 그래프의 구성</a></li>
  </ul></li>
  <li><a href="#이중-계층-네트워크-구조" id="toc-이중-계층-네트워크-구조" class="nav-link" data-scroll-target="#이중-계층-네트워크-구조">4.2 이중 계층 네트워크 구조</a></li>
  <li><a href="#결합-최적화" id="toc-결합-최적화" class="nav-link" data-scroll-target="#결합-최적화">4.3 결합 최적화</a></li>
  </ul></li>
  <li><a href="#실험" id="toc-실험" class="nav-link" data-scroll-target="#실험">5 실험</a>
  <ul class="collapse">
  <li><a href="#실험-설정" id="toc-실험-설정" class="nav-link" data-scroll-target="#실험-설정">5.1 실험 설정</a></li>
  <li><a href="#효과성-실험과-분석" id="toc-효과성-실험과-분석" class="nav-link" data-scroll-target="#효과성-실험과-분석">5.2 효과성 실험과 분석</a></li>
  <li><a href="#어블레이션-연구" id="toc-어블레이션-연구" class="nav-link" data-scroll-target="#어블레이션-연구">5.3 어블레이션 연구</a></li>
  <li><a href="#하이퍼파라미터-민감도" id="toc-하이퍼파라미터-민감도" class="nav-link" data-scroll-target="#하이퍼파라미터-민감도">5.4 하이퍼파라미터 민감도</a></li>
  </ul></li>
  <li><a href="#결론" id="toc-결론" class="nav-link" data-scroll-target="#결론">6 결론</a></li>
  <li><a href="#진술" id="toc-진술" class="nav-link" data-scroll-target="#진술">7 진술</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">리뷰 ▷ D2GSL</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>클로드 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 30, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>http://doi.org/10.32604/journal.2026.000000</p>
<p>ARTICLE</p>
<section id="d2gsl-self-supervised-dual-layer-structure-driven-graph-structure-learning" class="level1">
<h1>D2GSL: Self-supervised Dual-Layer Structure-Driven Graph Structure Learning</h1>
<p>Juncheng Zhang<span class="math inline">\(^{1,2}\)</span>, Xuhao Wei<span class="math inline">\(^{1,2}\)</span>, Xiaolei Gu<span class="math inline">\(^3\)</span>, Haixing Zhao<span class="math inline">\(^{4,*}\)</span>, Zhonglin Ye<span class="math inline">\(^{1,2,5,*}\)</span></p>
<p><span class="math inline">\(^1\)</span> School of Computer, Qinghai Normal University, Xining 810008, China <span class="math inline">\(^2\)</span> State Key Laboratory of Tibetan Intelligent, Xining 810008, China <span class="math inline">\(^3\)</span> Qinghai Provincial Public Security Department, Xining 810000, China <span class="math inline">\(^4\)</span> College of Intelligent Science and Engineering, Qinghai Minzu University, Xining 810007, China <span class="math inline">\(^5\)</span> Graduate School of Engineering, Nagasaki Institute of Applied Science, Nagasaki 851-0193, Japan *Corresponding Author: Haixing Zhao. Email: h.x.zhao@163.com, Zhonglin Ye. Email: yezhonglin@qhnu.edu.cn</p>
<p>Version March 30, 2026; submitted to Journal Not Specified</p>
<section id="초록" class="level2">
<h2 class="anchored" data-anchor-id="초록">초록</h2>
<p>그래프 구조 학습은 그래프 데이터의 무결성과 신뢰성에 의존한다. 그러나 실제 환경의 그래프는 흔히 잡음, 정보 결손, 편향을 포함하고 있어 기존 모델의 표현 능력을 제약한다. 단일 계층 구조 학습 방법은 국소적 상호작용과 전역 구조를 동시에 포착하지 못한다. 또한 고품질의 레이블 데이터에 의존하기 때문에 레이블 희소성과 높은 주석 비용 문제가 발생한다. 이러한 문제를 해결하기 위해, 본 논문은 D2GSL이라는 자기지도 이중 계층 구조 기반 그래프 구조 학습 방법을 제안한다. D2GSL은 의미적 유사도 채널과 스펙트럼 특징 채널을 구성하여 국소 의미 및 전역 스펙트럼 관점에서 노드 관계를 모델링한다. 본 방법은 계층 간 노드 대응 관계를 명시적으로 모델링하고 채널 간 결합 구조 재구성을 가능하게 하는 초인접 행렬(hyperadjacency matrix)을 도입한다. 또한 구조 재구성 제약을 적용하고 대조 학습 메커니즘을 채택하여 자기지도 환경에서의 구조 표현을 개선한다. 실험 결과 D2GSL은 공개 벤치마크 데이터셋에서 주류 기준 모델을 능가하며, 구조적 잡음과 레이블 희소성 조건에서 강력한 효과를 보임을 입증한다.</p>
</section>
<section id="핵심어" class="level2">
<h2 class="anchored" data-anchor-id="핵심어">핵심어</h2>
<p>Graph Structure Learning; Dual-layer Structure; Hyperadjacency Matrix; Graph Contrastive Learning</p>
</section>
</section>
<section id="서론" class="level1">
<h1>1 서론</h1>
<p>최근 몇 년 동안 그래프 신경망(Graph Neural Networks, GNNs) 기반 방법은 소셜 네트워크[1,2], 교통 네트워크[3,4], 생물정보학[5,6] 등 다양한 분야에 폭넓게 적용되어 왔다. 그래프 구조는 다재다능하고 유연한 데이터 표현으로서 복잡한 관계형 데이터를 효과적으로 포착한다. GNN은 노드 사이의 인접 관계에 기반하여 정보를 전파하고 특징을 집계함으로써 노드, 엣지 또는 전체 그래프의 고수준 표현을 학습한다. 이들은 노드 분류[7,8], 링크 예측[9,10], 그래프 분류[11,12], 노드 군집화[13,14]와 같은 다양한 그래프 학습 과제에서 뛰어난 일반화 성능을 보여주었다. 전형적인 GNN 모델에서는 메시지 전달(message-passing) 메커니즘이 사용되며, 각 계층에서 노드는 이웃 노드의 특징을 집계하고 자신의 특징과 결합하여 자신의 표현을 갱신한다.</p>
<p>GNN이 강력한 표현력과 모델 유연성을 보여주었지만, 여전히 핵심적인 한계에 직면해 있다. 대부분의 GNN 방법은 한 가지 근본적인 가정에 의존하는데, 즉 원래의 그래프 구조가 노드 간의 진정한 관계를 안정적으로 반영하고 다운스트림 과제에 충분한 지침을 제공한다고 가정한다. 그러나 이 가정은 실제 그래프 데이터에서는 충족되기 어렵고 지나치게 이상적인 경우가 많다. 실제로 그래프 구조에는 잡음, 정보 결손, 편향[15] 같은 문제가 종종 동반된다. 예를 들어, 소셜 네트워크에는 조작된 관계나 정보 단절이 포함될 수 있다. 분자 그래프에는 핵심 화학 결합 연결이 누락될 수 있다. 인용 네트워크에는 중복되거나 부정확한 인용 관계가 포함될 수 있다. 이러한 구조적 결함은 GNN의 학습 성능에 큰 영향을 미쳐 모델 성능 저하와 일반화 능력 제약으로 이어진다.</p>
<p>앞서 언급한 문제를 해결하기 위해 그래프 구조 학습(Graph Structure Learning, GSL)이 점차 효과적인 해결책으로 자리 잡으며 다양한 분야에 폭넓게 적용되어 왔다. GSL은 학습 과정 중에 그래프 구조를 동적으로 구성하거나 최적화함으로써, 그래프 합성곱 신경망(Graph Convolutional Networks, GCNs)이 불완전하거나 잡음이 있거나 편향된 그래프 데이터를 다룰 때에도 더 강건하고 표현력 있는 노드 표현을 학습할 수 있게 한다. GSL 방법은 잠재적인 의미적 연관성을 드러내고 노드 간 정보 전파의 효율성을 향상시키는 데 도움을 준다. 또한 다운스트림 과제에 대한 구조 적응력을 높이고 모델의 표현 능력과 일반화 성능을 한층 강화한다. 최근 몇 년 동안 연구자들은 그래프 구조 구성과 최적화를 위한 다양한 전략을 제안해 왔다. 이러한 전략에는 거리 학습 기반 방법[16-18], 구조 생성을 위한 확률적 표본 추출 방법[19-21], 그리고 인접 행렬을 학습 가능한 파라미터로 취급하여 직접 최적화하는 종단간(end-to-end) 접근법[22,23]이 포함된다. 이러한 방법들은 그래프 구조 학습의 유연성과 표현력을 어느 정도 향상시켜 그래프 신경망의 성능 개선에 기여했다. 그러나 대부분의 기존 방법은 여전히 지도 학습 틀 안에서 그래프 구조를 최적화하고 있어, 구조 조정을 안내하는 데 레이블 정보에 크게 의존한다. 이는 레이블 데이터가 부족한 실제 시나리오에서 중대한 제약이 된다. 많은 방법들이 여전히 정적이고 단일한 구조적 관점에 의존한다. 이러한 한계는 모델이 서로 다른 의미 공간에서 노드 간의 복잡한 관계를 포착하기 어렵게 만든다. 일부 방법들은 채널 간의 구조적 상호작용을 학습하지 못한다. 이 약점은 다중 관점(multi-view) 정보 융합의 효과를 감소시키고 모델의 강건성을 떨어뜨린다.</p>
<p>이러한 문제를 고려하여, 본 논문은 D2GSL이라는 자기지도 이중 계층 구조 기반 그래프 구조 학습 방법을 제안한다. 본 방법은 레이블 지도에 의존하지 않고 다중 채널 구조 정보를 통합하여 더 강한 표현력을 갖는 그래프 구조 표현을 구축하는 것을 목표로 한다. D2GSL은 먼저 노드 임베딩에 기반하여 두 개의 구조적 채널을 구성한다. 의미적 유사도 채널은 노드 간의 국소적 의미 관계를 포착한다. 스펙트럼 특징 채널은 전역 구조 패턴을 포착한다. 두 종류의 구조적 정보를 더욱 통합하기 위해, 본 논문은 이중 계층 네트워크 구조를 설계한다. 두 채널 그래프는 독립된 그래프 계층으로 취급되고, 계층 간 연결을 통해 초인접 행렬(hyperadjacency matrix)이 구성된다. 이러한 채널 간 융합은 국소 정보와 전역 정보 사이의 결합을 포착하고 학습된 구조의 전체 표현력을 강화한다. 본 논문은 또한 구조 재구성 제약을 도입한다. 이 제약은 각 채널 구조와 전체 구조 사이의 일관성을 유지하며 정보 손실이나 중복을 줄인다. 또한 자기지도 환경에서 원래 그래프의 의미를 보존하기 위해 대조 학습 메커니즘이 통합된다. 본 논문의 주요 기여는 다음과 같이 요약된다:</p>
<ul>
<li>의미적 유사도 채널과 스펙트럼 특징 채널을 구성한다. 이 두 시점은 그래프 정보를 국소 의미 및 전역 스펙트럼 관점에서 포착하고, 그래프 구조의 표현력과 다중 노드 표현의 이해도를 향상시킨다.</li>
<li>이중 계층 그래프 구조가 설계되고 초인접 행렬이 도입되어 다중 채널 구조 정보를 통합한다. 대조 학습 목적과 구조 재구성 손실을 결합한 이중 채널 협력 최적화 메커니즘이 적용되어 채널 간의 일관성을 향상시키고 표현 공간과 구조 공간의 식별 능력을 강화한다.</li>
<li>다수의 실세계 데이터셋에서 광범위한 실험을 수행하였으며, 결과는 기준 방법들과 비교하여 D2GSL이 노드 분류 과제에서 강력한 성능을 달성함을 보여준다.</li>
</ul>
</section>
<section id="관련-연구" class="level1">
<h1>2 관련 연구</h1>
<section id="그래프-신경망" class="level2">
<h2 class="anchored" data-anchor-id="그래프-신경망">2.1 그래프 신경망</h2>
<p>GNN은 그래프 구조 데이터를 다루는 강력한 도구로서 노드 분류와 링크 예측 등의 과제에서 뛰어난 성능을 보여 왔다. GCN[24]과 같은 초기 방법들은 이웃 특징을 국소적으로 집계하여 노드 표현을 갱신하고, 그래프 신경망이 더 깊은 네트워크 구조를 학습할 수 있는 토대를 마련했다. 이를 바탕으로 연구자들은 다양한 GNN 구조 변형과 개선안을 제안하여 모델 성능과 확장성을 한층 향상시켰다. 예를 들어 GAT[25]는 메시지 전달에 어텐션 메커니즘을 도입해 이웃 노드에 다른 가중치를 부여함으로써 모델이 특징 집계 과정에서 식별 능력을 갖게 하였다. GraphSAGE[26]는 확장 가능한 이웃 표본 추출 전략을 채택하여 GNN이 효율적으로 대규모 그래프 데이터를 처리할 수 있게 한다. ChebNet[27]은 체비셰프 다항식으로 그래프 합성곱 연산을 근사하여 모델의 표현력과 계산 효율성을 향상시킨다. 해당 분야의 발전과 다양한 GNN 모델에 관한 추가 정보는 최신 종설[28-30]을 참고하기 바란다.</p>
</section>
<section id="그래프-구조-학습" class="level2">
<h2 class="anchored" data-anchor-id="그래프-구조-학습">2.2 그래프 구조 학습</h2>
<p>GSL은 그래프 머신 러닝 분야의 핵심 연구 영역이다. 학습 과정에서 그래프의 잠재적 구조를 동적으로 최적화하고자 한다. 이러한 최적화는 노드 분류, 링크 예측, 그래프 분류와 같은 다운스트림 과제의 성능을 향상시킨다. 기존 연구는 그래프 구조의 표현력과 강건성을 향상시키는 다양한 방법을 제안해 왔다. CoGSL[18]은 그래프 구조 학습을 위한 정보-이론적 그래프 구조 학습 방법을 제안한다. 다중 시점 그래프 구조에서 핵심 정보를 추출하는 것을 목표로 하며, 다운스트림 과제에 견고하고 잉여 잡음을 적게 갖는 그래프 구조를 구축한다. 이 방법은 노이즈와 외란에 대한 모델의 강건성을 유지하면서 예측 성능을 향상시키는 데 도움이 된다.</p>
<p>IDGL[16]은 그래프 구조 학습을 유사도 측정 문제로 다룬다. 다중 헤드 코사인 유사도와 <span class="math inline">\(\epsilon\)</span>-이웃 희소화를 결합하여 적응적 그래프를 생성한다. 이는 과제 손실과 그래프 정규화 항을 동시에 최적화하여 잡음에 강하고 적대적 공격에 잘 견디며 GNN의 파라미터 학습을 함께 안내한다. 그래프의 본질적 특성을 활용하여 표현력을 더욱 끌어올리고 잡음, 희소성, 특징 비대칭에 대한 강건성을 향상시킨다. TO-GCN[31]은 노드 토폴로지를 함께 정제하고 측면 정보를 사용해 완전 연결 네트워크의 파라미터를 학습한다. SUBLIME[32]은 자기 강화 신호를 대조 학습을 통해 구성하고 자기지도 그래프 구조 학습 목적을 함께 최적화하며, 비지도 그래프 구조 학습이 가능하게 한다.</p>
<p>PROSE[33]는 상태 인지 점진적 그래프 구조 학습 프레임워크를 제안한다. 노드 간 관계를 우선순위화하고 점진적으로 그래프 구조를 확장하여 학습 그래프의 강건성을 유지한다. 이 방법은 잡음 환경에서의 인접 관계와 표현 학습 능력을 효과적으로 처리한다. GEN[15]은 GNN 학습 과정을 향상시키기 위해 그래프 구조 추정 신경망을 제안한다. 이 모델은 동적으로 그래프 구조를 최적화하고 학습 가능한 파라미터를 도입함으로써 모델의 표현력을 강화한다. 한편, GEN은 GNN 학습의 강건성을 높이고 다운스트림 과제 성능을 개선한다. 이러한 방법들은 다양한 시나리오에서 그래프 구조 학습의 표현력과 강건성을 어느 정도 향상시켰지만, 한계는 여전히 존재한다. 대부분의 기존 방법은 비지도 학습 프레임워크에서 작동하지만, 레이블 비용이 높은 실세계 시나리오에서는 효율이 제한된다. 또한, 대부분의 방법은 정적이고 단일한 구조적 관점에 의존한다. 이 한계는 다른 의미 공간에서 노드 간의 표현 능력을 포착하기 어렵게 만들고, 다중 채널 정보의 표현력을 감소시킨다.</p>
</section>
<section id="그래프-대조-학습" class="level2">
<h2 class="anchored" data-anchor-id="그래프-대조-학습">2.3 그래프 대조 학습</h2>
<p>그래프 대조 학습(Graph Contrastive Learning, GCL)은 비지도 그래프 표현 학습 분야에서 중요한 진보를 이룩했다. 최근 몇 년 동안 그 핵심 아이디어는 데이터 증강을 통해 양성·음성 쌍을 구성하여 그래프 수준 표현의 식별성과 일반화 능력을 향상시키는 것이다. 이 설계는 레이블 정보의 의존성을 제거하며 연구자들로부터 광범위한 주목을 받았다. DGI[34]는 노드 임베딩을 향상시키고 글로벌 그래프 구조를 최대화함으로써 글로벌 구조를 캡처하는 학습 능력을 개선한다. MVGRL[35]은 다중 시점 학습을 적용하여 다른 수준의 대조를 보장한다. 그래프 구조 정보를 캡처하고, 비슷한 의미를 가진 의미적 특징과 식별 가능한 다른 특징을 구별하여, 다운스트림 과제에서 분류 정확도가 크게 떨어지는 결과를 낳는다. GRACE[36]는 노드 수준 대조 학습 전략을 도입함으로써 노드 임베딩의 식별성과 강건성을 향상시킨다. 인접 행렬을 통해 노드와 엣지를 마스킹하여 강건한 자기지도 노드 표현을 학습한다. 이러한 방법들은 노드 또는 그래프 표현 학습의 진보를 이끌어 왔지만, 대부분은 단일 대조 시점만 사용하고 다중 채널 구조 정보를 거의 활용하지 않는다.</p>
</section>
</section>
<section id="문제-정의" class="level1">
<h1>3 문제 정의</h1>
<p>무방향 그래프 <span class="math inline">\(G = (V, E)\)</span>에서 <span class="math inline">\(V = \{v_1, v_2, \dots, v_N\}\)</span>은 노드 집합을 나타내고, <span class="math inline">\(E \subseteq V \times V\)</span>는 엣지 집합을, <span class="math inline">\(X \in \mathbb{R}^{N \times d}\)</span>는 노드의 특징 행렬을 나타내며 여기서 <span class="math inline">\(d\)</span>는 특징의 차원 수이다. 인접 행렬 <span class="math inline">\(A\)</span>는 <span class="math inline">\(a_{ij} = 1\)</span>이면 노드 <span class="math inline">\(v_i\)</span>와 <span class="math inline">\(v_j\)</span> 사이에 엣지가 있고, 그렇지 않으면 <span class="math inline">\(a_{ij} = 0\)</span>으로 그래프 구조를 표현한다. GCN과 같은 그래프 신경망은 인접 구조를 활용하여 메시지 전파와 특징 집계를 수행하며, 다음 식으로 표현된다:</p>
<p><span class="math display">\[H^{(l+1)} = \sigma\!\left( D^{-1/2}\, \tilde{A}\, D^{-1/2}\, H^{(l)}\, W^{(l)} \right) \tag{1}\]</span></p>
<p>여기서 <span class="math inline">\(H^{(l)}\)</span>은 <span class="math inline">\(l\)</span>번째 계층에서의 노드 특징을 나타내며, 초기 입력은 <span class="math inline">\(H^{(0)} = X\)</span> (<span class="math inline">\(\tilde{A} = A + I\)</span>는 자기 루프를 더한 인접 행렬, <span class="math inline">\(D\)</span>는 차수 행렬, <span class="math inline">\(W^{(l)}\)</span>은 <span class="math inline">\(l\)</span>번째 계층의 학습 가능한 가중치 행렬, <span class="math inline">\(\sigma(\cdot)\)</span>는 비선형 활성화 함수)이다. 그러나 실세계 그래프에서는 종종 잡음이나 불완전한 데이터와 같은 문제가 있어 노드 사이의 진정한 관계를 충분히 포착하기 어렵게 만들고, 표현 능력을 향상시키기 위해 지도 하에 향상된 그래프 구조의 구성을 안내할 필요가 있다.</p>
<p>정의 1 (Fiedler Value 및 Fiedler Vector). 그래프 이론에서 무방향 그래프의 라플라시안 행렬은 그 구조를 라플라시안 행렬로 특징짓는다. 무방향 정규화 라플라시안 행렬은 다음과 같이 정의된다:</p>
<p><span class="math display">\[L = I - D^{-1/2}\, A\, D^{-1/2} \tag{2}\]</span></p>
<p>여기서 <span class="math inline">\(A\)</span>는 인접 행렬, <span class="math inline">\(D\)</span>는 그래프의 차수 행렬, <span class="math inline">\(I\)</span>는 단위 행렬이다. 정규화된 그래프 라플라시안 행렬 <span class="math inline">\(L\)</span>은 양의 준정부호이며, 모든 고유값은 <span class="math inline">\(0 \leq \lambda_0 \leq \lambda_1 \leq \cdots \leq \lambda_{N-1}\)</span>로 음이 아닌 실수이다. <span class="math inline">\(\lambda_0 = 0\)</span>임에 유의하자. 두 번째로 작은 고유값 <span class="math inline">\(\lambda_1\)</span>은 그래프의 Fiedler value로 불리고, 그에 대응하는 고유벡터는 Fiedler vector로 불린다.</p>
<p>정의 2 (다중 계층 네트워크). 다중 계층 네트워크는 <span class="math inline">\(M = (G, \varepsilon_c)\)</span>로 표현되며, <span class="math inline">\(G = \{G_\alpha; \alpha \in \{1, 2, \dots, M\}\}\)</span>은 <span class="math inline">\(M\)</span>개의 방향 또는 무방향 그래프의 클래스이며 각 <span class="math inline">\(G_\alpha = (V_\alpha, E_\alpha)\)</span>이다. 계층 간 엣지 집합 <span class="math inline">\(\varepsilon_c\)</span>는 다음과 같이 정의된다:</p>
<p><span class="math display">\[\varepsilon_c = \{ E_{\alpha\beta} \subseteq V_\alpha \times V_\beta \mid \alpha, \beta \in \{1, \dots, M\}, \alpha \neq \beta \} \tag{3}\]</span></p>
<p>이는 동일한 계층 또는 서로 다른 계층의 노드 사이의 상호 연결 집합을 나타낸다 (<span class="math inline">\(\alpha = \beta\)</span>일 때 또는 <span class="math inline">\(\alpha \neq \beta\)</span>일 때). <span class="math inline">\(\varepsilon_c\)</span>의 원소는 cross-layer edges로 불린다. 각 <span class="math inline">\(E_{\alpha\alpha}\)</span>는 계층 간 엣지의 집합으로, <span class="math inline">\(M\)</span>의 계층 내 엣지로 간주된다 (<span class="math inline">\(\alpha = \beta\)</span>).</p>
<p>정의 3 (그래프 구조 학습). 무방향 그래프 <span class="math inline">\(G = (V, E)\)</span>가 주어지면, GSL은 인접 행렬 <span class="math inline">\(A \in \{0, 1\}^{N \times N}\)</span> (또는 확률 행렬 <span class="math inline">\(P(A)\)</span>)를 최적화하여 목적 함수 <span class="math inline">\(\mathcal{L}\)</span>을 최소화한다. 그래프 구조 학습 메커니즘은 다음과 같이 표현된다:</p>
<p><span class="math display">\[\hat{A} = \arg\min_A \mathcal{L}(A, X, \Theta) + R(A) \tag{4}\]</span></p>
<p>여기서 <span class="math inline">\(\Theta\)</span>는 모델 파라미터를 나타내고, <span class="math inline">\(\mathcal{L}(A, X, \Theta)\)</span>는 그래프 구조와 예측된 그래프 구조 사이의 차이를 정량화하는 구조 손실 함수이며, <span class="math inline">\(R(A)\)</span>는 인접 행렬 <span class="math inline">\(A\)</span>의 희소성이나 복잡도를 제어하는 정규화 항이다.</p>
<p>정의 4 (그래프 대조 학습). GCL의 목적은 차원 축소된 공간으로 노드 표현을 사상하는 사영 함수 <span class="math inline">\(f_\theta : \mathbb{R}^{N \times d} \to \mathbb{R}^{N \times k}\)</span>를 학습하는 것이다. 여기서 <span class="math inline">\(d\)</span>는 입력 특징의 차원이고 <span class="math inline">\(k\)</span>는 차원 축소된 공간의 차원이다. 목적 함수는 다음과 같이 최적화된다:</p>
<p><span class="math display">\[\mathcal{L}(f_\theta(G_1), f_\theta(G_2)) = -\sum_{i=1}^N \log \frac{\exp(\text{sim}(f_\theta(z_i^{(G_1)}), f_\theta(z_i^{(G_2)})))}{\sum_{j=1}^N \exp(\text{sim}(f_\theta(z_i^{(G_1)}), f_\theta(z_j^{(G_2)})))} \tag{5}\]</span></p>
<p>최적의 사영 함수는 다음으로 얻어진다:</p>
<p><span class="math display">\[\hat\theta = \arg\min_\theta\, \mathcal{L}(f_\theta(G_1), f_\theta(G_2)) \tag{6}\]</span></p>
<p>여기서 <span class="math inline">\(\text{sim}(z_i, z_j)\)</span>는 노드 <span class="math inline">\(i\)</span>와 노드 <span class="math inline">\(j\)</span>의 표현 사이의 유사도를 나타내며, <span class="math inline">\(G_1\)</span>과 <span class="math inline">\(G_2\)</span>는 그래프의 서로 다른 시점을 나타낸다.</p>
</section>
<section id="방법론" class="level1">
<h1>4 방법론</h1>
<p>이 절에서는 자기지도 GSL 프레임워크의 전체 구조를 그림 1에 나타낸 대로 자세히 설명한다.</p>
<p><img src="attachments/260430_6e8216_01.png" class="img-fluid"></p>
<p>그림 1: 제안된 D2GSL의 전체 프레임워크. D2GSL은 먼저 의미 유사도 채널 그래프를 구성하고 Fiedler 벡터를 활용해 스펙트럼 특징 채널 그래프를 생성한다. 그런 다음, 다중 채널 그래프 구조와 계층 간 상호작용을 결합하여 그래프의 표현 능력을 향상시킨다. 또한 두 채널 그래프의 의미와 하이퍼인접성-기반 정보 손실 사이의 구조적 차이를 최소화하여 정보 압축과 일관성을 동시에 유지한다. 마지막으로, 원본 그래프의 기저 구조 정보를 보존하기 위해 대조 학습 목적을 사용한다.</p>
<p>D2GSL은 세 가지 주요 구성 요소로 이루어진다: 다중 채널 그래프 구조 학습 모듈, 이중 계층 네트워크 구조 재구성 모듈, 그리고 결합 최적화 모듈. D2GSL은 먼저 의미 유사도 채널 그래프를 구성하고 Fiedler 벡터를 활용하여 전역 스펙트럼 구조를 포착하는 스펙트럼 특징 채널 그래프를 생성한다. 이 두 채널은 상호 보완적이며 함께 학습되어 의미적 및 구조적 수준 모두에서 그래프의 구조적 표현력을 향상시킨다. 두 채널 그래프는 그런 다음 이중 계층 그래프 구조로 구성된다. 초인접 행렬이 다중 채널 사이의 구조적 상호작용 관리를 가능하게 하기 위해 도입된다. 다음으로, 구조 재구성 손실이 두 채널 그래프와 초인접 행렬 사이의 구조적 차이를 최소화하기 위해 도입된다. 이 손실은 구조적 압축과 정보 보존을 모두 달성한다. 대조 학습 목적이 원본 그래프와 두 채널 그래프 사이의 구조적 차이를 정렬하기 위해 설계되었다. 이는 모델이 원본 그래프의 의미를 보존하면서 잠재적 구조 정보를 포착하도록 안내한다.</p>
<section id="다중-채널-그래프-구조-학습" class="level2">
<h2 class="anchored" data-anchor-id="다중-채널-그래프-구조-학습">4.1 다중 채널 그래프 구조 학습</h2>
<p>D2GSL은 국소 의미 및 전역 구조 관점에서 그래프 데이터의 깊은 학습을 달성하는 것을 목표로 한다. 이는 두 개의 상보적 채널을 구성하여 그래프에 내재된 다차원 구조 정보를 충분히 포착한다: 의미 유사도 채널 그래프와 스펙트럼 구조 채널 그래프.</p>
<section id="의미-유사도-채널-그래프의-구성" class="level3">
<h3 class="anchored" data-anchor-id="의미-유사도-채널-그래프의-구성">4.1.1 의미 유사도 채널 그래프의 구성</h3>
<p>노드 사이의 의미적 관계를 고려하여, 우리는 GCN 모델로 원본 노드 특징 <span class="math inline">\(X \in \mathbb{R}^{N \times d}\)</span>를 사상한다. 모델은 <span class="math inline">\(X\)</span>를 노드 임베딩 <span class="math inline">\(H = f_\theta(X) \in \mathbb{R}^{N \times d}\)</span>로 변환한다. 각 임베딩 <span class="math inline">\(h_i \in \mathbb{R}^k\)</span>는 노드 <span class="math inline">\(v_i\)</span>의 특징 벡터를 나타낸다. 본 논문은 의미적 및 구조적 그래프 모두에 대한 두 가지 다른 그래프 구성 메커니즘을 설계한다.</p>
<ol type="1">
<li>K-최근접 이웃</li>
</ol>
<p>각 임베딩의 노드를 얻은 후, 노드 수 <span class="math inline">\(N\)</span>과 그래프 표현의 차원을 가지고, 각 노드 <span class="math inline">\(h_i \in \mathbb{R}^k\)</span>. 우리는 임베딩 사이의 유클리디언 거리를 최소화하여 <span class="math inline">\(K\)</span>-최근접 이웃 방법을 사용한다. <span class="math inline">\(A_S = \{(v_i, v_j) \mid v_j \in \text{KNN}(v_i), i \in \{1, \dots, N\}\}\)</span>로, 여기서 인접 행렬 항목은 임베딩의 <span class="math inline">\(L^2\)</span>-노름의 음수 값으로 가중치를 부여하여 표현된다. <span class="math inline">\(w_{ij} = \mathcal{O}(\| h_i - h_j \|^2)\)</span>. 마지막으로, 일부 엣지를 무작위로 제거하기 위해 DropEdge 기법을 적용하여, 정제된 그래프 <span class="math inline">\(G_S = (X, A_S)\)</span>를 얻는다.</p>
<ol start="2" type="1">
<li>코사인 유사도</li>
</ol>
<p>노드 사이의 의미적 관계를 더 잘 포착하기 위해, 또 다른 그래프 구성 방법은 노드 임베딩 사이의 코사인 유사도에 기반한다. 노드 <span class="math inline">\(i\)</span>와 <span class="math inline">\(j\)</span> 사이의 코사인 유사도는 다음과 같이 계산된다:</p>
<p><span class="math display">\[\text{sim}_{ij}^{(s)} = \frac{h_i^\top h_j}{\| h_i \|_2 \| h_j \|_2} \tag{7}\]</span></p>
<p>이는 노드 <span class="math inline">\(v_i\)</span>와 <span class="math inline">\(v_j\)</span> 사이의 관계의 방향성을 포착하며, 우리는 가장 높은 코사인 유사도를 가진 상위 <span class="math inline">\(K\)</span>를 모든 노드에 대해 유지한다. 이는 <span class="math inline">\(A_S = \{(v_i, v_j) \mid i, j \in \{1, \dots, N\}\}\)</span>로 표현된다. 우리는 위와 동일한 활성화 함수 <span class="math inline">\(\varphi(\cdot)\)</span>와 DropEdge 기법을 적용하여 최종 그래프 <span class="math inline">\(G_S = (X, A_S)\)</span>를 얻는다.</p>
</section>
<section id="스펙트럼-특징-채널-그래프의-구성" class="level3">
<h3 class="anchored" data-anchor-id="스펙트럼-특징-채널-그래프의-구성">4.1.2 스펙트럼 특징 채널 그래프의 구성</h3>
<p>특징 공간에서 그래프 구조의 표현력을 향상시키기 위해, 본 논문은 라플라시안 스펙트럼 분해 방법을 스펙트럼 그래프 이론에서 도입한다. 이 방법은 Fiedler 벡터의 두 번째 가장 작은 고유값을 그래프의 스펙트럼 특징 채널 그래프로 구성하며, 이는 전역적인 저주파 구조 특징을 포착하여 전역 연결 정보를 포착한다.</p>
<p>원본 그래프 <span class="math inline">\(G = (V, E)\)</span>가 주어지면, 우리는 먼저 인접 행렬 <span class="math inline">\(A\)</span>에 자기 루프를 더하여 인접 행렬 <span class="math inline">\(A = A + I\)</span>를 도입한다. 차수 행렬 <span class="math inline">\(D \in \mathbb{R}^{N \times N}\)</span>는 갱신된 인접 행렬 <span class="math inline">\(A = A + I\)</span>의 노드 차수와 같으며, 그런 다음 우리는 대각선 원소가 노드 <span class="math inline">\(v_i\)</span>의 차수와 같은 대각 행렬 <span class="math inline">\(D_{ii}\)</span>를 갖는 차수 행렬 <span class="math inline">\(D_{ii} = \sum_{j=1}^N A_{ij}\)</span>로 정규화한다. 다음으로, 우리는 정규화된 라플라시안 행렬을 <span class="math inline">\(L = D - A\)</span>로 정의한다. 이 행렬은 대칭적이며 양의 준정부호이다. 두 번째로 작은 고유값 <span class="math inline">\(\lambda_1 \leq \cdots\)</span>의 고유벡터는 그래프의 저주파 구조 특징과 함께 전역 연결성 정보를 포착한다.</p>
<p>그래프 <span class="math inline">\(G = (V, E)\)</span>가 주어지면, 우리는 먼저 인접 행렬 <span class="math inline">\(A\)</span>에 자기 루프를 더한다 — 결과적으로 <span class="math inline">\(A = A + I\)</span>. 그런 다음, 우리는 정규화된 라플라시안 행렬을 <span class="math inline">\(L = D - A\)</span>로 갱신한다. 다음으로, 우리는 정규화된 라플라시안 행렬을 <span class="math inline">\(L = D - A\)</span>로 정의한다. 이 행렬은 대칭적이고 양의 준정부호이며, 그 두 번째 가장 작은 고유값에 해당하는 고유벡터는 저주파 구조 특징과 함께 전역 그래프 연결성 정보를 캡처한다.</p>
<p>이 벡터를 <span class="math inline">\(f = u_2 \in \mathbb{R}^N\)</span>으로 표시하고 각 노드의 임베딩을 그 차수에 의해 표현한다.</p>
</section>
</section>
<section id="이중-계층-네트워크-구조" class="level2">
<h2 class="anchored" data-anchor-id="이중-계층-네트워크-구조">4.2 이중 계층 네트워크 구조</h2>
<p>본 논문은 다중 채널 그래프 학습을 기반으로 깊은 관계와 보완적 특징을 다른 채널 구조 사이에서 탐색한다. 이는 두 채널 학습을 위한 형식적 프레임워크를 도입하고, 이중 계층 그래프 구조를 구성하여, 그래프 네트워크 <span class="math inline">\(M = ((G_D, G_S), \varepsilon_c)\)</span>를 만든다. 여기서 <span class="math inline">\(G_D = (X_D, E_D)\)</span>와 <span class="math inline">\(G_S = (X_S, E_S)\)</span>는 두 계층에 해당하는 그래프 구조를 나타내고, <span class="math inline">\(\varepsilon_c\)</span>는 계층 간 상호작용 엣지 집합을 나타낸다.</p>
<p>두 그래프 사이의 계층 간 연결을 위해, 각 노드 <span class="math inline">\(v_i^{(D)}\)</span>를 <span class="math inline">\(G_D\)</span> 그래프에서 골라 <span class="math inline">\(G_S\)</span> 그래프의 가장 비슷한 노드 상위 <span class="math inline">\(K\)</span>를 선택하여 연결을 구축한다. 이 계층 간 엣지 집합 <span class="math inline">\(\varepsilon_c\)</span>는 다음과 같이 정의된다:</p>
<p><span class="math display">\[\varepsilon_c = \bigcup_{i=1}^N \left\{ \bigl( v_i^{(D)}, v_j^{(S)} \bigr) \,\Big|\, v_j^{(S)} \in \text{TopK}\!\bigl(\text{sim}(h_i^{(D)}, h_j^{(S)})\bigr) \right\} \tag{8}\]</span></p>
<p>여기서 <span class="math inline">\(h_i^{(D)}\)</span>와 <span class="math inline">\(h_j^{(S)}\)</span>는 <span class="math inline">\(G_D\)</span>와 <span class="math inline">\(G_S\)</span> 그래프의 노드 임베딩을 각각 나타내고, <span class="math inline">\(\text{TopK}(\cdot)\)</span>는 가장 비슷한 노드 상위 <span class="math inline">\(K\)</span>를 선택하는 것을 나타낸다.</p>
<p>위에서 설명한 절들에서, 우리는 이중 계층 그래프의 노드 집합 <span class="math inline">\(X_D = x_1^{(D)}, x_2^{(D)}, \dots, x_{N_D}^{(D)}\)</span>로 노드 집합을 나타내기로 한다. <span class="math inline">\(G_D\)</span>. 각 계층 <span class="math inline">\(G_D\)</span>에 대해, 그 인접 행렬은 <span class="math inline">\(A^{(D)} = (a_{ij}^{(D)}) \in \mathbb{R}^{N_D \times N_D}\)</span>로 식 (9)에 나타낸 대로 정의된다.</p>
<p><span class="math display">\[a_{ij}^{(D)} = \begin{cases} 1, &amp; \text{if } (v_i^{(D)}, v_j^{(D)}) \in E_D, \\ 0, &amp; \text{otherwise.} \end{cases} \tag{9}\]</span></p>
<p><span class="math inline">\(1 \leq i, j \leq N_D\)</span>에 대해, 계층 간 관계 <span class="math inline">\(G_D\)</span>와 <span class="math inline">\(G_S\)</span>는 다음 식에 나타낸 대로 두 그래프 사이의 중요한 cross-graph 관계를 반영한다. 그런 다음 우리는 cross-layer adjacency matrix <span class="math inline">\(A^{(DS)} = (a_{ij}^{(DS)}) \in \mathbb{R}^{N_D \times N_S}\)</span>를 다음과 같이 정의한다:</p>
<p><span class="math display">\[a_{ij}^{(DS)} = \begin{cases} 1, &amp; \text{if } j \in \text{TopK}(\text{dist}(h_i^{(D)}, h_j^{(S)})), \\ 0, &amp; \text{otherwise.} \end{cases} \tag{10}\]</span></p>
<p>여기서 <span class="math inline">\(N_D\)</span>와 <span class="math inline">\(N_S\)</span>는 <span class="math inline">\(G_D\)</span>와 <span class="math inline">\(G_S\)</span>의 노드 수를 각각 나타내며, <span class="math inline">\(h_i\)</span>와 <span class="math inline">\(h_j^{(D)}\)</span>는 다른 계층에서 온 노드 임베딩을 나타낸다. 마지막으로, cross-layer 초인접 행렬 <span class="math inline">\(\tilde{A}\)</span>는 이중 계층 네트워크에 대해 식 (11)에 정의된다:</p>
<p><span class="math display">\[A = \begin{pmatrix} A^{(D)} &amp; A^{(DS)} \\ \bigl(A^{(DS)}\bigr)^\top &amp; A^{(S)} \end{pmatrix} \in \mathbb{R}^{(M+N) \times (M+N)} \tag{11}\]</span></p>
<p>여기서 <span class="math inline">\(A^{(DS)}\)</span>는 <span class="math inline">\(G_D\)</span>와 <span class="math inline">\(G_S\)</span> 사이의 계층 간 연결을 나타낸다.</p>
</section>
<section id="결합-최적화" class="level2">
<h2 class="anchored" data-anchor-id="결합-최적화">4.3 결합 최적화</h2>
<p>표현 공간과 구조적 공간에서의 일관성을 유지하기 위해, 본 연구는 결합 최적화 목적을 도입한다. 이 목적은 다중 채널 그래프 구조에서 대조 학습 목적과 구조 재구성 손실을 결합하여, 다중 채널 정보가 의미 보존을 유지하고, 두 시점에서의 잠재적 표현이 잘 정렬되도록 한다. 첫째, 표현 공간의 일관성을 향상시키기 위해, 우리는 모델이 다른 채널의 노드 임베딩을 정렬하도록 강제하여, 동일한 노드 쌍 사이의 유사도를 최대화하고 음성 표본 쌍 사이의 유사도를 최소화한다. D2GSL은 의미 수준에서 채널 간 정렬을 달성한다. 이는 식 (12)의 다음 손실 함수에 의해 구체적으로 정의된다:</p>
<p><span class="math display">\[\mathcal{L}_{\text{con}} = -\sum_{i=1}^N \log \frac{\exp\!\bigl(\text{sim}(h_i^{(D)}, h_i^{(S)})/\tau\bigr)}{\sum_{j=1}^N \!\bigl[ \exp\!\bigl(\text{sim}(h_i^{(D)}, h_j^{(D)})/\tau\bigr) + \exp\!\bigl(\text{sim}(h_i^{(D)}, h_j^{(S)})/\tau\bigr) \bigr]} \tag{12}\]</span></p>
<p>여기서 <span class="math inline">\(\text{sim}(\cdot)\)</span>은 코사인 유사도 함수를 나타내고 <span class="math inline">\(\tau\)</span>는 온도 계수이다. 다음으로, 구조적 수준에서의 위상학적 일관성을 유지하기 위해, 이중 계층 네트워크 재구성 손실은 채널 간의 다중 채널 그래프, 구조적 정렬을 달성한다. 또한, 두 시점의 멀티채널 그래프, 구조 정렬은 두 그래프의 임베딩으로부터 구성된 더 높은 차수의 구조 표현으로 합쳐지며, 식 (11)에 의해 정의된다. D2GSL은 두 그래프의 임베딩으로부터 인접 행렬 <span class="math inline">\(A^{(D)}\)</span>와 <span class="math inline">\(A^{(S)}\)</span>를 예측하고, 그런 다음 구조 재구성 손실을 초인접 행렬 <span class="math inline">\(\tilde{A}\)</span>와 두 행렬 사이에서 계산한다.</p>
<p><span class="math display">\[\mathcal{L}_{\text{rec}}(\tilde{A}, A^{(D)}) = -\frac{1}{N^2} \sum_{i=1}^N \sum_{j=1}^N \!\left[ w_p \cdot A^{(D)}_{ij} \log\!\bigl(\sigma(\tilde{A}_{ij})\bigr) + w_n \cdot \bigl(1 - A^{(D)}_{ij}\bigr) \log\!\bigl(1 - \sigma(\tilde{A}_{ij})\bigr) \right] \tag{13}\]</span></p>
<p>여기서 <span class="math inline">\(\sigma(\cdot)\)</span>는 시그모이드 활성화 함수이며, <span class="math inline">\(w_p\)</span>와 <span class="math inline">\(w_n\)</span>은 양성 및 음성 표본의 가중치를 각각 나타낸다. 또한 희소 그래프에서의 불균등 엣지 분포 문제를 다루는 것이다. 최종 결합 최적화 목적은 식 (14)에서 정의된다.</p>
<p><span class="math display">\[\mathcal{L} = \beta \cdot \mathcal{L}_{\text{con}} + (1-\beta) \cdot \mathcal{L}_{\text{rec}} \tag{14}\]</span></p>
<p>이러한 이중 채널 결합 최적화 메커니즘을 통해 D2GSL은 표현 공간과 구조적 공간 모두에서 의미적 관점과 스펙트럼 관점에서 일관성을 달성한다.</p>
</section>
</section>
<section id="실험" class="level1">
<h1>5 실험</h1>
<p>이 절에서는 제안된 D2GSL 방법의 성능을 다양한 과제와 데이터셋에서 비교 실험을 통해 평가한다. 이러한 실험은 D2GSL의 전반적인 효과성과 우수성을 검증한다.</p>
<section id="실험-설정" class="level2">
<h2 class="anchored" data-anchor-id="실험-설정">5.1 실험 설정</h2>
<p>데이터셋: D2GSL의 효과를 평가하기 위해, 광범위한 자기지도 노드 분류 실험을 세 개의 일반적으로 사용되는 데이터셋에서 수행한다. 데이터셋 속성에 대한 자세한 설명은 표 1에 제공된다.</p>
<p>표 1: 데이터셋 속성 통계.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Datasets</th>
<th>Nodes</th>
<th>Edges</th>
<th>Classes</th>
<th>Features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cora</td>
<td>2708</td>
<td>5429</td>
<td>7</td>
<td>1433</td>
</tr>
<tr class="even">
<td>Citeseer</td>
<td>3327</td>
<td>4732</td>
<td>6</td>
<td>3703</td>
</tr>
<tr class="odd">
<td>DBLP</td>
<td>2975</td>
<td>2398</td>
<td>4</td>
<td>334</td>
</tr>
</tbody>
</table>
<p>기준선: 본 연구는 비교 실험을 위해 일곱 개의 대표적인 기준선 모델을 선택한다. 자기지도 학습 방법은 고전적인 GCN과 GAT를 포함하고, 자기지도 학습 방법은 DGI, IDGL, GEN을 포함하며, 그래프 구조 최적화 방법은 ProGNN과 SUBLIME을 포함한다.</p>
<p>실험적 세부 사항: 제안된 D2GSL 방법에 대한 실험은 NVIDIA GeForce RTX 4070 Ti GPU가 장착된 컴퓨터에서 수행되었으며, PyTorch 1.10.1과 CUDA 11.3이 사용되었다. 모델은 두 계층 GCN을 인코더로 사용하여 공유된 파라미터를 사용한다. 세 데이터셋에 대한 최적의 실험 하이퍼파라미터는 표 2에 표시된다.</p>
<p>표 2: 자세한 파라미터 설정.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Datasets</th>
<th>EP</th>
<th>LR</th>
<th><span class="math inline">\(\beta\)</span></th>
<th><span class="math inline">\(\tau\)</span></th>
<th>HD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cora</td>
<td>300</td>
<td>1e-3</td>
<td>0.4</td>
<td>0.5</td>
<td>512</td>
</tr>
<tr class="even">
<td>Citeseer</td>
<td>400</td>
<td>1e-3</td>
<td>0.4</td>
<td>0.6</td>
<td>512</td>
</tr>
<tr class="odd">
<td>DBLP</td>
<td>400</td>
<td>1e-3</td>
<td>0.4</td>
<td>0.5</td>
<td>512</td>
</tr>
</tbody>
</table>
<p>표 2에서 EP는 학습 epoch 수, LR은 모델 파라미터 갱신 시 단계 크기를 제어하는 데 사용되고, <span class="math inline">\(\beta\)</span>는 과제에 대한 hyperparameter이며, <span class="math inline">\(\tau\)</span>는 온도 파라미터이고, HD는 은닉 계층 차원이다.</p>
</section>
<section id="효과성-실험과-분석" class="level2">
<h2 class="anchored" data-anchor-id="효과성-실험과-분석">5.2 효과성 실험과 분석</h2>
<p>이 연구에서, 우리는 다운스트림 과제로서 노드 분류를 평가한다. 실험 결과는 표 3에 표시되어 있으며, 가장 좋은 결과는 굵게 표시되어 있다.</p>
<p>표 3: 다른 데이터셋에 대한 노드 분류 결과.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 26%">
<col style="width: 32%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Cora Mi-F1 / Ma-F1</th>
<th>Citeseer Mi-F1 / Ma-F1</th>
<th>DBLP Mi-F1 / Ma-F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GCN</td>
<td>81.84±0.57 / 80.46±1.10</td>
<td>71.81±0.31 / 68.12±0.44</td>
<td>90.99±0.28 / 90.02±0.32</td>
</tr>
<tr class="even">
<td>GAT</td>
<td>82.80±0.50 / 81.80±0.30</td>
<td>72.10±1.00 / 67.10±1.30</td>
<td>91.13±0.40 / 90.22±0.37</td>
</tr>
<tr class="odd">
<td>DGI</td>
<td>80.10±0.44 / 75.06±0.07</td>
<td>71.99±0.46 / 67.74±2.65</td>
<td>83.00±0.03 / 78.21±0.01</td>
</tr>
<tr class="even">
<td>IDGL</td>
<td>84.00±0.44 / 82.65±0.45</td>
<td>72.10±0.46 / 69.05±0.26</td>
<td>83.00±0.03 / 78.21±0.01</td>
</tr>
<tr class="odd">
<td>GEN</td>
<td>81.36±0.49 / 80.16±0.46</td>
<td>72.90±0.49 / 68.43±0.72</td>
<td>89.77±0.67 / 87.54±0.52</td>
</tr>
<tr class="even">
<td>Pro-GNN</td>
<td>81.26±0.51 / 80.94±0.49</td>
<td>80.49±1.40 / 70.98±1.27</td>
<td>89.77±0.67 / 87.54±0.52</td>
</tr>
<tr class="odd">
<td>SUBLIME</td>
<td>83.82±0.57 / 82.82±0.66</td>
<td>72.72±0.49 / 68.19±0.61</td>
<td>91.82±0.27 / 90.89±0.37</td>
</tr>
<tr class="even">
<td>D2GSL</td>
<td>85.12±0.83 / 83.54±0.71</td>
<td>73.45±0.42 / 68.74±0.21</td>
<td>91.76±0.30 / 89.32±0.45</td>
</tr>
</tbody>
</table>
<p>표 3에서 보듯이, D2GSL은 세 개의 벤치마크 데이터셋: Cora, Citeseer, DBLP에서 기준 방법들에 비해 유의한 우수성을 보여준다. 구체적으로, Cora 데이터셋에서, 그 정확도는 기준선 방법들에 비해 1.12%와 0.89%만큼 GCN과 GAT를 각각 능가한다. 두 번째로 좋은 방법인 IDGL에 대해서, D2GSL은 Mi-F1에서 1.12%만큼 더 잘 수행한다. SUBLIME에 대해서, 이는 Mi-F1에서 1.30% 더 잘 수행한다. DBLP 데이터셋에서, D2GSL은 Mi-F1에서 SUBLIME과 비교하여 약간 떨어지지만 여전히 두 번째로 잘 수행하는 방법으로, SUBLIME(91.76% 대 91.82%)에 비해 약간 떨어진다. 그러나, 그것은 강건한 구조와 의미를 모두에서 다른 기준 데이터셋에 대해 결정적으로 성능을 발휘하며, 이러한 데이터셋들에 대한 D2GSL의 우수한 분류 능력을 입증한다. 이러한 결과들은 다음 결론을 도출하게 한다:</p>
<ol type="1">
<li><p>다중 채널 구조 모델링이 특징 표현을 강화한다: D2GSL은 의미적 유사도 채널과 스펙트럼 특징 채널을 구성하여, 이는 국소 의미와 전역 구조 정보를 별도로 포착한다. 두 채널은 상보적이며, 모델이 균형 있고 식별성이 풍부한 그래프 표현 사이에서 균형을 잡을 수 있게 한다.</p></li>
<li><p>이중 계층 구조와 초인접 행렬이 정보 융합을 향상시킨다: D2GSL은 채널 간 상호작용을 통해 초인접 행렬을 구성한다. 이 설계는 깊은 통합을 가능하게 한다. 국소적 및 전역적 할당 구조의 다양성을 향상시키고 학습된 노드 표현의 다양성을 향상시킨다.</p></li>
<li><p>구조 재구성과 대조 학습이 표현 일관성을 향상시킨다: 구조 재구성은 다중 채널 구조에 대한 의미 일관성을 유지하며, 대조 학습은 의미를</p></li>
</ol>
</section>
<section id="어블레이션-연구" class="level2">
<h2 class="anchored" data-anchor-id="어블레이션-연구">5.3 어블레이션 연구</h2>
<p>이 절에서, 우리는 D2GSL 모델에 대한 어블레이션 실험을 수행하여 각 핵심 구성 요소의 기여를 검토한다. 두 모델 변형을 Cora와 Citeseer 데이터셋에서 구성하고, 핵심 모듈을 점진적으로 제거하여 그 성능을 비교한다. 실험 결과는 표 4에 요약되어 있다.</p>
<p>표 4: D2GSL과 그 변형의 성능.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 38%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Cora Mi-F1 / Ma-F1</th>
<th>Citeseer Mi-F1 / Ma-F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>D2GSL w/o <span class="math inline">\(\mathcal{L}_{\text{rec}}\)</span></td>
<td>84.12±0.11 / 82.11±0.23</td>
<td>72.91±0.01 / 67.22±0.05</td>
</tr>
<tr class="even">
<td>D2GSL w/o <span class="math inline">\(\mathcal{L}_{\text{con}}\)</span></td>
<td>83.80±0.23 / 82.27±0.10</td>
<td>72.10±0.22 / 66.87±0.56</td>
</tr>
<tr class="odd">
<td>D2GSL</td>
<td>85.12±0.83 / 83.54±0.71</td>
<td>73.45±0.42 / 68.74±0.21</td>
</tr>
</tbody>
</table>
<p>표 4에서 보듯이, 모델의 성능은 핵심 구성 요소가 제거될 때 Cora와 Citeseer 데이터셋에서 떨어진다. 이 결과는 설계된 구성 요소의 효과성과 필요성을 모두 입증한다. 구체적으로, <span class="math inline">\(\mathcal{L}_{\text{con}}\)</span>은 노드 특징의 식별성을 비슷한 의미적 차이로 향상시킨다. <span class="math inline">\(\mathcal{L}_{\text{rec}}\)</span>이 제거되면, 모델은 비슷한 특징을 집계하고 식별 가능한 특징을 구별하는 능력을 잃으며, 두 데이터셋 모두에서 분류 정확도가 유의하게 떨어진다. 이는 <span class="math inline">\(\mathcal{L}_{\text{rec}}\)</span>이 효과적인 특징을 학습하기 위한 필요한 구성 요소임을 보여준다. 한편, <span class="math inline">\(\mathcal{L}_{\text{rec}}\)</span>은 핵심 위상학적 구조 정보가 이중 계층 네트워크에서 보존됨을 보장한다. <span class="math inline">\(\mathcal{L}_{\text{rec}}\)</span>이 제거되면, 모델의 성능이 떨어진다. 그것의 핵심적인 역할을 강조하면서 이중 계층 네트워크의 이점을 유지한다.</p>
</section>
<section id="하이퍼파라미터-민감도" class="level2">
<h2 class="anchored" data-anchor-id="하이퍼파라미터-민감도">5.4 하이퍼파라미터 민감도</h2>
<p>D2GSL에 대한 하이퍼파라미터의 영향을 종합적으로 분석하기 위해, 우리는 Citeseer 데이터셋에서 실험을 수행한다.</p>
<p><img src="attachments/260430_6e8216_02.jpeg" class="img-fluid"></p>
<p>그림 2: Citeseer에 대한 강건성 분석.</p>
<p>그림 2는 다른 하이퍼파라미터, 예를 들어 Beta와 학습률이 Citeseer 데이터셋에 대한 Micro F1 점수에 미치는 영향을 보여준다. 학습률이 [0.005, 0.04] 범위에 있을 때, 모델은 더 높은 Micro F1 점수를 달성한다. 그러나, 학습률이 증가함에 따라 학습 과정은 감소를 보이는데, 이는 최적화 과정에서 유의한 감소로 이어진다. 이는 hyperparameter Beta에 관해서 유의한 감소를 보인다. Beta가 더 높은 값을 가질 때, D2GSL 모델이 점진적으로 기준 방법들의 성능 수준에 도달한다. Beta를 [0.4, 0.5]의 범위에서 유지하는 것은 더 좋은 성능을 가져온다. 요약하면, Beta와 학습률은 Citeseer 데이터셋에 대해 잘 조정될 필요가 있다. 두 파라미터는 비교적 낮은 값을 안정된 결과를 얻기 위해 필요로 한다.</p>
</section>
</section>
<section id="결론" class="level1">
<h1>6 결론</h1>
<p>본 논문은 자기지도 이중 계층 구조 기반 그래프 구조 학습 방법인 D2GSL을 제안한다. 이 방법은 구조적 잡음, 정보 손실, 그래프 데이터에서의 표현의 편향과 같은 도전들을 다루는 것을 목표로 한다. 단일 시점 그래프 구조에서 레이블 데이터에 대한 의존성을 제거한다. D2GSL은 의미 유사도 채널과 스펙트럼 특징 채널을 구성하여 다중 채널 계산 관점을 채택한다. 이 채널들은 다른 의미 공간에서 국소 의미적 관계와 전역 구조 특징을 포착한다. 두 채널은 그런 다음 이중 계층 그래프 구조에서 통합된다. 이 설계는 표현 공간과 구조적 공간 사이의 일관성을 유지한다. 모듈은 채널 사이의 일관성과 보완성을 향상시킨다. 다중 실세계 데이터셋에 대한 실험 결과들은 D2GSL이 노드 분류와 같은 다운스트림 과제에서 좋은 성능을 보임을 입증한다. 향후 연구는 D2GSL의 큰 그래프 데이터에 대한 확장성을 탐구할 것이며, 또한 cross-domain 그래프 데이터와 다중 과제 학습에서의 D2GSL의 잠재력을 검토할 것이다.</p>
</section>
<section id="진술" class="level1">
<h1>7 진술</h1>
<p>Acknowledgement: None</p>
<p>Funding Statement: This work is supported by Scientific Research Innovation Capability Support Project for Young Faculty(SRICSPYF-BS2025007), Natural Science Foundation of Qinghai Province (2025-ZJ-994M), National Natural Science Foundation of China(62566050)</p>
<p>Author Contributions: In this study, Zhang primarily contributed to conceptualization, methodology development and manuscript writing. Wei and Gu was involved in data curation and analysis. Ye and Zhao provided overall research guidance, supervision and manuscript revision.</p>
<p>Conflicts of Interest: All authors declare that there is no conflict of interest</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ol type="1">
<li>Kumar S, Mallik A, Panda BS. Influence maximization in social networks using transfer learning via graph-based LSTM. Expert Syst Appl. 2023;212:118770. [CrossRef]</li>
<li>Wei X, Liu Y, Sun J, Jiang Y, Tang Q, Yuan K. Dual subgraph-based graph neural network for friendship prediction in location-based social networks. ACM Trans Knowl Discov Data. 2023;17(3):1-28. [CrossRef]</li>
<li>Chen C, Liu Y, Chen L, Zhang C. Bidirectional spatial-temporal adaptive transformer for urban traffic flow forecasting. IEEE Trans Neural Netw Learn Syst. 2022;34(10):6913-6925. [CrossRef]</li>
<li>Jiang W, Luo J. Graph neural network for traffic forecasting: A survey. Expert Syst Appl. 2022;207:117921. [CrossRef]</li>
<li>Li R, Yuan X, Radlar M, Marendy P, Ni W, O’Brien TJ, Casillas-Espinosa PM. Graph signal processing, graph neural network and graph learning on biological data: a systematic review. IEEE Rev Biomed Eng. 2021;16:109-135. [CrossRef]</li>
<li>Gao Z, Jiang C, Zhang J, Jiang X, Li L, Zhao P, et al.&nbsp;Hierarchical graph learning for protein-protein interaction. Nat Commun. 2023;14(1):1093. [CrossRef]</li>
<li>Kipf TN, Welling M. Semi-supervised classification with graph convolutional networks. arXiv:1609.02907. 2016.</li>
<li>Zou M, Gan Z, Cao R, Guan C, Leng S. Similarity-navigated graph neural networks for node classification. Inf Sci. 2023;633:41-69. [CrossRef]</li>
<li>Kipf TN, Welling M. Variational graph auto-encoders. arXiv:1611.07308. 2016. [CrossRef]</li>
<li>Peng Z, Huang W, Luo M, Zheng Q, Rong Y, Xu T, et al.&nbsp;Graph representation learning via graphical mutual information maximization. Proc WWW. 2020:259-270. [CrossRef]</li>
<li>Zeng J, Xie P. Contrastive self-supervised learning for graph classification. Proc AAAI. 2021;35(12):10824-10832. [CrossRef]</li>
<li>Du J, Wang S, Miao H, Zhang J. Multi-channel pooling graph neural networks. Proc IJCAI. 2021:1442-1448. [CrossRef]</li>
<li>Tsitsulin A, Palowitch J, Perozzi B, Müller E. Graph clustering with graph neural networks. J Mach Learn Res. 2023;24(127):1-21. [CrossRef]</li>
<li>Bhowmick A, Kosan M, Huang Z, Singh A, Medya S. DGCLUSTER: a neural framework for attributed graph clustering via modularity maximization. Proc AAAI. 2024;38(10):11069-11077. [CrossRef]</li>
<li>Wang R, Mou S, Wang X, Xiao W, Ju Q, Shi C, et al.&nbsp;Graph structure estimation neural networks. Proc WWW. 2021:342-353. [CrossRef]</li>
<li>Chen Y, Wu L, Zaki M. Iterative deep graph learning for graph neural networks: better and robust node embeddings. Proc NeurIPS. 2020;33:19314-19326.</li>
<li>Fatemi B, El Asri L, Kazemi SM. SLAPS: self-supervision improves structure learning for graph neural networks. Proc NeurIPS. 2021;34:22667-22681.</li>
<li>Liu N, Wang X, Wu L, Chen Y, Guo X, Shi C. Compact graph structure learning via mutual information compression. Proc WWW. 2022:1601-1610. [CrossRef]</li>
<li>Franceschi L, Niepert M, Pontil M, He X. Learning discrete structures for graph neural networks. Proc ICML. 2019;97:1972-1982.</li>
<li>Sun Q, Li J, Peng H, Wu J, Fu X, Ji C, et al.&nbsp;Graph structure learning with variational information bottleneck. Proc AAAI. 2022;36(4):4165-4174. [CrossRef]</li>
<li>Zhao J, Wen Q, Ju H, Zhang C, Ye Y. Self-supervised graph structure refinement for graph neural networks. Proc WSDM. 2023:159-167. [CrossRef]</li>
<li>Wu Q, Zhao W, Li Z, Wipf DP, Yan J. NodeFormer: a scalable graph structure learning transformer for node classification. Proc NeurIPS. 2022;35:27387-27401.</li>
<li>Jin W, Ma Y, Liu X, Tang X, Wang S, Tang J. Graph structure learning for robust graph neural networks. Proc KDD. 2020:66-74. [CrossRef]</li>
<li>Kipf TN, Welling M. Semi-supervised classification with graph convolutional networks. Proc ICLR. 2017. [CrossRef]</li>
<li>Veličković P, Cucurull G, Casanova A, Romero A, Liò P, Bengio Y. Graph attention networks. Proc ICLR. 2018. [CrossRef]</li>
<li>Hamilton WL, Ying Z, Leskovec J. Inductive representation learning on large graphs. Proc NeurIPS. 2017;30.</li>
<li>Defferrard M, Bresson X, Vandergheynst P. Convolutional neural networks on graphs with fast localized spectral filtering. Proc NeurIPS. 2016;29:3844-3852.</li>
<li>Jin W, Koh HY, Wen Q, Zambon D, Alippi C, Webb GI, et al.&nbsp;A survey on graph neural networks for time series: forecasting, classification, imputation, and anomaly detection. IEEE Trans Pattern Anal Mach Intell. 2023;46(12):10466-10485. [CrossRef]</li>
<li>Dai E, Zhao T, Zhu H, Xu J, Guo Z, Liu H, et al.&nbsp;A comprehensive survey on trustworthy graph neural networks: privacy, robustness, fairness, and explainability. Mach Intell Res. 2024;21(6):1011-1061. [CrossRef]</li>
<li>Lu H, Wang L, Ma X, Cheng J, Zhou M. A survey of graph neural networks and their industrial applications. Neurocomputing. 2025;614:128761. [CrossRef]</li>
<li>Yang L, Kang Z, Cao X, Jin D, Yang B, Guo Y. Topology optimization based graph convolutional network. Proc IJCAI. 2019:4054-4061. [CrossRef]</li>
<li>Liu Y, Zheng Y, Zhang D, Chen H, Peng H, Pan S. Towards unsupervised deep graph structure learning. Proc WWW. 2022:1392-1403. [CrossRef]</li>
<li>Wang H, Fu Y, Yu T, Hu L, Jiang W, Pu S. PROSE: graph structure learning via progressive strategy. Proc KDD. 2023:2447-2458. [CrossRef]</li>
<li>Veličković P, Fedus W, Hamilton WL, Liò P, Bengio Y, Hjelm RD. Deep graph infomax. arXiv:1809.10341. 2018. [CrossRef]</li>
<li>Hassani K, Khasahmadi AH. Contrastive multi-view representation learning on graphs. Proc ICML. 2020;119:4116-4126. [CrossRef]</li>
<li>Zhu Y, Xu Y, Yu F, Liu Q, Wu S, Wang L. Deep graph contrastive representation learning. arXiv:2006.04131. 2021. [CrossRef]</li>
<li>Zeng X, Wang Y, Sun Y, Guo G, Ding W, Zhang B. Graph structure refinement with energy-based contrastive learning. Proc AAAI. 2025;39(21):22326-22335. [CrossRef]</li>
</ol>
<p>© 2026 by the Authors. Submitted to Journal Not Specified for possible open access publication under the terms and conditions of the Creative Commons Attribution 4.0 International License (CC BY 4.0).</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>