<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="신록예찬">
<meta name="dcterms.date" content="2026-04-20">

<title>리뷰 ▷ 웨이블릿 lead-lag 의존성 네트워크로 본 중국 투자-주식시장 비대칭 전이 – 신록예찬’s Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5b48ee63c5e90d651e19f9ead4b448f1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">신록예찬’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DL2024/"> 
<span class="menu-text">DL2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/AP2023/"> 
<span class="menu-text">AP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/PP2024/"> 
<span class="menu-text">PP2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DV2023/"> 
<span class="menu-text">DV2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/MP2023/"> 
<span class="menu-text">MP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SC2024/"> 
<span class="menu-text">SC2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DS2022/"> 
<span class="menu-text">DS2022</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SP2023/"> 
<span class="menu-text">SP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/IR2021/"> 
<span class="menu-text">IR2021</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan/"> 
<span class="menu-text">yechan</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan2/"> 
<span class="menu-text">yechan2</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/miruetoto/yechan"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#서론" id="toc-서론" class="nav-link active" data-scroll-target="#서론">1. 서론</a></li>
  <li><a href="#방법론" id="toc-방법론" class="nav-link" data-scroll-target="#방법론">2. 방법론</a>
  <ul class="collapse">
  <li><a href="#데이터-출처-및-전처리" id="toc-데이터-출처-및-전처리" class="nav-link" data-scroll-target="#데이터-출처-및-전처리">2.1 데이터 출처 및 전처리</a></li>
  <li><a href="#웨이블릿-일관성-lead-lag-의존성-네트워크-프레임워크" id="toc-웨이블릿-일관성-lead-lag-의존성-네트워크-프레임워크" class="nav-link" data-scroll-target="#웨이블릿-일관성-lead-lag-의존성-네트워크-프레임워크">2.2 웨이블릿 일관성 lead-lag 의존성 네트워크 프레임워크</a></li>
  <li><a href="#네트워크-토폴로지-지표-및-비대칭성-측도" id="toc-네트워크-토폴로지-지표-및-비대칭성-측도" class="nav-link" data-scroll-target="#네트워크-토폴로지-지표-및-비대칭성-측도">2.3 네트워크 토폴로지 지표 및 비대칭성 측도</a></li>
  <li><a href="#예측-성과-검증-프레임워크" id="toc-예측-성과-검증-프레임워크" class="nav-link" data-scroll-target="#예측-성과-검증-프레임워크">2.4 예측 성과 검증 프레임워크</a></li>
  </ul></li>
  <li><a href="#결과" id="toc-결과" class="nav-link" data-scroll-target="#결과">3. 결과</a>
  <ul class="collapse">
  <li><a href="#다중-주파수-lead-lag-의존성-네트워크-구조의-특성" id="toc-다중-주파수-lead-lag-의존성-네트워크-구조의-특성" class="nav-link" data-scroll-target="#다중-주파수-lead-lag-의존성-네트워크-구조의-특성">3.1 다중 주파수 lead-lag 의존성 네트워크 구조의 특성</a></li>
  <li><a href="#산업-비대칭-역할의-식별" id="toc-산업-비대칭-역할의-식별" class="nav-link" data-scroll-target="#산업-비대칭-역할의-식별">3.2 산업 비대칭 역할의 식별</a></li>
  <li><a href="#정책-효과의-네트워크-구조에-대한-시변-분석" id="toc-정책-효과의-네트워크-구조에-대한-시변-분석" class="nav-link" data-scroll-target="#정책-효과의-네트워크-구조에-대한-시변-분석">3.3 정책 효과의 네트워크 구조에 대한 시변 분석</a></li>
  <li><a href="#네트워크-중심성-지표의-예측력-검증" id="toc-네트워크-중심성-지표의-예측력-검증" class="nav-link" data-scroll-target="#네트워크-중심성-지표의-예측력-검증">3.4 네트워크 중심성 지표의 예측력 검증</a></li>
  <li><a href="#강건성-검정-결과" id="toc-강건성-검정-결과" class="nav-link" data-scroll-target="#강건성-검정-결과">3.5 강건성 검정 결과</a></li>
  </ul></li>
  <li><a href="#논의" id="toc-논의" class="nav-link" data-scroll-target="#논의">4. 논의</a></li>
  <li><a href="#결론" id="toc-결론" class="nav-link" data-scroll-target="#결론">5. 결론</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">리뷰 ▷ 웨이블릿 lead-lag 의존성 네트워크로 본 중국 투자-주식시장 비대칭 전이</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>신록예찬 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>본 연구는 Morlet 웨이블릿 변환, 위상차 분석, 방향성 가중 네트워크 토폴로지를 결합한 시간-주파수 웨이블릿 lead-lag 의존성 네트워크 프레임워크를 개발하여 중국의 투자 사이클과 업종별 주식 수익률 간 비대칭 전이 메커니즘을 규명한다. 2010년 1월부터 2025년 9월까지 4개 투자 지표와 28개 업종에 대한 데이터를 이용하여, 본 프레임워크는 주파수 대역별로 lead-lag 네트워크를 분해하고, 고밀도 단기 확산에서 희소한 장기 의존성으로 이어지는 구조적 진화를 밝혀낸다. 네트워크 중심성 지표는 핵심 송신자, 주요 수신자, 양방향 전이 산업을 식별하며, 이는 신규 인프라 투자, 탄소중립 목표, 부동산 규제에서 비롯된 정책 주도적 네트워크 재구성을 반영한다. 롤링 윈도우 백테스트 결과, 연결 중심성(degree centrality)과 순 스필오버 지수(net spillover index)를 반영하면 주가 예측 정확도가 평균 18.3% 향상되며, 비대칭성이 높은 경기 순환 산업에서 개선 폭이 더 크다. 본 프레임워크는 방법론적 안정성과 비무작위적 경제 메커니즘을 확인하며, 규제 당국의 시스템 리스크 모니터링과 투자자의 동적 자산 배분을 뒷받침한다.</p>
<p>Keywords: wavelet coherence, lead-lag dependence network, investment cycle, sectoral stock returns, asymmetric transmission</p>
<section id="서론" class="level2">
<h2 class="anchored" data-anchor-id="서론">1. 서론</h2>
<p>투자 사이클은 금융경제학의 핵심 주제이며, 특히 중국 경제의 진행 중인 전환기에 더욱 중요하다. 거시경제의 핵심 동인으로서 자본시장과의 관계는 점점 더 복잡하고 동적인 특성을 보여 왔다. 2020년 이후 COVID-19 및 그에 따른 봉쇄 조치로 인해 중국 정부는 신규 인프라 건설, 탄소 피크 및 탄소중립 구축, 산업구조의 최적화와 고도화와 같은 일련의 중대한 전략적 조치들을 시행하였다. 이러한 정책 주도의 조치들은 가격 결정 메커니즘과 리스크 전이 경로를 변화시킴으로써 자본시장의 상태에 영향을 미쳤다 (Xia et al., 2020). 이러한 상황에서 투자와 주식시장 간 전이 메커니즘을 분석하는 전통적 프레임워크는 상당한 어려움에 직면해 있다. 정책 모호성의 지속적 누적은 기업의 위험 노출을 증가시키고, 기대 관리 채널을 통해 주식시장의 변동성을 더욱 심화시킨다 (Liu et al., 2025). COVID-19 팬데믹 기간 동안, 시장 간 전염 메커니즘의 복잡성은 글로벌 주가지수 간 팬데믹 관련 정책 불확실성의 스필오버 효과에 의해 더욱 확증되었다 (Su et al., 2025). 벡터자기회귀(VAR) 모델 및 Granger 인과성 검정과 같은 전통적 선형 접근법은 변수 간 평균적 관계를 정량화하는 데 이론적 장점이 있으나, 일반적으로 시간 불변 파라미터를 가정한다. 이러한 가정은 비대칭적, 다차원적, 척도 특이적 동학, 특히 서로 다른 투자 유형(인프라, 부동산, 제조업)이 서로 다른 업종별 주식에 미치는 이질적 영향과 시차 효과를 포착하는 능력을 제한한다.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>쉽게 풀어쓰면
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>요지</strong>: 2020년 이후 중국은 신 인프라·탄소중립·부동산 규제 같은 정책 충격이 계속 들어왔고, 이 때문에 “투자 → 주가”의 연결 고리가 <em>시시각각 모양을 바꾸는</em> 상태가 됐다. 그런데 기존 분석 도구(VAR, Granger 인과성)는 <strong>“변수 간 관계가 시간이 지나도 일정하다”</strong> 고 가정해서 이걸 못 따라잡는다.</p>
<p>구체적으로 전통 방법이 놓치는 세 가지:</p>
<ul>
<li><strong>비대칭</strong> — “A가 B에 미치는 영향”과 “B가 A에 미치는 영향”의 크기·방향이 다름</li>
<li><strong>다차원</strong> — 인프라·부동산·제조업 투자가 28개 업종에 <em>서로 다른 경로</em>로 퍼짐</li>
<li><strong>척도 특이적</strong> — 단기(몇 개월) 반응과 장기(몇 년) 추세가 전혀 다른 패턴을 보임</li>
</ul>
<p>예: 인프라 투자가 건축자재 주가를 <strong>1개월 뒤</strong> 끌어올리는 효과와, 부동산 투자가 가전 주가를 <strong>1~2년 뒤</strong> 움직이는 효과는 같은 VAR 안에 욱여넣기 어렵다. 그래서 “시간에 따라 변하고, 주파수별로 따로 보는” 도구가 필요하다는 모티베이션.</p>
</div>
</div>
</div>
<p>금융시장 상호연결성을 분석하기 위한 방법론적 지형은 세 가지 점진적 흐름을 따라 발전해 왔다. 첫 번째 흐름은 시간 영역 연결성 측정에 중점을 둔다. Diebold와 Yilmaz (Casoli &amp; Pedini, 2026)는 일반화된 분산분해(generalized variance decomposition)에 기반한 스필오버 지수를 도입하여 시스템 리스크 전이를 정량화하는 기초적 프레임워크를 확립하였다. 그러나 시간 영역 접근법은 주파수 전반에 걸쳐 동질적 동학을 가정하므로, 단기 충격과 장기 구조적 의존성을 구분하는 능력이 제한된다. 두 번째 흐름은 연결성 분석을 주파수 영역으로 확장한다. 스펙트럼 분해 기법은 단기 및 장기 스필오버 성분을 별도로 식별할 수 있게 한다 (Lovcha &amp; Perez-Laborda, 2020). 그럼에도 불구하고 이러한 주파수 영역 확장은 일반적으로 선형 VAR 구조에 의존하며, 각 주파수 대역 내의 시변 동학을 수용하지 못한다. 세 번째 흐름은 시간-주파수의 동시적 국소화를 달성하는 웨이블릿 분석을 활용한다. 따라서 시간 영역과 주파수 영역에서의 동시적 분해 특성 덕분에, 웨이블릿 분석 기법은 금융 자산의 공동 움직임(co-movement)을 연구하는 데 응용되어 왔다. 웨이블릿 일관성은 다양한 금융시장에 점점 더 널리 적용되고 있다. 핀테크, 녹색채권, 암호화폐 시장에서의 초기 적용 사례는 다중 스케일 의존 구조를 식별하는 데 있어 그 능력을 검증하였으며 (Le et al., 2021), 후속 연구들은 이 접근법을 녹색채권 시장의 위기 전이 분석 (Khalfaoui et al., 2023)과 글로벌 에너지 시장 연계 (Rehman et al., 2023)에까지 확장시켰다. 보다 최근의 연구는 외환 내재 변동성 (Yang, 2025) 및 통화정책 불확실성 스필오버 (Soltani &amp; Abbes, 2025)에서 입증된 바와 같이, 웨이블릿 일관성이 시간 척도 전반에 걸쳐 이질적 정책 충격 전이를 포착함을 보여주었다. 나아가, 웨이블릿 기법을 TVP-VAR 등 전통적 계량경제 모형과 결합하는 방식은 보다 포괄적인 리스크 전이 특성화를 산출하였으며 (Gupta et al., 2020), 글로벌 관광 주식 및 채권 시장에서의 산업 수준 적용 사례는 본 방법론의 광범위한 적용 가능성을 확인해 준다 (Nahiduzzaman et al., 2025).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>쉽게 풀어쓰면
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>“시장 간 영향 분석” 방법론의 3세대 발전사</strong> 라고 보면 됨.</p>
<p><strong>1세대 — 시간 영역만</strong> (Diebold &amp; Yilmaz, 2009/2012)<br>
“A가 B에 얼마나 영향 주나”를 <strong>하나의 평균값</strong>으로 뽑음. 한계: <em>단기 충격</em>(1~2개월)과 <em>장기 구조</em>(수년)가 <strong>한 숫자로 섞여버림</strong>. 투자→주가 반응이 단발성인지 추세성인지 구분 불가.</p>
<p><strong>2세대 — 주파수 영역 추가</strong> (Baruník &amp; Křehlík, 2018 계열)<br>
시간 영역 결과를 <strong>주파수 대역별로 쪼갬</strong>. 단기 스필오버와 장기 스필오버를 따로 볼 수 있게 됨. 한계: 여전히 <strong>선형 VAR</strong> 껍데기 안이라, 관계가 <em>시간이 지남에 따라 변하는</em> 현상(예: 코로나 전후의 구조 변화)은 못 잡음.</p>
<p><strong>3세대 — 시간-주파수 동시 분해 (웨이블릿)</strong> ← 본 논문의 계열<br>
“언제 / 어떤 주기에서 / 얼마나 같이 움직이나”를 <strong>2차원 평면</strong>(시간×주파수)으로 펼침. 최근 핀테크·녹색채권·암호화폐·외환·통화정책 스필오버 등에 폭넓게 쓰이고, TVP-VAR 같은 시변 모형과 섞어 쓰기도 함.</p>
<p>→ 즉 본 논문은 <strong>3세대 웨이블릿 위에 “네트워크 그래프”까지 얹는</strong> 게 포인트. “시간-주파수-네트워크” 3차원 구조를 동시에 본다는 야심.</p>
</div>
</div>
</div>
<p>스필오버 효과와 시간-주파수 분해를 측정하기 위한 다양한 방법론적 도구들이 문헌에서 개발되어 왔음에도 불구하고, 투자-주식 전이 메커니즘과 관련된 상당한 연구 공백이 세 가지 핵심 영역에서 여전히 충분히 연구되지 않은 채 남아 있다. 첫째, 대부분의 웨이블릿 기반 분석은 이변량 또는 저차원 일관성 측정에 국한되어 왔으며, 웨이블릿 일관성 행렬, 위상차 방향 결정, 네트워크 토폴로지를 체계적으로 결합하지 못했다. 이는 기존 연구들 가운데 어느 것도 스필오버 강도, 전이 방향, 네트워크 위치라는 3차원적 특성을 동시에 검토하지 못한 이유를 설명해 준다. 둘째, 최근 연구들이 글로벌 시스템적 중요 금융기관들 사이의 리스크 연계를 분석하기 위한 다계층 네트워크 접근법과, 글로벌 시스템적 중요 금융기관에 대한 다차원 리스크 연계 연구들을 정식화해 왔음에도 불구하고, 투자 사이클 지표를 다산업 주식 수익률에 매핑하면서 동시에 주파수 분해를 수행하는 방향성 가중 네트워크를 실증적으로 구현한 기존 연구는 없다 (Chen et al., 2025). 네트워크 기반의 시스템 리스크 문헌 분석이 해당 분야의 연구 핵심 영역과 진화 경로를 보여주고 있으나, 이질적 산업 특성을 가진 다중 노드 네트워크를 구축·분석하기 위한 운영 가능한 방법론을 제공하지는 못한다 (Rojas Rincón et al., 2025). 가장 중요한 연구 공백은 중국 주식시장과 관련된 산업 간 변동성 스필오버 및 시간적 동학 분석이다. 기존 연구 대부분은 시간 영역 방법론에 의존하고 있어, 특정 제도적 맥락 내에서 신규 인프라 및 이중 탄소(dual-carbon) 정책과 같은 구조적 충격, 그리고 이러한 충격이 시간-주파수 네트워크 채널을 통해 이질적 산업별 주식의 비대칭 전이 메커니즘에 어떤 영향을 미치는지에 관한 실증 분석이 제한적이다 (Xie &amp; Wei, 2025).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 서론의 인용 이상
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>앞 문단에 <strong>“Diebold와 Yilmaz (Casoli &amp; Pedini, 2026)”</strong> 로 인용되어 있음. 일반화 분산분해 기반 스필오버 지수의 원전은 <strong>Diebold &amp; Yilmaz (2009, <em>Economic Journal</em>)</strong> 및 <strong>(2012, <em>IJF</em>)</strong> 임. 2026년 논문이 원전일 수 없음 → 인용 꼬임, 혹은 LLM 생성 때 섞인 허위 인용(hallucinated citation) 의심.</p>
<p>서론 전반에 <strong>핀테크·암호화폐·관광 주식·FDI·외환 내재변동성</strong> 같은 주제 관련도 낮은 인용이 연이어 등장. “웨이블릿이 쓰였다”는 공통점만으로 묶여 있어서, 본 연구의 연구 공백(중국 투자↔︎업종 주가) 주장과 연결 고리가 약함. 리뷰어가 “왜 이 인용이 여기에?”라고 물을 확률 높음.</p>
</div>
</div>
</div>
</section>
<section id="방법론" class="level2">
<h2 class="anchored" data-anchor-id="방법론">2. 방법론</h2>
<section id="데이터-출처-및-전처리" class="level3">
<h3 class="anchored" data-anchor-id="데이터-출처-및-전처리">2.1 데이터 출처 및 전처리</h3>
<p>본 연구는 2010년 1월부터 2025년 9월까지 189개월에 걸친 중국 투자 사이클 데이터 및 업종별 주식시장 데이터를 사용한다. 투자 사이클 데이터는 중국 국가통계국(https://www.stats.gov.cn)에서 발간하는 월간 통계 보고서에서 수집되며, 네 가지 핵심 지표를 포함한다: 완료된 총 고정자산 투자는 월 누적 값을 1차 차분하여 월간 플로우로 변환하고, 부동산 개발 투자는 직접 공표된 월간 데이터를 이용하며, 제조업 투자는 통계 기준(statistical caliber) 조정 문제로 인해 산업 부가가치의 월간 전년동기 대비 성장률을 대리변수로 채택하고, 인프라 투자의 구축은 운송-창고-우편 서비스, 수리-환경-공공시설 관리, 전력-가스-수자원 생산 및 공급의 세 하위 부문 내 고정자산 투자를 합산하여 수행한다. 업종별 주식 데이터는 Wind Economic Database (https://www.wind.com.cn)에서 CITIC Level-1 업종 지수(2021년 판)의 월간 종가로 제공받으며, 은행(801780.SI), 비은행 금융(801790.SI), 부동산(801180.SI) 부문을 제외하여 28개 실물경제 업종을 유지하고, 월간 로그 수익률은 다음과 같이 계산된다:</p>
<p><span class="math display">\[r_t = \ln(P_t / P_{t-1}) \times 100 \tag{1}\]</span></p>
<p>이는 가격 시계열의 이분산성(heteroskedasticity)을 완화하면서 수익률의 시간적으로 일관된 집계를 가능하게 한다. 중국 거시경제 데이터셋에서 흔히 발견되는 계절적 공백 및 비정상성(non-stationarity)을 고려하여, 본 연구는 Census X-13 계절조정 및 달력효과 제거를 적용하고, 이어서 정상성 검정을 위한 augmented Dickey-Fuller 검정과 잔차 자기상관 검정을 위한 Ljung-Box Q 검정을 수행함으로써 중국 금융기관의 상호연결성 연구에서의 데이터 처리 표준을 준수한다 (Qi et al., 2022).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>데이터 실제 모양 — 한 번에 상상하기
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="한-줄-요약" class="level3">
<h3 class="anchored" data-anchor-id="한-줄-요약">한 줄 요약</h3>
<p><strong>189행 × 32열짜리 월간 시계열 테이블 하나</strong>.</p>
<ul>
<li>행(row) = 시점(2010년 1월부터 2025년 9월까지 189개 월)</li>
<li>열(column) = 변수 32개 (투자 지표 4개 + 업종 주가 28개)</li>
</ul>
</section>
<section id="각-열의-단위와-값-감" class="level3">
<h3 class="anchored" data-anchor-id="각-열의-단위와-값-감">각 열의 단위와 값 감</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>컬럼 종류</th>
<th>개수</th>
<th>단위</th>
<th>전형적 범위</th>
<th>가공 방식</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>① 총 고정자산 투자 (월간 플로우)</td>
<td>1</td>
<td>조 위안</td>
<td>2010년 ~1조 → 2025년 ~8–10조</td>
<td>누적값 1차 차분</td>
</tr>
<tr class="even">
<td>② 부동산 개발 투자</td>
<td>1</td>
<td>조 위안</td>
<td>2010년 ~0.3조 → 2021년 ~1.2조 → 2024년 ~0.7조</td>
<td>원본 월간</td>
</tr>
<tr class="odd">
<td>③ 인프라 투자 (3부문 합산)</td>
<td>1</td>
<td>조 위안</td>
<td>2010년 ~0.5조 → 2025년 ~2–3조</td>
<td>운송+수리+전력가스 합</td>
</tr>
<tr class="even">
<td>④ 제조업 산업VA YoY</td>
<td>1</td>
<td>퍼센트(%)</td>
<td>−10 ~ +15 (코로나 시 −25)</td>
<td>전년동월대비 성장률</td>
</tr>
<tr class="odd">
<td>업종별 주가 로그수익률</td>
<td><strong>28</strong></td>
<td>퍼센트(%)</td>
<td>월간 보통 −20 ~ +20</td>
<td><span class="math inline">\(\ln(P_t/P_{t-1})\times 100\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="실제-테이블-이미지-감-잡기용-실제-본문-값-아님" class="level3">
<h3 class="anchored" data-anchor-id="실제-테이블-이미지-감-잡기용-실제-본문-값-아님">실제 테이블 이미지 (감 잡기용 — 실제 본문 값 아님)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>월</th>
<th>총투자(조)</th>
<th>부동산(조)</th>
<th>인프라(조)</th>
<th>제조VA(%)</th>
<th>건축자재(%)</th>
<th>철강(%)</th>
<th>전력설비(%)</th>
<th>자동차(%)</th>
<th>컴퓨터(%)</th>
<th>… (28개 전체)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2010-01</td>
<td>0.8</td>
<td>0.22</td>
<td>0.32</td>
<td>20.7</td>
<td>4.2</td>
<td>−1.8</td>
<td>6.3</td>
<td>8.1</td>
<td>2.1</td>
<td>…</td>
</tr>
<tr class="even">
<td>2015-06</td>
<td>4.1</td>
<td>0.81</td>
<td>1.15</td>
<td>6.1</td>
<td>−3.4</td>
<td>−8.7</td>
<td>12.5</td>
<td>−1.2</td>
<td>−2.3</td>
<td>…</td>
</tr>
<tr class="odd">
<td>2020-04</td>
<td>3.8</td>
<td>0.78</td>
<td>1.02</td>
<td>3.9</td>
<td>11.2</td>
<td>6.8</td>
<td>18.4</td>
<td>7.3</td>
<td>4.7</td>
<td>…</td>
</tr>
<tr class="even">
<td>2023-01</td>
<td>5.1</td>
<td>0.65</td>
<td>1.72</td>
<td>2.4</td>
<td>−5.3</td>
<td>−8.2</td>
<td>−1.1</td>
<td>2.8</td>
<td>3.1</td>
<td>…</td>
</tr>
<tr class="odd">
<td>2025-09</td>
<td>8.1</td>
<td>0.68</td>
<td>2.43</td>
<td>5.8</td>
<td>2.1</td>
<td>1.3</td>
<td>4.2</td>
<td>5.6</td>
<td>6.9</td>
<td>…</td>
</tr>
</tbody>
</table>
<p>이런 표가 <strong>189줄</strong> 쌓여 있다고 보면 됨.</p>
</section>
<section id="한-시점의-구조" class="level3">
<h3 class="anchored" data-anchor-id="한-시점의-구조">“한 시점”의 구조</h3>
<p>예를 들어 2023년 5월 한 달의 관측치는 아래 <strong>32차원 벡터</strong> 하나:</p>
<p><span class="math display">\[
\mathbf{v}_{2023\text{-}05} = (\underbrace{X_1, X_2, X_3, X_4}_{\text{투자 4개}},\ \underbrace{r_1, r_2, \ldots, r_{28}}_{\text{업종 수익률 28개}})
\]</span></p>
<ul>
<li><span class="math inline">\(X_1\)</span>: 총 고정자산 투자 (조 위안)</li>
<li><span class="math inline">\(X_2\)</span>: 부동산 투자 (조 위안)</li>
<li><span class="math inline">\(X_3\)</span>: 인프라 투자 (조 위안)</li>
<li><span class="math inline">\(X_4\)</span>: 제조업 산업VA YoY (%)</li>
<li><span class="math inline">\(r_j\)</span>: <span class="math inline">\(j\)</span>번째 업종의 월간 로그수익률 (%)</li>
</ul>
</section>
<section id="스케일이-완전-다른데-괜찮나" class="level3">
<h3 class="anchored" data-anchor-id="스케일이-완전-다른데-괜찮나">스케일이 완전 다른데 괜찮나?</h3>
<p>맞음 — 투자는 <em>조 위안</em> 레벨이고 주가 수익률은 <em>%</em> 라서 자릿수가 크게 다름. 다만 이 논문이 쓰는 <strong>웨이블릿 일관성</strong> <span class="math inline">\(R^2\)</span> 는 <strong>정규화된 공동 움직임 측도</strong>라 크기 자체는 상쇄됨. 두 시계열이 “같은 리듬으로 오르내리느냐”만 보니까 스케일 차이는 문제 안 됨.</p>
<p>(정확히는 식(3)의 분모 <span class="math inline">\(S(s^{-1}|W_x|^2) \cdot S(s^{-1}|W_y|^2)\)</span> 가 각 시계열의 에너지로 나눠주는 역할.)</p>
</section>
<section id="개-업종이-뭔지" class="level3">
<h3 class="anchored" data-anchor-id="개-업종이-뭔지">28개 업종이 뭔지</h3>
<p>본문에 나열은 없지만 CITIC Level-1(2021판)에서 금융 3개 빼면 대개:</p>
<p>석유석화, 석탄, 비철금속, 전력공익, 철강, 기초화학, 건축자재, 건축, 경공업제조, 기계, 국방군공, 자동차, 상업무역, 소비자서비스, 가전, 방직의류, 식품음료, 농림목어, 의약, 컴퓨터, 미디어, 통신, 전력설비·신에너지, 전자, 운송, 환경보호, 종합, 부동산서비스 등 (판본마다 약간 변동).</p>
</section>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 제조업 투자 대리변수 치명적 치환
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>본문: <strong>“제조업 투자는 통계 기준(statistical caliber) 조정 문제로 인해 산업 부가가치의 월간 전년동기 대비 성장률을 대리변수로 채택”</strong></p>
<ul>
<li><strong>산업 부가가치(industrial value-added)는 산출(output)이지 투자(investment)가 아님</strong>. 투자는 자본 스톡의 증분(flow into capital), 부가가치는 그 자본이 생산한 결과물. 두 변수는 이론적으로도, 회계적으로도 다른 계정.</li>
<li>이 치환으로 연구 질문이 “제조업 <strong>투자</strong> 사이클이 업종 주가를 선행하는가”에서 사실상 “제조업 <strong>경기</strong>가 주가를 선행하는가”로 바뀜. 산업생산과 주가의 공동 움직임은 이미 매우 잘 알려진 결과라 기여도(novelty)가 희석됨.</li>
<li>더 나아가 “4개 투자 지표”라는 서술 자체도 부정확해짐. 실질적으로는 <strong>3개 투자 + 1개 산출</strong> 이 섞여 있음.</li>
</ul>
<p><strong>권고</strong>: (i) 중국 통계국이 공표하는 제조업 고정자산투자 항목을 calibre 조정해서 재구축, 혹은 (ii) 논문 프레임과 변수명에서 “제조업 투자”를 “제조업 경기(manufacturing business cycle)”로 수정해 오도를 제거.</p>
</div>
</div>
</div>
</section>
<section id="웨이블릿-일관성-lead-lag-의존성-네트워크-프레임워크" class="level3">
<h3 class="anchored" data-anchor-id="웨이블릿-일관성-lead-lag-의존성-네트워크-프레임워크">2.2 웨이블릿 일관성 lead-lag 의존성 네트워크 프레임워크</h3>
<p>본 연구는 분산분해(variance decomposition) 유형의 구조적 충격 전이와 달리, 투자 사이클과 업종별 주식 수익률이라는 두 현상에 대한 시간 비대칭적 공동 움직임과 시간적 선행성을 정량화하는, 연속 웨이블릿 변환에 기반한 시간-주파수 lead-lag 의존성 네트워크 프레임워크를 개발한다. Morlet 웨이블릿의 해석적 표현은 다음과 같다:</p>
<p><span class="math display">\[\psi(t) = \pi^{-1/4} e^{i\omega_0 t} e^{-t^2/2} \tag{2}\]</span></p>
<p>중심 주파수 파라미터는 <span class="math inline">\(\omega_0 = 6\)</span>으로 설정되며, 스케일 파라미터는 <span class="math inline">\(s \in \{2, 4, 8, 16, 32, 64, 128\}\)</span>로 설정되어 2개월부터 128개월까지의 주기에 대응하며, 투자-주식시장 전이의 단기 충격, 중기 사이클, 장기 추세를 동시에 포착한다. 빠른 푸리에 변환(Fast Fourier transform)은 1024점 이산화를 통해 효율적 계산을 달성하며, 단일 시계열 변환의 복잡도는 <span class="math inline">\(O(N \log N)\)</span>이다. 웨이블릿 일관성 측도는 두 시계열 간의 특정 스케일과 시점에서의 공동 움직임 강도를 정량화한다:</p>
<p><span class="math display">\[R^2(s,\tau) = \frac{|S(s^{-1}W_{xy})|^2}{S(s^{-1}|W_x|^2) \cdot S(s^{-1}|W_y|^2)} \tag{3}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>식(3) <span class="math inline">\(R^2\)</span> — 언제 커지고 언제 작아지나
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="한-줄-핵심" class="level3">
<h3 class="anchored" data-anchor-id="한-줄-핵심">한 줄 핵심</h3>
<p><span class="math inline">\(R^2(s, \tau)\)</span> 는 <strong>“스케일 <span class="math inline">\(s\)</span> 에서 두 시계열이 얼마나 같은 리듬으로 호흡하는가”</strong> 를 <span class="math inline">\([0, 1]\)</span> 사이 값으로 잡는다. 값이 <strong>크려면 두 조건 모두</strong> 필요:</p>
<ol type="1">
<li><strong>같은 주파수 성분이 양쪽 시계열에 존재</strong> (겹치는 주기)</li>
<li><strong>그 성분이 일정한 위상 관계</strong>를 유지 (구조적 연결)</li>
</ol>
</section>
<section id="시나리오별-r2-값-모두-스케일-s2개월-기준" class="level3">
<h3 class="anchored" data-anchor-id="시나리오별-r2-값-모두-스케일-s2개월-기준">시나리오별 <span class="math inline">\(R^2\)</span> 값 — 모두 스케일 <span class="math inline">\(s=2\)</span>개월 기준</h3>
<section id="예-1-완벽-동조-같은-주기-같은-위상" class="level4">
<h4 class="anchored" data-anchor-id="예-1-완벽-동조-같은-주기-같은-위상">🟢 예 1 — 완벽 동조 (같은 주기, 같은 위상)</h4>
<pre><code>x(t):   /\    /\    /\    /\    /\    /\
y(t):   /\    /\    /\    /\    /\    /\     (정확히 같이 진동)</code></pre>
<p><span class="math inline">\(R^2 \approx 1.0\)</span> (최대), 위상차 <span class="math inline">\(\phi = 0\)</span></p>
<hr>
</section>
<section id="예-2-같은-주기-일정한-시차-투자-주가-선행-케이스" class="level4">
<h4 class="anchored" data-anchor-id="예-2-같은-주기-일정한-시차-투자-주가-선행-케이스">🟢 예 2 — 같은 주기, 일정한 시차 (<strong>투자 → 주가 선행</strong> 케이스)</h4>
<pre><code>x(t):   /\    /\    /\    /\    /\    /\      (인프라 투자)
y(t):     /\    /\    /\    /\    /\    /\    (철강 주가, 1/4주기 지연)</code></pre>
<p><span class="math inline">\(R^2 \approx 0.9\)</span> (여전히 높음), <span class="math inline">\(\phi \approx \pi/4\)</span></p>
<p>→ <strong>시차가 있어도 일정하게 유지되면 <span class="math inline">\(R^2\)</span> 는 높음</strong>. 이게 본 논문이 lead-lag 관계를 잡아내는 원리.</p>
<hr>
</section>
<section id="예-3-주기가-다름" class="level4">
<h4 class="anchored" data-anchor-id="예-3-주기가-다름">🔴 예 3 — 주기가 다름</h4>
<pre><code>x(t):   /\    /\    /\    /\    /\    /\    (2개월 주기)
y(t):   /──\──/──\──/──\──/──\──/──\──/     (5개월 주기)</code></pre>
<p><span class="math inline">\(R^2 \approx 0.1\)</span> (낮음)</p>
<p>→ <strong>스케일 <span class="math inline">\(s=2\)</span> 에서 y의 에너지 <span class="math inline">\(|W_y|^2\)</span> 가 거의 없음</strong> (y 는 2개월 주기 성분이 없으니까). 그 주파수 대역에서 공유할 게 없음.</p>
<hr>
</section>
<section id="예-4-같은-주기-위상이-들쭉날쭉" class="level4">
<h4 class="anchored" data-anchor-id="예-4-같은-주기-위상이-들쭉날쭉">🔴 예 4 — 같은 주기, 위상이 들쭉날쭉</h4>
<pre><code>x(t):   /\    /\    /\    /\    /\    /\
y(t):   /\    \/    /\    \/    /\    \/    (위상이 뒤집어지며 불규칙)</code></pre>
<p><span class="math inline">\(R^2 \approx 0.2\)</span> (낮음)</p>
<p>→ 주기는 겹치지만 <strong>구조적 연결이 없음</strong>. 평활 윈도우 안에서 복소 교차 스펙트럼 <span class="math inline">\(W_{xy} = W_x \cdot \overline{W_y}\)</span> 의 복소수들이 서로 <strong>상쇄</strong>됨(양의 복소수 + 음의 복소수 → 0 근처).</p>
<hr>
</section>
<section id="예-5-한쪽은-진동-한쪽은-추세만" class="level4">
<h4 class="anchored" data-anchor-id="예-5-한쪽은-진동-한쪽은-추세만">🔴 예 5 — 한쪽은 진동, 한쪽은 추세만</h4>
<pre><code>x(t):   /\    /\    /\    /\    /\    /\    (진동)
y(t):   ────────────────────────────→       (우상향 추세만)</code></pre>
<p><span class="math inline">\(R^2 \approx 0.0\)</span></p>
<p>→ 스케일 <span class="math inline">\(s=2\)</span> 에서 y 의 에너지 <span class="math inline">\(|W_y|^2 \approx 0\)</span>. <strong>그 주파수 대역 자체가 비어 있음</strong>.</p>
<hr>
</section>
<section id="예-6-둘-다-독립-노이즈" class="level4">
<h4 class="anchored" data-anchor-id="예-6-둘-다-독립-노이즈">🔴 예 6 — 둘 다 독립 노이즈</h4>
<pre><code>x(t):   무작위 잡음 1
y(t):   무작위 잡음 2   (독립적으로 생성)</code></pre>
<p><span class="math inline">\(R^2 \approx 0.0 \sim 0.1\)</span> (작은 우연값)</p>
<p>→ 이게 논문의 <strong>몬테카를로 유의성 검정</strong> 이 걸러내는 영역. AR(1) 레드노이즈로 1000개 시계열을 생성해서 <span class="math inline">\(R^2\)</span> 의 95% 분위수를 임계값으로 삼고, 그 이상만 “유의한 일관성”으로 유지.</p>
<hr>
</section>
</section>
<section id="요약-표" class="level3">
<h3 class="anchored" data-anchor-id="요약-표">요약 표</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>상황</th>
<th style="text-align: center;">같은 주기?</th>
<th style="text-align: center;">일정 위상?</th>
<th style="text-align: center;"><span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>완전 동조</td>
<td style="text-align: center;">✅</td>
<td style="text-align: center;">✅ (0차)</td>
<td style="text-align: center;"><strong>~1.0</strong></td>
</tr>
<tr class="even">
<td>일정 시차</td>
<td style="text-align: center;">✅</td>
<td style="text-align: center;">✅ (상수)</td>
<td style="text-align: center;"><strong>~0.9</strong></td>
</tr>
<tr class="odd">
<td>다른 주기</td>
<td style="text-align: center;">❌</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">~0.1</td>
</tr>
<tr class="even">
<td>같은 주기 + 랜덤 위상</td>
<td style="text-align: center;">✅</td>
<td style="text-align: center;">❌</td>
<td style="text-align: center;">~0.2</td>
</tr>
<tr class="odd">
<td>진동 vs 추세</td>
<td style="text-align: center;">❌</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">~0.0</td>
</tr>
<tr class="even">
<td>독립 노이즈</td>
<td style="text-align: center;">❌</td>
<td style="text-align: center;">❌</td>
<td style="text-align: center;">~0.0–0.1</td>
</tr>
</tbody>
</table>
<p>핵심: <strong>위 두 조건(✅ + ✅)이 모두 만족될 때만 <span class="math inline">\(R^2\)</span>가 커짐.</strong></p>
</section>
<section id="본-논문-맥락에서-실제로-일어나는-일" class="level3">
<h3 class="anchored" data-anchor-id="본-논문-맥락에서-실제로-일어나는-일">본 논문 맥락에서 실제로 일어나는 일</h3>
<ul>
<li><strong>인프라 투자 vs 건축자재 주가</strong>: 같은 건설 경기 주기 공유 + 투자가 일정하게 선행 → <span class="math inline">\(R^2\)</span> 높음, <span class="math inline">\(\phi &gt; 0\)</span></li>
<li><strong>인프라 투자 vs 컴퓨터 주가</strong>: 섹터 동학이 서로 다른 주기 → <span class="math inline">\(R^2\)</span> 낮음 → 네트워크에서 엣지 약하거나 없음</li>
<li><strong>제조업 vs 전력설비</strong>: 2020년 탄소중립 선언 이후 공통 주기(정책 드라이브) 강화 → <span class="math inline">\(R^2\)</span> 가 <strong>0.42 → 0.71</strong> 로 상승 (본문 Figure 3B의 주장)</li>
</ul>
</section>
</div>
</div>
</div>
<p>평활화 연산자 <span class="math inline">\(S\)</span>는 시간 영역에서는 스케일 파라미터의 0.6배에 해당하는 이동 윈도우를, 스케일 영역에서는 0.6의 직사각형 윈도우를 사용한다. 위상차는 교차 웨이블릿 스펙트럼의 복소 편각(complex argument)을 통해 추출된다:</p>
<p><span class="math display">\[\phi_{xy}(s,t) = \arctan\left(\frac{\Im W_{xy}(s,t)}{\Re W_{xy}(s,t)}\right) \tag{4}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>식(4) 위상차 <span class="math inline">\(\phi_{xy}\)</span> — “누가 먼저인가”를 복소수 각도로 읽기
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="위상차란" class="level3">
<h3 class="anchored" data-anchor-id="위상차란">위상차란</h3>
<p>교차 웨이블릿 스펙트럼 <span class="math inline">\(W_{xy} = W_x \cdot \overline{W_y}\)</span> 는 <strong>복소수</strong>다. 복소평면 위에서의 <strong>각도</strong>가 바로 위상차:</p>
<ul>
<li>복소수 <span class="math inline">\(a + bi\)</span> 를 극좌표 <span class="math inline">\(re^{i\phi}\)</span> 로 표현 → <span class="math inline">\(\phi = \arctan(b/a)\)</span></li>
<li>여기서 <span class="math inline">\(r\)</span> 은 <strong>크기</strong> (공동 움직임 강도, 식 3의 분자에 들어감)</li>
<li><span class="math inline">\(\phi\)</span> 는 <strong>시점 차이</strong> (두 신호 중 누가 얼마나 먼저인지)</li>
</ul>
<p>직관: 두 싸인파가 있을 때, 파형을 나란히 놓고 <strong>“y 를 얼마나 밀어야 x 와 겹치는가”</strong> 가 위상차.</p>
</section>
<section id="복소평면-위의-네-구역" class="level3">
<h3 class="anchored" data-anchor-id="복소평면-위의-네-구역">복소평면 위의 네 구역</h3>
<pre><code>             Im (허수부) ↑
                        π/2
             ┌──────────┴──────────┐
             │                     │
   ② 역상   │                     │   ① 동상
   x가 y를  │       x가 y를        │
   선행     │        선행          │   
  (π/2, π)  │                     │   (0, π/2)
             │                     │
   ─π ───────┤                     ├───── 0  → Re (실수부)
             │                     │
             │                     │
   ③ 역상   │                     │   ④ 동상
   y가 x를  │       y가 x를        │   
   선행     │        선행          │   y가 x를
 (-π, -π/2) │                     │   선행
             │                     │   (-π/2, 0)
             └──────────┬──────────┘
                       -π/2</code></pre>
<ul>
<li><strong>Im &gt; 0 (위쪽)</strong>: x 가 y 를 선행</li>
<li><strong>Im &lt; 0 (아래쪽)</strong>: y 가 x 를 선행</li>
<li><strong>Re &gt; 0 (오른쪽)</strong>: 동상(in-phase), 같이 오르내림</li>
<li><strong>Re &lt; 0 (왼쪽)</strong>: 역상(anti-phase), 반대로 움직임</li>
</ul>
</section>
<section id="네-구간의-의미-투자x-vs-주가y-예시" class="level3">
<h3 class="anchored" data-anchor-id="네-구간의-의미-투자x-vs-주가y-예시">네 구간의 의미 — 투자(x) vs 주가(y) 예시</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>구간</th>
<th>위상차</th>
<th>선행 관계</th>
<th>상관 부호</th>
<th>경제적 해석</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>①</td>
<td><span class="math inline">\(\phi \in (0, \pi/2)\)</span></td>
<td><strong>x → y</strong></td>
<td>양(+)</td>
<td>투자 ↑ 하면 조금 뒤 주가 ↑ (정상 경기순환)</td>
</tr>
<tr class="even">
<td>②</td>
<td><span class="math inline">\(\phi \in (\pi/2, \pi)\)</span></td>
<td><strong>x → y</strong></td>
<td>음(−)</td>
<td>투자 ↑ 하면 조금 뒤 주가 ↓ (과열·규제 우려 신호)</td>
</tr>
<tr class="odd">
<td>③</td>
<td><span class="math inline">\(\phi \in (-\pi, -\pi/2)\)</span></td>
<td><strong>y → x</strong></td>
<td>음(−)</td>
<td>주가 ↑ 하면 조금 뒤 투자 ↓ (이상 신호)</td>
</tr>
<tr class="even">
<td>④</td>
<td><span class="math inline">\(\phi \in (-\pi/2, 0)\)</span></td>
<td><strong>y → x</strong></td>
<td>양(+)</td>
<td>주가 ↑ 하면 조금 뒤 투자 ↑ (기대 형성 후 현실화)</td>
</tr>
</tbody>
</table>
<p>📌 <strong>본문 서술의 한 구석</strong>: 논문은 <span class="math inline">\(\phi \in (-\pi, 0)\)</span> 을 한 덩어리로 “y가 x를 선행” 이라 처리하는데, 엄밀히는 ③(음 상관)과 ④(양 상관)로 갈라봐야 대칭이 맞음. (앞선 비판모드 callout에서 짚은 지점)</p>
</section>
<section id="위상차-실제-시차개월-변환" class="level3">
<h3 class="anchored" data-anchor-id="위상차-실제-시차개월-변환">위상차 → 실제 시차(개월) 변환</h3>
<p>스케일 <span class="math inline">\(s\)</span> 에서 한 주기(cycle)는 <span class="math inline">\(s\)</span> 개월. 따라서:</p>
<p><span class="math display">\[\Delta t = \frac{\phi_{xy}}{2\pi} \cdot s \quad (\text{개월})\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>예</th>
<th><span class="math inline">\(s\)</span></th>
<th><span class="math inline">\(\phi\)</span></th>
<th>실제 시차</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>단기</td>
<td>2개월</td>
<td><span class="math inline">\(0.34\pi\)</span></td>
<td><span class="math inline">\(\approx 0.34\)</span> 개월 (≈ 10일)</td>
</tr>
<tr class="even">
<td>중기</td>
<td>8개월</td>
<td><span class="math inline">\(\pi/4\)</span></td>
<td><span class="math inline">\(1\)</span> 개월</td>
</tr>
<tr class="odd">
<td>중기</td>
<td>16개월</td>
<td><span class="math inline">\(\pi/4\)</span></td>
<td><span class="math inline">\(2\)</span> 개월</td>
</tr>
<tr class="even">
<td>장기</td>
<td>64개월</td>
<td><span class="math inline">\(\pi/4\)</span></td>
<td><span class="math inline">\(8\)</span> 개월</td>
</tr>
</tbody>
</table>
<p><strong>같은 <span class="math inline">\(\phi\)</span> 여도 <span class="math inline">\(s\)</span> 가 커지면 개월 단위 시차는 비례해서 커짐</strong>. 단기 네트워크의 “1개월 선행”과 장기 네트워크의 “1년 선행”이 반드시 서로 다른 <span class="math inline">\(\phi\)</span> 를 의미하지는 않음 — 서로 다른 <span class="math inline">\(s\)</span> 일 수도 있음.</p>
</section>
<section id="네트워크-엣지로-연결되는-흐름" class="level3">
<h3 class="anchored" data-anchor-id="네트워크-엣지로-연결되는-흐름">네트워크 엣지로 연결되는 흐름</h3>
<p>식(4) 로 <span class="math inline">\(\phi\)</span> 를 뽑고 → 식(5) 에서:</p>
<ol type="1">
<li><span class="math inline">\(\phi &gt; 0\)</span> 인 시점 집합 <span class="math inline">\(T_{ij}^+\)</span> 만 골라냄 (x 가 y 를 선행하는 시기)</li>
<li>그 기간의 <span class="math inline">\(R^2\)</span> 평균 → 엣지 가중치 <span class="math inline">\(W_{ij}\)</span></li>
<li>투자 노드 <span class="math inline">\(i\)</span> → 업종 노드 <span class="math inline">\(j\)</span> 방향의 <strong>가중 유향 엣지</strong> 완성</li>
</ol>
<p>이렇게 모든 쌍에 대해 반복 → 방향성 가중 네트워크 한 장.</p>
</section>
</div>
</div>
</div>
<p>위상차 <span class="math inline">\(\phi_{xy}\)</span>는 스케일 <span class="math inline">\(s\)</span>에서의 진동적 공동 움직임 내의 시간적 선행성을 정량화한다: <span class="math inline">\(\phi_{xy} \in (0, \pi/2)\)</span>일 때 시계열 <span class="math inline">\(x\)</span> (투자)가 <span class="math inline">\(y\)</span> (주식 수익률)를 양의 상관관계로 선행하고, <span class="math inline">\(\phi_{xy} \in (\pi/2, \pi)\)</span>일 때 <span class="math inline">\(x\)</span>가 <span class="math inline">\(y\)</span>를 음의 상관관계로 선행하며, <span class="math inline">\(\phi_{xy} \in (-\pi, 0)\)</span>일 때 <span class="math inline">\(y\)</span>가 <span class="math inline">\(x\)</span>를 선행한다. 이러한 lead-lag 프레임워크는 주파수 영역에서 특정 동기화 하의 정보 흐름 방향을 규정하지만, 계량경제학적 의미의 구조적 인과성에 대한 프레임워크를 구성하지는 않는다. 이는 일관성이 외생적 충격으로 설명되는 분산에 대한 기여가 아니라 공동 움직임의 강도를 측정하기 때문이다. 충격반응 전파와 달리 동기화된 주파수 대역 내의 시간 영역 선행성은 Granger 인과성이나 분산분해 기반 스필오버 지수와는 상이하면서도 상호보완적인 현상을 포착한다. 몬테카를로 시뮬레이션은 1계 자기회귀(AR(1)) 레드 노이즈(red noise)에 기반한 1000개의 참조 시계열을 생성하여 95% 신뢰구간을 구성하며, 일관성 강도 <span class="math inline">\(R^2\)</span>가 임계값을 초과하는 시간-주파수 영역만을 유지한다. 이는 연결성의 구조적 변화 탐지 연구에서 검증된 유의성 검정 전략이다 (Greenwood-Nimmo et al., 2024).</p>
<p>방향성 의존 행렬의 구축은 일관성 강도와 위상차 방향성을 통합한다: 투자 지표 <span class="math inline">\(i\)</span>와 업종별 주식 <span class="math inline">\(j\)</span>에 대해, 양의 위상차를 갖는 시점 집합을 <span class="math inline">\(T_{ij}^{+}\)</span> (<span class="math inline">\(i\)</span>가 <span class="math inline">\(j\)</span>를 선행하는 경우)로 정의하면, lead-lag 의존성 가중치는 다음과 같이 계산된다:</p>
<p><span class="math display">\[W_{ij} = \frac{1}{|T_{ij}^{+}|} \sum_{t \in T_{ij}^{+}} R_{ij}(s,t) \tag{5}\]</span></p>
<p>이 가중치 <span class="math inline">\(W_{ij}\)</span>는 지정된 주파수 대역 내에서 투자 지표 <span class="math inline">\(i\)</span>가 업종별 주식 <span class="math inline">\(j\)</span>를 시간적으로 선행하는 기간 동안의 평균 일관성 강도를 측정하며, 충격 전이 규모보다는 예측적 정보 내용을 반영한다. 이로부터 도출되는 <span class="math inline">\(32 \times 32\)</span> 차원의 방향성 가중 인접행렬 <span class="math inline">\(\mathbf{W}\)</span>는 비대칭적 lead-lag 네트워크 구조를 포착하는데, 엣지 방향은 시간적 선행성을 나타내고 엣지 가중치는 동기화된 공동 움직임 강도를 정량화한다. 임계화(thresholding)는 상위 30 백분위수에 해당하는 연결만을 유지한다. 단기 네트워크 밀도 0.43, 중기 0.31, 장기 0.18로, 이는 유럽 금융 통합 연구에서의 네트워크 특성과의 비교 가능성을 유지한다 (Maurin et al., 2024). 알고리즘 작업 흐름은 다음과 같다: 4차원 투자 시계열 <span class="math inline">\(X\)</span>와 28차원 업종별 수익률 시계열 <span class="math inline">\(Y\)</span>를 입력하고, 각 스케일 <span class="math inline">\(s\)</span>에 대해 연속 웨이블릿 변환, 일관성 및 위상차 계산, 몬테카를로 유의성 스크리닝, 위상 부호 기반 방향성 스필오버 누적, 시간 평균화, 임계화를 수행하여 다중 스케일 스필오버 행렬 집합 <span class="math inline">\(W(s)\)</span>를 출력한다. 총 계산 복잡도는 <span class="math inline">\(O(M^2 NT \log N)\)</span>이며, <span class="math inline">\(M=32\)</span>, <span class="math inline">\(N=189\)</span>, <span class="math inline">\(T=7\)</span>로, 단일 스레드 실행 시 약 14분이 소요되고 병렬화 시 3.5분으로 단축된다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 방법론 2.2의 4가지 의문
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(1) 위상차 해석의 비대칭 서술</strong>: 본문에서 <span class="math inline">\(\phi_{xy} \in (0,\pi/2)\)</span> 양상관 선행, <span class="math inline">\((\pi/2,\pi)\)</span> 음상관 선행까지 부호를 쪼개 놓고, <span class="math inline">\((-\pi,0)\)</span>은 “y가 x를 선행”이라고 <strong>뭉뚱그림</strong>. 대칭적으로 <span class="math inline">\((-\pi/2,0)\)</span> vs <span class="math inline">\((-\pi,-\pi/2)\)</span>로 쪼개 부호(양/음 상관)를 분리해야 네트워크 엣지 해석이 일관됨.</p>
<p><strong>(2) 식(5) 가중치의 frequency 정보 소실</strong>: <span class="math inline">\(W_{ij} = \frac{1}{|T_{ij}^{+}|}\sum_{t \in T_{ij}^{+}} R_{ij}(s,t)\)</span>. “i가 j를 선행한 기간의 <strong>평균</strong> 일관성”만 남기고 <strong>그 기간이 얼마나 길었는지</strong>(prevalence)는 분모에서 상쇄되어 사라짐. → 단 1기만 강하게 선행한 노드 A와, 100기 동안 꾸준히 같은 강도로 선행한 노드 B가 같은 <span class="math inline">\(W\)</span> 값을 가질 수 있음. <span class="math inline">\(\frac{|T_{ij}^{+}|}{T} \cdot \bar{R}_{ij}\)</span> 같은 <strong>빈도×강도</strong> 형태가 정보 흐름의 지속성을 담기에 더 적절함.</p>
<p><strong>(3) <span class="math inline">\(32\times 32\)</span> 인접행렬 vs 실제 <span class="math inline">\(4 \times 28\)</span> 구조</strong>: 투자 4개 + 업종 28개 = 32노드이지만, <strong>관심 대상 엣지는 투자→업종 방향 <span class="math inline">\(4\times 28 = 112\)</span>개</strong>. 32×32 행렬에는 업종↔︎업종(784엣지), 투자↔︎투자(16엣지)도 포함되는데, 본문에서는 이들 엣지의 해석·처리가 전혀 언급되지 않음. (a) 모두 계산해서 자르는지, (b) 투자→업종만 계산하는지, (c) 업종 간 엣지가 중심성 계산에 섞여 들어가는지 불명확. 특히 업종 간 lead-lag를 섞으면 <span class="math inline">\(DC_j^{\text{in}}\)</span>(업종 j의 내향 차수)이 투자 충격 수용도가 아니라 <strong>업종 간 상호연결</strong>까지 합쳐진 양이 됨 → 해석 붕괴.</p>
<p><strong>(4) 임계화 vs 보고된 밀도의 불일치</strong>: 본문 “상위 <strong>30 백분위수</strong>에 해당하는 연결만을 유지”인데, 곧이어 “단기 밀도 0.43 / 중기 0.31 / 장기 0.18”로 보고. 동일 임계 규칙이면 밀도는 모든 대역에서 0.30이어야 함. 주파수별 임계값을 다르게 적용한 것인지, 몬테카를로 유의성 스크리닝과 임계화의 <strong>순서</strong>에 따라 밀도가 달라진 것인지 서술 필요.</p>
</div>
</div>
</div>
</section>
<section id="네트워크-토폴로지-지표-및-비대칭성-측도" class="level3">
<h3 class="anchored" data-anchor-id="네트워크-토폴로지-지표-및-비대칭성-측도">2.3 네트워크 토폴로지 지표 및 비대칭성 측도</h3>
<p>본 연구는 노드의 시스템적 중요성을 정량화하기 위해 세 가지 범주의 중심성 지표를 계산한다. 연결 중심성은 연결 강도 관점에서 노드의 영향력을 특성화한다: 외향 연결 중심성(out-degree centrality)</p>
<p><span class="math display">\[DC_i^{\text{out}} = \sum_j W_{ij} \tag{6}\]</span></p>
<p>은 노드 <span class="math inline">\(i\)</span>로부터 유출되는 전체 예측적 정보 흐름을 누적하며, 내향 연결 중심성(in-degree centrality)</p>
<p><span class="math display">\[DC_i^{\text{in}} = \sum_j W_{ji} \tag{7}\]</span></p>
<p>은 해당 노드가 수신하는 외부 스필오버 강도를 집계한다. 매개 중심성(betweenness centrality)은 전역적 위상 관점에서 노드의 교량 역할을 평가한다:</p>
<p><span class="math display">\[BC_i = \sum_{s \neq i \neq t} \frac{\sigma_{st}(i)}{\sigma_{st}} \tag{8}\]</span></p>
<p>여기서 <span class="math inline">\(\sigma_{st}\)</span>는 노드 <span class="math inline">\(s\)</span>와 <span class="math inline">\(t\)</span> 사이 최단 경로의 총 개수를, <span class="math inline">\(\sigma_{st}(i)\)</span>는 노드 <span class="math inline">\(i\)</span>를 경유하는 최단 경로의 수를 나타낸다. 합은 <span class="math inline">\(s \neq t\)</span>이고 <span class="math inline">\(i \notin \{s, t\}\)</span>인 모든 노드 쌍 <span class="math inline">\(s\)</span>, <span class="math inline">\(t\)</span>에 대해 이루어진다. 이 지표는 복잡도 <span class="math inline">\(O(M^3)\)</span>의 Floyd-Warshall 알고리즘을 통해 구현되며, 시스템적으로 중요한 기관을 식별하는 데 있어 그 효과가 은행 간 유동성 네트워크 연구에서 확인되었다 (Denbee et al., 2021). 고유벡터 중심성(eigenvector centrality)은 인접행렬의 최대 고윳값에 대응하는 고유벡터를 도출하여 네트워크 내의 위세(prestige) 흐름 메커니즘을 포착한다.</p>
<p>비대칭성 측도는 순 스필오버 지수를 통해 양방향 전이의 불균형을 정량화한다:</p>
<p><span class="math display">\[NSI_i = DC_i^{\text{out}} - DC_i^{\text{in}} \tag{9}\]</span></p>
<p><span class="math inline">\(NSI_i &gt; 0\)</span>일 때 해당 노드는 순 스필오버 송신자로 작용하고, <span class="math inline">\(NSI_i &lt; 0\)</span>일 때는 순 수신자로 기능한다. 방향성 비대칭 비율(directional asymmetry ratio)은 이 측도를 표준화한다:</p>
<p><span class="math display">\[DAR_i = \frac{|NSI_i|}{DC_i^{\text{out}} + DC_i^{\text{in}}} \tag{10}\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>식(6)~(10) 네트워크 지표 — 직관적 의미
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>앞 단계에서 <strong>방향성 가중 네트워크</strong> (32개 노드, 엣지 가중치 <span class="math inline">\(W_{ij}\)</span>) 를 완성했음. 이제 각 노드의 <strong>시스템에서의 역할</strong> 을 숫자로 요약하는 단계. 다섯 지표가 각각 다른 질문에 답함.</p>
<hr>
<section id="식6-외향-중심성-dctextout-얼마나-강한-송신자인가" class="level3">
<h3 class="anchored" data-anchor-id="식6-외향-중심성-dctextout-얼마나-강한-송신자인가">식(6) 외향 중심성 <span class="math inline">\(DC^{\text{out}}\)</span> — “얼마나 강한 송신자인가”</h3>
<p><span class="math display">\[DC_i^{\text{out}} = \sum_j W_{ij}\]</span></p>
<p>노드 <span class="math inline">\(i\)</span> 에서 <strong>나가는 모든 엣지 가중치의 합</strong>.</p>
<p>🎙️ <strong>비유</strong>: 방송국의 <strong>총 송출 전력</strong>.</p>
<ul>
<li>크면 → “다른 여러 노드를 강하게 선행하는 <strong>주도적 송신자</strong>”</li>
<li>논문 예: 단기 네트워크에서 인프라 투자 <span class="math inline">\(DC^{\text{out}} \approx 5.12\)</span> → 거의 모든 실물업종 주가를 선행</li>
</ul>
<hr>
</section>
<section id="식7-내향-중심성-dctextin-얼마나-많이-받는가" class="level3">
<h3 class="anchored" data-anchor-id="식7-내향-중심성-dctextin-얼마나-많이-받는가">식(7) 내향 중심성 <span class="math inline">\(DC^{\text{in}}\)</span> — “얼마나 많이 받는가”</h3>
<p><span class="math display">\[DC_i^{\text{in}} = \sum_j W_{ji}\]</span></p>
<p>노드 <span class="math inline">\(i\)</span> 로 <strong>들어오는 모든 엣지 가중치의 합</strong>.</p>
<p>📻 <strong>비유</strong>: 라디오 수신기의 <strong>총 수신 신호량</strong>.</p>
<ul>
<li>크면 → “여러 노드로부터 신호를 받아먹는 <strong>수동적 수신자</strong>”</li>
<li>논문 예: 건축자재 <span class="math inline">\(DC^{\text{in}} \approx 3.21\)</span> → 사회 총 투자·부동산 투자 등을 이중으로 흡수</li>
</ul>
<hr>
</section>
<section id="식8-매개-중심성-bc-얼마나-중요한-교량인가" class="level3">
<h3 class="anchored" data-anchor-id="식8-매개-중심성-bc-얼마나-중요한-교량인가">식(8) 매개 중심성 <span class="math inline">\(BC\)</span> — “얼마나 중요한 교량인가”</h3>
<p><span class="math display">\[BC_i = \sum_{s \neq i \neq t} \frac{\sigma_{st}(i)}{\sigma_{st}}\]</span></p>
<ul>
<li><span class="math inline">\(\sigma_{st}\)</span>: 노드 <span class="math inline">\(s\)</span> 에서 <span class="math inline">\(t\)</span> 까지의 <strong>최단 경로 개수</strong></li>
<li><span class="math inline">\(\sigma_{st}(i)\)</span>: 그중 <span class="math inline">\(i\)</span> 를 경유하는 것의 개수</li>
<li>모든 쌍 <span class="math inline">\((s, t)\)</span> 에 대해 그 비율을 합산</li>
</ul>
<p>✈️ <strong>비유</strong>: <strong>공항 허브(인천공항)</strong>. 최종 목적지도 출발지도 아니지만, 다른 도시로 가려면 거쳐야 하는 길목.</p>
<ul>
<li>크면 → <strong>정보 흐름의 병목(bottleneck)</strong>. 이 노드가 사라지면 많은 쌍이 연결을 잃거나 우회.</li>
<li><span class="math inline">\(DC\)</span> (출입 모두) 는 낮아도 <span class="math inline">\(BC\)</span> 는 높을 수 있음 — “조용한 실세” 타입</li>
<li>논문 예: 화학 <span class="math inline">\(BC \approx 0.23\)</span> → 투자와 하류 소비재 사이 <strong>가교</strong></li>
</ul>
<hr>
</section>
<section id="식9-순-스필오버-지수-nsi-송신자인가-수신자인가" class="level3">
<h3 class="anchored" data-anchor-id="식9-순-스필오버-지수-nsi-송신자인가-수신자인가">식(9) 순 스필오버 지수 NSI — “송신자인가 수신자인가”</h3>
<p><span class="math display">\[NSI_i = DC_i^{\text{out}} - DC_i^{\text{in}}\]</span></p>
<p><strong>내보낸 양에서 받은 양을 뺀 것</strong>.</p>
<p>💱 <strong>비유</strong>: <strong>무역수지 (수출 − 수입)</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>NSI</th>
<th>의미</th>
<th>논문 예시</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(&gt; 0\)</span></td>
<td><strong>순 송신자</strong> (수출국 타입)</td>
<td>인프라 투자 <span class="math inline">\(+2.37\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(&lt; 0\)</span></td>
<td><strong>순 수신자</strong> (수입국 타입)</td>
<td>건축 인테리어 <span class="math inline">\(-1.62\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\approx 0\)</span></td>
<td><strong>양방향 균형</strong></td>
<td>자동차 <span class="math inline">\(-0.18\)</span></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="식10-방향성-비대칭-비율-dar-단방향성의-정도" class="level3">
<h3 class="anchored" data-anchor-id="식10-방향성-비대칭-비율-dar-단방향성의-정도">식(10) 방향성 비대칭 비율 DAR — “단방향성의 정도”</h3>
<p><span class="math display">\[DAR_i = \frac{|NSI_i|}{DC_i^{\text{out}} + DC_i^{\text{in}}}\]</span></p>
<p><strong>순 방향성 ÷ 전체 활동량</strong>. 범위는 <span class="math inline">\([0, 1]\)</span>.</p>
<p>📊 <strong>비유</strong>: <strong>“무역수지 절댓값 ÷ 총 무역량”</strong> = 무역의 <strong>불균형 비율</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>DAR</th>
<th>의미</th>
<th>비유</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>~1.0</td>
<td>거의 <strong>단방향</strong> (보내기만 / 받기만)</td>
<td>순수 원자재 수출국</td>
</tr>
<tr class="even">
<td>~0.5</td>
<td>한쪽 우세하지만 양쪽 다 있음</td>
<td>약간 수출 우위</td>
</tr>
<tr class="odd">
<td>~0.0</td>
<td><strong>완전 양방향 균형</strong></td>
<td>무역 균형 국가</td>
</tr>
</tbody>
</table>
<p><strong>왜 NSI 말고 DAR 도 필요한가</strong>: NSI 만 보면 “크기”만 잡히고 “얼마나 치우쳤는지”는 안 보임. 예컨대:</p>
<ul>
<li>A: <span class="math inline">\(DC^{\text{out}}=6\)</span>, <span class="math inline">\(DC^{\text{in}}=4\)</span> → NSI <span class="math inline">\(=+2\)</span>, DAR <span class="math inline">\(=0.2\)</span> (크게 활동하지만 비교적 균형)</li>
<li>B: <span class="math inline">\(DC^{\text{out}}=2\)</span>, <span class="math inline">\(DC^{\text{in}}=0\)</span> → NSI <span class="math inline">\(=+2\)</span>, DAR <span class="math inline">\(=1.0\)</span> (작게 활동하지만 완전 단방향)</li>
</ul>
<p>두 노드 NSI 는 같지만 <strong>성격이 완전히 다름</strong>. DAR 이 그 차이를 구별해줌.</p>
<p>논문 예: 인프라 투자 <span class="math inline">\(DAR = 0.81\)</span> → 거의 일방적 송신자 (받는 건 거의 없음)</p>
<hr>
</section>
<section id="개-지표-한눈에-축구-선수-비유" class="level3">
<h3 class="anchored" data-anchor-id="개-지표-한눈에-축구-선수-비유">5개 지표 한눈에 — 축구 선수 비유</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>지표</th>
<th>축구 비유</th>
<th>묻는 질문</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(DC^{\text{out}}\)</span></td>
<td><strong>슈팅 시도 횟수</strong></td>
<td>얼마나 적극적으로 내보내나?</td>
</tr>
<tr class="even">
<td><span class="math inline">\(DC^{\text{in}}\)</span></td>
<td><strong>받은 패스 횟수</strong></td>
<td>얼마나 많이 받나?</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(BC\)</span></td>
<td><strong>플레이메이커 역할</strong></td>
<td>나를 거쳐야 플레이가 돌아가나?</td>
</tr>
<tr class="even">
<td><span class="math inline">\(NSI\)</span></td>
<td><strong>공격 기여 − 수비 기여</strong></td>
<td>공격수인가 수비수인가?</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(DAR\)</span></td>
<td><strong>포지션 순도</strong></td>
<td>전문 공격수/수비수인가, 만능 올라운더인가?</td>
</tr>
</tbody>
</table>
<p>이 5개를 <strong>각 노드(32개) × 각 주파수 대역(단기/중기/장기)</strong> 별로 계산 → “단기엔 송신자였다가 중기엔 수신자로 바뀌는” 역할 전환 패턴이 드러남. 본문 3.2절에서 전력설비가 “중기·장기 네트워크에서 순 송신자로 전환”되는 것이 이 프레임워크로 잡힌 결과.</p>
</section>
</div>
</div>
</div>
<p>비율이 1에 근접할수록 스필오버 관계가 단방향 전이 쪽으로 기울어져 있음을 시사한다. 이와 관련하여, 다계층 금융 네트워크 연구들은 위험 전염의 원천을 식별하는 데 있어 이 지표가 갖는 판별력을 지적해 왔다 (Gao et al., 2024). 강건성 검정은 네트워크의 3차원 구조의 신뢰성을 살펴본다. 예컨대 웨이블릿 기저함수 블록의 경우, Morlet, Paul, DOG 기저함수를 사용하여 네트워크 구조를 평가한다. 리샘플링 블록의 경우, 12개월 블록에 대해 1000회 생성 및 리샘플링을 수행한 후, 순 스필오버 지수 순위를 재계산하고 Spearman 순위상관계수를 이용하여 순위 안정성을 평가한다. 순위 강건성 블록의 경우, 연결 강도의 상위 20%, 30%, 40%를 유지하는 세 가지 방식을 사용하여 밀도 파라미터 변화에 따른 핵심 노드의 정체성 변화를 평가한다. 데이터 품질 및 일관성과 최소 15년의 시간 범위 커버리지 간의 균형을 맞추기 위해, 표본 기간은 2025년 9월에 종료되며, 이는 최대 스케일 파라미터인 128개월(10.7년)에서의 장기 웨이블릿 분해를 허용한다.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>강건성 검정 — 왜 이 세 블록인가
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="강건성-검정의-목적" class="level3">
<h3 class="anchored" data-anchor-id="강건성-검정의-목적">강건성 검정의 목적</h3>
<p>연구 결과는 여러 <strong>분석 선택(analysis choice)</strong> 위에서 계산됨:</p>
<ul>
<li>웨이블릿 <strong>어떤 함수</strong>로 잡을까 (Morlet?)</li>
<li><strong>어떤 시점 표본</strong>을 쓸까 (2010~2025?)</li>
<li>엣지를 <strong>얼마나 유지</strong>할까 (상위 30%?)</li>
</ul>
<p>이 선택 하나만 살짝 바꿔도 결과가 뒤집힌다면? → “그 선택 덕에 운좋게 나온 결과”라는 비판 가능. 각 선택에 대해 결과가 얼마나 안정적인지 확인하는 게 <strong>강건성 검정</strong>.</p>
<p>핵심 질문: 결과 <span class="math inline">\(= f(\text{기저함수},\ \text{표본},\ \text{임계값})\)</span> 일 때, <strong>세 인수 각각에 <span class="math inline">\(f\)</span> 가 얼마나 민감한가?</strong></p>
</section>
<section id="세-블록이-세-개의-독립-축을-검사" class="level3">
<h3 class="anchored" data-anchor-id="세-블록이-세-개의-독립-축을-검사">세 블록이 세 개의 독립 축을 검사</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>블록</th>
<th>검증하는 축</th>
<th>묻는 질문</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>① 웨이블릿 기저함수</td>
<td><strong>수학 도구</strong></td>
<td>“Morlet 말고 다른 웨이블릿으로도 같은 결과?”</td>
</tr>
<tr class="even">
<td>② 블록 리샘플링</td>
<td><strong>표본</strong></td>
<td>“189개월이 아닌 다른 시점 조합이었어도 같은 결과?”</td>
</tr>
<tr class="odd">
<td>③ 임계값 강건성</td>
<td><strong>네트워크 정의</strong></td>
<td>“상위 30% 대신 20%·40%여도 같은 핵심 노드?”</td>
</tr>
</tbody>
</table>
<p>세 축이 서로 독립이라 <strong>하나만 검증하면 나머지에서 샌다</strong>. 예: Morlet을 고수한 채 표본만 바꿔 검증하면, “기저함수 덕에 결과가 나온 것”을 못 걸러냄. 그래서 세 블록 <strong>모두</strong> 필요.</p>
<hr>
</section>
<section id="블록-①-웨이블릿-기저함수-교체-morlet-paul-dog" class="level3">
<h3 class="anchored" data-anchor-id="블록-①-웨이블릿-기저함수-교체-morlet-paul-dog">블록 ① — 웨이블릿 기저함수 교체 (Morlet / Paul / DOG)</h3>
<p>세 웨이블릿은 같은 CWT 프레임 안에서 <strong>다른 수학적 성격</strong>을 가짐:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>웨이블릿</th>
<th>수학적 형태</th>
<th>특징</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Morlet</strong> (본 논문 기본)</td>
<td>가우시안 × 복소 지수</td>
<td><strong>주파수 국소화</strong> 우수, 위상 정보 선명</td>
</tr>
<tr class="even">
<td><strong>Paul</strong></td>
<td>복소 다항식</td>
<td><strong>시간 국소화</strong> 우수, 단기 사건에 민감</td>
</tr>
<tr class="odd">
<td><strong>DOG</strong> (Derivative of Gaussian)</td>
<td>실수 함수</td>
<td>위상 정보 약함, 크기만 잘 잡음</td>
</tr>
</tbody>
</table>
<p>→ 세 가지로 돌려서 <strong>네트워크 구조가 비슷하게 나오면</strong> (논문 결과: 상관 0.78~0.91), “Morlet 덕에 나온 결과가 아님”을 확인.</p>
<p>🔧 <strong>비유</strong>: 같은 옷감을 재는데 <strong>줄자 / 접자 / 디지털캘리퍼</strong> 세 도구로 재봄. 세 측정치가 비슷하면 치수는 믿을 만함.</p>
<hr>
</section>
<section id="블록-②-12개월-블록-부트스트랩-리샘플링" class="level3">
<h3 class="anchored" data-anchor-id="블록-②-12개월-블록-부트스트랩-리샘플링">블록 ② — 12개월 블록 부트스트랩 리샘플링</h3>
<p><strong>왜 “개별 관측치”가 아니라 “12개월 블록”인가?</strong></p>
<p>시계열 데이터는 시점 간 자기상관(autocorrelation)이 있음 → 개별 월(月) 을 랜덤하게 섞으면 시계열의 <strong>내부 구조가 부서짐</strong>. 그래서 <strong>블록 단위</strong>로 잘라서 섞음:</p>
<pre><code>원본: [1월][2월][3월]...[189월]
 │
 ▼ 12개월 블록으로 자름
[1-12월 블록][13-24월 블록]...
 │
 ▼ 복원추출로 새 시계열 구성
[25-36월][1-12월][109-120월]...  ← 이렇게 1000번 생성</code></pre>
<p>각 버전에서 <strong>NSI 순위를 다시 계산</strong> → 1000개의 순위 리스트.</p>
<p><strong>Spearman 순위상관계수 <span class="math inline">\(\rho = 0.89\)</span></strong> 는 “원본 순위와 리샘플 순위가 얼마나 일치하는지”:</p>
<ul>
<li><span class="math inline">\(\rho = 1\)</span> → 순위 완전 동일 (매우 강건)</li>
<li><span class="math inline">\(\rho = 0\)</span> → 무관 (불안정)</li>
<li>0.89 → 표본이 조금 달랐어도 “어떤 업종이 송신자고 어떤 업종이 수신자인가”는 거의 그대로</li>
</ul>
<p>🎲 <strong>비유</strong>: 같은 반 학생 100명 중 몇 명만 결석했다고 가정하고 반 평균을 다시 내봄. 1000번 반복했을 때 평균 순위가 크게 안 바뀌면 반 구조가 안정.</p>
<hr>
</section>
<section id="블록-③-임계값-변경-상위-20-30-40" class="level3">
<h3 class="anchored" data-anchor-id="블록-③-임계값-변경-상위-20-30-40">블록 ③ — 임계값 변경 (상위 20% / 30% / 40%)</h3>
<p>식(5)의 <span class="math inline">\(W_{ij}\)</span> 를 다 계산한 뒤 <strong>상위 몇 %만 엣지로 유지</strong> 하는 임계화 단계가 있었음. 기본은 30%인데, 만약 20%(더 엄격)나 40%(더 관대)였다면 다른 결과가 나올 수도 있음.</p>
<p>→ 세 임계값에서 <strong>상위 10개 연결 중심성 산업 중 8개가 공통으로 유지</strong> (논문 결과). 즉:</p>
<ul>
<li>30%에서 중심이던 8개 산업은 20%로 타이트하게 잘라도 살아남음</li>
<li>그리고 40%로 느슨하게 풀어도 여전히 중심</li>
</ul>
<p>→ 임계값 선택이 <strong>결론의 핵심 식별(누가 중심 노드인가)을 바꾸지 않음</strong>.</p>
<p>🗺️ <strong>비유</strong>: 서울 지하철 “주요 환승역”을 5개 꼽을 때 10개든 20개든 뽑아봐도 공통으로 포함되는 역(강남·잠실·사당 등)은 그대로.</p>
<hr>
</section>
<section id="세-블록-통과-강건성-주장-완성" class="level3">
<h3 class="anchored" data-anchor-id="세-블록-통과-강건성-주장-완성">세 블록 통과 → 강건성 주장 완성</h3>
<p>각 블록은 <strong>다른 종류의 실패 가능성</strong>을 막음:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>만약 이 블록이 없었다면</th>
<th>가능한 비판</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>① 빠짐</td>
<td>“Morlet 특유의 평활 효과로 나온 인공 결과 아닌가?”</td>
</tr>
<tr class="even">
<td>② 빠짐</td>
<td>“2020년 코로나 기간만 유독 특이한 샘플이어서 결과가 튄 게 아닌가?”</td>
</tr>
<tr class="odd">
<td>③ 빠짐</td>
<td>“상위 30%를 고른 저자의 임의 결정으로 네트워크 중심이 바뀐 게 아닌가?”</td>
</tr>
</tbody>
</table>
<p>세 개 다 통과 → “우리 발견은 <strong>방법·표본·정의</strong> 세 축 어디에도 크게 의존하지 않는다” 는 주장이 완성됨.</p>
</section>
</div>
</div>
</div>
</section>
<section id="예측-성과-검증-프레임워크" class="level3">
<h3 class="anchored" data-anchor-id="예측-성과-검증-프레임워크">2.4 예측 성과 검증 프레임워크</h3>
<p>예측 성과 검증을 고려한 롤링 윈도우 VAR 프레임워크가 사용되었으며, 학습 기간은 120개월, 검정 기간은 48개월(2021년 10월~2025년 9월)로 설정하고 연결 중심성과 순 스필오버 지수를 외생 예측변수로 사용한다. 기준 모형은 과거 수익률과 거시경제 변수만을 포함하며, 확장 모형에는 네트워크 토폴로지 변수들이 추가된다. 1개월 주가 예측은 평균제곱근오차(RMSE) 및 방향 정확도(DA)를 이용하여 평가되며, 성과 차이의 통계적 유의성은 Diebold-Mariano 검정을 통해 평가된다. 네트워크 회복탄력성(resilience)은 노드 제거 실험을 통해 평가되며, 부동산 투자 노드를 제거한 후 최대 연결 성분의 크기를 계산하여 시스템 분절 위험을 측정한다. 이 반사실적(counterfactual) 분석은 서로 다른 정책 체제에서 네트워크 연결성을 유지하는 데 있어 부동산 투자가 갖는 시스템적 중요성을 정량화한다.</p>
<p>방법론적 한계 및 통계적 해석. 구조적 충격반응이나 분산분해 기반 스필오버 지수와 달리, 웨이블릿 일관성 기반 네트워크 프레임워크는 주파수 특이적(frequency-specific) lead-lag 의존성 구조를 분석하고 정량화한다 (Diebold &amp; Yilmaz, 2012; Sims, 1980). 다만, 동기화된 진동의 경우 위상차가 시간상 사건의 순서를 보여주지만, 추가적인 식별 제약이 없는 경우 외생성이나 구조적 인과성을 증명하지는 못한다는 점에 유의해야 한다. 네트워크 엣지를 기술할 때 사용되는 “스필오버”라는 용어는 충격의 크기라기보다, 대칭적이지 않은 공동 움직임 흐름에 기인한 예측의 방향으로 이해되어야 한다. 표본 외 성과(out-of-sample performance)와 롤링 윈도우 예측은 lead-lag 네트워크 구조가 경제적으로 유의미한 정보 흐름 패턴을 포착함을 실증적으로 확인한다. 이와 관련하여, 높은 외향 차수(out-degree, 다수의 다른 노드를 선행함)와 양의 순 lead-lag 지수를 가진 노드들은 네트워크의 횡단면 수익률 예측력을 통계적으로 강화한다. 따라서 본 네트워크는 거시경제 전이 채널과 부합하는 미래 지향적(forward-looking) 예측 관계를 포착하며, 구조적 연결성 측도에 대한 보완적 통찰을 제공한다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 예측 검증 프레임워크의 약점
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(1) 기준 모형 명세 부족</strong>: “과거 수익률과 거시경제 변수만 포함”이 베이스라인인데 <strong>거시경제 변수가 무엇인지 전혀 명시되지 않음</strong>. 산업생산? CPI? 통화량? 금리? 환율? 몇 개 포함? 시차는? — 18.3% RMSE 감소라는 수치는 베이스라인이 약할수록 커지므로, 베이스라인이 불투명하면 효과 크기 해석 불가.</p>
<p><strong>(2) 네트워크 중심성의 look-ahead 위험</strong>: 중심성이 <em>전체 189개월 표본</em> 위에서 한 번 계산되고 그 값이 48개월 out-of-sample 예측에 투입되었다면, 이것은 <strong>미래 정보를 과거 예측에 주입</strong>한 것 — 공정한 OOS 성능이 아님. 매 롤링 윈도우마다 네트워크를 재추정해야 하는데 본문에 명시가 없음. 재추정한다면 단일 스레드 14분 × 48회 = 약 11시간 → 실제 돌렸다면 명시 필요. 재추정하지 않았다면 18.3% 수치 전체가 look-ahead biased.</p>
<p><strong>(3) “외생 예측변수”라는 표현의 순환성</strong>: 중심성은 웨이블릿 일관성에서 도출되고, 일관성은 투자·업종 수익률 시계열 자체에서 계산됨. 따라서 네트워크 중심성은 <strong>엄밀하게는 외생변수가 아니라 수익률의 비선형 변환</strong>. “외생(exogenous)” 표현은 용어 오용.</p>
</div>
</div>
</div>
</section>
</section>
<section id="결과" class="level2">
<h2 class="anchored" data-anchor-id="결과">3. 결과</h2>
<section id="다중-주파수-lead-lag-의존성-네트워크-구조의-특성" class="level3">
<h3 class="anchored" data-anchor-id="다중-주파수-lead-lag-의존성-네트워크-구조의-특성">3.1 다중 주파수 lead-lag 의존성 네트워크 구조의 특성</h3>
<p>투자 사이클과 업종별 주식 수익률 간 lead-lag 의존성 구조는 다양한 시간 척도에서 상당한 이질성을 보인다. 네트워크 토폴로지는 주파수에 따라 고밀도 단기 연계에서 희소한 장기 의존성으로 변화한다. Figure 1은 단기, 중기, 장기 주파수 계층에 걸친 다중 스케일 웨이블릿 lead-lag 의존성 네트워크의 전반적 모습을 제공한다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_01.png" class="img-fluid"></p>
<p>Figure 1A는 2-4개월 내의 고밀도 상호연결이 가속화됨을 보여주며, 이는 예측적 lead-lag 관계를 통해 투자로부터 주가로의 정보 흐름을 신속하게 촉진한다. 건축자재는 내향 중심성 점수 3.21로 최상위에 위치하는데, 이는 사회 총 건설 투자와 부동산 투자(각각 lead-lag 의존성 가중치 0.87과 0.76)로부터의 이중 견인에 기인한다. 기계와 화학 업종은 각각 2.94와 2.67의 내향 중심성으로 그 뒤를 잇는다. 투자 지표는 주식시장을 약 1개월 선행하며, 위상차 <span class="math inline">\(0.34\pi\)</span>는 8-10 거래일 간격에 대응한다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 단위 혼동 (월간→거래일)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>“위상차 <span class="math inline">\(0.34\pi\)</span>는 <strong>8-10 거래일</strong> 간격에 대응”</p>
<ul>
<li>원 데이터는 <strong>월간(monthly)</strong> 이고, 최소 스케일이 <span class="math inline">\(s=2\)</span>개월. 월간 시계열은 <strong>거래일(daily) 해상도를 구조적으로 가질 수 없음</strong>.</li>
<li>수식상으로는 <span class="math inline">\(s=2\)</span>개월에서 <span class="math inline">\(\frac{0.34\pi}{2\pi}\times 2 = 0.34\)</span>개월 <span class="math inline">\(\approx 10\)</span>일이 나올 수 있지만, 이것은 “일별 데이터에서 10일”이 아니라 <strong>월간 주기의 위상차를 ‘일’ 단위로 환산한 수학적 기댓값</strong>. 월간 관측 한 점 사이의 내부 동학은 관측되지 않은 영역이라 일 단위 해석은 무근거.</li>
<li>본문 표현은 독자가 일별 고빈도 해상도가 있는 것처럼 오해하게 만듦. “월의 1/3에 해당하는 위상 진행” 정도로 쓰거나, 이 수치 자체를 빼는 편이 정직함.</li>
</ul>
</div>
</div>
</div>
<p>투자 노드가 외향 중심성의 38%를 차지하는 스타 토폴로지는 투자가 지배적인 거시 선행지표로서의 위상을 강화한다. Figure 1B에서 보듯, 모듈성 계수가 0.42로 상승하는 모듈 구조가 존재하며, 이는 세 개의 기능적 하위 모듈로 세분될 수 있다: 전통적 산업 연쇄 모듈은 인프라 투자의 신호를 석탄, 철강, 건축자재로 전달하며 각각의 lead-lag 의존성 가중치는 0.61, 0.54, 0.48로, “투자-에너지-원자재-건설”의 연쇄를 형성한다; 신흥 산업 모듈은 제조업 투자를 강도 0.71로 전력설비와 연결한 뒤 0.53으로 자동차와 연결하여 구조적 전환을 시사한다; 소비 모듈에서는 부동산 투자가 후속 소비 품목인 가전 및 소매와 각각 0.42, 0.37로 연관된다.</p>
<p>Figure 1C는 전력설비와 제조업 투자 사이에서 양방향 전이가 발전하고 있음을 보여준다. 투자 진흥은 2010년부터 2015년까지 73%의 양의 위상차로 우세하였으나, 2021년 “3대 레드라인(three red lines)” 정책 이후 붕괴하여 0.32로 급락하였다. 2024-2025년에 예정된 “화이트리스트(whitelist)” 규제 완화 및 저렴한 주택 건설 정책에도 불구하고, 종단적 lead-lag 효과는 실질적인 회복의 부재를 계속 보여주며, 일관성은 0.28-0.35 구간에서 정체되어 있다. 이는 산업 연쇄 연계의 규제 관련 재구성이 상당 기간 지속되고 있음을 시사한다. Table 1은 세 가지 주파수 수준에서 네트워크의 위상적 특성과 핵심 노드 차수 측정 지표를 정량적으로 요약한다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_02.png" class="img-fluid"></p>
<p>Table 1은 주파수 의존적 네트워크 구조 법칙을 강조하는 주파수 간 분석을 제시한다. 네트워크의 단기 고밀도 특성은 투자 지표와 업종별 주식 수익률 간의 급속한 공동 움직임을 반영한다. 총 투자와 부동산 투자의 외향 중심성은 각각 5.12와 4.87로, 다른 노드들보다 유의하게 높다. 스타 토폴로지는 신호 정책의 신속하고 효율적인 전파를 촉진한다. 또한 중기 네트워크 구조의 모듈성이 주목할 만한데, 모듈성 계수가 0.42에 이르러 단기 네트워크의 0.28에 비해 50% 높다. 세 하위 모듈 간에는 엣지 밀도에서 뚜렷한 차이가 있다: 산업 연쇄가 0.51로 가장 높고, 신흥 산업 모듈이 0.47, 소비 모듈이 0.39로 뒤를 이으며, 이는 산업 클러스터 간의 연계 변동성을 반영한다. 기간이 경과함에 따라 네트워크는 매우 뚜렷한 희소화 경향을 보이며, 이는 유효 엣지 수가 단기 네트워크의 412개에서 장기 네트워크의 97개로 감소한 것에서 확인된다. 부동산 투자 노드의 외향 중심성은 3.21로 여전히 최상위이지만, 단기 네트워크 대비 36% 감소한 수치이다. 매개 중심성이 0.18에서 0.09로 감소한 것은 장기 전이 경로에 대한 의존의 단순화와 집중을 보여준다. 단기 네트워크의 평균 경로 길이는 1.68이고 장기 네트워크는 2.84로, 더 크고 지연된 정보 전이가 낮은 주파수와 연관된다는 점은 시간 기반의 다중 스케일 lead-lag 의존 구조와 그 계층적 속성을 확인해 준다.</p>
</section>
<section id="산업-비대칭-역할의-식별" class="level3">
<h3 class="anchored" data-anchor-id="산업-비대칭-역할의-식별">3.2 산업 비대칭 역할의 식별</h3>
<p>산업 역할 분류별 순 스필오버 지수 분석은 투자-주식시장 네트워크 내에서 시스템적 송신자와 시스템적 수신자 간의 명확한 구분을 식별해 낸다. Figure 2는 각 산업의 순 스필오버 순위와 그 시간적 진화 경로를 도시한다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_03.png" class="img-fluid"></p>
<p>Figure 2A는 가장 두드러진 시스템 구동 능력을 지닌 주요 핵심 선행 지표들을 보여준다. 인프라 투자는 순 lead-lag 지수 값 2.37과 방향성 비대칭 비율 0.81로 가장 강한 선행 강도를 나타낸다. 또한 전통 산업 연쇄 연계 내에서 중기 외향 중심성 4.21을 유지한다. 부동산 투자는 순 lead-lag 지수 1.89, 방향성 비대칭 0.76으로 다양한 주파수 범위에 걸쳐 상대적으로 높은 차수 특성을 유지하지만, 강도 면에서는 주목할 만한 하락이 나타난다: 평균 lead-lag 의존성 가중치(무차원 일관성 계수)는 2010-2020년 구간의 0.53에서 2021-2025년 기간의 0.29로 감소하였으며, 2024-2025년 구간에서는 0.32로 한계적 상승을 보여 지속적 규제 정책의 효과를 확인해 준다. 사회 총 고정자산 투자는 순 lead-lag 지수 1.62, 방향성 비대칭 0.68로, 건축자재 및 화학의 단기 네트워크에 대한 상당한 1-2개월 선행 연결을 반영하며, 이는 Granger 인과성 검정(F=8.34, P&lt;0.01; F=7.21, P&lt;0.01)에서도 뒷받침된다.</p>
<p>Figure 2B는 수동적 반응 위치에 있는 초기 후행 업종들을 보여준다. 건축 인테리어는 순 lead-lag 지수 -1.62와 내향 중심성 3.87을 보이며, 이는 부동산 투자 투입에 대한 강한 의존을 시사한다. 부동산-건축 연쇄의 웨이블릿 일관성은 2015-2018년의 0.82에서 2021-2023년의 0.45로 악화되었고 2024-2025년에는 0.38로 추가 약화되어 규제로 인한 취약성을 반영한다. 순 lead-lag 지수는 2021-2023년 동안 -1.62에서 -2.13으로 악화되었으며, 2024-2025년에는 -2.05로 한계적 개선을 보였다. 건축자재는 순 lead-lag 지수 -1.43과 내향 중심성 3.54를 보이며, 사회 투자와 인프라 투자로부터 단기 탄력성 1.27로 이중의 충격을 받는다. 철강은 순 lead-lag 지수 -1.28과 내향 중심성 3.21을 보이며, 이는 주가 분산의 62%가 투자로부터의 분산분해로 설명되는 전형적 수동적 반응을 시사한다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 자기 모순 (분산분해 언어 누출)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>“철강은 … 주가 분산의 <strong>62%가 투자로부터의 분산분해(variance decomposition)로 설명</strong>되는 전형적 수동적 반응”</p>
<p>그런데 앞선 2.2절·2.4절에서는:</p>
<ul>
<li>“분산분해 유형의 구조적 충격 전이와 <strong>달리</strong>, 본 프레임워크는 … lead-lag 의존성을 정량화”</li>
<li>“네트워크 엣지의 ’스필오버’는 <strong>충격 크기가 아니라 예측 방향</strong>”</li>
</ul>
<p>이라며 분산분해가 <strong>아님</strong>을 명시적으로 선 그어 놓았음. 본 프레임워크가 산출하는 것은 일관성 가중 lead-lag 가중치 <span class="math inline">\(W_{ij}\)</span>이지, Cholesky·일반화 분산분해가 아님. “분산의 62%가 분산분해로 설명”이라는 수치는:</p>
<ul>
<li><ol type="a">
<li>별도 VAR 모형에서 계산된 결과가 섞여 들어왔거나,</li>
</ol></li>
<li><ol start="2" type="a">
<li>용어를 관행적으로 오용했거나 (예: 단순히 <span class="math inline">\(DC^{\text{in}}\)</span>의 비율을 “분산분해”라 지칭),</li>
</ol></li>
<li><ol start="3" type="a">
<li>LLM 생성 과정에서 유사 표현이 주입됨</li>
</ol></li>
</ul>
<p>→ 방법론의 자기 정합성 훼손. 본문의 주 주장을 약화시키는 부분.</p>
</div>
</div>
</div>
<p>양방향 전이 산업들은 주파수에 따른 역할 전환을 보인다. 전력설비는 순 lead-lag 지수 +0.31과 방향성 비대칭 0.19를 보이며, 단기 네트워크에서는 순 수신자로 작용하는 반면, 중기 및 장기 네트워크에서는 순 송신자 역할로 전환된다. 이와 함께 외향 중심성 2.67은 내향 중심성 2.36보다 크다. 2020년 태양광 및 풍력 발전 설비 설치량 증가 이후 위상차는 +0.28에서 -0.17로 변하였으며, 순 lead-lag 지수는 2024-2025년에 +0.48로 상승하여 순 수신자에서 균형 송신자로의 전환을 완성한다. 자동차는 순 lead-lag 지수 -0.18, 방향성 비대칭 0.11로 균형 잡힌 양방향 특성을 유지한다. 화학 산업은 매개 중심성 0.23으로 구조적 공백(structural hole) 위치를 차지하며, 투자와 하류 소비재 간을 교량한다. 산업별 예측 검증 결과는 Table 2에 보고되어 있다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_04.png" class="img-fluid"></p>
<p>Table 2의 VAR 롤링 윈도우 백테스트는 2021년 10월부터 2025년 9월까지 48개월 기간에 걸쳐 네트워크 위치 지표의 예측력을 확인한다. 연결 중심성과 순 스필오버 지수를 포함한 확장 모형은 기준 모형 대비 1개월 앞 주가 예측의 RMSE를 평균 18.3% 감소시키며, 방향 정확도는 11.2% 증가시킨다. 경기 순환 산업들이 가장 큰 개선을 보이는데, 건축자재, 철강, 화학이 각각 RMSE 27.0%, 23.9%, 21.0% 감소를 보여, 네트워크 중심성 정보가 투자 민감 산업의 가격 예측에 유용함을 뒷받침한다. 반면 컴퓨터와 제약과 같은 확장 업종은 각각 9.0%, 10.6%의 완만한 변화만 보여 네트워크 위치에 대한 의존이 낮음을 시사한다. 비대칭성 분석은 고비대칭 산업(<span class="math inline">\(|NSI|&gt;1.2\)</span>)이 RMSE 24.9% 감소로 네트워크 지표로부터 더 많은 이득을 얻는 반면, 저비대칭 산업(<span class="math inline">\(|NSI|&lt;0.5\)</span>)은 8.2%의 개선에 그쳐 이득이 더 적음을 제시한다. Diebold-Mariano 검정은 확장 모형이 기준 모형을 유의하게 능가함을 보여주며 (DM=-3.47, P&lt;0.01), 부동산 규제 및 제조업 변화로 인한 구조적 단절을 포함하는 전체 검정 기간 동안 확장 모형은 예측의 강건성을 입증한다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ “고/저 비대칭” 임계값의 정당화 부재 — 가장 치명적 하자
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>이 논문의 핵심 주장 중 하나가 여기 담겨 있음:</p>
<blockquote class="blockquote">
<p><strong>“고비대칭 산업 (<span class="math inline">\(|NSI|&gt;1.2\)</span>) 은 RMSE 24.9% 감소, 저비대칭 산업 (<span class="math inline">\(|NSI|&lt;0.5\)</span>) 은 8.2% 감소 — 네트워크 지표가 비대칭 산업에 특히 유용하다”</strong></p>
</blockquote>
<p>이 한 문장이 “네트워크 위상 정보 = 거래 가능한 리스크 프리미엄” 주장의 근거. 그런데 기반이 <strong>매우 약함</strong>.</p>
<section id="임계값-1.2-와-0.5-가-어디서-왔는지-아무-근거-없음" class="level3">
<h3 class="anchored" data-anchor-id="임계값-1.2-와-0.5-가-어디서-왔는지-아무-근거-없음">1. 임계값 <span class="math inline">\(1.2\)</span> 와 <span class="math inline">\(0.5\)</span> 가 어디서 왔는지 <strong>아무 근거 없음</strong></h3>
<ul>
<li>표본 분포 분위수(예: 상위 20%)도 아니고</li>
<li>경제 이론이 주는 자연 임계값도 아니고</li>
<li>강건성 검정(2.3절) 세 블록 중 어디에도 “NSI 임계값 민감도”가 <strong>없음</strong></li>
<li>저자의 <strong>ad hoc 선택</strong>이라는 인상을 지우기 어려움</li>
</ul>
</section>
<section id="임계값을-바꾸면-서사가-완전히-달라짐-p-hacking-가능-공간" class="level3">
<h3 class="anchored" data-anchor-id="임계값을-바꾸면-서사가-완전히-달라짐-p-hacking-가능-공간">2. 임계값을 바꾸면 서사가 완전히 달라짐 — <strong>P-hacking 가능 공간</strong></h3>
<p>본문 실제 NSI 값을 대입해 시뮬레이션:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>만약 기준이 이랬다면…</th>
<th>고비대칭 그룹</th>
<th>저비대칭 그룹</th>
<th>예상 효과</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\|NSI\|&gt;1.5\)</span>, <span class="math inline">\(&lt;0.3\)</span></td>
<td>더 극단적으로 선별</td>
<td>더 극단적으로 선별</td>
<td><strong>격차 확대</strong> (예: 30% vs 5%)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\|NSI\|&gt;1.2\)</span>, <span class="math inline">\(&lt;0.5\)</span> (본문)</td>
<td>6개 업종</td>
<td>2~3개 업종</td>
<td><strong>24.9% vs 8.2%</strong></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\|NSI\|&gt;1.0\)</span>, <span class="math inline">\(&lt;0.7\)</span></td>
<td>희석됨</td>
<td>희석됨</td>
<td><strong>격차 축소</strong> (예: 20% vs 15%)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\|NSI\|&gt;0.8\)</span>, <span class="math inline">\(&lt;0.8\)</span> (연속 이분)</td>
<td>대부분 포함</td>
<td>대부분 포함</td>
<td><strong>격차 거의 사라짐</strong></td>
</tr>
</tbody>
</table>
<p>→ 저자가 여러 임계값을 시도해보고 <strong>격차가 가장 극적으로 벌어지는 조합을 골랐을 가능성</strong>을 배제할 수 없음. 사전 등록(pre-registration) 없이는 검증 불가능.</p>
</section>
<section id="이산-비교가-진짜-정보를-숨김" class="level3">
<h3 class="anchored" data-anchor-id="이산-비교가-진짜-정보를-숨김">3. 이산 비교가 진짜 정보를 숨김</h3>
<p>연구 질문이 “비대칭성이 네트워크 지표의 유용성을 결정하는가?”라면, <strong>연속 관계</strong>를 보여야 정직함:</p>
<pre><code>잘 그린 그림 (본문에 없음):
    RMSE
    개선률
     │       ·
   30%│      ··
     │     ···
   20%│    ·· · · ·
     │   ···
   10%│  ··
     │ ··
    0%└──┬────┬────┬──── |NSI|
       0    1    2    3</code></pre>
<p><span class="math inline">\(|NSI|\)</span> vs 개선률의 <strong>산점도/회귀</strong> 한 장이면, 두 개의 단편적 요약(24.9%, 8.2%)이 주는 오해 없이 관계 모양을 전달 가능. 본문은 이 연속 그림을 일부러/무심코 <strong>두 개의 덩어리로 이산화</strong>했음. 그 결과:</p>
<ul>
<li><strong>중간 그룹 (<span class="math inline">\(0.5 \leq \|NSI\| \leq 1.2\)</span>)</strong> 에 대한 성능은 <strong>침묵</strong>. 3~4개 업종이 이 구간에 있을 텐데, 그 결과만 공개해도 “정말 선형 관계인지” 판정 가능.</li>
</ul>
</section>
<section id="토톨로지-위험-정의가-결론을-품고-있음" class="level3">
<h3 class="anchored" data-anchor-id="토톨로지-위험-정의가-결론을-품고-있음">4. 토톨로지 위험 — 정의가 결론을 품고 있음</h3>
<ul>
<li><strong>고비대칭 노드 = 한쪽 방향으로 크게 치우친 노드</strong> (정의)</li>
<li><strong>이런 노드는 네트워크 상 위치가 극단적</strong> (정의에 내재)</li>
<li><strong>극단적 위치는 위치 지표로 예측하기 쉬움</strong> (자명)</li>
</ul>
<p>→ “<span class="math inline">\(|NSI|\)</span> 큰 노드가 네트워크 정보로 예측 잘 된다” = <strong>거의 토톨로지</strong>. 앞서 논의 끝 callout 에서 지적한 <strong>“당연함의 정량화”</strong> 와 같은 맥락.</p>
</section>
<section id="이-흠결이-왜-치명적인가" class="level3">
<h3 class="anchored" data-anchor-id="이-흠결이-왜-치명적인가">5. 이 흠결이 왜 치명적인가</h3>
<ul>
<li>논문의 <strong>정책 함의</strong>(“거래 가능한 리스크 프리미엄”, “동적 섹터 로테이션 전략”)가 대부분 이 격차 수치에 의존</li>
<li>격차가 임계값 cherry-picking 의 산물이라면, 18.3% 평균 효과 위에 얹힌 <strong>“특히 비대칭 산업에서 24.9%”</strong> 주장은 공중에 뜸</li>
<li>결론 5절의 “고비대칭 산업에서 예측 향상이 24.9%에 달하여, 네트워크 위상 위치 데이터가 거래 가능한(tradeable) 리스크 프리미엄을 대표함” 문장이 직격으로 약화됨</li>
</ul>
</section>
<section id="최소한의-방어-방안-저자-입장에서-해야-할-것" class="level3">
<h3 class="anchored" data-anchor-id="최소한의-방어-방안-저자-입장에서-해야-할-것">최소한의 방어 방안 (저자 입장에서 해야 할 것)</h3>
<ol type="1">
<li><strong>임계값 민감도 그리드</strong>: <span class="math inline">\(|NSI|\)</span> 절단점을 <span class="math inline">\(\{0.3, 0.5, 0.7, 1.0, 1.2, 1.5, 1.8\}\)</span> 에 대해 모두 돌려 RMSE 감소율 곡선을 제시</li>
<li><strong>연속 회귀</strong>: <span class="math inline">\(\Delta\text{RMSE}_j = \alpha + \beta |NSI_j| + \epsilon_j\)</span> 로 <strong>계수 <span class="math inline">\(\beta\)</span> 의 유의성과 크기</strong>를 직접 보고</li>
<li><strong>사전 등록</strong>: 분석 설계를 잠금한 뒤 OOS 성능 재측정</li>
<li><strong>중간 구간 공개</strong>: <span class="math inline">\(0.5 \leq |NSI| \leq 1.2\)</span> 인 업종들의 RMSE 감소율 개별 보고</li>
</ol>
<p>세 가지 다 안 하고 두 수치(24.9%, 8.2%)만 던지는 현재 상태는 <strong>양적 주장을 뒷받침한다기보다 독자를 설득하기 위한 수사에 가까움</strong>.</p>
</section>
</div>
</div>
</div>
</section>
<section id="정책-효과의-네트워크-구조에-대한-시변-분석" class="level3">
<h3 class="anchored" data-anchor-id="정책-효과의-네트워크-구조에-대한-시변-분석">3.3 정책 효과의 네트워크 구조에 대한 시변 분석</h3>
<p>특정 정책의 시행은 투자-주식시장 lead-lag 의존성 네트워크의 위상 형성을 변화시키며, 네트워크 속성은 정책 시행 전후에 걸쳐 방법론적 재구성을 보여준다. Figure 3은 팬데믹 전후 및 이중 탄소(dual-carbon) 정책 기간 동안의 네트워크 구조 차이를 도시한다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_05.png" class="img-fluid figure-img"></p>
<figcaption>alt text</figcaption>
</figure>
</div>
<p>Figure 3A는 팬데믹 전후의 네트워크 구조 변화를 강조하며, 전이 경로의 재구성을 보여준다. 2019년 중반, 인프라 투자는 석탄, 철강, 건축자재, 기계, 화학으로 이어졌으며 lead-lag 의존성 가중치는 각각 0.68, 0.63, 0.61, 0.52, 0.49였다. 2021-2022년 중반에 이르러 순위는 전력설비, 건축자재, 환경보호, 자동차, 컴퓨터로 바뀌었으며 가중치는 각각 0.71, 0.58, 0.51, 0.47, 0.38이었다. 전력설비의 강도는 67% 증가한 반면, 석탄은 측정 가능한 수준으로 하락하였고 철강은 8% 감소하였다. 이는 전통 인프라에서 신(新) 인프라로의 전략적 전환을 반영한다.</p>
<p>Figure 3B는 이중 탄소 정책이 발전설비에 미치는 효과를 도시한다. 2020년 9월 탄소중립 선언 이후, 투자-주식의 선행 시차는 2021년까지 8-10개월에서 4-6개월로 단축되었으며, 이로 인해 가격 결정 효율이 42% 개선되었다. 2024-2025년 기간에는 전력설비의 lead-lag 의존성 강도가 0.73에서 유의하게 안정화되는 현상이 관찰되었는데, 이는 태양광 설치량의 높은 수준 유지와 시기를 같이한다. 에너지 저장 및 수소 에너지와 같은 신흥 하위 업종은 독립 노드 특성을 드러내 산업 가치사슬의 뚜렷한 수직적 해체를 반영한다.</p>
<p>Figure 3C는 부동산 규제가 네트워크 비대칭성에 미치는 효과를 드러낸다. “3대 레드라인(Three Red Lines)” 정책은 부동산 투자의 선행 역할을 유의하게 축소시키고 하류 산업의 수동적 위치를 악화시켰다. 순 lead-lag 지수의 진화에 대한 상세 분석은 Figure 4B에 제시된다. 네트워크 회복탄력성 검정은 Figure 4와 같이 부동산의 투자 노드를 제거하여 시스템의 충격 대응 능력을 평가한다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_06.png" class="img-fluid"></p>
<p>Figure 4A는 부동산 노드 제거 검정을 바탕으로 네트워크 회복탄력성을 검토한다. 2019년 부동산 노드를 제거했을 때 최대 연결 성분은 노드의 78%를 유지했다. 이 비율은 2022년 61%로 유의하게 감소하였고, 2024-2025년에는 64%로 소폭 반등했지만 여전히 2019년에 비해 현저히 낮다. 이는 부동산 규제가 전통 산업 연쇄에 지속적인 단절 위험을 야기함을 부각시킨다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ Figure 4A 노드 제거 실험의 근거 취약
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>“부동산 투자 노드 제거 → 최대 연결 성분 78% → 61% → 64%” 라는 <strong>숫자 자체</strong> 는 계산으로 나올 수 있지만, 이를 <strong>“부동산 규제의 지속적 단절 위험”</strong> 이라고 결론짓기엔 방법론이 너무 가벼움. 표준 네트워크 회복탄력성 문헌이 요구하는 요소들이 대부분 빠져 있음.</p>
<section id="부동산-투자-노드는-허브hub가-아니라-소스source" class="level3">
<h3 class="anchored" data-anchor-id="부동산-투자-노드는-허브hub가-아니라-소스source">1. 부동산 투자 노드는 “허브(hub)”가 아니라 “소스(source)”</h3>
<p>네트워크 회복탄력성 실험의 원 취지는 <strong>병목 역할의 허브를 파괴했을 때의 충격</strong> 을 보는 것 (Albert-Jeong-Barabási 2000 계열). 그런데 본 논문의 투자 4개 노드는 주로 업종에 엣지를 <strong>내보내는 입력층</strong> 임:</p>
<ul>
<li><span class="math inline">\(DC^{\text{out}}\)</span>: 매우 큼 (부동산 투자 4.87)</li>
<li><span class="math inline">\(DC^{\text{in}}\)</span>: 거의 0 (업종 → 투자 방향 엣지 미미)</li>
</ul>
<p>즉 부동산 투자 노드를 “제거” 하는 것은 병목 허브 파괴가 아니라 <strong>“4개의 입력 신호 중 하나를 끄는 것”</strong> 에 가까움. “노드 제거 실험”이라는 포맷을 빌려오긴 했지만 해석 프레임이 맞지 않음.</p>
</section>
<section id="업종-간-엣지-구조의-불투명성이-결과-해석을-흔듦" class="level3">
<h3 class="anchored" data-anchor-id="업종-간-엣지-구조의-불투명성이-결과-해석을-흔듦">2. 업종 간 엣지 구조의 불투명성이 결과 해석을 흔듦</h3>
<p>앞서(2.2절 비판모드) 지적한 “32×32 vs 실제 4×28” 문제가 여기서 직격으로 작동:</p>
<ul>
<li>업종↔︎업종 엣지가 <strong>거의 없다면</strong>: 부동산 투자 1개 빼도 다른 3개 투자로 업종들이 연결됨 → 최대 성분 크기가 거의 변하지 않아야 함</li>
<li>78 → 61 변화가 실제로 발생했다면: 업종 간 엣지가 <strong>상당히 많이</strong> 포함돼 있어야 함 → 네트워크가 투자-업종 이분 구조가 아니라는 뜻 → 논문의 “투자→업종 선행” 내러티브와 충돌</li>
</ul>
<p>두 경우 모두 본문 설명과 불일치. 어느 쪽인지 구조 명시 없음.</p>
</section>
<section id="무작위-노드-제거-baseline-부재-비교-기준-없음" class="level3">
<h3 class="anchored" data-anchor-id="무작위-노드-제거-baseline-부재-비교-기준-없음">3. 무작위 노드 제거 baseline 부재 — 비교 기준 없음</h3>
<p>“부동산 제거 시 61%”가 <strong>특별히</strong> 타격이 큰 값인지 알려면 대조군 필요:</p>
<ul>
<li><strong>무작위 제거 baseline</strong>: 32개 노드 중 하나를 무작위로 뽑아 제거 → 평균 최대 성분 크기 계산 (여러 회 반복)</li>
<li><strong>다른 투자 노드 제거</strong>: 총투자·인프라·제조업을 각각 제거했을 때 비교</li>
<li><strong>업종 노드 제거</strong>: 건축자재·철강 같은 고차수 업종을 뺐을 때 비교</li>
</ul>
<p>이 대조군이 없으므로, <strong>61% 라는 숫자가 “부동산 특유의 시스템적 중요성”을 반영하는지, 아니면 “어떤 노드 하나 빼도 61% 부근”인지</strong> 구별 불가.</p>
</section>
<section id="통계적-유의성-주장의-근거-누락" class="level3">
<h3 class="anchored" data-anchor-id="통계적-유의성-주장의-근거-누락">4. 통계적 유의성 주장의 근거 누락</h3>
<p>본문: <em>“이 비율은 2022년 61%로 <strong>유의하게</strong> 감소”</em></p>
<ul>
<li>단일 시점의 최대 성분 크기 = <strong>단일 점 추정</strong>. 이게 이전 시점과 “유의하게” 다르려면 불확실성 측정 필요.</li>
<li>방법: bootstrap resampling (시계열 블록 리샘플링 후 네트워크 재추정, 각 버전에서 제거 실험 반복) → 61%의 95% CI 산출</li>
<li>본문엔 신뢰구간도 p-value도 없음. “유의하게”라는 표현 자체가 부적절.</li>
</ul>
</section>
<section id="전반적-네트워크-희소화와-혼동" class="level3">
<h3 class="anchored" data-anchor-id="전반적-네트워크-희소화와-혼동">5. 전반적 네트워크 희소화와 혼동</h3>
<p>2022년 네트워크 자체가 부동산 규제와 <strong>무관하게</strong> 전체적으로 더 성긴 상태일 수 있음 (예: 코로나 이후 산업 동학 둔화로 전반적 일관성 감소). 이 경우:</p>
<ul>
<li><strong>어떤 노드를 빼도</strong> 2022년엔 최대 성분 크기가 낮게 나옴</li>
<li>부동산 노드 제거의 “고유 효과”가 아니라 <strong>밀도 변화의 부산물</strong></li>
</ul>
<p>이를 분리하려면 “같은 시기의 무작위 제거 평균”으로 <strong>정규화</strong>해야 함. 즉 표적 제거 / 무작위 제거 비율을 봐야 함. 본문은 원 수치만 보고.</p>
</section>
<section id="인과-해석의-도약-단절-위험-귀속" class="level3">
<h3 class="anchored" data-anchor-id="인과-해석의-도약-단절-위험-귀속">6. 인과 해석의 도약 — “단절 위험” 귀속</h3>
<p>78 → 61 → 64 라는 변화를 <strong>부동산 규제 탓</strong> 으로 돌리지만 동일 기간 공변량:</p>
<ul>
<li>2020: COVID-19 글로벌 충격</li>
<li>2020.9: 탄소중립 선언 (산업 구조 재편)</li>
<li>2021: 미중 갈등, 공급망 교란</li>
<li>2022: 러우 전쟁, 글로벌 인플레·금리 상승</li>
<li>2024: 중국 소비 부진, 디플레 우려</li>
</ul>
<p>→ 네트워크 구조 변화를 <strong>“부동산 규제 때문”</strong> 이라고 단정하기 어려움. 반사실(counterfactual) 없이 사후 서사.</p>
</section>
<section id="표준-네트워크-회복탄력성-체크리스트-대비" class="level3">
<h3 class="anchored" data-anchor-id="표준-네트워크-회복탄력성-체크리스트-대비">7. 표준 네트워크 회복탄력성 체크리스트 대비</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>표준 요소</th>
<th>본문 수행</th>
<th>누락 여부</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>여러 노드 순차 제거 후 resilience 곡선</td>
<td>❌</td>
<td>누락</td>
</tr>
<tr class="even">
<td>표적 제거 vs 무작위 제거 비교</td>
<td>❌</td>
<td>누락</td>
</tr>
<tr class="odd">
<td>Bootstrap CI / 불확실성 정량화</td>
<td>❌</td>
<td>누락</td>
</tr>
<tr class="even">
<td>엣지 제거(attack) 실험 병행</td>
<td>❌</td>
<td>누락</td>
</tr>
<tr class="odd">
<td>밀도 통제된 정규화</td>
<td>❌</td>
<td>누락</td>
</tr>
<tr class="even">
<td>다른 노드 제거 시 동일 효과 여부</td>
<td>❌</td>
<td>누락</td>
</tr>
<tr class="odd">
<td>점 추정치 단일 보고</td>
<td>✅</td>
<td>유일하게 수행</td>
</tr>
</tbody>
</table>
<p>→ 문헌 표준(Albert et al.&nbsp;2000, Cohen et al.&nbsp;2001) 기준으로 볼 때 <strong>가장 기본적 포맷</strong> 만 흉내낸 수준. “네트워크 회복탄력성 검정”이라 부르기엔 과함.</p>
</section>
<section id="요약" class="level3">
<h3 class="anchored" data-anchor-id="요약">요약</h3>
<p>결국 이 실험은:</p>
<ul>
<li><strong>계산 과정</strong>: 기계적으로는 수행 가능 (숫자 나옴)</li>
<li><strong>해석</strong>: “부동산 규제가 단절 위험을 야기”라는 주장을 지탱하기엔 근거 너무 빈약</li>
<li><strong>방법론</strong>: 네트워크 회복탄력성 문헌의 표준 프로토콜에서 크게 이탈</li>
<li><strong>인과 귀속</strong>: 동시대 다른 거대 충격(코로나, 미중갈등, 금리)을 통제 안 함</li>
</ul>
<p>→ 본 실험은 <strong>“정성적 관찰”</strong> 수준의 증거이지, 결론 5절이 주장하는 수준의 <strong>“시스템 리스크 모니터링 프레임워크”</strong> 근거로는 부적합.</p>
</section>
</div>
</div>
</div>
<p>Figure 4B는 부동산 규제가 네트워크 비대칭성에 미치는 영향을 드러낸다. “3대 레드라인(Three Red Lines)” 정책(2020년 8월 시범 시행, 2021년 본격 시행)은 부동산 투자의 순 lead-lag 지수를 +1.89에서 +0.52로 축소시켰고, 건축 지수를 -1.62에서 -2.13으로 악화시켰으며(수동성 31% 증가), 건축자재 지수도 -1.43에서 -1.96으로 악화시켰다. 2024년 “화이트리스트(whitelist)” 및 저렴한 주택 규제 완화에도 불구하고, 부동산 지수는 +0.58로 한계적으로만 개선되었고 건축은 -2.05에 그쳤으며, 산업 연쇄의 취약성은 지속되었다. 통합적 통화완화와 신(新)질적 생산성 혁신은 2024년 9월 금리 인하 이후 네트워크를 재구성하였다; 제조업 투자의 기계 및 설비에 대한 lead-lag 강도는 0.48에서 0.56으로 증가하였고, 첨단 제조업의 컴퓨터 및 통신 부문에 대한 강도는 0.38에서 0.51로 강화되었다. 이는 표적 구조적 정책 전이의 효과를 검증한다. 부동산 투자의 순 lead-lag 지수는 +0.52에서 +0.58의 낮은 범위에서 정체 상태를 유지하였다. 이는 “신(新)동력 강화, 구(舊)동력 약화”라는 차별화된 패턴을 반영하며, 거시 정책이 미시 수준의 전이 메커니즘에 미치는 이질적 효과를 정량적으로 식별해 준다.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>3.3 방법론 정리 — 시변 네트워크 비교는 어떻게 이루어지나
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="이-하는-일-한-줄" class="level3">
<h3 class="anchored" data-anchor-id="이-하는-일-한-줄">3.3이 하는 일 한 줄</h3>
<p><strong>“네트워크가 정책 이벤트 전후로 어떻게 바뀌었는가”</strong> 를 보이기 위해, 2.2의 파이프라인을 <strong>시점 부분집합별로 재실행</strong>해서 여러 장의 네트워크 스냅샷을 비교.</p>
</section>
<section id="기본-아이디어" class="level3">
<h3 class="anchored" data-anchor-id="기본-아이디어">기본 아이디어</h3>
<p>식(3)의 <span class="math inline">\(R^2(s, \tau)\)</span> 와 식(4)의 <span class="math inline">\(\phi(s, \tau)\)</span> 는 이미 <strong>시간축 <span class="math inline">\(\tau\)</span> 에 국소화</strong>되어 있음. 그래서 전체 189개월 평균이 아니라 <strong>특정 기간의 <span class="math inline">\(\tau\)</span> 값만 골라</strong> 식(5)를 재적용하면, 그 기간의 네트워크 스냅샷을 뽑을 수 있음.</p>
<pre><code>전체 189개월 (2010.1 ~ 2025.9)
    │
    ├── 부분집합 A: 2019년 중반 근처 ──► 네트워크 스냅샷 A
    ├── 부분집합 B: 2021~2022년 중반 ──► 네트워크 스냅샷 B
    ├── 부분집합 C: 2024~2025년       ──► 네트워크 스냅샷 C
    │
    ▼
 스냅샷끼리 비교해서 변화 측정</code></pre>
<p>즉 <strong>같은 공장(2.2)을 시기를 바꿔가며 여러 번 돌리는</strong> 것. 식 자체가 새로 나오진 않음.</p>
</section>
<section id="figure-3-정책-이벤트별-네트워크-변화" class="level3">
<h3 class="anchored" data-anchor-id="figure-3-정책-이벤트별-네트워크-변화">Figure 3 — 정책 이벤트별 네트워크 변화</h3>
<section id="figure-3a-팬데믹-전후-2019-중반-vs-20212022-중반" class="level4">
<h4 class="anchored" data-anchor-id="figure-3a-팬데믹-전후-2019-중반-vs-20212022-중반">Figure 3A: 팬데믹 전후 (2019 중반 vs 2021~2022 중반)</h4>
<p>각 기간에서 <strong>인프라 투자에서 나가는 상위 5개 엣지</strong> 를 꼽고 비교:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>시기</th>
<th>상위 수신 업종 (가중치)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2019 중반</td>
<td>석탄(0.68), 철강(0.63), 건축자재(0.61), 기계(0.52), 화학(0.49)</td>
</tr>
<tr class="even">
<td>2021~22 중반</td>
<td>전력설비(0.71), 건축자재(0.58), 환경보호(0.51), 자동차(0.47), 컴퓨터(0.38)</td>
</tr>
</tbody>
</table>
<p>→ 전력설비 +67%, 석탄·철강은 감소/하락. “전통 인프라 → 신(新) 인프라” 전환의 정량적 증거라고 주장.</p>
</section>
<section id="figure-3b-이중-탄소-정책-2020년-9월-탄소중립-선언" class="level4">
<h4 class="anchored" data-anchor-id="figure-3b-이중-탄소-정책-2020년-9월-탄소중립-선언">Figure 3B: 이중 탄소 정책 (2020년 9월 탄소중립 선언)</h4>
<p><strong>위상차 <span class="math inline">\(\phi\)</span> 를 시차(개월)로 환산</strong> 해서 시간 변화 추적.</p>
<ul>
<li>선언 이전 → 이후: 전력설비 lead-lag 시차 <strong>8~10개월 → 4~6개월</strong> 단축</li>
<li>일관성 <span class="math inline">\(R^2\)</span> 값: 0.42 → 0.71 로 상승</li>
<li>2024-25: 0.73 수준에서 안정화 (태양광 설치량 유지와 동기화)</li>
</ul>
<p>→ “정책 기대 관리가 가격 결정 효율을 42% 높였다”는 주장.</p>
</section>
<section id="figure-3c-3대-레드라인-부동산-규제" class="level4">
<h4 class="anchored" data-anchor-id="figure-3c-3대-레드라인-부동산-규제">Figure 3C: 3대 레드라인 (부동산 규제)</h4>
<p>부동산 투자 → 건축 인테리어의 <strong>양의 위상차 비중 변화</strong> 추적.</p>
<ul>
<li>2010~15: 73% (정상 진흥)</li>
<li>2021 3대 레드라인 후: 0.32 로 급락</li>
<li>2024~25 화이트리스트 완화 후: 0.28~0.35 (회복 실패)</li>
</ul>
<p>→ 양의 위상차 비중이 무너졌다는 건 <strong>“부동산 투자 → 건축 인테리어”가 더 이상 일정한 lead-lag 관계가 아님</strong> 을 의미.</p>
<hr>
</section>
</section>
<section id="figure-4-회복탄력성과-nsi-진화" class="level3">
<h3 class="anchored" data-anchor-id="figure-4-회복탄력성과-nsi-진화">Figure 4 — 회복탄력성과 NSI 진화</h3>
<section id="figure-4a-노드-제거-실험" class="level4">
<h4 class="anchored" data-anchor-id="figure-4a-노드-제거-실험">Figure 4A: 노드 제거 실험</h4>
<p>특정 시기의 네트워크에서 <strong>부동산 투자 노드를 삭제</strong>하고, 남은 그래프의 <strong>최대 연결 성분(largest connected component) 크기</strong>를 측정:</p>
<pre><code>부동산 노드 제거 전 (원본):  32 노드 모두 하나의 컴포넌트
          │
          │ 부동산 노드 삭제
          ▼
부동산 노드 제거 후:  일부 노드가 고립되기도, 컴포넌트가 쪼개지기도
                      │
                      ▼
          "최대 컴포넌트 크기 / 전체 노드 수"를 복원탄력 지표로 사용</code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>시기</th>
<th>제거 후 최대 성분 크기</th>
<th>의미</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2019</td>
<td>78% (≈ 25개)</td>
<td>부동산 빠져도 구조 유지</td>
</tr>
<tr class="even">
<td>2022</td>
<td><strong>61%</strong> (≈ 20개)</td>
<td>12개 노드가 고립/단절</td>
</tr>
<tr class="odd">
<td>2024~25</td>
<td>64%</td>
<td>소폭 회복하지만 여전히 취약</td>
</tr>
</tbody>
</table>
<p>→ “부동산 규제가 실물경제 네트워크의 구조적 의존성을 뚜렷하게 바꿨다”는 주장.</p>
</section>
<section id="figure-4b-nsi-진화" class="level4">
<h4 class="anchored" data-anchor-id="figure-4b-nsi-진화">Figure 4B: NSI 진화</h4>
<p>식(9) <span class="math inline">\(NSI_i = DC_i^{\text{out}} - DC_i^{\text{in}}\)</span> 을 각 시기별로 재계산하고 시간축에 따라 추적:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>노드</th>
<th>3대 레드라인 이전</th>
<th>이후</th>
<th>2024 완화 후</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>부동산 투자</td>
<td><span class="math inline">\(+1.89\)</span></td>
<td><span class="math inline">\(+0.52\)</span></td>
<td><span class="math inline">\(+0.58\)</span></td>
</tr>
<tr class="even">
<td>건축 인테리어</td>
<td><span class="math inline">\(-1.62\)</span></td>
<td><span class="math inline">\(-2.13\)</span></td>
<td><span class="math inline">\(-2.05\)</span></td>
</tr>
<tr class="odd">
<td>건축자재</td>
<td><span class="math inline">\(-1.43\)</span></td>
<td><span class="math inline">\(-1.96\)</span></td>
<td>—</td>
</tr>
</tbody>
</table>
<p>2024.9 금리 인하 후의 변화도 포착:</p>
<ul>
<li>제조업 → 기계·설비: <span class="math inline">\(0.48 \to 0.56\)</span></li>
<li>첨단 제조업 → 컴퓨터·통신: <span class="math inline">\(0.38 \to 0.51\)</span></li>
</ul>
<p>→ “신동력 강화, 구동력 약화” 서사의 정량 근거.</p>
<hr>
</section>
</section>
<section id="이-분석법의-전제-암묵적-가정" class="level3">
<h3 class="anchored" data-anchor-id="이-분석법의-전제-암묵적-가정">이 분석법의 전제 (암묵적 가정)</h3>
<ol type="1">
<li><strong>네트워크 구조가 실제로 “시변”한다는 가정</strong>: 웨이블릿 변환이 이미 <span class="math inline">\(\tau\)</span> 축에서 시간 국소화돼 있긴 하지만, 시기별로 식(5)를 다시 돌린다는 것은 본문에 명시적으로 쓰지 않음 — 암묵 가정.</li>
<li><strong>비교 기간이 충분히 길다는 가정</strong>: 단기 대역(<span class="math inline">\(s=2, 4\)</span>)은 관측 표본이 짧아도 되지만, 장기 대역(<span class="math inline">\(s=32\)</span> 이상)은 작은 하위 기간에선 웨이블릿 COI(cone of influence) 밖으로 빠져 신뢰성 감소.</li>
<li><strong>정책-이벤트 귀속 가정</strong>: 네트워크 변화의 원인을 정책으로 돌리려면 <strong>동시기 다른 충격</strong>(코로나, 미중 갈등, 글로벌 금리)의 기여분을 분리해야 하는데, 본문엔 통제 장치 없음. (사후 서사에 가까움)</li>
</ol>
</section>
<section id="요약-1" class="level3">
<h3 class="anchored" data-anchor-id="요약-1">요약</h3>
<p><strong>같은 파이프라인(2.2) × 다른 시점 윈도우 × 노드 제거 실험</strong> = 3.3의 전부. 식은 새로 등장하지 않고, 해석(narrative) 이 많이 붙음.</p>
</section>
</div>
</div>
</div>
</section>
<section id="네트워크-중심성-지표의-예측력-검증" class="level3">
<h3 class="anchored" data-anchor-id="네트워크-중심성-지표의-예측력-검증">3.4 네트워크 중심성 지표의 예측력 검증</h3>
<p>lead-lag 의존성 구조로부터 도출되는 위상적 속성은 개별 산업의 향후 주가 움직임에 대해 유의미한 추가 예측 가치를 포착하는 능력을 입증하였다. 이러한 예측변수들은 네트워크 내의 위치가 충격 노출을 구조적으로 측정함을 확인해 주지는 않지만, 데이터가 과거 가격-거래량 정보에 불과할 수 있다는 우려에 대해 웨이블릿 일관성 위상차로 기술되는 시간순 관계가 예측적 가치를 가짐을 확인해 준다. 연결 중심성과 순 lead-lag 지수는 정보 흐름 타이밍의 횡단면적 차이를 반영하며, 이는 분산분해 기반 연결성 측도와 관련되어 있으면서도 구별된다. 고전적 시계열 모형에 연결 중심성과 순 유출 지수를 추가하면 예측 성과가 향상된다. Table 3은 네트워크 중심성 지표의 예측 성과 개선 효과를 요약한다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_07.png" class="img-fluid"></p>
<p>Section 3.2 (Table 2)에서 보고된 바와 같이, 연결 중심성과 순 스필오버 지수를 포함하는 확장 VAR 모형은 1개월 앞 RMSE를 평균 18.3% 감소시키고 방향 정확도를 11.2%p 개선하며, 통계적으로 유의한 우위는 Diebold-Mariano 검정(DM = -3.47, P &lt; 0.01)을 통해 확인된다. Table 3은 이러한 예측 이득이 방법론적 변동에 대해 강건한지를 추가로 검토한다. 강건성 검정은 네트워크 중심성 지표의 예측 우위가 특정 파라미터 선택의 산물이 아님을 확인해 준다. 부트스트랩 리샘플링은 순 lead-lag 지수 순위의 안정성을 유지하며 (Spearman <span class="math inline">\(\rho = 0.89\)</span>), 웨이블릿 기저함수 대체는 방법 간 높은 상관관계(0.78-0.91)를 유지하고, 임계값 변동은 밀도 기법 전반에 걸쳐 상위 중심성 산업 10개 중 8개를 유지한다. 이러한 결과들은 본 프레임워크가 포착하는 네트워크 위상 위치 정보가 방법론적 설정에 걸쳐 안정적인, 경제적으로 유의미한 예측 내용을 담고 있음을 종합적으로 검증한다.</p>
</section>
<section id="강건성-검정-결과" class="level3">
<h3 class="anchored" data-anchor-id="강건성-검정-결과">3.5 강건성 검정 결과</h3>
<p>다차원 강건성 검정은 네트워크 구조 식별 결과의 타당성과 알고리즘 파라미터 선택의 강건성을 확인해 준다. Figure 5는 웨이블릿 기저함수 민감도 분석 및 부트스트랩 리샘플링 검정 결과를 도시한다.</p>
<p><img src="attachments/260420_리뷰_웨이블릿lead-lag의존성네트워크로본중국투자-주식시장비대칭전이_08.png" class="img-fluid"></p>
<p>Figure 5A는 순 lead-lag 지수 순위 안정성에 대한 부트스트랩 블록 리샘플링 검정 결과를 도시한다. 12개월 블록 길이와 1000회 리샘플링을 사용하여 평균 Spearman 순위상관계수는 0.89 (95% CI [0.85, 0.92])이다. 표본의 92%에서 상위 15위 내 선행 및 후행 업종의 순위가 상위 10위 내에 보존되어, 189개월 데이터로부터 도출된 비대칭적 기능성에 대한 통계적 강건성 주장을 강화한다. Figure 5B는 Morlet, Paul, DOG 등 다양한 유형의 웨이블릿을 사용한 네트워크 민감도 검정의 구성을 보여준다. 단기 네트워크 상관관계는 0.87과 0.91 사이이며, 중기는 0.85를 상회하고, 장기는 0.78에서 0.82 범위에 걸쳐 있다. lead-lag 의존성 가중치가 0.5를 상회하는 핵심 엣지들은 세 가지 기저함수 전반에 걸쳐 완전한 일관성을 보이며, 이는 웨이블릿 선택의 유연성을 확인해 준다. 20%, 30%, 40%의 연결 유지 방식을 사용한 임계값 강건성 검정을 적용할 경우, 상위 10개 연결 중심성 산업 중 8개가 일관되게 유지되는 것으로 나타났으며, 순 lead-lag 지수 부호 일관성 94%는 밀도 파라미터 변화에 대한 핵심 노드 식별의 비민감성을 입증한다. Figure 5C는 몬테카를로 영모형(null model) 검정을 도시하며, 차수 분포가 보존된 1,000개의 무작위 네트워크를 통제 벤치마크로 사용한 결과를 보여준다. 네트워크의 모듈성 계수 0.42는 무작위 네트워크의 평균 0.18보다 유의하게 높으며 (P &lt; 0.001), 매개 중심성 지니계수 0.61 역시 무작위 네트워크 평균 0.23보다 유의하게 높다 (P &lt; 0.001). 이러한 결과는 네트워크가 무작위적으로 생성되었다는 영가설의 기각을 시사한다. 이는 투자-주식 lead-lag 의존성 네트워크가 순수한 우연이 아닌 경제적 요인에 의해 구동되는 비무작위적 구조적 특성을 가지고 있음을 확인해 준다.</p>
</section>
</section>
<section id="논의" class="level2">
<h2 class="anchored" data-anchor-id="논의">4. 논의</h2>
<p>본 연구는 웨이블릿 일관성 프레임워크를 활용하여 시간-주파수 lead-lag 의존성 네트워크를 구축함으로써, 중국의 투자 사이클과 다양한 산업 주식시장의 비대칭 전이 메커니즘을 규명한다. 투자 주도형 성장 모델에서 비롯된 단기 고밀도 네트워크는 투자 지표와 주식 수익률 간의 신속한 예측적 lead-lag 공동 움직임을 반영한다. 고정자산 투자의 GDP 대비 비중은 42-45% 사이에서 안정적으로 유지되어 왔다. 이는 최종소비지출 비중인 38-40%보다 유의하게 높은 수준이다. 건축자재 산업의 내향 연결 중심성은 3.21에 이르며, 이는 “투자 주문 → 상류 원자재 → 중류 제조업 → 하류 건설”이라는 4단계 전이 사슬의 말단 증폭 효과를 정밀하게 매핑한다. 투자로부터 주가로 이어지는 지배적인 단방향 lead-lag 패턴은 외부금융(은행대출)이 68%, 지분금융이 12%를 구성하는 자금조달 구조와 부합한다. 제한된 역방향 lead-lag 의존성은 비대칭 정보 이론과 부합하며, 미국 및 BRICS 국가 주식시장에서의 패닉 오버플로우(panic overflow) 연구와는 상반된다. 본 연구는 중국의 투자-주식시장 네트워크 방향성 비대칭이 정상 상황과 위기 상황 모두에서 일정하게 유지됨을 보여주는 반면, 금융시장 간의 양방향 전염은 위기 동안 실질적으로 증가한다 (Zhang et al., 2025).</p>
<p>중기 네트워크의 모듈 구조는 정책 지향적 전이에 대한 미시 수준의 증거를 제공한다. 새롭게 제정된 인프라 정책은 전력설비, 통신, 첨단장비 부문에서 인프라 투자로부터의 스필오버 수신 수준을 각각 67%, 42%, 38% 증가시킨 반면, 같은 기간 석탄 및 철강 부문의 lead-lag 의존성 가중치는 각각 32%, 28% 감소시켰다. 네트워크 토폴로지의 체계적 재구성은 “철도 및 기반시설(iron roads and infrastructure)”에서 “신(新)인프라(new infrastructure)”로의 투자 구조의 전략적 전환을 정확하게 포착하였다. 탄소중립 목표가 발표된 이후, 2021년 태양광 및 풍력 발전의 설치 용량은 각각 55.8%, 34.6% 증가하였고, 파동 일관성(wave coherence)은 0.42에서 0.71로 개선되었으며, 투자와 주가의 lead-lag 시간은 10개월에서 5개월로 단축되어 정책 기대 관리가 경제 전이 속도에 미치는 영향을 확인하였다. 거시 구조적 변수들은 지속적인 작용 메커니즘을 통해 자산 가격결정의 기초를 변화시켰다 (Alovokpinhou &amp; Malikane, 2024). 부동산 규제 “3대 레드라인(three red lines)” 정책은 건축 인테리어 및 건축자재 산업의 NSI를 각각 -2.13과 -1.96으로 악화시켰다. 네트워크 회복탄력성 검정은 부동산 노드를 제거할 경우 최대 연결 성분이 2019년 78%에서 2022년 61%로 감소함을 보여주었다. 예측적 산업 연쇄 취약성 지표는 향후 발생 가능한 시스템 리스크를 신호하였다. 이는 핵심 네트워크 코어로서 부동산 투자의 시스템적 중요성과 정책 민감성을 반영하였다 (Berisha et al., 2023).</p>
<p>본 연구의 시간-주파수 네트워크 프레임워크 구축에 사용된 방법론은 세 가지 돌파구를 가져왔다. 시간-주파수 영역에서의 웨이블릿 변환의 이중 분해 능력에 의한 VAR 모델의 시간 불변 파라미터 가정의 극복, 그리고 위상차의 결정은 객관적이고 데이터 주도적인 시간적 선행성 식별 기준을 제시한다. 네트워크 중심성 지수는 고차원 다변량 시스템을 이해 가능한 위상적 특성으로 단순화하며, 그 중 하나는 화학 산업의 매개 중심성이 갖는 교량 역할로서 그 값은 0.23이며, 이는 기존 VAR 충격반응 함수로는 보이기 어려운 결과이다. 지배 전염에서 위험 전염으로의 연구는 시스템 리스크 확산에서의 네트워크 외부성 현상을 부각시키며, 본 연구는 자산 가격결정에서 토폴로지를 설정하는 것의 추가적 가치를 검토한다. 고비대칭 산업의 RMSE는 24.9% 감소하여 저비대칭 산업의 8.2% 감소보다 상당히 컸다 (Jia &amp; Yin, 2024). 은행-자산 이진 네트워크는 다계층 네트워크의 기술적 모델링에 대한 벤치마크를 제공한다. 본 프레임워크를 기존의 연결성 방법론과 비교하는 것은 유익하다. 일반화된 분산분해에 기반한 Diebold-Yilmaz 스필오버 지수는 예측오차 분산 중 변수 간 충격에 기인하는 비율을 정량화하며, 단일 집계 연결성 측도를 제공한다. Baruník-Křehlík의 주파수 영역 확장은 이러한 연결성을 스펙트럼 대역으로 분해하지만, 각 추정 윈도우 내에서 선형 VAR 구조와 시간 불변 파라미터 가정을 유지한다. 여기에서 개발된 웨이블릿 일관성 기반 네트워크 프레임워크는 세 가지 측면에서 차별화된다. 첫째, 이산적 스펙트럼 대역 분해가 아닌 연속적 시간-주파수 국소화를 달성하여, 롤링 윈도우 VAR 접근법이 평활화할 수 있는 일시적 공동 움직임 에피소드의 식별을 허용한다. 둘째, 위상차 분석을 통해 방향성 비대칭을 도입하며, 분산분해 순서에 의존하기보다는 각 시간-주파수 지점에서의 시간적 선행성을 구별한다. 셋째, 네트워크 토폴로지 표현은 쌍별 스필오버 지수로부터는 얻을 수 없는 노드의 시스템적 중요성 측도(연결 중심성, 매개 중심성)의 직접적 계산을 가능하게 한다. 그러나 본 프레임워크는 구조적 충격 전이가 아닌 공동 움직임 기반 lead-lag 의존성을 측정하므로, 분산분해 기반 연결성 분석을 대체한다기보다는 이를 보완한다. 본 연구는 국경 간 전염 모델을 개발하기 위해 원유 가격 및 미연방준비제도(Federal Reserve)가 설정하는 금리와 같은 외생적 충격 변수들을 포함함으로써 확장될 수 있다 (Fan &amp; Hu, 2024). 외국 자본의 철수가 국내 기업의 부가가치율에 어떻게 영향을 미치는지에 관한 연구는 기업 수준에서의 충격에 대한 거시 수준 스필오버 효과를 입증한다. 본 연구에서 식별된 스필오버 강도는 기업 이질성에 의해 야기되는 미시 수준 전이 메커니즘으로 추가적으로 분해될 수 있다 (Xiong et al., 2025).</p>
<p>제안되는 규제 정책은 네트워크 중심성에 기반하여 시스템적으로 중요한 산업을 모니터링하기 위한 보다 포괄적인 프레임워크를 마련하는 것이다. 이 고려사항은 중심성 지수가 3.0을 초과하거나 순 스필오버 지수가 1.5를 초과하는 모든 산업을 포함한다. NSI 악화가 조기에 모니터링되면 시스템 리스크 경보가 정량적으로 신호될 수 있다. 투자 정책을 수립할 때는 전이 시차의 이질적 주파수를 반드시 고려해야 한다. 신(新)인프라 정책의 중기 전이 시차는 4-6개월이다. 주식시장은 정책 시행 전 반년 이내에 반응하는 반면, 실물경제에 대한 효과는 1-2년에 걸쳐 나타난다. 투자 실무 응용 내에서, 동적 산업 로테이션 전략은 NSI 기호를 활용하여 스필오버 방향의 변화를 파악할 수 있다. 전력설비의 NSI는 2020년에 음에서 양으로 변화하였고, 2020-2021년 구간의 성장은 127%였다. 이는 NSI의 지속적 강화에 의해 주도되는 종목 선정의 효능을 확인해 준다. 전염 파동 확산 네트워크 내의 중국 시스템적 금융 리스크 분석은 리스크 상태 전환을 파악하는 데 있어 제도 전환 모델의 중요성을 부각시킨다. 본 연구의 시변 네트워크 분석은 이에 대한 방법론적 대응물(counterpart)이다 (Zhang et al., 2024). 외국인 직접투자의 생산성 이득에 관한 연구는 성(省) 단위를 매개체로 제시한다. 향후 연구는 네트워크 분석 프레임워크 내에서 지역적 이질성을 통합할 수 있다 (Hiep &amp; Trung, 2022).</p>
<p>본 연구의 한계는 세 가지 측면에 있다. 웨이블릿 일관성 프레임워크는 충격의 구조적 전이보다는 lead-lag 관계를 측정한다. 이는 리스크에 대한 보다 총체적 이해를 위해 분산분해 기반 연결성 분석을 확장함을 의미한다. 주파수 특이적 접근법이 다중 스케일 이질성을 유지하긴 하지만, 위기 기간에 지배적일 수 있는 꼬리 의존성(tail dependence) 및 극단적 공동 움직임 패턴을 보이는 데는 덜 효과적이므로, 향후 코퓰러 기반(copula-based) 또는 극단값(extreme value) 기법과 통합하는 것이 권장된다. 집계된 산업 수준 데이터는 개별 기업이 투자에 어떻게 반응하고 네트워크 내에서 어떻게 자리 잡는지에 대한 차이를 은폐한다. 이는 특히 분석 수단이 수천 개 기업으로 구성된 네트워크를 수용할 수 있을 때, 미시 수준 데이터로 분석을 확장할 필요성을 정당화한다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>비판모드 ▷ 기여도 부재 — “당연함의 정량화”
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>앞의 6개 비판은 모두 <strong>테크니컬 하자</strong>(데이터 치환, 수식 편향, 단위 오류, 자기 모순 등)였음. 그러나 이 논문에 대한 <strong>가장 치명적인 공격</strong>은 다른 곳에 있음: <strong>이 모든 정교한 장치가 결국 상식을 확인하는 데 쓰였다</strong>는 점.</p>
<section id="주요-발견의-토톨로지성" class="level3">
<h3 class="anchored" data-anchor-id="주요-발견의-토톨로지성">1. 주요 발견의 토톨로지성</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>논문의 발견</th>
<th>상식 수준 반박</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>건축자재·건설이 건설투자·부동산투자의 영향을 강하게 받음</td>
<td>건축자재 수요 = 건설 수요. <strong>정의상 동어반복</strong></td>
</tr>
<tr class="even">
<td>“투자→에너지→원자재→건설”의 산업 연쇄</td>
<td>1970년대 input-output 교과서 그대로</td>
</tr>
<tr class="odd">
<td>3대 레드라인 이후 부동산→건축 스필오버 약화</td>
<td><strong>정책의 목적 자체</strong>가 그것. 안 약해지면 정책 실패</td>
</tr>
<tr class="even">
<td>탄소중립 선언 이후 전력설비 스필오버 강화</td>
<td>정책 의도대로 자금이 돈 걸 뒤늦게 확인</td>
</tr>
<tr class="odd">
<td>부동산 노드 제거 시 네트워크 연결성 붕괴</td>
<td>중심노드 빼면 네트워크 무너짐 = <strong>네트워크 이론 101</strong></td>
</tr>
<tr class="even">
<td>투자 지표가 주가를 <strong>1개월 선행</strong></td>
<td>월간 투자 통계의 <strong>발표 시차</strong> 자체가 약 1개월 — 정보 공개 스케줄을 lead-lag로 포장한 셈</td>
</tr>
<tr class="odd">
<td>고비대칭(<span class="math inline">\(\|NSI\|&gt;1.2\)</span>) 산업이 네트워크 정보로 더 잘 예측됨</td>
<td>비대칭 = 한쪽으로 정보 흐름. 정의상 예측 가능한 업종 → <strong>토톨로지</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="인과성을-포기했으면-처방도-못-함" class="level3">
<h3 class="anchored" data-anchor-id="인과성을-포기했으면-처방도-못-함">2. 인과성을 포기했으면 처방도 못 함</h3>
<ul>
<li>2.2·2.4절: “구조적 인과성 <strong>아님</strong>, 공동 움직임의 방향일 뿐” 이라 선 그음</li>
<li>논의·결론: 그런데 정작 <strong>규제 당국 시스템 리스크 모니터링 프레임워크</strong>, <strong>동적 산업 로테이션 전략</strong> 같은 <em>처방</em>을 내놓음 → 상관관계로 정책 쓰는 전형적 오류</li>
</ul>
</section>
<section id="rmse-감소의-경제적-유의성-공백" class="level3">
<h3 class="anchored" data-anchor-id="rmse-감소의-경제적-유의성-공백">3. “18.3% RMSE 감소”의 경제적 유의성 공백</h3>
<p>통계적 유의(Diebold-Mariano DM=-3.47)는 있지만:</p>
<ul>
<li><strong>모멘텀, 유동성, 산업 인덱스, Fama-French 팩터</strong>를 통제한 뒤에도 남는 알파인지 검증 없음</li>
<li>투자 지표는 이미 산업 생산·수요의 대리변수 → 업종 주가를 “예측”한다기보다 <strong>회계적으로 연결</strong>된 지표일 개연성</li>
<li>18.3%가 거래비용·슬리피지·리밸런싱 비용을 넘는 수준인지 Sharpe 비교 없음</li>
</ul>
</section>
<section id="정책-주도적-재구성은-사후-해석post-hoc" class="level3">
<h3 class="anchored" data-anchor-id="정책-주도적-재구성은-사후-해석post-hoc">4. “정책 주도적 재구성”은 사후 해석(post-hoc)</h3>
<p>2020년 이후 관찰된 변화를 “신 인프라 정책”, “탄소중립”, “3대 레드라인” 탓으로 귀속시키지만 <strong>반사실(counterfactual) 부재</strong>. 해당 기간은 코로나·글로벌 금리 사이클·중국 경기순환·미중 갈등 등 교란 요인 다수. 동일 변화를 <em>다른 서사</em>로도 쓸 수 있음 → 이야기 맞추기(narrative fitting).</p>
</section>
<section id="종합" class="level3">
<h3 class="anchored" data-anchor-id="종합">종합</h3>
<blockquote class="blockquote">
<p>방법론의 정교함과 발견의 참신함은 별개 축이다. 이 논문은 <strong>축 1(정교함)</strong> 은 높이 평가할 수 있지만, <strong>축 2(통찰)</strong> 에서는 “알고 있던 걸 wavelet·graph·NSI로 재번역했다”는 비판에서 자유롭기 어렵다.</p>
</blockquote>
<p>방어하려면: (i) 상식에 반하는 비직관적 lead-lag 엣지 <em>한두 개</em>를 전면에 세우거나, (ii) 이 프레임워크가 <strong>사전에 예측 불가능했던 체제 전환</strong>(예: 2024년 9월 금리 인하 후 네트워크 재배선)을 <em>포착한 시점</em> 과 <em>실현된 경제 사건의 시점</em> 을 정렬해서, “모델이 사후가 아닌 사전 신호를 줬다”는 사례를 명시적으로 제시하는 것이 필요.</p>
</section>
</div>
</div>
</div>
</section>
<section id="결론" class="level2">
<h2 class="anchored" data-anchor-id="결론">5. 결론</h2>
<p>본 연구에서 개발된 시간-주파수 웨이블릿 lead-lag 의존성 네트워크 프레임워크는 Morlet 웨이블릿 변환, 위상차 시간적 선행성 식별, 방향성 가중 네트워크 토폴로지 분석을 결합한다. 이 프레임워크는 전통적 이변량 분석 및 시간 영역 VAR 모델이 부과한 제약을 뛰어넘어, 투자-주식시장 전이 메커니즘의 다중 스케일 이질성 정량분석을 완수하였다. 2010년 1월부터 2025년 9월까지 중국의 189개월 표본 데이터에 대한 실증 분석에 기반하여, 투자 정보의 신속한 전파는 단기 고밀도 네트워크에 의해 촉진되고, 중기에는 모듈 구조가 전통 산업 연쇄, 신흥 산업, 소비 모듈의 차별화된 전이 경로를 보여주며, 장기 희소 네트워크는 부동산 투자의 시스템적 중요성을 부각시킨다. 분류 기능을 갖춘 순 스필오버 지수는 인프라, 부동산, 사회 총 투자를 핵심 송신자로 식별하고, 인테리어, 건축자재, 철강을 수신자로, 전력설비를 이중 탄소(dual-carbon) 정책에 힘입어 수신자에서 송신자로의 역할 진화를 완성한 것으로 식별한다. 네트워크 중심성 지표는 1개월 앞 주가 예측의 RMSE를 평균 18.3% 낮추고, 방향 정확도를 11.2% 개선하며, 고비대칭 산업에서는 예측 향상이 24.9%에 달하여, 네트워크 위상 위치 데이터가 거래 가능한(tradeable) 리스크 프리미엄을 대표함을 확인해 준다. 네트워크 구조 식별과 경제 구동 메커니즘의 비무작위적 특성은 강건하며 통계적으로 검정 가능하고, 부트스트랩 리샘플링, 웨이블릿 기저함수 민감도, 임계값 강건성, 몬테카를로 제로 모델 검정을 통해 확인된다.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>