<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="유진">
<meta name="dcterms.date" content="2026-06-05">

<title>연구 ▷ HST ▷ C_0는 small set이다 — Doeblin minorization K_3 예제 – 신록예찬's Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-42eb1ed98d6b40681f6bda2512c0def3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">신록예찬’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DL2024/"> 
<span class="menu-text">DL2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/AP2023/"> 
<span class="menu-text">AP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/PP2024/"> 
<span class="menu-text">PP2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DV2023/"> 
<span class="menu-text">DV2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/MP2023/"> 
<span class="menu-text">MP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SC2024/"> 
<span class="menu-text">SC2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DS2022/"> 
<span class="menu-text">DS2022</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SP2023/"> 
<span class="menu-text">SP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/IR2021/"> 
<span class="menu-text">IR2021</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan/"> 
<span class="menu-text">yechan</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan2/"> 
<span class="menu-text">yechan2</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/miruetoto/yechan"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">연구 ▷ HST ▷ <span class="math inline">\(C_0\)</span>는 small set이다 — Doeblin minorization <span class="math inline">\(K_3\)</span> 예제</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>유진 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>먼저 무엇을 보일지 못박자 (결론부터).</strong> Lemma 8(§5.2, hst_AAA.tex)이 주장하는 건 한 줄이다 — 작은 집합 <span class="math inline">\(C_0\)</span>가 라운드 스켈레톤 커널 <span class="math inline">\(P^{\star}\)</span>에 대해 <em>small</em>이다: <span class="math display">\[(P^{\star})^{\,nL}(s^{\star},\cdot) \;\geq\; \eta\,\nu \qquad (\forall\, s^{\star} \in C_0).\]</span> 즉 <span class="math inline">\(C_0\)</span> 안 <strong>어디서 출발하든</strong> <span class="math inline">\(nL\)</span>라운드 뒤 분포가 공통 바닥 <span class="math inline">\(\eta\,\nu\)</span>를 깐다. 이것만 보이면 끝이다. 그래서 우리가 직접 <strong>구성</strong>할 것은 기준측도 <span class="math inline">\(\nu\)</span>, 스텝 수 <span class="math inline">\(m=nL\)</span>, 양수 <span class="math inline">\(\eta&gt;0\)</span> 셋뿐이고, 그러기 위해 <span class="math inline">\(\eta\)</span>를 여러 양수 인자의 곱으로 쪼개 하나씩 “<span class="math inline">\(&gt;0\)</span>”을 확인한다.</p>
<p>이 글은 그 구성을 완전그래프 <span class="math inline">\(K_3\)</span>, <span class="math inline">\(b=1\)</span>, 시작 높이 <span class="math inline">\((5,7,3)\)</span>으로 직접 따라간다(<strong>1·2·3부 통합</strong>). <strong>1부</strong>에서 무대(상태공간·<span class="math inline">\(C_0\)</span>·<span class="math inline">\(\mathsf{O}\)</span>·<span class="math inline">\(\mathsf{U}\)</span>)를 수치로 못박고, <strong>2부</strong>에서 proof sketch를 시나리오 넷(favourable→realistic)으로 따라가고, <strong>3부</strong>에서 full proof로 <span class="math inline">\(\eta\)</span>를 만든다. 정본(2026-06-12판)은 이를 <strong>두 바닥</strong>으로 조직한다 — <strong>discrete floor</strong>(cyclic fall·branch 픽·non-fall 억제)와 <strong>density floor</strong>(<span class="math inline">\((\dagger)\)</span> 치환적분 → slice floor → robust core → transport). 옛 판본의 coarea·Hausdorff 측도는 폐지됐고 전부 Lebesgue로 간다. 엄밀한 일반 증명은 hst_AAA.tex Lemma 8 참조.</p>
<hr>
<section id="제1부.-무대-상태공간c_0mathsfou" class="level1">
<h1>제1부. 무대 — 상태공간·<span class="math inline">\(C_0\)</span>·<span class="math inline">\(\mathsf{O}\)</span>·<span class="math inline">\(U\)</span></h1>
<blockquote class="blockquote">
<p><strong>1부 안내</strong>: 2·3부의 증명에 들어가기 전에 무대를 잡는다 — 그래프 <span class="math inline">\(K_3\)</span>, small set 후보 <span class="math inline">\(C_0\)</span>, 도달역 <span class="math inline">\(\mathsf{O}\cdot L\cdot\mathsf{O}\)</span>, chamber <span class="math inline">\(U\)</span>와 변위 목표 집합 <span class="math inline">\(K_{\mathsf{U}}\)</span>.</p>
</blockquote>
<section id="k_3와-상태공간" class="level2">
<h2 class="anchored" data-anchor-id="k_3와-상태공간">§1. <span class="math inline">\(K_3\)</span>와 상태공간</h2>
<p>증명의 무대를 못박는다.</p>
<ul>
<li><strong>전장</strong>: 완전그래프 <span class="math inline">\(K_3\)</span> — 봉우리 <span class="math inline">\(\{v_1, v_2, v_3\}\)</span>, 세 능선 모두 연결.</li>
<li><strong>눈의 단위</strong>: <span class="math inline">\(b = 1\)</span> (한 번에 쌓이는 눈 <span class="math inline">\(\sim \mathrm{Unif}(0,1)\)</span>).</li>
<li><strong>시작 고도</strong>: <span class="math inline">\(h(v_1) = 5,\quad h(v_2) = 7,\quad h(v_3) = 3.\)</span></li>
</ul>
<blockquote class="blockquote">
<p><strong>용어 약속 (falls / non-fall).</strong> 매 라운드 각 노드에 눈이 한 덩이씩 새로 떨어진다. 이 <strong>노드별 강설 증분</strong> <span class="math inline">\(b^{\sharp}_i \sim \mathrm{Unif}(0,b)\)</span>이 <em>fall</em>(페이퍼 표기 위첨자 <span class="math inline">\(\sharp\)</span>)이다. 반면 강설 외 동역학(이웃 노드로 흘러내리는 <em>flow</em>, 뭉쳐 머무는 <em>block</em> 등)이 만드는 잔여 교란을 <em>non-fall</em>(위첨자 <span class="math inline">\(\flat\)</span>)이라 부른다. §5.2 증명의 핵심은 <em>falls의 누적 변위가 non-fall 잔차(<span class="math inline">\(\leq\varepsilon_{\flat}\)</span>)를 흡수하고도 목표 chamber <span class="math inline">\(U\)</span>에 양의 밀도로 도달한다</em>는 것이다.</p>
</blockquote>
<p>절대 고도는 잊어도 된다 — 증명에서 역할을 하는 건 <strong>고도차</strong>다. 상태(state)를 정의한다.</p>
<blockquote class="blockquote">
<p><strong>용어 약속 (라운드 스켈레톤 / 윗줄 <span class="math inline">\(\bar{\,\cdot\,}\)</span> 표기).</strong> 연속적으로 굴러가는 눈 동역학을 <strong>한 라운드 단위로 띄엄띄엄 관찰</strong>한 이산 마르코프 체인을 <em>라운드 스켈레톤</em>(round skeleton)이라 한다 (뼈대만 남긴다는 뜻). 앞으로 윗줄 표기 — 상태공간 <span class="math inline">\(\mathsf{S}^{\star}\)</span>, 전이커널 <span class="math inline">\(P^{\star}\)</span> — 는 모두 <em>이 스켈레톤 체인의 것</em>이다. 예컨대 <span class="math inline">\((P^{\star})^{\,nL}(s^{\star},\cdot)\)</span>은 “<span class="math inline">\(s^{\star}\)</span>에서 출발해 <span class="math inline">\(nL\)</span>라운드 뒤 상태 분포”.</p>
</blockquote>
<p>스켈레톤 상태공간은 <span class="math inline">\(\mathsf{S}^{\star} = \mathbb{R}^{n-1} \times V\)</span> (<span class="math inline">\(n = 3\)</span>이라 <span class="math inline">\(\mathbb{R}^2 \times V\)</span>). 두 좌표는:</p>
<p><strong>(1) 높이차 <span class="math inline">\(\mathring{\mathbf{h}}\)</span></strong> — <span class="math inline">\(v_1\)</span>을 기준으로 뺀 anchored 높이차: <span class="math display">\[\mathring{\mathbf{h}}(s^{\star}) = \bigl(h(v_2) - h(v_1),\ h(v_3) - h(v_1)\bigr) = (7-5,\ 3-5) = (2, -2).\]</span></p>
<p><strong>(2) 현재 노드 <span class="math inline">\(X\)</span></strong> — walker가 지금 있는 노드 (예: <span class="math inline">\(v_1\)</span>).</p>
<p>→ 우리 예제의 상태는 <span class="math inline">\(s^{\star} = \bigl((2,-2),\ v_1\bigr)\)</span>이다. (<span class="math inline">\(\mathring{\mathbf{h}}\)</span>가 절대높이 <span class="math inline">\(5,7,3\)</span>을 안 기억해도 되는 이유: 눈은 모든 노드에 똑같이 와 닿는 게 아니라 <strong>높이차</strong>만 동역학에 들어오기 때문. 높이를 통째로 <span class="math inline">\(+10\)</span> 해도 같은 상태.)</p>
<div id="a1ec1e5e" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-2-output-1.png" width="669" height="298" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="small-set-후보-c_0" class="level2">
<h2 class="anchored" data-anchor-id="small-set-후보-c_0">§2. Small set 후보 <span class="math inline">\(C_0\)</span></h2>
<p>ergodic 정리(Meyn–Tweedie)를 쓰려면 가정 셋이 필요한데, 그중 <strong>H2 = “어떤 small set이 존재한다”</strong>를 이 절에서 댄다. small set의 정의는:</p>
<blockquote class="blockquote">
<p>집합 <span class="math inline">\(C\)</span>가 <strong>small</strong>이다 <span class="math inline">\(\iff\)</span> 어떤 스텝 수 <span class="math inline">\(m\)</span>과 0이 아닌 측도 <span class="math inline">\(\nu\)</span>가 있어, <span class="math inline">\(C\)</span> 안 <strong>어디서 출발하든</strong> <span class="math inline">\(m\)</span>스텝 뒤 분포가 공통 바닥 <span class="math inline">\(\nu\)</span>를 깐다: <span class="math display">\[P^m(s^{\star}, \cdot) \geq \nu(\cdot) \qquad (\forall\, s \in C).\]</span></p>
</blockquote>
<p><strong>먼저 <span class="math inline">\(s^{\star}\)</span>가 어디의 원소인지</strong> 못박자. 라운드 스켈레톤의 상태공간은 <span class="math display">\[\mathsf{S}^{\star} \;=\; \mathbb{R}^{n-1} \times V \;=\; \mathbb{R}^2 \times \{v_1, v_2, v_3\},\]</span> 즉 상태는 <span class="math inline">\(s^{\star} = (\mathring{\mathbf{h}},\ X)\)</span> — <strong>(높이차 벡터, 현재 노드)</strong> 쌍이다. 우리 예제에선 <span class="math display">\[s^{\star} = \bigl((2,-2),\ v_1\bigr) \in \mathsf{S}^{\star}.\]</span></p>
<p>후보 small set은 <strong>높이가 너무 치우치지 않은 상태들</strong>이다. 페이퍼 정의를 따라, 평균 <span class="math inline">\(\bar h = \tfrac1n\sum_i h(v_i)\)</span>로 <strong>중심화한 높이</strong> <span class="math inline">\(\hbar(v_i) := h(v_i) - \bar h\)</span>를 쓰고, 그 최대 절댓값을</p>
<p><span class="math display">\[M(s^{\star}) := \max_i \,|\hbar(v_i)| \qquad (\text{centered 높이 범위})\]</span></p>
<p>로 정의한다. (<span class="math inline">\(K_3\)</span> 예제: <span class="math inline">\(\bar h = \tfrac{5+7+3}{3} = 5\)</span>, <span class="math inline">\(\hbar = (0, 2, -2)\)</span>, 따라서 <span class="math inline">\(M(s^{\star}) = 2\)</span>.) small set은 이 <span class="math inline">\(M\)</span>의 sublevel:</p>
<p><span class="math display">\[C_0 = \{\, M \leq M_0 \,\} \times V, \qquad \text{이 예제 } M_0 := 2.\]</span></p>
<p>우리 <span class="math inline">\(s^{\star}\)</span>는 <span class="math inline">\(M(s^{\star}) = 2 = M_0\)</span>이라 <span class="math inline">\(C_0\)</span> <strong>경계</strong>(사실 꼭짓점) 위 — <span class="math inline">\(v_2\)</span>가 천장, <span class="math inline">\(v_3\)</span>가 바닥인 <strong>가장 치우친 worst case</strong>다. <span class="math inline">\(M\)</span>은 anchored 좌표 <span class="math inline">\(\mathring{\mathbf{h}}=(u_1,u_2)\)</span> (<span class="math inline">\(u_1{=}h(v_2){-}h(v_1)\)</span>, <span class="math inline">\(u_2{=}h(v_3){-}h(v_1)\)</span>)만으로도 쓸 수 있고(<span class="math inline">\(\hbar = (0,u_1,u_2)-\tfrac{u_1+u_2}{3}\mathbf{1}\)</span>), <span class="math inline">\(C_0\)</span>는 그 평면에서 <strong>육각형</strong>(<span class="math inline">\(\times V\)</span>, 꼭짓점 <span class="math inline">\(\pm(4,2),\pm(2,4),\pm(2,-2)\)</span>)으로 나타난다.</p>
<div id="6d663cd2" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-3-output-1.png" width="424" height="435" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>이 육각형이 <span class="math inline">\(C_0\)</span>(<span class="math inline">\(\times\)</span> 노드 <span class="math inline">\(V\)</span>) — 중심화 높이 최대치 <span class="math inline">\(M(s^{\star})=\max_i|\hbar(v_i)|\)</span>가 <span class="math inline">\(M_0=2\)</span> 이하인 상태들이며, 출발 <span class="math inline">\(s^{\star}=(2,-2)\)</span>는 <span class="math inline">\(\hbar=(0,2,-2)\)</span>로 <span class="math inline">\(M=2=M_0\)</span>, 즉 <span class="math inline">\(C_0\)</span>의 <strong>꼭짓점</strong>(=가장 불균형한 worst case: <span class="math inline">\(v_2\)</span> 천장·<span class="math inline">\(v_3\)</span> 바닥)에 놓인다.</p>
<hr>
</section>
<section id="도달역-mathsfolcdotmathsfo와-chamber-u" class="level2">
<h2 class="anchored" data-anchor-id="도달역-mathsfolcdotmathsfo와-chamber-u">§3. 도달역 <span class="math inline">\(\mathsf{O}\)</span>·<span class="math inline">\(L\cdot\mathsf{O}\)</span>와 chamber <span class="math inline">\(U\)</span></h2>
<p>falls가 쓰는 영역을 <strong>두 종류</strong>로 나눠 잡는다 (전부 <span class="math inline">\(\mathring{\mathbf{h}}\)</span>가 사는 <span class="math inline">\(\mathbb{R}^2\)</span>의 부분집합이지만 <strong>역할이 다르다</strong>):</p>
<ul>
<li><strong>(가) 증분/도달 영역 <span class="math inline">\(\mathsf{O}\)</span>, <span class="math inline">\(L\cdot\mathsf{O}\)</span></strong> — “한 블록/<span class="math inline">\(L\)</span>블록이 <span class="math inline">\(\mathring{\mathbf{h}}\)</span>를 <em>얼마나 미는가</em>” (현재 위치 <span class="math inline">\(p\)</span>에 <span class="math inline">\(p+\mathsf{O}\)</span>로 더해지는 <strong>변위</strong>). 아래 ①②.</li>
<li><strong>(나) chamber <span class="math inline">\(U\)</span></strong> — “궤적이 <em>어디서 끝나는가</em>” (원점 근처 <strong>최종 위치</strong>). 아래 ③.</li>
</ul>
<p>둘 다 같은 박스 <span class="math inline">\(\mathsf{O}\)</span> 안에 살지만(③에서 <span class="math inline">\(\mathsf{U} \Subset \mathsf{O}\)</span>), <strong>변위(가) vs 위치(나)라 한 줄로 묶어 읽으면 안 된다</strong> (이 혼동은 ③에서 다시 짚는다). <span class="math inline">\(b=1\)</span>, <span class="math inline">\(n=3\)</span>.</p>
<p><strong>① <span class="math inline">\(\mathsf{O}\)</span> — 한 블록 증분의 밀도가 양수 하한을 갖는 영역.</strong> <span class="math display">\[\mathsf{O} := \{\,\|\boldsymbol{\zeta}\|_\infty &lt; b/4\,\} = (-\tfrac14, \tfrac14)^2.\]</span></p>
<p><strong>용어 정의 (“밀도 하한”).</strong> 한 블록의 차분벡터 <span class="math inline">\(\mathring{\mathbf{b}}^{\sharp} = (b^{\sharp}_2 - b^{\sharp}_1,\ b^{\sharp}_3 - b^{\sharp}_1)\)</span> (<span class="math inline">\(b^{\sharp}_i \sim \mathrm{Unif}(0,b)\)</span> 독립; 페이퍼 표기)의 확률밀도를 <span class="math inline">\(f\)</span>라 하자. pushforward 보조정리가 <span class="math display">\[f(\boldsymbol{\zeta}) \;\geq\; \frac{b^{1-n}}{2} = \frac12 \qquad (\forall\, \boldsymbol{\zeta} \in \mathsf{O})\]</span> 를 보장한다. 동치로, 임의의 가측 <span class="math inline">\(B \subseteq \mathsf{O}\)</span>에 대해 <span class="math inline">\(\mathbb{P}(\mathring{\mathbf{b}}^{\sharp} \in B) \geq \tfrac12\,|B|_{\mathrm{Leb}}\)</span>. <strong>이 “밀도 <span class="math inline">\(f\)</span>가 <span class="math inline">\(\mathsf{O}\)</span> 위에서 양수 상수 <span class="math inline">\(\tfrac12\)</span> 이상”이 앞으로 쓸 <em>밀도 하한(floor)</em>의 정확한 뜻</strong>이다 (양수란 게 핵심; 어디서도 <span class="math inline">\(0\)</span>으로 안 꺼짐).</p>
<p>핵심은 <span class="math inline">\(\mathsf{O}\)</span>가 <strong>위치가 아니라 “한 블록이 만드는 <span class="math inline">\(\mathring{\mathbf{h}}\)</span>의 증분(이동량)”의 영역</strong>이라는 점이다. 우리 예제로 “<span class="math inline">\(\mathring{\mathbf{h}}(s^{\star})=(2,-2)\)</span>가 한 블록 뒤 어떻게 바뀌나”를 직접 따라가자.</p>
<p>한 블록 = 각 노드에 fall 하나씩 (<span class="math inline">\(K_3\)</span>이라 <span class="math inline">\(v_1, v_2, v_3\)</span>에 각각 <span class="math inline">\(b^{\sharp}_1, b^{\sharp}_2, b^{\sharp}_3 \sim \mathrm{Unif}(0,1)\)</span>). 그러면 높이가 <span class="math inline">\(h(v_i) \mapsto h(v_i) + b^{\sharp}_i\)</span>로 오르고: <span class="math display">\[
\begin{aligned}
\mathring{\mathbf{h}}_{\text{new}}
&amp;= \bigl(\,(h(v_2){+}b^{\sharp}_2) - (h(v_1){+}b^{\sharp}_1),\ \ (h(v_3){+}b^{\sharp}_3) - (h(v_1){+}b^{\sharp}_1)\,\bigr)\\
&amp;= \underbrace{\bigl(h(v_2){-}h(v_1),\ h(v_3){-}h(v_1)\bigr)}_{=\,(2,-2)} \;+\; \underbrace{\bigl(b^{\sharp}_2 - b^{\sharp}_1,\ b^{\sharp}_3 - b^{\sharp}_1\bigr)}_{=:\ \text{증분 }\mathring{\mathbf{b}}^{\sharp}}.
\end{aligned}
\]</span></p>
<p>즉 한 블록의 증분은 <span class="math inline">\(\mathring{\mathbf{b}}^{\sharp} = (b^{\sharp}_2 - b^{\sharp}_1,\ b^{\sharp}_3 - b^{\sharp}_1)\)</span>. <strong><span class="math inline">\(v_1\)</span>에 쌓인 <span class="math inline">\(b^{\sharp}_1\)</span>이 모든 차이에서 상쇄</strong>돼, 절대 적립량은 안 남고 <strong>노드 간 상대 차이만</strong> <span class="math inline">\(\mathring{\mathbf{h}}\)</span>를 옮긴다. (그래서 pushforward 보조정리가 다루는 양이 deposit 자체가 아니라 차이벡터 <span class="math inline">\(\mathring{\mathbf{b}}^{\sharp}\)</span>인 것.)</p>
<p>수치 예시 (<span class="math inline">\((2,-2)\)</span>에서 출발):</p>
<ul>
<li><span class="math inline">\(b^{\sharp} = (0.5,\ 0.6,\ 0.4)\)</span> → 증분 <span class="math inline">\((0.6{-}0.5,\ 0.4{-}0.5) = (0.1, -0.1)\)</span> → <span class="math inline">\((2.1, -2.1)\)</span>. 두 성분 다 <span class="math inline">\(|\cdot| &lt; \tfrac14\)</span> 라 <span class="math inline">\(\mathsf{O}\)</span> 안 — <strong>밀도 <span class="math inline">\(\geq \tfrac12\)</span> 보장</strong>.</li>
<li><span class="math inline">\(b^{\sharp} = (0.7,\ 0.55,\ 0.85)\)</span> → 증분 <span class="math inline">\((-0.15,\ 0.15)\)</span> → <span class="math inline">\((1.85, -1.85)\)</span>. 역시 <span class="math inline">\(\mathsf{O}\)</span> 안.</li>
<li><span class="math inline">\(b^{\sharp} = (0.5,\ 0.9,\ 0.3)\)</span> → 증분 <span class="math inline">\((0.4,\ -0.2)\)</span>. 첫 성분 <span class="math inline">\(0.4 &gt; \tfrac14\)</span> 라 <span class="math inline">\(\mathsf{O}\)</span> <strong>밖</strong> — 가능은 하지만 밀도 보장 안 됨.</li>
</ul>
<p>위 밀도 하한의 유도 (왜 <span class="math inline">\(\mathsf{O}\)</span> 위에서만 <span class="math inline">\(f \geq \tfrac12\)</span>인가): 증분 밀도 <span class="math inline">\(f\)</span>는 <span class="math inline">\(b^{\sharp}_1\)</span>을 적분해 없앤 것인데, 모든 <span class="math inline">\(|b^{\sharp}_i - b^{\sharp}_1| &lt; b/4\)</span>일 때 적분 구간이 길이 <span class="math inline">\(\geq b/2\)</span>를 품어 <span class="math inline">\(f \geq b^{1-n}/2\)</span>로 떨어진다 (<span class="math inline">\(b{=}1, n{=}3\)</span>이라 <span class="math inline">\(\tfrac12\)</span>). 그 조건이 정확히 <span class="math inline">\(\mathring{\mathbf{b}}^{\sharp} \in \mathsf{O}\)</span>.</p>
<p><strong>주의 — <span class="math inline">\(\mathsf{O}\)</span>는 “한 블록으로 갈 수 있는 전부”가 아니다.</strong> 증분 <span class="math inline">\(\mathring{\mathbf{b}}^{\sharp} = (b^{\sharp}_2 - b^{\sharp}_1,\ b^{\sharp}_3 - b^{\sharp}_1)\)</span>은 각 <span class="math inline">\(b^{\sharp}_i \in [0,b]\)</span>라, 실제 <strong>도달 영역</strong>은 박스가 아니라 <strong>육각형</strong> <span class="math display">\[\{\, \boldsymbol{\zeta} : |\boldsymbol{\zeta}_1| \leq b,\ |\boldsymbol{\zeta}_2| \leq b,\ |\boldsymbol{\zeta}_1 - \boldsymbol{\zeta}_2| \leq b \,\}\]</span> 이다 (증분도 높이차 벡터라 pairwise range <span class="math inline">\(\leq b=1\)</span>). 예컨대 모서리 <span class="math inline">\((b, -b)\)</span>는 <span class="math inline">\(b^{\sharp}_1\)</span>을 공유하는 제약 때문에 도달 불가(<span class="math inline">\(|x-y|=2b &gt; b\)</span>). 박스 <span class="math inline">\(\mathsf{O}\)</span>(한 좌표 <span class="math inline">\(\pm b/4\)</span>)는 그 육각형 <strong>안쪽의 밀도 <span class="math inline">\(\geq \tfrac12\)</span> 보장 부분</strong>일 뿐이다. 증명이 박스만 쓰는 이유: 깔끔한 밀도 하한 <span class="math inline">\(b^{1-n}/2\)</span>가 거기서만 나오기 때문 (육각형 안·박스 밖은 밀도가 양수지만 그 하한은 안 나옴). 아래 그림은 (A) <strong>큰 <span class="math inline">\(C_0\)</span> 안에 한 블록 도달역(작은 육각형)이 작게 들어있는 모습</strong> — 둘 다 육각형이지만 정의가 다르다(<span class="math inline">\(C_0\)</span>는 centered <span class="math inline">\(M\leq M_0{=}2\)</span>·원점 중심, 도달역은 pairwise range <span class="math inline">\(\leq b{=}1\)</span>·<span class="math inline">\(s{=}(2,-2)\)</span> 중심) — 과 (B) 그 도달역 줌인(도달 육각형 <span class="math inline">\(\supset\)</span> 밀도박스 <span class="math inline">\(\mathsf{O}\)</span>)을 보여준다.</p>
<div id="5c54325d" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-4-output-1.png" width="723" height="344" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>한 블록은 <span class="math inline">\(\mathring{\mathbf{h}}\)</span>를 육각형(range <span class="math inline">\(\leq b\)</span>)만큼 밀 수 있고, 그중 <strong>밀도 하한 <span class="math inline">\(f \geq \tfrac12\)</span>을 갖는</strong> 부분이 박스 <span class="math inline">\(\mathsf{O}\)</span>(한 좌표 <span class="math inline">\(\pm\tfrac14\)</span>)다. (<span class="math inline">\(L\)</span>블록 누적 버전은 ② 참조.)</p>
<p><strong>② <span class="math inline">\(L\cdot\mathsf{O}\)</span> — <span class="math inline">\(L\)</span>블록이 도달하는 영역 (Minkowski 합). 이하 <em>도달역</em>이라 부른다.</strong> <span class="math display">\[L := \Bigl\lceil \tfrac{16M_0}{b} + 3 \Bigr\rceil, \qquad L\cdot\mathsf{O} := \underbrace{\mathsf{O}+\mathsf{O}+\cdots+\mathsf{O}}_{L\text{개}} = \bigl\{\, \boldsymbol{\zeta} : \|\boldsymbol{\zeta}\|_\infty &lt; \tfrac{Lb}{4} \,\bigr\}.\]</span></p>
<blockquote class="blockquote">
<p><strong>정의 (도달역).</strong> 한 블록 증분이 밀도바닥 박스 <span class="math inline">\(\mathsf{O}\)</span> 안에 있을 때, <span class="math inline">\(L\)</span>블록을 누적한 총변위가 떨어질 수 있는 곳이 곧 Minkowski 합 <span class="math inline">\(L\cdot\mathsf{O}\)</span>다. 이 집합을 <strong>도달역</strong>(reachable region)이라 부른다 — “<span class="math inline">\(L\)</span>번 걸어서 닿을 수 있는 모든 점”. 출발점 <span class="math inline">\(s^{\star}\)</span>에서 시작하면 도달역은 <span class="math inline">\(s^{\star} + L\cdot\mathsf{O}\)</span>로 평행이동한다.</p>
</blockquote>
<p><span class="math inline">\(M_0 = 2\)</span>, <span class="math inline">\(b = 1\)</span>이라 <span class="math inline">\(L = \lceil 16\cdot 2 + 3 \rceil = 35\)</span>. 그러면 <span class="math inline">\(L\cdot\mathsf{O} = (-\tfrac{L}{4}, \tfrac{L}{4})^2 = (-8.75, 8.75)^2\)</span> — <strong>출발 <span class="math inline">\(\mathring{\mathbf{h}}(s^{\star})=(2,-2)\)</span>를 원점 근처로 끌어내릴 만큼 넉넉</strong>하다. (falls가 채울 변위 <span class="math inline">\(\boldsymbol{\zeta} = u - \mathring{\mathbf{h}}(s^{\star}) - r \approx (0,0)-(2,-2) = (-2,2)\)</span>가 <span class="math inline">\(\pm 8.75\)</span> 안에 푹 들어옴. 여기 <span class="math inline">\(r\)</span>은 <strong>non-fall 잔차</strong>로 ③에서 정의·범위를 못박는다.)</p>
<div id="479de94f" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-5-output-1.png" width="553" height="550" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>한 블록은 <span class="math inline">\(\mathsf{O}\)</span>(<span class="math inline">\(\pm\tfrac14\)</span>)짜리 작은 걸음이지만, <span class="math inline">\(L=35\)</span>번 누적하면 도달 영역이 <span class="math inline">\(\pm 8.75\)</span>까지 커져 — 출발 <span class="math inline">\(s^{\star}=(2,-2)\)</span>에서 목표 <span class="math inline">\(U(\approx 0)\)</span>가 그 안에 푹 들어온다 (위 그림).</p>
<p><strong>밀도 하한의 L블록 버전 (정의).</strong> <span class="math inline">\(L\)</span>블록 총 차분 <span class="math inline">\(Y = \sum_{k=1}^{L} Y_k\)</span> (독립 합; <span class="math inline">\(Y_k\)</span> = <span class="math inline">\(k\)</span>번째 블록의 차분벡터 <span class="math inline">\(\mathring{\mathbf{b}}^{\sharp}\)</span>)의 밀도는 <span class="math inline">\(L\)</span>겹 합성곱 <span class="math inline">\(f^{*L}\)</span>이고, <span class="math inline">\(\operatorname{int}(L\cdot\mathsf{O})\)</span>의 임의의 <strong>컴팩트</strong> 부분집합 <span class="math inline">\(K\)</span>에 대해 양수 상수 <span class="math inline">\(c_K\)</span>가 존재해 <span class="math display">\[f^{*L}(z) \;\geq\; c_K \;&gt;\; 0 \quad (z \in K), \qquad\text{즉}\qquad \mathbb{P}(Y \in B) \;\geq\; c_K\,|B|_{\mathrm{Leb}}\ \ (B \subseteq K).\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🔽 접어둔 군사 계산 — <span class="math inline">\(L\)</span>겹 바닥 <span class="math inline">\(c_K\)</span>는 얼마나 작나 (사실 안 작다)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>주의 세 가지: (i) <span class="math inline">\(c_K\)</span>는 한 블록의 <span class="math inline">\(\tfrac12\)</span>이 <strong>아니다</strong> (합성곱은 곱이 아니라 적분이라 <span class="math inline">\((\tfrac12)^L\)</span>과 다름). (ii) floor는 <span class="math inline">\(L\cdot\mathsf{O}\)</span> <strong>전체</strong>가 아니라 <strong>경계에서 떨어진 컴팩트 <span class="math inline">\(K\)</span></strong> 위에서만 — <span class="math inline">\(f^{*L}\)</span>은 <span class="math inline">\(L\cdot\mathsf{O}\)</span> 경계로 갈수록 <span class="math inline">\(0\)</span>으로 떨어진다. (iii) <strong><span class="math inline">\(c_K\)</span>의 크기 — 사실 <span class="math inline">\((\tfrac12)^L\)</span>보다 훨씬 크다.</strong> Lemma 8의 합성곱-바닥 단계가 증명하는 하한 <span class="math inline">\(c_K \geq (\tfrac{b^{1-n}}{2})^{L}(\omega_d s^d)^{L-1}\)</span> 은 “<span class="math inline">\(c_K&gt;0\)</span>”만 보이려는 <strong>매우 loose한 과소평가</strong>(지수적으로 작은 값)일 뿐, <strong>실제 <span class="math inline">\(c_K\)</span>는 이보다 한참 크다.</strong> 합 <span class="math inline">\(Y\)</span>의 분포는 평균 <span class="math inline">\(0\)</span> 주위로 표준편차 <span class="math inline">\(\sqrt{L/6}\approx 2.4\)</span> 퍼지고(CLT), 타깃(<span class="math inline">\(\|\boldsymbol{\zeta}\|_\infty\lesssim 8.6\)</span>)은 그 <strong>bulk</strong>에 있어 밀도가 <span class="math inline">\(f^{*L} \sim L^{-d/2}\)</span> — 즉 <strong>다항적</strong>으로만 작다 (<span class="math inline">\(\sim 1/L\)</span>). 정리하면 <span class="math inline">\((\tfrac12)^L\)</span>(loose 하한) <span class="math inline">\(\ll\)</span> 실제 <span class="math inline">\(c_K \sim L^{-d/2}\)</span>. 증명엔 <span class="math inline">\(c_K&gt;0\)</span>만 필요해 loose bound로 충분할 뿐.</p>
</div>
</div>
</div>
<p><strong>③ <span class="math inline">\(U\)</span> — 도착 chamber를 증분 박스 <span class="math inline">\(\mathsf{O}\)</span> 안에 직접 잡는다.</strong> falls가 최종적으로 떨어뜨릴 위치(chamber) <span class="math inline">\(U\)</span>는 <strong>증분 박스 <span class="math inline">\(\mathsf{O}\)</span> 안에 직접</strong> 둔다: <span class="math display">\[\mathsf{U} \Subset \mathsf{O} = \{\,\|\boldsymbol{\zeta}\|_\infty &lt; b/4\,\} \qquad (\text{즉 } \|u\|_\infty &lt; b/4 = 0.25).\]</span> 여기서 한 번 짚고 가자: <strong><span class="math inline">\(U\)</span>는 ① <span class="math inline">\(\mathsf{O}\)</span>와 같은 박스에 살지만 역할이 정반대다.</strong> <span class="math inline">\(\mathsf{O}\)</span>는 “한 블록이 미는 <strong>증분</strong>”의 영역이고, <span class="math inline">\(U\)</span>는 “궤적이 끝나는 <strong>위치</strong>”다. falls가 “<span class="math inline">\(U\)</span>만큼 민다”는 게 전혀 아니고 (falls는 여전히 <span class="math inline">\(\mathsf{O}\)</span>/<span class="math inline">\(L\cdot\mathsf{O}\)</span> 전체로 움직인다), <span class="math inline">\(U\)</span>는 도착점 후보들의 작은 집합이다. 그 역할은 하나 — <strong><span class="math inline">\(U\)</span>를 도달역 안쪽에 충분히 작게 가두는 것</strong>:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(\mathsf{U} \Subset \mathsf{O}\)</span>이면 목표 집합 <span class="math inline">\(K_{\mathsf{U}} = \{u - \mathring{\mathbf{h}}(s^{\star}) - r\}\)</span>가 도달역 내부에 컴팩트하게 든다: <span class="math inline">\(K_{\mathsf{U}} \Subset \operatorname{int}(L\cdot\mathsf{O})\)</span>.</p>
</blockquote>
<p>(또 다른 <span class="math inline">\(U\)</span> 조건인 <strong>등호 초평면 회피</strong>는 박스 크기와 무관하므로 ④에서 다룬다. <em>예전 판본은 <span class="math inline">\(U\)</span>를 더 작은 <span class="math inline">\(\mathsf{O}^\dagger{=}\{\|\boldsymbol{\zeta}\|_\infty&lt;b/16\}\)</span>에 가뒀으나, <span class="math inline">\(L\)</span>을 <span class="math inline">\(\lceil 16M_0/b{+}3\rceil\)</span>로 키워 <span class="math inline">\(\mathsf{U}\Subset\mathsf{O}\)</span>만으로 containment가 되도록 정리됐다 — 정본 정합.</em>)</p>
<p><strong><span class="math inline">\(K_{\mathsf{U}}\)</span>란 — falls가 맞혀야 할 변위 목표 전체 (“숙제 목록”).</strong> <span class="math inline">\(K_{\mathsf{U}}\)</span>는 한 점이 아니라 <strong>집합</strong>인데, 세 조각이 각각 범위를 갖기 때문이다:</p>
<ul>
<li><strong><span class="math inline">\(\mathbf{u} \in \mathsf{U}\)</span></strong> — 도착지(chamber)가 한 점이 아니라 <span class="math inline">\(U\)</span> 전체에 퍼짐 (기준측도 <span class="math inline">\(\nu=\mathrm{Unif}(\mathsf{U})\)</span>라 <span class="math inline">\(U\)</span>의 모든 점을 덮어야).</li>
<li><strong><span class="math inline">\(s^{\star} \in C_0\)</span></strong> — 출발 상태가 <span class="math inline">\(C_0\)</span> 안 어디든 (minorization은 <span class="math inline">\(\forall s\)</span>); <span class="math inline">\(s^{\star}\)</span>마다 <span class="math inline">\(\mathring{\mathbf{h}}(s^{\star})\)</span>가 다름.</li>
<li><strong><span class="math inline">\(r\)</span> (<span class="math inline">\(\|r\|_\infty \leq Lb/8\)</span>)</strong> — non-fall 잔차가 그때그때 다름 (정체는 바로 아래).</li>
</ul>
<p>이 <span class="math inline">\((u,s,r)\)</span> <strong>모든 조합</strong>이 변위 <span class="math inline">\(\boldsymbol{\zeta} = u-\mathring{\mathbf{h}}(s^{\star})-r\)</span> 하나씩을 만들고, 그 전부의 모임이 <span class="math inline">\(K_{\mathsf{U}}\)</span>다. 즉 <strong>falls의 “숙제 목록”</strong> — minorization이 성립하려면 falls가 이 목록의 <strong>모든 점</strong>을 밀도 깔며 맞혀야 한다 (하나라도 못 맞히면 그 출발·도착·잔차 조합에서 floor가 깨짐). 그래서 “<span class="math inline">\(K_{\mathsf{U}} \Subset \operatorname{int}(L\cdot\mathsf{O})\)</span>”는 <strong>숙제 목록 전체가 도달역 안쪽에 든다</strong>는 뜻이고, 그래야 Lemma 8의 slice-floor 단계(<span class="math inline">\(L\)</span>겹 합성곱 하한 + <span class="math inline">\((\dagger)\)</span>)가 모든 목표에 slice floor <span class="math inline">\(m_0\)</span>를 깔아준다.</p>
<p><strong>이 식을 거꾸로 읽으면 — falls가 통제하는 건 <span class="math inline">\(\boldsymbol{\zeta}\)</span> 하나뿐.</strong> <span class="math inline">\(\boldsymbol{\zeta} = u - \mathring{\mathbf{h}}(s^{\star}) - r\)</span>를 <span class="math inline">\(u\)</span>에 대해 풀면</p>
<p><span class="math display">\[u \;=\; \underbrace{\mathring{\mathbf{h}}(s^{\star})}_{\text{출발 현황}} \;+\; \underbrace{r}_{\text{non-fall 부작용 (side effect)}} \;+\; \underbrace{\boldsymbol{\zeta}}_{\text{fall 액션 (} \sum_k \mathring{\mathbf{b}}^\sharp_k \text{)}},\]</span></p>
<p>즉 <strong>최종 착지 위치 <span class="math inline">\(u\)</span> = (출발 현황) <span class="math inline">\(+\)</span> (non-fall 부작용) <span class="math inline">\(+\)</span> (fall 액션)</strong>이다. 앞 두 항은 falls가 못 바꾼다 — <span class="math inline">\(\mathring{\mathbf{h}}(s^{\star})\)</span>는 이미 주어진 출발점, <span class="math inline">\(r\)</span>은 HST 알고리즘을 진행하며 얻는 랜덤성에 의해 결정되는 부작용. falls가 손댈 수 있는 건 <strong>세 번째 항 <span class="math inline">\(\boldsymbol{\zeta}\)</span> (<span class="math inline">\(=L\)</span>블록 fall 증분의 합 <span class="math inline">\(\sum_k \mathring{\mathbf{b}}^\sharp_k\)</span>)뿐</strong>이다. 그래서 “주어진 <span class="math inline">\(\mathring{\mathbf{h}}(s^{\star})\)</span>·<span class="math inline">\(r\)</span> 아래 <span class="math inline">\(u\)</span>에 정확히 착지하려면 falls가 만들어내야 할 증분 합”이 곧 표적 <span class="math inline">\(\boldsymbol{\zeta} = u - \mathring{\mathbf{h}}(s^{\star}) - r\)</span>이고, 이게 falls의 명중 목표다.</p>
<p><strong>잔차 <span class="math inline">\(r\)</span>은 어디서 나오나 — “그렇다고 치는” 게 아니다.</strong> <span class="math inline">\(r\)</span>은 자유롭게 고르는 값이 아니라, <span class="math inline">\(nL\)</span>라운드 동안 <strong>non-fall(flow·block) 스텝이 높이차에 보탠 누적 변위</strong>다 (페이퍼: <span class="math inline">\(r = \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^\flat\)</span> — 여기서 <span class="math inline">\(\amalg\)</span>는 <strong>분기</strong>(branch), 즉 non-fall 스텝이 밟은 노드 순서다. <span class="math inline">\(r\)</span>은 non-fall 증분 <span class="math inline">\(\mathbf{b}^\flat\)</span>의 결정론적 선형 함수 — HST 알고리즘을 진행하며 얻는 랜덤성에 의해 결정된다). 상한 <span class="math inline">\(\|r\|_\infty \leq \tfrac{Lb}{8}\)</span>은 임의로 박은 게 아니라 <strong>“스텝 수 <span class="math inline">\(\times\)</span> 한 스텝 크기”</strong>로 나온다. 증명이 non-fall을 억누른 사건 <span class="math inline">\(\mathcal{A}^\flat\)</span> 위에서만 작업하므로 각 스텝이 <span class="math inline">\(\leq \varepsilon_{\flat}\)</span>로 작다:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">양</th>
<th style="text-align: left;">뜻</th>
<th style="text-align: center;"><span class="math inline">\(K_3\)</span> 값</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(nLT_{\max}\)</span></td>
<td style="text-align: left;">non-fall 스텝 최대 개수</td>
<td style="text-align: center;"><span class="math inline">\(3\cdot 35\cdot 6 = 630\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\varepsilon_{\flat}\)</span></td>
<td style="text-align: left;">한 스텝 크기 상한 (<span class="math inline">\(\leq \tfrac{b}{8nT_{\max}}\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\leq \tfrac{1}{144} \approx 0.0069\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\|r\|_\infty \leq nLT_{\max}\,\varepsilon_{\flat}\)</span></td>
<td style="text-align: left;">누적 잔차 상한</td>
<td style="text-align: center;"><span class="math inline">\(\leq 630 \times 0.0069 = 4.375 = \tfrac{Lb}{8}\)</span></td>
</tr>
</tbody>
</table>
<p>즉 <span class="math inline">\(4.375\)</span>는 <strong>“630개의 미세한 flow·block 밀림(각 <span class="math inline">\(\leq 0.0069\)</span>)이 최악으로 한 방향 누적됐을 때”의 상한</strong>이지 아무 값이나가 아니다. <span class="math inline">\(K_{\mathsf{U}}\)</span>가 <span class="math inline">\(\|r\|_\infty \leq \tfrac{Lb}{8}\)</span> 공 <strong>전체</strong>를 덮는 이유도 — <em>우리가 <span class="math inline">\(r\)</span>을 고르는 게 아니라 <strong>HST 알고리즘 진행 중 어떤 랜덤성이 어떤 <span class="math inline">\(r\)</span>을 줄지 몰라</strong> 가능한 모든 경우를 커버</em>해야 하기 때문(worst-case 합집합). 그리고 각 <span class="math inline">\(r\)</span>은 버려지지 않고, fall 적립을 강체 평행이동 <span class="math inline">\(\mathbf{b}^\sharp \mapsto \mathbf{b}^\sharp - Q\,\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^\flat\)</span> 해서 fibre를 <span class="math inline">\(-r\)</span>만큼 밀어 <strong>정확히 흡수</strong>한다 (결산표 (iv) transport).</p>
<p>주의: <strong><span class="math inline">\(K_{\mathsf{U}} \neq U\)</span>.</strong> <span class="math inline">\(U\)</span>는 작은 <strong>도착지</strong>(<span class="math inline">\(\pm0.006\)</span>), <span class="math inline">\(K_{\mathsf{U}}\)</span>는 그걸 <span class="math inline">\(-\mathring{\mathbf{h}}(s^{\star})\)</span>(<span class="math inline">\(C_0\)</span>만큼)·<span class="math inline">\(-r\)</span>(잔차만큼)로 부풀린 <strong>큰 변위 목표 집합</strong>(<span class="math inline">\(\pm8.6\)</span>, 약 <span class="math inline">\(1400\times\)</span>).</p>
<p><strong>숙제 목록 <span class="math inline">\(K_{\mathsf{U}}\)</span>를 숫자로 — 출발 <span class="math inline">\(6\)</span> × 잔차 <span class="math inline">\(5\)</span> = <span class="math inline">\(30\)</span>개 곱집합.</strong> <span class="math inline">\(\mathbf{u} \in \mathsf{U}\)</span>는 거의 한 점(<span class="math inline">\(\approx (0.003,\,0.005)\)</span>)이라 고정하고, <strong>출발 <span class="math inline">\(s^{\star}\)</span></strong>는 <span class="math inline">\(C_0\)</span>의 6개 꼭짓점, <strong>잔차 <span class="math inline">\(r\)</span></strong>은 박스 <span class="math inline">\(\|r\|_\infty\leq\tfrac{Lb}{8}=4.375\)</span>의 중심+네 모서리 — 둘의 <strong>곱집합</strong>이 변위 <span class="math inline">\(\boldsymbol{\zeta} = u - \mathring{\mathbf{h}}(s^{\star}) - r\)</span>로 <span class="math inline">\(K_{\mathsf{U}}\)</span>를 채운다 (아래 30행 = 위 3×2 그림의 30점):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">출발 <span class="math inline">\(s^{\star}\)</span></th>
<th style="text-align: center;">잔차 <span class="math inline">\(r\)</span></th>
<th style="text-align: center;">변위 <span class="math inline">\(\boldsymbol{\zeta} = u - \mathring{\mathbf{h}}(s^{\star}) - r\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\|\boldsymbol{\zeta}\|_\infty\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\((2,-2)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-1.997,\ 2.005)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.01\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-6.372,\ 6.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.378,\ -2.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.378,\ 6.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-6.372,\ -2.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.37\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\((4,2)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-3.997,\ -1.995)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.00\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-8.372,\ 2.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.37\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0.378,\ -6.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.37\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0.378,\ 2.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-8.372,\ -6.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.37\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\((2,4)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-1.997,\ -3.995)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.00\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-6.372,\ 0.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.37\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.378,\ -8.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.37\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.378,\ 0.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-6.372,\ -8.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.37\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\((-2,2)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.003,\ -1.995)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.00\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-2.372,\ 2.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((6.378,\ -6.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((6.378,\ 2.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-2.372,\ -6.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.37\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\((-4,-2)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((4.003,\ 2.005)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.00\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-0.372,\ 6.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.378,\ -2.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((8.378,\ 6.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-0.372,\ -2.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.37\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\((-2,-4)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((0,0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((2.003,\ 4.005)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.01\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-2.372,\ 8.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((6.378,\ -0.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(6.38\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((-4.375,-4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((6.378,\ 8.380)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(8.38\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\((4.375,4.375)\)</span></td>
<td style="text-align: center;"><span class="math inline">\((-2.372,\ -0.370)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.37\)</span></td>
</tr>
</tbody>
</table>
<p>(<span class="math inline">\(u\)</span>는 chamber 중심 <span class="math inline">\(\tfrac{b}{128n}(1,2) = (\tfrac1{384},\tfrac1{192}) \approx (0.003,\,0.005)\)</span>로 고정 — <strong>정확히 <span class="math inline">\(0\)</span>이 아니라</strong> 등호 초평면을 피한 미세 offset이라, 그 꼬리가 <span class="math inline">\(\boldsymbol{\zeta}\)</span>의 셋째 자리에 남는다. 잔차 <span class="math inline">\(r\)</span>의 부호 조합에 따라 같은 크기인데도 <span class="math inline">\(\|\boldsymbol{\zeta}\|\)</span>가 <span class="math inline">\(\sim2.4\)</span> vs <span class="math inline">\(\sim8.4\)</span>로 갈린다: <span class="math inline">\(u-\mathring{\mathbf{h}}(s^{\star})\)</span>를 한쪽으로 밀면 커지고 상쇄하면 작아진다.)</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>이 표를 오해 없이 읽기 — 30점은 “집합 <span class="math inline">\(K_{\mathsf{U}}\)</span>의 표본·눈금”이지 “고른 표적 리스트”가 아니다.</strong> (i) <span class="math inline">\(r\)</span>값 <span class="math inline">\(0,\pm4.375\)</span>는 <strong>우리가 고른 게 아니라</strong> 잔차 박스의 <em>중심·네 모서리를 집어 범위를 보인 것</em> — 실제 <span class="math inline">\(r\)</span>은 HST 알고리즘을 진행하며 얻는 랜덤성에 의해 결정되고 우리는 바운드만 안다. (ii) <span class="math inline">\(u\)</span>도 편의상 중심에 고정했지만 실제론 <span class="math inline">\(U\)</span> 전체를 훑는다. (iii) 따라서 진짜 <span class="math inline">\(K_{\mathsf{U}}\)</span>는 점 30개가 아니라 <strong>위 그림의 연속 집합</strong>이고, falls는 이 점들을 명중하는 게 아니라 <strong>영역 전체에 밀도를 깐다</strong>(한 점은 측도 <span class="math inline">\(0\)</span>이라 애초에 명중 대상이 아니다).</p>
</div>
</div>
<p><span class="math inline">\(30\)</span>점 모두 <span class="math inline">\(\|\boldsymbol{\zeta}\|_\infty\leq8.38&lt;8.75\)</span> — “<span class="math inline">\(-\mathring{\mathbf{h}}(s^{\star})\)</span> (출발, 최대 <span class="math inline">\(2M_0{=}4\)</span>)”와 “<span class="math inline">\(-r\)</span> (잔차, 최대 <span class="math inline">\(4.375\)</span>)” 두 손잡이가 점만 한 <span class="math inline">\(U\)</span>를 <span class="math inline">\(\pm8.6\)</span>짜리 큰 집합 <span class="math inline">\(K_{\mathsf{U}}\)</span>로 부풀려도 도달역 안에 여유 두고 든다.</p>
<div id="d0e6e7fa" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-6-output-1.png" width="672" height="1002" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>6개 패널 = 6개 출발 <span class="math inline">\(s^{\star}\)</span></strong>(<span class="math inline">\(C_0\)</span>의 꼭짓점). 각 패널에서 색 박스는 그 출발의 표적 모임 — 중심 <span class="math inline">\(u-\mathring{\mathbf{h}}(s^{\star})\approx-s\)</span>, 한 변 <span class="math inline">\(\pm Lb/8=\pm4.375\)</span>인 <strong>잔차 박스</strong>(점 5개 = 중심+네 모서리), 그리고 연한 보라 외곽선이 <strong>전체 <span class="math inline">\(K_{\mathsf{U}}\)</span></strong>(6패널 박스의 합집합) 참조용. 출발마다 박스가 <span class="math inline">\(-s\)</span> 위치로 옮겨다니며 <span class="math inline">\(K_{\mathsf{U}}\)</span>를 채우는 게 한눈에 보인다. <span class="math inline">\(6\times5=30\)</span>개 표본 모두 <span class="math inline">\(\|\boldsymbol{\zeta}\|_\infty\leq8.38&lt;8.75\)</span>라 도달역(초록 점선) 안에 <strong>여유 <span class="math inline">\(\sim0.37\)</span></strong> 두고 든다.</p>
<p>각 패널의 <strong>다이아몬드는 그 박스의 중심 <span class="math inline">\(u-\mathring{\mathbf{h}}(s^{\star})\approx-s\)</span></strong>다. 이 6개 중심만 한 그림에 모으면 — 출발 <span class="math inline">\(s^{\star}\)</span>가 <span class="math inline">\(C_0\)</span> 꼭짓점이라 <span class="math inline">\(-s\)</span>도 <span class="math inline">\(C_0\)</span> 꼭짓점이므로 — <strong>다이아몬드 6개가 그대로 <span class="math inline">\(C_0\)</span> 육각형을 이룬다</strong> (잔차 박스를 떼고 “출발 손잡이만” 본 그림):</p>
<div id="b027d224" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-7-output-1.png" width="589" height="579" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>다이아몬드 6개(<span class="math inline">\(=\)</span>출발 손잡이만)가 <span class="math inline">\(-C_0\)</span> 육각형 꼭짓점에 놓이고, 여기에 각 다이아몬드마다 <span class="math inline">\(\pm4.375\)</span> 잔차 박스를 씌우면 위 3×2의 전체 <span class="math inline">\(K_{\mathsf{U}}\)</span>가 된다. 아래 접이식에 삼각부등식 증명을 둔다.</p>
<blockquote class="blockquote">
<p><strong>좌표계 주의 — 이 그림은 §2②의 도달역 그림과 축이 다르다.</strong> ②(LO_reach)는 <strong>위치 공간</strong>(축 <span class="math inline">\(h(v_i){-}h(v_1)\)</span>, 도달역이 출발 <span class="math inline">\(s^{\star}\)</span> 중심 <span class="math inline">\(s^{\star}+L\cdot\mathsf{O}\)</span>)이고, 이 그림은 <strong>변위 공간</strong> <span class="math inline">\(\boldsymbol{\zeta}\)</span>(원점 중심 <span class="math inline">\(\operatorname{int}(L\cdot\mathsf{O})\)</span>)다. 둘은 <span class="math inline">\(\boldsymbol{\zeta} = (\text{도착}) - (\text{출발 } s)\)</span>로 연결돼 — <strong>②의 화살표 하나(변위 <span class="math inline">\(\approx(-2,2)\)</span>)가 여기선 점 하나(A)</strong>다. “위치 = $s^{} + $ 변위”라, 변위 그림은 위치 그림을 <span class="math inline">\(s^{\star}\)</span>만큼 원점으로 끌어온 셈.</p>
</blockquote>
<p><strong>두 좌표계를 한 그림에 — 같은 변위, <span class="math inline">\(-s\)</span> 평행이동.</strong> 아래 통일 비교에서 (A) 위치 공간의 <strong>화살표</strong> <span class="math inline">\(s^{\star}\to U\)</span>가 (B) 변위 공간의 <strong>점 A</strong>로 그대로 옮겨간다. (B)는 (A)를 “출발 <span class="math inline">\(s^{\star}\)</span>를 원점으로” 끌어온 것 — 도달역 박스도 <span class="math inline">\(s^{\star}+L\cdot\mathsf{O}\)</span>(A)에서 <span class="math inline">\(L\cdot\mathsf{O}\)</span>(B)로 같이 평행이동한다.</p>
<div id="965e772f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-8-output-1.png" width="723" height="398" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>(A)에서 화살표가 가리키는 변위가 (B)에서 점 A로 찍힌다. <strong>(A)의 보라 영역이 <span class="math inline">\(s^{\star}+K_{\mathsf{U}}\)</span></strong> — 즉 <span class="math inline">\(K_{\mathsf{U}}\)</span>(변위)를 출발 <span class="math inline">\(s^{\star}\)</span>만큼 평행이동한 위치 집합이고, 도착 <span class="math inline">\(U\)</span>(<span class="math inline">\(\approx\)</span>원점)가 그 안에 든다(<strong><span class="math inline">\(U \subset s^{\star}+K_{\mathsf{U}}\)</span></strong>, <span class="math inline">\(u = \mathring{\mathbf h}(s^{\star})+\boldsymbol{\zeta}+r\)</span>이라). <span class="math inline">\(U\)</span>가 변위 그림 (B)에 직접 안 찍히는 이유가 이것 — <span class="math inline">\(U\)</span>는 위치라 <span class="math inline">\(K_{\mathsf{U}}\)</span>와 만나려면 <span class="math inline">\(s^{\star}\)</span>만큼 옮겨야 한다. 단, (B)의 <span class="math inline">\(K_{\mathsf{U}}\)</span>는 <strong>이 한 출발 <span class="math inline">\(s^{\star}\)</span>만이 아니라 <span class="math inline">\(C_0\)</span>의 모든 출발</strong>까지 union한 집합이라 (A)의 화살표 하나보다 크다 — 출발이 <span class="math inline">\(C_0\)</span> 안에서 움직이면 (B)의 점도 <span class="math inline">\(K_{\mathsf{U}}\)</span> 안을 훑는다.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🔽 접어둔 군사 계산 — 왜 숙제 목록 <span class="math inline">\(K_{\mathsf{U}}\)</span>가 도달역 안에 드나 (삼각부등식 + <span class="math inline">\(K_3\)</span> 수치)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>목표 집합의 한 점은 세 조각의 합이다: <span class="math display">\[\boldsymbol{\zeta} \;=\; \underbrace{u}_{\in\, \mathsf{U} \Subset \mathsf{O}} \;-\; \underbrace{\mathring{\mathbf{h}}(s^{\star})}_{s\,\in\, C_0} \;-\; \underbrace{r}_{\text{잔차}}.\]</span> 각 조각의 크기는: <span class="math inline">\(\|u\|_\infty &lt; \tfrac{b}{4}\)</span> (<span class="math inline">\(\mathsf{U} \Subset \mathsf{O}\)</span>), <span class="math inline">\(\|\mathring{\mathbf{h}}(s^{\star})\|_\infty \leq 2M_0\)</span> (각 anchored 차이 <span class="math inline">\(|\hbar(v_i){-}\hbar(v_1)| \leq 2M \leq 2M_0\)</span>), <span class="math inline">\(\|r\|_\infty \leq \tfrac{Lb}{8}\)</span> (잔차 예산). 삼각부등식으로 <span class="math display">\[\|\boldsymbol{\zeta}\|_\infty \;\leq\; \|u\|_\infty + \|\mathring{\mathbf{h}}(s^{\star})\|_\infty + \|r\|_\infty \;&lt;\; \frac{b}{4} + 2M_0 + \frac{Lb}{8}.\]</span> 이게 <span class="math inline">\(\operatorname{int}(L\cdot\mathsf{O}) = \{\|\cdot\|_\infty &lt; \tfrac{Lb}{4}\}\)</span> 안에 들려면 <span class="math inline">\(&lt; \tfrac{Lb}{4}\)</span>여야 하는데, <span class="math inline">\(L = \lceil 16M_0/b + 3\rceil\)</span>이라 <span class="math inline">\(\tfrac{Lb}{8} \geq 2M_0 + \tfrac{3b}{8}\)</span>이고 남는 margin이 <span class="math display">\[\frac{Lb}{4} - \Bigl(\frac{b}{4} + 2M_0 + \frac{Lb}{8}\Bigr) = \frac{Lb}{8} - \frac{b}{4} - 2M_0 \;\geq\; \bigl(2M_0 + \tfrac{3b}{8}\bigr) - \tfrac{b}{4} - 2M_0 = \frac{b}{8} \;&gt;\; 0.\]</span> 양의 margin(<span class="math inline">\(b/8\)</span>)이 남으니 <span class="math inline">\(K_{\mathsf{U}}\)</span>가 경계에서 떨어진 채(컴팩트하게) <span class="math inline">\(\operatorname{int}(L\cdot\mathsf{O})\)</span> 안에 든다.</p>
<p><strong>K3 수치로 확인</strong> (<span class="math inline">\(M_0 = 2\)</span>, <span class="math inline">\(b = 1\)</span>, <span class="math inline">\(L = 35\)</span>): <span class="math display">\[\|u\|_\infty &lt; \tfrac{1}{4} = 0.25, \quad \|\mathring{\mathbf{h}}(s^{\star})\|_\infty \leq 2M_0 = 4, \quad \|r\|_\infty \leq \tfrac{35}{8} = 4.375\]</span> <span class="math display">\[\Rightarrow \|\boldsymbol{\zeta}\|_\infty &lt; 0.25 + 4 + 4.375 = 8.625 \;&lt;\; \tfrac{Lb}{4} = 8.75,\]</span> margin <span class="math inline">\(= 8.75 - 8.625 = 0.125\,(= b/8)\)</span>. 즉 목표 전체가 도달역 <span class="math inline">\(\operatorname{int}(L\cdot\mathsf{O})\)</span> 안에 여유 <span class="math inline">\(b/8\)</span> 두고 들어간다. (<span class="math inline">\(L\)</span>의 상수를 <span class="math inline">\(+1\)</span>이 아니라 <span class="math inline">\(+3\)</span>으로 키운 게 바로 이 <span class="math inline">\(b/8\)</span> 여유를 — <span class="math inline">\(U\)</span>를 <span class="math inline">\(\mathsf{O}^\dagger\)</span> 없이 <span class="math inline">\(\mathsf{O}\)</span> 안에 직접 둬도 — 보장하는 장치다.)</p>
</div>
</div>
</div>
<div id="a3e733d4" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-9-output-1.png" width="723" height="351" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ol type="A">
<li>chamber <span class="math inline">\(U\)</span>(초록)는 원점 근처의 아주 작은 공이고(<span class="math inline">\(\mathsf{O}=\pm0.25\)</span> 박스 안에 들지만 그 박스는 너무 커서 화면 밖), 등호면 셋이 <strong>원점을 관통</strong>한다. (B) 더 줌인하면 <span class="math inline">\(U\)</span>가 등호면들에서 <span class="math inline">\(\kappa_{\mathsf{U}}\)</span> 떨어져 있다. <em>이 그림은 <strong>도착(chamber) 공간</strong>이라 원점 기준이다 (한 블록 reach의 <span class="math inline">\(\mathsf{O}\)</span>는 §2①의 <span class="math inline">\(s^{\star}\)</span>-기준 그림 참조).</em></li>
</ol>
<p><strong>④ <span class="math inline">\(U\)</span> — 실제 목표 chamber.</strong> (<em>chamber</em>란 등호 초평면 <span class="math inline">\(\{\widetilde{u}_i = \widetilde{u}_j\}\)</span>들로 잘려 나온 영역 하나 — 그 안에서는 노드 높이들의 <strong>대소 순서가 고정</strong>된 cell이다. 순서가 안 바뀌어야 fall이 목표를 일관되게 맞힐 수 있다.) <span class="math inline">\(U\)</span>는 증분 박스 <span class="math inline">\(\mathsf{O}\)</span> 안의 작은 <span class="math inline">\(\ell^\infty\)</span>-공인데, <strong>이 chamber 안에 들도록</strong>(=final-equality 초평면을 피해서) 잡는다. anchored 전체높이 <span class="math inline">\(\widetilde{u} = (0, u_1, u_2)\)</span> (여기 <span class="math inline">\(u=(u_1,u_2)\in U\)</span>)의 세 등호면 <span class="math display">\[\{u_1 = 0\},\quad \{u_2 = 0\},\quad \{u_1 = u_2\}\]</span> 위에선 fall이 목표를 robust하게 못 맞힌다 (퇴화 비교). 그래서 이 셋에서 떨어진 곳에 중심을 둔다: <span class="math display">\[\text{중심} = \tfrac{b}{128n}(1, 2) = \bigl(\tfrac{1}{384}, \tfrac{1}{192}\bigr) \approx (0.0026,\ 0.0052), \qquad \text{반경 } r_U = \tfrac{1}{1536}.\]</span> 이 <span class="math inline">\(U\)</span>는 세 초평면에서 최소 <span class="math inline">\(\kappa_{\mathsf{U}} = \tfrac{1}{768} \approx 0.0013\)</span> 떨어져 있다 (<span class="math inline">\((\ast)\)</span> 조건). 최종 기준측도가 바로 이 <span class="math inline">\(U\)</span> 위의 균등측도: <span class="math inline">\(\nu = \mathrm{Unif}(\mathsf{U})\otimes\delta_{v_3}\)</span>.</p>
<p><strong>Remark — <span class="math inline">\(U\)</span>가 원점일 이유는 없다 (원점은 편의·안전 선택).</strong> <span class="math inline">\(U\)</span>를 원점 근처에 둔 게 <em>필연</em>처럼 보이지만, 실제로 <span class="math inline">\(U\)</span>에 걸리는 제약은 둘뿐이고 둘 다 “<span class="math inline">\(U=\)</span> 원점”을 요구하지 않는다.</p>
<ol type="1">
<li><strong>모든 <span class="math inline">\(s^{\star}\in C_0\)</span>에서 도달 + density floor.</strong> <span class="math inline">\(U\)</span>는 <span class="math inline">\(C_0\)</span> 안 어느 출발점에서도 밀도를 깔며 닿아야 하므로 (도달역 <span class="math inline">\(\approx s^{\star} + L\cdot\mathsf{O}\)</span>), <span class="math display">\[U \subset \bigcap_{s^{\star}\in C_0}\bigl(s^{\star} + L\cdot\mathsf{O}\bigr).\]</span> <span class="math inline">\(C_0\)</span>가 원점 대칭이라 이 교집합은 <strong>원점 중심</strong>이지만 반경이 <span class="math inline">\(\sim 3M_0\)</span>로 <strong>크다</strong> — <span class="math inline">\(U\)</span>는 그 큰 영역 어디든 가능하지 원점에 붙을 필요가 없다.</li>
<li><strong>등호 초평면 회피 (<span class="math inline">\(\kappa_{\mathsf{U}}\)</span>).</strong> ties <span class="math inline">\(\{\widetilde{u}_i=\widetilde{u}_j\}\)</span>만 피하면 된다.</li>
</ol>
<p>어느 제약도 “<span class="math inline">\(U=\)</span> 원점”을 강제하지 않는다. 그럼 왜 논문은 원점 근처에 두나?</p>
<ul>
<li><strong>원점 <span class="math inline">\(=\)</span> 대칭 중심 <span class="math inline">\(=\)</span> 최대 여유점.</strong> <span class="math inline">\(\bigcap_{s}(s^{\star}+L\cdot\mathsf{O})\)</span>가 원점 중심이라 원점 근처가 도달역 경계에서 가장 멀다 — “아무 데나 둬도 되지만 가장 안전한 데” 둔 것.</li>
<li><strong><span class="math inline">\(\mathsf{U} \Subset \mathsf{O}\)</span> (b/4)면 충분.</strong> containment <span class="math inline">\(K_{\mathsf{U}} \Subset \operatorname{int}(L\cdot\mathsf{O})\)</span>는 <span class="math inline">\(\|u\|_\infty &lt; b/4\)</span>로 충분하다 (위 삼각부등식, margin <span class="math inline">\(b/8\)</span>). <em>옛 판본은 <span class="math inline">\(U\)</span>를 더 작은 <span class="math inline">\(\mathsf{O}^\dagger{=}\{b/16\}\)</span>에 가뒀지만, <span class="math inline">\(L\)</span>의 상수를 <span class="math inline">\(+3\)</span>으로 키워 그 과조임을 없애고 <span class="math inline">\(\mathsf{O}\)</span> 안에 직접 두도록 정리됐다 — 정본 정합.</em></li>
<li><strong>위치에 의미 있는 단 하나:</strong> chamber 중심 <span class="math inline">\(\tfrac{b}{128n}(1,2,\ldots,n-1)\)</span>은 높이가 살짝 <strong>증가</strong>(<span class="math inline">\(v_n\)</span> 최고)하게 잡혔다 — 끝노드 <span class="math inline">\(v_n\)</span> pinning(<span class="math inline">\(\delta_{v_n}\)</span>) 때문. 즉 “원점 자체”가 아니라 “원점에서 <span class="math inline">\(v_n\)</span> 쪽으로 미세하게 기운 작은 공”이고, 이건 pinning용이지 원점이라서가 아니다.</li>
</ul>
<p><strong>요컨대</strong> <span class="math inline">\(U\)</span>의 위치는 “<span class="math inline">\(\bigcap_{s^{\star}\in C_0}(s^{\star}+L\cdot\mathsf{O})\)</span> (원점 중심 큰 영역) 안 <span class="math inline">\(+\)</span> ties 밖”이면 <strong>자유</strong>다. 원점 근처에 둔 건 대칭 중심의 최대-여유 <em>편의 선택</em>(<span class="math inline">\(+\,v_n\)</span> pinning용 미세 기울기)이지 필연이 아니다.</p>
<hr>
</section>
<section id="무엇을-보일지-다시-구성-목표" class="level2">
<h2 class="anchored" data-anchor-id="무엇을-보일지-다시-구성-목표">§4. 무엇을 보일지 다시 — 구성 목표</h2>
<p>이 절이 최종적으로 보일 부등식은, 라운드 스켈레톤 커널 <span class="math inline">\(P^{\star}\)</span>에 대해: <span class="math display">\[(P^{\star})^{\,m}(s^{\star}, \cdot) \;\geq\; \eta\,\mathrm{Unif}(\mathsf{U})\otimes\delta_{v_n} \qquad (\forall\, s^{\star} \in C_0),\]</span> 즉 <strong><span class="math inline">\(C_0\)</span> 안 모든 <span class="math inline">\(s^{\star}\)</span>에서 <span class="math inline">\(m\)</span>라운드 뒤 분포에 공통 바닥이 깔린다.</strong> smallness가 <span class="math inline">\(\mathsf{U}\)</span>에 요구하는 건 양의 Lebesgue 측도뿐이고, 편의상 (i) <span class="math inline">\(\mathbf{0}\)</span> 근처 + (ii) <strong>하나의 ordering chamber 안</strong>(노드 높이 대소가 <span class="math inline">\(\mathsf{U}\)</span> 전체에서 한 가지로 고정 — <span class="math inline">\(\mathbf{0}\)</span> 근처이되 tie에서 떨어진 곳)에 잡는다 (1부 §3 ④). 직접 <strong>구성</strong>할 것은 <span class="math inline">\(\mathsf{U}\)</span>·<span class="math inline">\(m\)</span>·<span class="math inline">\(\eta&gt;0\)</span> 셋. 기준측도는 <span class="math display">\[\nu = \mathrm{Unif}(\mathsf{U}) \otimes \delta_{v_3},\]</span> “높이차는 chamber <span class="math inline">\(\mathsf{U}\)</span>를 균등하게 덮고, walker는 <span class="math inline">\(v_3\)</span>(<span class="math inline">\(=v_n\)</span>)에 못박힌다.”</p>
<hr>
</section>
</section>
<section id="제2부.-proof-sketch-시나리오-넷으로-점진-조이기" class="level1">
<h1>제2부. Proof sketch — 시나리오 넷으로 점진 조이기</h1>
<blockquote class="blockquote">
<p><strong>2부 안내</strong>: 정본 Lemma 8의 proof sketch를 그대로 따라간다. 비현실적인 favourable 시나리오에서 출발해, <strong>(1→4) 네 번 고쳐 쓰며</strong> realistic 시나리오로 조여간다. 매 시나리오는 다섯 항목 — (1) fall, (2) non-fall 적립, (3) branch, (4) 라운드 증분, (5) 종착 높이차 — 으로 쓰고, 직전 대비 바뀐 부분만 밑줄로 발전한다 (대표 “동일내용 동일언어”).</p>
</blockquote>
<section id="scenario-1-favourable-확률-0짜리-픽션에서-출발" class="level2">
<h2 class="anchored" data-anchor-id="scenario-1-favourable-확률-0짜리-픽션에서-출발">Scenario 1 (favourable) — 확률 0짜리 픽션에서 출발</h2>
<p>증명 전체에서 <strong>branch</strong>(분기) <span class="math inline">\(\amalg\)</span>는 한 라운드에서 walker가 non-fall 스텝에 실제로 밟는 경로 — falls가 정해주지 않는 이산 자유도다.</p>
<blockquote class="blockquote">
<p><strong>Scenario 1 (favourable).</strong> (1) 매 라운드는 fall로 시작: 노드가 <span class="math inline">\(\boldsymbol{\mu}_0\)</span>로 뽑히고 적립 <span class="math inline">\(b^{\sharp}_{t_r}\sim\mathrm{Unif}(0,b)\)</span>을 받는다; (2) 모든 non-fall 스텝은 <strong>아무것도 적립하지 않는다</strong> (zero deposit); (3) 라운드의 branch는 (1)의 fall 적립만으로 고정 — (2)의 교란 없음; (4) 각 라운드의 anchored 높이 <span class="math inline">\(\mathring{\mathbf{h}}\)</span> 변화는 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>에만 의존; (5) <span class="math inline">\(m\)</span>라운드 뒤 높이차는 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>에만 의존하고, <span class="math inline">\(\mathsf{U}\)</span>에 떨어진다.</p>
</blockquote>
</section>
<section id="항목-1-들여다보기-cyclic-falls와-바닥-mu_sharp" class="level2">
<h2 class="anchored" data-anchor-id="항목-1-들여다보기-cyclic-falls와-바닥-mu_sharp">항목 (1) 들여다보기 — cyclic falls와 바닥 <span class="math inline">\(\mu_{\sharp}\)</span></h2>
<p><span class="math inline">\(r\)</span>번째 fall 표적을 <span class="math inline">\(v^{\sharp}_r\)</span>라 쓰고 <span class="math inline">\(v_1, v_2, \dots, v_n\)</span> 순환으로 잡는다. <span class="math inline">\(m\)</span>이 <span class="math inline">\(n\)</span>의 배수면 마지막 fall이 <span class="math inline">\(v_n\)</span>에 못박혀, falls가 표적만 다 맞히면 노드 좌표 <span class="math inline">\(\{v_n\}\)</span>은 <strong>확정</strong>이다. (스켈레톤은 fall 시각에 읽으므로 윈도우는 terminal fall에서 닫힌다 — 그 뒤 flow는 다음 라운드 소속.) 맞히기는 쉽다: fall 위치가 i.i.d. <span class="math inline">\(\boldsymbol{\mu}_0\)</span>-draw(snowfall A)라 <span class="math display">\[\mathbb{P}\Bigl(\bigcap_{r=1}^{m}\{X_{t_r} = v^{\sharp}_r\}\Bigr) \;=\; \prod_{r=1}^{m}\boldsymbol{\mu}_0(v^{\sharp}_r) \;\geq\; \Bigl(\min_{i}\boldsymbol{\mu}_0(v_i)\Bigr)^{m} \;=:\; \mu_{\sharp},\]</span> 시작 <span class="math inline">\(s^{\star}\)</span>와 무관한 바닥. <strong><span class="math inline">\(K_3\)</span> 수치</strong>: <span class="math inline">\(\boldsymbol{\mu}_0\)</span> 균등이면 <span class="math inline">\(\mu_{\sharp} = (\tfrac13)^{105}\)</span> — 지수적으로 작지만 양수, 그게 전부다.</p>
<p>왜 <span class="math inline">\(m\)</span>이 <span class="math inline">\(n\)</span>의 배수여야 하나? <span class="math inline">\(v_1,\dots,v_n\)</span> 한 바퀴가 <strong>cycle</strong>(<span class="math inline">\(n\)</span> falls)이고, <span class="math inline">\(m=nL\)</span>(<span class="math inline">\(L\)</span>=cycle 수)로 잡으면 마지막 fall이 <span class="math inline">\(v_n\)</span>에 고정된 채 <span class="math inline">\(L\)</span>을 마음껏 키울 수 있다. <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\(L=35\)</span>, <span class="math inline">\(m=nL=105\)</span>.</p>
<blockquote class="blockquote">
<p><strong>Scenario 2 (favourable, with the fall floor).</strong> (1) 매 라운드는 fall로 시작: 노드가 <span class="math inline">\(\boldsymbol{\mu}_0\)</span>로 뽑히고 적립 <span class="math inline">\(b^{\sharp}_{t_r}\sim\mathrm{Unif}(0,b)\)</span>을 받고, <u>falls는 <span class="math inline">\(nL\)</span>라운드(<span class="math inline">\(L\)</span> cycles)에 걸쳐 <span class="math inline">\(v_1,\dots,v_n\)</span> 순서로 순환하며, 그 표적을 전부 맞힐 확률 <span class="math inline">\(\geq\mu_{\sharp}\)</span></u>; (2)~(5) Scenario 1과 동일.</p>
</blockquote>
</section>
<section id="항목-5로-fall-map-boldsymbollambdasharp" class="level2">
<h2 class="anchored" data-anchor-id="항목-5로-fall-map-boldsymbollambdasharp">항목 (5)로 — fall map <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span></h2>
<p>(2)로 non-fall 적립이 전부 0이면 <strong>flow 알고리즘이 사실상 삭제</strong>된다: walker가 falls 사이에 어떻게 흐르든 아무것도 안 쌓으니, HST는 “매 fall마다 새 노드에 눈이 쏟아지는” 과정으로 환원된다 — (4)가 기록하는 내용. 그러면 (5)는 도달 가능성 문제가 된다: 원하는 표적 <span class="math inline">\(\mathbf{u}\in\mathsf{U}\)</span>에 대해 fall 적립 <span class="math inline">\(\mathbf{b}^{\sharp}\in[0,b]^{m}\)</span>과 그 누적 효과를 담는 선형 <strong>fall map</strong> <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>가 있어 <span class="math display">\[\mathbf{u} \;=\; \mathring{\mathbf{h}}(s^{\star}) + \boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp} + \mathbf{0},\]</span> 셋째 항이 <span class="math inline">\(\mathbf{0}\)</span>인 건 이 시나리오에서 <span class="math inline">\(\mathbf{b}^{\flat}=\mathbf{0}\)</span>이기 때문. <span class="math inline">\(L\)</span>은 fall 변위가 <span class="math inline">\(\mathring{\mathbf{h}}(s^{\star})\)</span>에서 <span class="math inline">\(\mathbf{u}\)</span>까지 닿도록 크게 잡는다 (1부 §3 ②의 <span class="math inline">\(L\cdot\mathsf{O}\)</span> 도달역, <span class="math inline">\(K_3\)</span>에서 <span class="math inline">\(L=35\)</span>면 <span class="math inline">\(\pm8.75\)</span>).</p>
<p><strong><span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>의 모양을 들여다보자.</strong> <span class="math inline">\(m=nL\)</span> falls라 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\in\mathbb{R}^{(n-1)\times nL}\)</span>, 성분은 <span class="math inline">\(0,1,-1\)</span>뿐이다. cycle 하나가 <span class="math inline">\((n-1)\times n\)</span> 블록 하나를 기여하고, <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>는 그 <span class="math inline">\(L\)</span>개 블록을 옆으로 이어붙인 것: <span class="math display">\[\boldsymbol{\Lambda}^{\sharp} \;=\; \underbrace{\left[\begin{array}{ccc|ccc|c|ccc} -1&amp;1&amp;0 &amp; -1&amp;1&amp;0 &amp; \cdots &amp; -1&amp;1&amp;0\\ -1&amp;0&amp;1 &amp; -1&amp;0&amp;1 &amp; &amp; -1&amp;0&amp;1 \end{array}\right]}_{L\ \text{blocks}} \;\in\; \mathbb{R}^{2\times 105} \qquad (K_3:\ n=3,\ L=35).\]</span> 각 블록은 첫 열이 <span class="math inline">\(-1\)</span>, 나머지 <span class="math inline">\(n-1\)</span>열이 항등 — 블록의 <span class="math inline">\(k\)</span>행은 그 cycle의 anchored 증분 <span class="math inline">\(b^{\sharp}_{k+1}-b^{\sharp}_1\)</span>을 돌려준다. 블록꼴로 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp} = [\,\boldsymbol{\Lambda}^{\sharp}_1 \mid \cdots \mid \boldsymbol{\Lambda}^{\sharp}_L\,]\)</span>, <strong><span class="math inline">\(L\)</span>개 블록이 전부 동일</strong>하다. 이 행렬은 falls가 노드를 방문한 순서의 기록 그 자체이고, <span class="math inline">\(m=nL\)</span>이 고정되면 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>는 고정 행렬, <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>는 값은 몰라도 <strong>길이는 고정</strong>이다.</p>
<blockquote class="blockquote">
<p><strong>Scenario 3 (favourable, with the fall map).</strong> (1)~(4) Scenario 2와 동일; (5) <u><span class="math inline">\(m=nL\)</span></u>라운드 뒤 높이차는 <u><span class="math inline">\(\mathbf{u} = \mathring{\mathbf{h}}(s^{\star}) + \boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp}\)</span>와 같고</u>, <span class="math inline">\(\mathsf{U}\)</span>에 떨어진다.</p>
</blockquote>
</section>
<section id="픽션-걷어내기-varepsilon_flat와-non-fall-map-boldsymbollambdaflat_amalg" class="level2">
<h2 class="anchored" data-anchor-id="픽션-걷어내기-varepsilon_flat와-non-fall-map-boldsymbollambdaflat_amalg">픽션 걷어내기 — <span class="math inline">\(\varepsilon_{\flat}\)</span>와 non-fall map <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\)</span></h2>
<p>이 favourable 시나리오는 물론 <strong>확률 0짜리 픽션</strong>이다. 이미 (2) — non-fall 적립이 정확히 0 — 부터 연속분포라 절대 안 일어난다. 0에 못박는 대신 <strong>작은 <span class="math inline">\(\varepsilon_{\flat}\in(0,b)\)</span>로 묶는다</strong>: non-fall 적립이 <span class="math inline">\(\mathrm{Unif}(0,b)\)</span>라 한 스텝이 <span class="math inline">\(\varepsilon_{\flat}\)</span> 아래일 확률은 <span class="math inline">\(\varepsilon_{\flat}/b&gt;0\)</span> (<span class="math inline">\(\varepsilon_{\flat}&lt;b\)</span>라 양수). 효과는 더 이상 소멸하지 않지만 시나리오가 <strong>양의 확률 사건</strong>이 된다 — 바닥에 필요한 건 그게 전부다.</p>
<p>이 0 아닌(하지만 <span class="math inline">\(\leq\varepsilon_{\flat}\)</span>) non-fall 적립을 나르는 것이 <span class="math display">\[\boldsymbol{\Lambda}^{\flat}_{\amalg}\,\mathbf{b}^{\flat} \;\in\; \mathbb{R}^{n-1},\]</span> <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp}\)</span>의 non-fall 짝이다 (<span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\)</span>가 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span> 역할, <span class="math inline">\(\mathbf{b}^{\flat}\)</span>가 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span> 역할). 아래첨자 <span class="math inline">\(\amalg\)</span>는 <strong>윈도우 전체의 branch</strong> — 이 맵이 거기 의존한다. <span class="math inline">\(\mathbf{b}^{\flat}\)</span>의 길이는 선험적으로 고정이 아니다: 모든 fall 직후 block이면 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>와 같은 차원, flow가 하나 늘 때마다 좌표가 하나 늘고 <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\)</span>도 따라 자란다.</p>
<p>고정 아닌 걸 고정하면 편하다 — <strong>padding trick</strong>: 라운드당 non-fall 스텝은 최대 <span class="math inline">\(T_{\max}\)</span>개니, 각 라운드의 빈 슬롯을 0 더미로 채운다. 그러면 <span class="math inline">\(\mathbf{b}^{\flat}\)</span>는 길이 <span class="math inline">\(nLT_{\max}\)</span> 고정 벡터, <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\)</span>는 <span class="math inline">\((n-1)\times nLT_{\max}\)</span> 고정 크기 행렬 — 성분은 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>처럼 <span class="math inline">\(0,1,-1\)</span> (패딩 슬롯은 0열). 역시 라운드당 한 블록으로 쪼개진다: <span class="math display">\[\boldsymbol{\Lambda}^{\flat}_{\amalg} \;=\; \bigl[\, \boldsymbol{\Lambda}^{\flat}_1 \mid \boldsymbol{\Lambda}^{\flat}_2 \mid \cdots \mid \boldsymbol{\Lambda}^{\flat}_{nL} \,\bigr], \qquad \boldsymbol{\Lambda}^{\flat}_r \in \mathbb{R}^{(n-1)\times T_{\max}},\]</span> 각 <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_r\)</span>는 라운드 <span class="math inline">\(r\)</span>의 branch 조각(그 라운드의 non-fall 방문 노드들)에 의존하고 그 라운드의 non-fall 적립 <span class="math inline">\(\mathbf{b}^{\flat}_r\in\mathbb{R}^{T_{\max}}\)</span>에 작용한다 — 방문 노드의 열은 그 anchored 증분, 미사용 슬롯의 열은 <span class="math inline">\(\mathbf{0}\)</span>. <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\(T_{\max}=2n=6\)</span>, <span class="math inline">\(\mathbf{b}^{\flat}\in\mathbb{R}^{630}\)</span>, <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\in\mathbb{R}^{2\times630}\)</span>, 블록 <span class="math inline">\(105\)</span>개(각 <span class="math inline">\(2\times6\)</span>).</p>
</section>
<section id="branch에-대한-한마디-mathbfbflat이-branch-집합을-흔든다" class="level2">
<h2 class="anchored" data-anchor-id="branch에-대한-한마디-mathbfbflat이-branch-집합을-흔든다">branch에 대한 한마디 — <span class="math inline">\(\mathbf{b}^{\flat}\)</span>이 branch 집합을 흔든다</h2>
<p>favourable 시나리오에선 가능한 branch 집합이 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>에만 의존했다. <span class="math inline">\(\mathbf{b}^{\flat}\)</span>이 들어오는 순간 그 집합은 더 이상 고정이 아니다 — 라운드 중 쌓이는 작은 적립이 높이 비교 하나를 <strong>뒤집어</strong> 열리는 flow 경로를 바꿀 수 있으니까.</p>
<blockquote class="blockquote">
<p><strong>Example (branch set perturbed by non-fall deposits, 정본 Example 1).</strong> 경로 그래프 <span class="math inline">\(v_1\!-\!v_2\!-\!v_3\)</span>에서 <span class="math inline">\(v_1\)</span>에 fall이 떨어져 높이가 <span class="math inline">\((1,\ 0.99,\ 0.999)\)</span>가 됐다 하자. - <span class="math inline">\(\mathbf{b}^{\flat}=\mathbf{0}\)</span>이면: walker는 <span class="math inline">\(v_1\to v_2\)</span> (<span class="math inline">\(v_1\)</span>의 유일한 하류) 후 — <span class="math inline">\(v_2\)</span>에 아무것도 안 쌓이니 <span class="math inline">\(h(v_2)=0.99\)</span>로 양 이웃(<span class="math inline">\(1\)</span>, <span class="math inline">\(0.999\)</span>)이 다 위라 <strong>block</strong>. branch는 <span class="math inline">\(v_1\,v_2\)</span> 하나뿐. - <span class="math inline">\(\mathbf{b}^{\flat}\neq\mathbf{0}\)</span>이면: <span class="math inline">\(v_2\)</span>에 <span class="math inline">\(b^{\flat}\)</span>이 쌓여 <span class="math inline">\(h(v_2)=0.99+b^{\flat}\)</span>. - <span class="math inline">\(b^{\flat}\in[0,0.009)\)</span>: <span class="math inline">\(0.99+b^{\flat}&lt;0.999\)</span> — 여전히 block, branch <span class="math inline">\(v_1\,v_2\)</span>; - <span class="math inline">\(b^{\flat}\in(0.009,0.01)\)</span>: <span class="math inline">\(0.999&lt;0.99+b^{\flat}&lt;1\)</span> — <span class="math inline">\(v_3\)</span>만 열림, branch <span class="math inline">\(v_1\,v_2\,v_3\)</span>; - <span class="math inline">\(b^{\flat}&gt;0.01\)</span>: 양 이웃 다 열림 — walker가 각 <span class="math inline">\(\tfrac12\)</span>로 픽, branch <span class="math inline">\(v_1\,v_2\,v_1\)</span> 또는 <span class="math inline">\(v_1\,v_2\,v_3\)</span>.</p>
<p>같은 fall인데 <span class="math inline">\(b^{\flat}\)</span>만으로 branch가 갈린다. 그래서 <span class="math inline">\(\amalg\)</span>는 “여럿 중 실현된 한 branch”로 읽어야 하고, <span class="math inline">\(\mathbf{b}^{\flat}\)</span>과 독립적으로 고를 수 없다 — 어떤 <span class="math inline">\(\mathbf{b}^{\flat}\)</span>에서는 주어진 <span class="math inline">\(\amalg\)</span>가 아예 안 일어난다.</p>
</blockquote>
</section>
<section id="종착-높이의-세-가지-동등한-분해" class="level2">
<h2 class="anchored" data-anchor-id="종착-높이의-세-가지-동등한-분해">종착 높이의 세 가지 동등한 분해</h2>
<p><span class="math display">\[\begin{aligned} \mathbf{u} &amp;= \mathring{\mathbf{h}}(s^{\star}) + \boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp} + \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat} \quad (\text{complete maps}) \\ &amp;= \mathring{\mathbf{h}}(s^{\star}) + \sum_{\ell=1}^{L} \boldsymbol{\Lambda}^{\sharp}_{\ell}\mathbf{b}^{\sharp}_{\ell} + \sum_{\ell=1}^{L} \boldsymbol{\Lambda}^{\flat}_{\ell}\mathbf{b}^{\flat}_{\ell} \quad (\text{by cycle}) \\ &amp;= \mathring{\mathbf{h}}(s^{\star}) + \sum_{r=1}^{nL} \boldsymbol{\lambda}^{\sharp}_{r}\, b^{\sharp}_{r} + \sum_{r=1}^{nL} \boldsymbol{\Lambda}^{\flat}_r \mathbf{b}^{\flat}_r \quad (\text{by round}), \end{aligned}\]</span></p>
<p><span class="math inline">\(\ell=1,\dots,L\)</span>은 cycle, <span class="math inline">\(r=1,\dots,nL\)</span>은 round 인덱스: <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}_{\ell}\)</span>·<span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\ell}\)</span>는 cycle <span class="math inline">\(\ell\)</span>의 fall·non-fall 블록(<span class="math inline">\(\mathbf{b}^{\sharp}_{\ell}\in\mathbb{R}^{n}\)</span>, <span class="math inline">\(\mathbf{b}^{\flat}_{\ell}\in\mathbb{R}^{nT_{\max}}\)</span>에 작용 — <span class="math inline">\(K_3\)</span>: <span class="math inline">\(\mathbb{R}^3\)</span>, <span class="math inline">\(\mathbb{R}^{18}\)</span>), <span class="math inline">\(\boldsymbol{\lambda}^{\sharp}_{r}\in\mathbb{R}^{n-1}\)</span>은 round <span class="math inline">\(r\)</span>의 단일 fall 적립 <span class="math inline">\(b^{\sharp}_{r}\)</span>의 열벡터. <strong>대비가 포인트다: fall 블록은 전부 동일, non-fall 블록은 서로 다르다</strong> — 그래서 <span class="math inline">\(m=nL\)</span>을 고정해도 <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\)</span>는 branch 의존으로 남는다. 끝으로 모든 non-fall 적립이 <span class="math inline">\(\varepsilon_{\flat}\)</span> 아래일 확률은 <span class="math display">\[\mathbb{P}\Bigl(\bigcap_{t\,\text{non-fall}}\{b^{\flat}_t \leq \varepsilon_{\flat}\}\Bigr) \;=\; \prod_{t\,\text{non-fall}}\frac{\varepsilon_{\flat}}{b} \;\geq\; \Bigl(\frac{\varepsilon_{\flat}}{b}\Bigr)^{nLT_{\max}},\]</span> non-fall 스텝이 최대 <span class="math inline">\(nLT_{\max}\)</span>개이고 <span class="math inline">\(\varepsilon_{\flat}/b&lt;1\)</span>이라 부등식이 성립. <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\((\varepsilon_{\flat})^{630}\)</span> (<span class="math inline">\(b=1\)</span>).</p>
<blockquote class="blockquote">
<p><strong>Scenario 4 (realistic).</strong> — 이제 현실적이지만, 대가가 있다: <span class="math inline">\(\mathbf{b}^{\flat}\neq\mathbf{0}\)</span>이라 branch를 더는 고정 못 하고, <span class="math inline">\(m=nL\)</span>라운드 뒤 높이차도 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>만으로는 못 박는다. (1) Scenario 3과 동일; (2) 모든 non-fall 스텝은 <u>작지만 0 아닌 양을, 최대 <span class="math inline">\(\varepsilon_{\flat}\)</span>까지, 확률 <span class="math inline">\(\geq(\varepsilon_{\flat}/b)^{nLT_{\max}}\)</span>로</u> 적립; (3) 라운드의 branch는 <u>더 이상</u> (1)의 fall 적립만으로 고정되지 <u>않는다: (2)의 작은 적립이 높이 비교를 뒤집어 바꿀 수 있다</u>; (4) 각 라운드의 <span class="math inline">\(\mathring{\mathbf{h}}\)</span> 변화는 <u><span class="math inline">\(\mathbf{b}^{\sharp}\)</span>만이 아니라 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>, <span class="math inline">\(\amalg\)</span>, <span class="math inline">\(\mathbf{b}^{\flat}\)</span> 셋에 함께</u> 의존; (5) <span class="math inline">\(m=nL\)</span>라운드 뒤 높이차는 <span class="math inline">\(\mathbf{u} = \mathring{\mathbf{h}}(s^{\star}) + \boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp}\)</span><u><span class="math inline">\({}+\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\)</span></u>.</p>
</blockquote>
<p>여기까지가 sketch다. 남은 일은 Scenario 4 위에서 <strong>밀도 바닥</strong>을 실제로 깔아내는 것 — 3부 full proof의 몫.</p>
<hr>
</section>
</section>
<section id="제3부.-full-proof-두-바닥discrete-density으로-닫기" class="level1">
<h1>제3부. Full proof — 두 바닥(discrete · density)으로 닫기</h1>
<blockquote class="blockquote">
<p><strong>3부 안내</strong>: 정본 full proof의 station 사슬을 그대로 따른다 — 목표선언 → 좌변 전개(master 부등식) → <strong>discrete floor</strong> 즉시 해소 → <strong>density floor</strong>를 환원 사슬로: <span class="math inline">\((\dagger)\)</span> 치환적분 → slice floor <span class="math inline">\(m_0\)</span> → robust core <span class="math inline">\(m_*\)</span> → transport → 조립 <span class="math inline">\(c_*\)</span>. 옛 판본의 coarea/Hausdorff 측도는 <strong>폐지</strong>됐고, 전부 <strong>Lebesgue만으로</strong> 간다.</p>
</blockquote>
<section id="목표선언-eta의-정체" class="level2">
<h2 class="anchored" data-anchor-id="목표선언-eta의-정체">목표선언 — <span class="math inline">\(\eta\)</span>의 정체</h2>
<p><span class="math inline">\(nL\)</span>라운드와 chamber 측도 <span class="math inline">\(\nu := \mathrm{Unif}(\mathsf{U})\otimes\delta_{v_n}\)</span>로 <span class="math display">\[(P^{\star})^{nL}(s^{\star},\cdot) \;\geq\; \eta\,\nu \quad (s^{\star}\in C_0), \qquad \eta := \mu_{\min}^{nL}\,q_{\min}^{D}\,(\varepsilon_{\flat}/b)^{nLT_{\max}}\,c_*\,|\mathsf{U}|_{\mathrm{Leb}} \;&gt;\; 0\]</span> 을 증명한다. 동치로, 모든 Borel <span class="math inline">\(B\subseteq\mathsf{U}\)</span>에 대해 <span class="math inline">\((P^{\star})^{nL}(s^{\star}, B\times\{v_n\}) \geq \eta\,|B|_{\mathrm{Leb}}/|\mathsf{U}|_{\mathrm{Leb}}\)</span> (<span class="math inline">\(\because \nu(B\times\{v_n\}) = |B|_{\mathrm{Leb}}/|\mathsf{U}|_{\mathrm{Leb}}\)</span>). <span class="math inline">\(\eta\)</span>는 <strong>discrete floor</strong> <span class="math inline">\(\mu_{\min}^{nL}q_{\min}^{D}(\varepsilon_{\flat}/b)^{nLT_{\max}}\)</span> 곱하기 <strong>fall-density floor</strong> <span class="math inline">\(c_*&gt;0\)</span>로 쪼개지고, 모든 인자가 <span class="math inline">\(s^{\star}\)</span>와 무관하다.</p>
</section>
<section id="좌변을-확률로-읽기-good-event-g_b와-rho_mathbfbflat" class="level2">
<h2 class="anchored" data-anchor-id="좌변을-확률로-읽기-good-event-g_b와-rho_mathbfbflat">좌변을 확률로 읽기 — good event <span class="math inline">\(G_B\)</span>와 <span class="math inline">\(\rho_{\mathbf{b}^{\flat}}\)</span></h2>
<p><span class="math display">\[(P^{\star})^{nL}(s^{\star}, B\times\{v_n\}) \;=\; \mathbb{P}_{s^{\star}}\bigl(S^{\star}_{r+nL}\in B\times\{v_n\}\bigr)\]</span> — <span class="math inline">\(nL\)</span>라운드 뒤 스켈레톤 walker가 <span class="math inline">\(v_n\)</span>에 있고 anchored 높이가 <span class="math inline">\(B\)</span>에 들 확률. (종점은 terminal fall 시각 <span class="math inline">\(t_{r+nL}\)</span><strong>에서</strong> 읽으므로 <span class="math inline">\(X_{t_{r+nL}}=v_n\)</span>은 마지막 fall의 표적 그대로 — 그 뒤 라운드 내 flow는 구간 <span class="math inline">\((t_{r+nL},t_{r+nL+1}]\)</span>, 이 전이 밖이다.) 윈도우 동안 anchored 높이는 <span class="math display">\[\mathring{\mathbf{h}}(s^{\star}) \;\longmapsto\; \mathring{\mathbf{h}}(s^{\star}) + \boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp} + \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\]</span> 로 움직인다 — 2부 Scenario 4의 (5) 그대로. non-fall 기여는 “사후에야 아는 shift”가 아니라 <strong>branch-고정 선형 맵의 작은 출력</strong>이다.</p>
<p>전이를 한 favourable 시나리오로 하한한다: <span class="math inline">\(nL\)</span> falls가 <span class="math inline">\(v_1,\dots,v_n\)</span> 순환 표적을 맞히고(terminal <span class="math inline">\(v_n\)</span>), walker가 고정 branch <span class="math inline">\(\amalg\)</span>를 실현하며 fall 적립은 robust core <span class="math inline">\(\mathcal{R}_{\delta,\amalg}\)</span>(아래에서 깎음) 안, 모든 non-fall 적립 <span class="math inline">\(\leq\varepsilon_{\flat}\)</span>. 그 위에서 walker는 <span class="math inline">\(v_n\)</span>에 도착하고, 높이가 <span class="math inline">\(B\)</span>에 드는 것은 정확히 <strong>good event</strong> <span class="math display">\[G_B \;=\; \Bigl\{(\mathbf{b}^{\sharp},\mathbf{b}^{\flat}) : \mathbf{b}^{\flat}\in[0,\varepsilon_{\flat}]^{nLT_{\max}},\ \ \boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp} = \mathbf{u} - \mathring{\mathbf{h}}(s^{\star}) - \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\ \text{ for some } \mathbf{u}\in B\Bigr\}.\]</span> fall 적립은 i.i.d. <span class="math inline">\(\mathrm{Unif}(0,b)\)</span> (결합밀도 <span class="math inline">\(b^{-nL}\)</span> on <span class="math inline">\([0,b]^{nL}\)</span>), non-fall 적립도 i.i.d. <span class="math inline">\(\mathrm{Unif}(0,b)\)</span> (결합밀도 <span class="math inline">\(b^{-nLT_{\max}}\)</span>), 이산적인 fall 스케줄·branch 픽과 독립 — 그 이산 부분이 discrete floor <span class="math inline">\(\mu_{\min}^{nL}q_{\min}^{D}\)</span>를 나른다. <span class="math inline">\(\mathbf{b}^{\flat}\)</span> 고정 시 favourable fall 이미지는 아래 <span class="math inline">\((\dagger)\)</span> 항등식에 의해 <span class="math inline">\(\mathbf{u}\in\mathsf{U}\)</span>에서 Lebesgue 밀도 <span class="math display">\[\rho_{\mathbf{b}^{\flat}}(\mathbf{u}) \;:=\; \frac{|\det[\mathbf{Q}\ \mathbf{N}]|}{b^{nL}}\sum_{\amalg}\Bigl|\Bigl\{\mathbf{w} : \mathbf{Q}\bigl(\mathbf{u}-\mathring{\mathbf{h}}(s^{\star})-\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\bigr)+\mathbf{N}\mathbf{w} \,\in\, \mathcal{R}_{\delta,\amalg}\Bigr\}\Bigr|_{\mathrm{Leb}}\]</span> 를 갖는다 — 표적 <span class="math inline">\(\mathbf{u}\)</span> 위 <strong>robust-core slice 측도</strong>에 배율 <span class="math inline">\(|\det[\mathbf{Q}\ \mathbf{N}]|/b^{nL}\)</span>. (branch 제약이 없으면 full-slice 밀도 <span class="math inline">\(b^{-nL}|\det[\mathbf{Q}\ \mathbf{N}]|\,|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\}|_{\mathrm{Leb}}\)</span>; walker가 <span class="math inline">\(\amalg\)</span>를 <strong>실제로 따르라</strong>는 요구가 각 slice에서 <span class="math inline">\(\delta\)</span>-튜브를 도려내 full slice를 robust core <span class="math inline">\(\mathcal{R}_{\delta,\amalg}\)</span>로 바꾼다 — slice-floor 단계가 <span class="math inline">\(m_0\)</span>를, robust-core 단계가 <span class="math inline">\(m_*\)</span>를 준다.) 좌변 전개, 한 줄에 한 연산: <span class="math display">\[\begin{aligned} (P^{\star})^{nL}(s^{\star}, B\times\{v_n\}) &amp;\;\geq\; \mu_{\min}^{nL}\,q_{\min}^{D}\int_{[0,\varepsilon_{\flat}]^{nLT_{\max}}}\!\!\! b^{-nLT_{\max}}\int_{B}\rho_{\mathbf{b}^{\flat}}(\mathbf{u})\,d\mathbf{u}\,d\mathbf{b}^{\flat} &amp;&amp; (\because G_B,\ (\dagger)) \\ &amp;\;\geq\; \mu_{\min}^{nL}\,q_{\min}^{D}\int_{[0,\varepsilon_{\flat}]^{nLT_{\max}}}\!\!\! b^{-nLT_{\max}}\int_{B} c_*\,d\mathbf{u}\,d\mathbf{b}^{\flat} &amp;&amp; (\because \rho_{\mathbf{b}^{\flat}}\geq c_*\ \text{(아래)}) \\ &amp;\;=\; \mu_{\min}^{nL}\,q_{\min}^{D}\,c_*\,|B|_{\mathrm{Leb}}\int_{[0,\varepsilon_{\flat}]^{nLT_{\max}}}\!\!\! b^{-nLT_{\max}}\,d\mathbf{b}^{\flat} &amp;&amp; (\because c_*\ \text{factor out}) \\ &amp;\;=\; \mu_{\min}^{nL}\,q_{\min}^{D}\,(\varepsilon_{\flat}/b)^{nLT_{\max}}\,c_*\,|B|_{\mathrm{Leb}} &amp;&amp; (\because \mathbf{b}^{\flat}\ \text{적분}) \\ &amp;\;=\; \eta\,|B|_{\mathrm{Leb}}/|\mathsf{U}|_{\mathrm{Leb}} \;&gt;\;0 &amp;&amp; (\because \eta\ \text{정의}). \end{aligned}\]</span> 따라서 두 바닥만 손에 넣으면 끝: <strong>(i) discrete floor</strong> <span class="math inline">\(\mu_{\min}^{nL}\,q_{\min}^{D}\,(\varepsilon_{\flat}/b)^{nLT_{\max}}\)</span>, <strong>(ii) density floor</strong> <span class="math inline">\(\rho_{\mathbf{b}^{\flat}}\geq c_*\)</span>. (i)을 즉시 닫고 (ii)로 간다.</p>
</section>
<section id="i-discrete-floor-mu_minnlq_mindvarepsilon_flatbnlt_max" class="level2">
<h2 class="anchored" data-anchor-id="i-discrete-floor-mu_minnlq_mindvarepsilon_flatbnlt_max">(i) Discrete floor — <span class="math inline">\(\mu_{\min}^{nL}\,q_{\min}^{D}\,(\varepsilon_{\flat}/b)^{nLT_{\max}}\)</span></h2>
<ul>
<li><strong>cyclic fall 스케줄</strong> <span class="math inline">\(\mathcal{A}^{\sharp} := \bigcap_{r=1}^{nL}\{X_{t_r}=v^{\sharp}_r\}\)</span> (표적 <span class="math inline">\(v_1,\dots,v_n\)</span> 순환, terminal <span class="math inline">\(v^{\sharp}_{nL}=v_n\)</span>): i.i.d. <span class="math inline">\(\boldsymbol{\mu}_0\)</span>-draw(snowfall A)라 <span class="math inline">\(\mathbb{P}(\mathcal{A}^{\sharp}\mid s^{\star}) = (\prod_{i=1}^{n}\boldsymbol{\mu}_0(v_i))^{L} \geq \mu_{\min}^{nL}\)</span>, <span class="math inline">\(s^{\star}\)</span> 무관. <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\((\tfrac13)^{105}\)</span>.</li>
<li><strong>small-deposit 사건</strong> <span class="math inline">\(\mathcal{A}^{\flat} := \{\text{모든 non-fall 적립} \leq \varepsilon_{\flat}\}\)</span>: <span class="math inline">\(\leq nLT_{\max}\)</span>개 non-fall 스텝 각각에서 적립이 <span class="math inline">\(\mathcal{F}_{t-1}\)</span>-가측 분류와 독립인 <span class="math inline">\(\mathrm{Unif}(0,b)\)</span>라, tower property로 스텝마다 인자 <span class="math inline">\(\varepsilon_{\flat}/b\)</span> — <span class="math inline">\(\mathbb{P}(\mathcal{A}^{\flat}\mid\mathcal{A}^{\sharp},s^{\star}) \geq (\varepsilon_{\flat}/b)^{nLT_{\max}}\)</span>. <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\(\varepsilon_{\flat}^{630}\)</span>.</li>
<li><strong>branch 픽</strong>: favourable branch <span class="math inline">\(\amalg\)</span>의 실현은, 강하 이웃이 둘 이상인 각 flow 스텝에서 walker의 degree-weighted 픽도 고정한다. 각 픽은 확률 <span class="math inline">\(\geq q_{\min} := 1/\deg_{\max}\)</span> (<span class="math inline">\(\deg_{\max} := \max_i \deg(v_i)\)</span>)인 이산 atom이고 윈도우에 <span class="math inline">\(D\)</span>개 — 유한·graph-bounded, 정확한 값은 무관하고 <span class="math inline">\(q_{\min}^{D}&gt;0\)</span>이 <span class="math inline">\(s^{\star}\)</span>-무관 상수라는 것만 쓴다. <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\(\deg_{\max}=2\)</span>라 <span class="math inline">\(q_{\min}=\tfrac12\)</span>. (라운드별 threshold <span class="math inline">\(\Theta^{(r)}\sim\mathrm{Unif}\{n,\ldots,2n\}\)</span>은 강하 경로가 <span class="math inline">\(\leq n-1 &lt; \Theta^{(r)}\)</span> flow로 끝나 <strong>non-binding</strong> — 인자 없음. <span class="math inline">\(T_{\max}=2n\)</span>은 그 a.s. 상한.)</li>
</ul>
<p>세 독립 이산 바닥의 곱이 discrete floor다. fall의 <strong>크기</strong>는 여기 안 들어가고 아래 density floor에서 non-fall 적립과 <strong>결합으로</strong> 적분된다 (조건부 fall 법칙 경유 X).</p>
</section>
<section id="ii로-가는-신무기-치환적분-항등식-dagger-hausdorff-폐지" class="level2">
<h2 class="anchored" data-anchor-id="ii로-가는-신무기-치환적분-항등식-dagger-hausdorff-폐지">(ii)로 가는 신무기 — 치환적분 항등식 <span class="math inline">\((\dagger)\)</span> (Hausdorff 폐지)</h2>
<blockquote class="blockquote">
<p><strong>무엇이 바뀌었나.</strong> 옛 판본은 “fibre의 103차원 Hausdorff 측도 <span class="math inline">\(\mathcal{H}^{103}\)</span> + coarea 공식(Federer)”으로 밀도를 만들었다. 정본은 이를 <strong>폐지</strong>하고, 학부 수준 <strong>치환적분 + Tonelli</strong>만으로 같은 밀도를 만든다. 외부 의존(기하측도론)이 사라지고 모든 측도가 Lebesgue다.</p>
</blockquote>
<p><strong>fall map의 선형대수 (Setup).</strong> <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}:\mathbb{R}^{nL}\to\mathbb{R}^{d}\)</span> (<span class="math inline">\(d:=n-1\)</span>)는 rank <span class="math inline">\(d\)</span> — per-block 차분(rank <span class="math inline">\(d\)</span>)의 <span class="math inline">\(L\)</span>겹 합이므로. 따라서:</p>
<ul>
<li><strong>오른쪽 역원</strong> <span class="math inline">\(\mathbf{Q}:\mathbb{R}^d\to\mathbb{R}^{nL}\)</span>, <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\mathbf{Q} = \mathbf{I}_d\)</span>, <span class="math inline">\(C_Q := \|\mathbf{Q}\|_{\infty\to\infty}&lt;\infty\)</span>;</li>
<li><strong>커널</strong> <span class="math inline">\(K := \ker\boldsymbol{\Lambda}^{\sharp}\)</span>, 차원 <span class="math inline">\(nL-d\)</span>. 그 <strong>정규직교기저를 열로 갖는 행렬</strong> <span class="math inline">\(\mathbf{N}\in\mathbb{R}^{nL\times(nL-d)}\)</span>을 한 번 고정한다.</li>
<li>transpose range: <span class="math inline">\(\operatorname{Range}((\boldsymbol{\Lambda}^{\sharp})^{\top}) = \{\boldsymbol{\xi}\in\mathbb{R}^{nL} : \xi_{k,\ell} = a_k\ (\ell\text{-무관}),\ \sum_k a_k = 0\}\)</span> — <span class="math inline">\(\boldsymbol{\xi}=(\boldsymbol{\Lambda}^{\sharp})^{\top}\theta\)</span>가 <span class="math inline">\(\xi_{1,\ell}=-\sum_q\theta_q\)</span>, <span class="math inline">\(\xi_{k,\ell}=\theta_{k-1}\)</span> (<span class="math inline">\(k\geq2\)</span>)라 노드 그룹별 상수 + 그룹합 0.</li>
</ul>
<p><strong><span class="math inline">\(K_3\)</span> 수치</strong>: <span class="math inline">\(d=2\)</span>, <span class="math inline">\(nL=105\)</span>, <span class="math inline">\(K\)</span>는 <span class="math inline">\(103\)</span>차원, <span class="math inline">\(\mathbf{N}\in\mathbb{R}^{105\times103}\)</span>, <span class="math inline">\(\mathbf{Q}\in\mathbb{R}^{105\times2}\)</span>.</p>
<p><strong>좌표 교체.</strong> 선형사상 <span class="math inline">\((\boldsymbol{\zeta},\mathbf{w})\mapsto \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span>는 <span class="math inline">\(\mathbb{R}^{d}\times\mathbb{R}^{nL-d}\)</span>에서 <span class="math inline">\(\mathbb{R}^{nL}\)</span>로의 <strong>전단사</strong>다: <span class="math inline">\(\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}=\mathbf{0}\)</span>이면 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>를 적용해 <span class="math inline">\(\boldsymbol{\zeta}=\mathbf{0}\)</span> (<span class="math inline">\(\because\boldsymbol{\Lambda}^{\sharp}\mathbf{Q}=\mathbf{I}_d\)</span>, <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\mathbf{N}=\mathbf{0}\)</span>), 이어 <span class="math inline">\(\mathbf{N}\)</span> 열 독립으로 <span class="math inline">\(\mathbf{w}=\mathbf{0}\)</span>. 이 좌표에서 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}(\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}) = \boldsymbol{\zeta}\)</span>:</p>
<ul>
<li><span class="math inline">\(\boldsymbol{\zeta}\)</span> = <strong>fall shift</strong> (어디로 미는가),</li>
<li><span class="math inline">\(\mathbf{w}\)</span> = 그 shift를 <strong>실현하는 적립들의 매개변수</strong> (“같은 곳으로 미는 서로 다른 적립 조합”의 좌표).</li>
</ul>
<p><strong><span class="math inline">\(K_3\)</span> 그림</strong>: 적립 105개 좌표를 (목적지 2 + 자유도 103)으로 갈아끼운 것. 예컨대 표적 <span class="math inline">\(\boldsymbol{\zeta}=(-2,2)\)</span>를 만드는 적립은 무수히 많고 — 매 cycle 똑같이 조금씩 밀거나, 앞 cycle에서 몰아 밀거나 — 그 “방법”이 <span class="math inline">\(\mathbf{w}\in\mathbb{R}^{103}\)</span> 하나로 라벨링된다.</p>
<p><strong>항등식 <span class="math inline">\((\dagger)\)</span>.</strong> <span class="math inline">\(X\sim\mathrm{Unif}([0,b]^{nL})\)</span>, 가측 <span class="math inline">\(S\subseteq\mathbb{R}^{nL}\)</span>, <span class="math inline">\(A\subseteq\mathbb{R}^d\)</span>에 대해, 치환 <span class="math inline">\(\mathbf{b}^{\sharp} = \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span> 후 Tonelli: <span class="math display">\[\mathbb{P}\bigl(X\in S,\ \boldsymbol{\Lambda}^{\sharp}X\in A\bigr) \;=\; b^{-nL}\,\bigl|\det[\mathbf{Q}\ \mathbf{N}]\bigr|\int_{A}\bigl|\bigl\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\cap S\bigr\}\bigr|_{\mathrm{Leb}}\,d\boldsymbol{\zeta} \qquad \cdots\ (\dagger)\]</span> 즉 <span class="math inline">\(\{X\in S\}\)</span>로 제한한 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}X\)</span>의 법칙은 <span class="math inline">\(\boldsymbol{\zeta}\)</span>에서 Lebesgue 밀도 <span class="math inline">\(b^{-nL}|\det[\mathbf{Q}\ \mathbf{N}]|\,|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\cap S\}|_{\mathrm{Leb}}\)</span>를 갖는다. <strong>아래의 모든 밀도 바닥은 <span class="math inline">\((\dagger)\)</span>에서 적절한 적립 집합 <span class="math inline">\(S\)</span>의 <span class="math inline">\(\mathbf{w}\)</span>-slice 측도를 바닥내는 것으로 얻는다.</strong> (옛 “fibre의 <span class="math inline">\(\mathcal{H}^{103}\)</span> 측도” 역할을 이제 “<span class="math inline">\(\mathbf{w}\)</span>-slice의 <span class="math inline">\(103\)</span>차원 Lebesgue 측도”가 한다 — 자가 큐브 안 조각이 아니라 <span class="math inline">\(\mathbf{w}\)</span>-공간에 깔린다는 점이 다르다.)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>🔽 <span class="math inline">\(K_3\)</span>에서 <span class="math inline">\(|\det[\mathbf{Q}\ \mathbf{N}]|\)</span>는 얼마? — <span class="math inline">\(\mathbf{Q}\)</span> 선택에 의존하지만, 곧 상쇄된다
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\([\mathbf{Q}\ \mathbf{N}]\)</span>은 <span class="math inline">\(105\times105\)</span> 정방행렬. <span class="math inline">\(\mathbf{Q}\)</span>를 <strong>유사역원</strong> <span class="math inline">\(\mathbf{Q} = (\boldsymbol{\Lambda}^{\sharp})^{\top}(\boldsymbol{\Lambda}^{\sharp}(\boldsymbol{\Lambda}^{\sharp})^{\top})^{-1}\)</span>로 고르면 <span class="math inline">\(\mathbf{Q}\)</span>의 열이 row space에 살아 <span class="math inline">\(\mathbf{Q}^{\top}\mathbf{N} = \mathbf{0}\)</span>, 그러면 <span class="math display">\[\det[\mathbf{Q}\ \mathbf{N}]^2 = \det\!\begin{pmatrix}\mathbf{Q}^{\top}\mathbf{Q} &amp; \mathbf{0}\\ \mathbf{0} &amp; \mathbf{I}\end{pmatrix} = \det\bigl((\boldsymbol{\Lambda}^{\sharp}(\boldsymbol{\Lambda}^{\sharp})^{\top})^{-1}\bigr) = \frac{1}{L^{n-1}n}\]</span> (<span class="math inline">\(\because\)</span> Gram <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}(\boldsymbol{\Lambda}^{\sharp})^{\top} = L(\mathbf{I}_d+\mathbf{1}\mathbf{1}^{\top})\)</span>, <span class="math inline">\(\det = L^d n\)</span>). <span class="math inline">\(K_3\)</span>: <span class="math inline">\(|\det[\mathbf{Q}\ \mathbf{N}]| = 1/(35\sqrt3) \approx 1/60.62\)</span> — 옛 야코비안 <span class="math inline">\(J(\boldsymbol{\Lambda}^{\sharp})=35\sqrt3\)</span>의 역수다. 다른 <span class="math inline">\(\mathbf{Q}\)</span>를 고르면 값이 달라지지만 <strong>걱정 없다</strong>: 아래에서 <span class="math inline">\(m_0\)</span>에는 <span class="math inline">\(|\det|^{-1}\)</span>로, <span class="math inline">\(c_*\)</span>에는 <span class="math inline">\(|\det|\)</span>로 들어가 <strong>정확히 상쇄</strong>되고, 최종 <span class="math inline">\(c_* = c_{K_{\mathsf{U}}}/2\)</span>는 <span class="math inline">\(\mathbf{Q}\)</span> 선택과 무관하다.</p>
</div>
</div>
</div>
</section>
<section id="ii-1.-slice-floor-컴팩트-표적에서-m_0" class="level2">
<h2 class="anchored" data-anchor-id="ii-1.-slice-floor-컴팩트-표적에서-m_0">(ii)-1. Slice floor — 컴팩트 표적에서 <span class="math inline">\(m_0\)</span></h2>
<p>목표: 모든 표적 <span class="math inline">\(\boldsymbol{\zeta}\in K_{\mathsf{U}}\)</span>에서 full-slice 측도 <span class="math inline">\(\bigl|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\}\bigr|_{\mathrm{Leb}}\geq m_0&gt;0\)</span>.</p>
<p><strong>non-fall 잔차.</strong> branch <span class="math inline">\(\amalg\)</span>의 맵 <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\)</span>는 non-fall 누적 기여 <span class="math inline">\(\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat} = \sum_{t\,\text{non-fall}} (\mathring{\mathbf{h}}(t) - \mathring{\mathbf{h}}(t-1))\)</span>, 연산자 노름이 graph-bounded라 <span class="math inline">\(\mathcal{A}^{\flat}\)</span> 위에서 <span class="math display">\[\|\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\|_\infty \leq \|\boldsymbol{\Lambda}^{\flat}_{\amalg}\|_{\infty\to\infty}\,\|\mathbf{b}^{\flat}\|_\infty \leq nLT_{\max}\,\varepsilon_{\flat}\leq Lb/8 \qquad (\because \varepsilon_{\flat}\leq b/(8nT_{\max})).\]</span> <strong><span class="math inline">\(K_3\)</span></strong>: <span class="math inline">\(630\times\tfrac1{144} = 4.375 = \tfrac{Lb}8\)</span> (1부 §3의 잔차표 그대로). 따라서 모든 표적 <span class="math inline">\(\boldsymbol{\zeta} = \mathbf{u}-\mathring{\mathbf{h}}(s^{\star})-\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\)</span> (<span class="math inline">\(\mathbf{u}\in \mathsf{U}\)</span>, <span class="math inline">\(s^{\star}\in C_0\)</span>)는 컴팩트 <span class="math inline">\(K_{\mathsf{U}} := \{\mathbf{u} - \mathring{\mathbf{h}}(s^{\star}) - \mathbf{r} : \mathbf{u}\in \mathsf{U},\ s^{\star}\in C_0,\ \|\mathbf{r}\|_\infty\leq Lb/8\}\)</span>에 들고, 1부 §3의 삼각부등식 계산대로 <span class="math inline">\(K_{\mathsf{U}} \Subset \operatorname{int}(L\cdot\mathsf{O})\)</span> (margin <span class="math inline">\(\geq b/8 = 0.125\)</span>).</p>
<p><strong>합성곱 바닥 <span class="math inline">\(c_{K_{\mathsf{U}}}\)</span>.</strong> favourable fall 이미지는 per-block 밀도 <span class="math inline">\(f := f_{\mathring{\mathbf{b}}^{\sharp}}\)</span> (<span class="math inline">\(\geq c_f := b^{1-n}/2\)</span> on <span class="math inline">\(\mathsf{O}\)</span>, 1부 §3 ①)의 <span class="math inline">\(L\)</span>겹 합성곱 <span class="math inline">\(f^{\ast L}\)</span>. <span class="math inline">\(\boldsymbol{\zeta}\in K_{\mathsf{U}}\subset\operatorname{int}(L\cdot\mathsf{O})\)</span>를 고정하면 <span class="math inline">\(\boldsymbol{\zeta} = \boldsymbol{\zeta}_1+\cdots+\boldsymbol{\zeta}_L\)</span> (각 <span class="math inline">\(\boldsymbol{\zeta}_\ell\in\mathsf{O}\)</span>)로 쪼개지고, <span class="math inline">\(\mathsf{O}\)</span> 열림성이 <span class="math inline">\(r&gt;0\)</span>을 줘 <span class="math inline">\(B(\boldsymbol{\zeta}_\ell, 2r)\subset\mathsf{O}\)</span>. <span class="math inline">\(s := r/(L-1)\)</span>로 두면 임의의 <span class="math inline">\(\boldsymbol{\zeta}'\in B(\boldsymbol{\zeta}, r)\)</span>와 <span class="math inline">\(\mathbf{x}_\ell\in B(\boldsymbol{\zeta}_\ell, s)\)</span> (<span class="math inline">\(\ell&lt;L\)</span>)에 대해 마지막 인자 <span class="math inline">\(\mathbf{x}_L := \boldsymbol{\zeta}'-\sum_{\ell&lt;L}\mathbf{x}_\ell\)</span>가 <span class="math display">\[\|\mathbf{x}_L - \boldsymbol{\zeta}_L\| = \Bigl\|(\boldsymbol{\zeta}'-\boldsymbol{\zeta}) + \textstyle\sum_{\ell&lt;L}(\boldsymbol{\zeta}_\ell-\mathbf{x}_\ell)\Bigr\| &lt; r + (L-1)s = 2r\]</span> 이라 <span class="math inline">\(\mathbf{x}_L\in B(\boldsymbol{\zeta}_L,2r)\subset\mathsf{O}\)</span> — <span class="math inline">\(L\)</span>개 인자 전부 <span class="math inline">\(f\geq c_f\)</span>인 곳에 있어 <span class="math display">\[f^{\ast L}(\boldsymbol{\zeta}') \;\geq\; c_f^L\,(\omega_d\,s^d)^{L-1} \;&gt;\; 0 \qquad (\omega_d s^d = \mathrm{Leb}\,B(\cdot,s)).\]</span> 컴팩트 <span class="math inline">\(K_{\mathsf{U}}\)</span>를 유한개 공으로 덮고 최솟값을 취하면 <span class="math inline">\(c_{K_{\mathsf{U}}} := \inf_{K_{\mathsf{U}}} f^{\ast L} &gt; 0\)</span>. (1부 콜아웃의 “loose하지만 양수면 충분 / 실제 bulk 밀도는 다항적” 논의 그대로.)</p>
<p><strong>slice로 환전.</strong> <span class="math inline">\(f^{\ast L}\)</span>는 <span class="math inline">\(\mathrm{Unif}([0,b]^{nL})\)</span>의 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\)</span>-pushforward 밀도이므로, <span class="math inline">\((\dagger)\)</span>의 <span class="math inline">\(S=\mathbb{R}^{nL}\)</span> 경우가 <span class="math display">\[b^{-nL}|\det[\mathbf{Q}\ \mathbf{N}]|\,\bigl|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\}\bigr|_{\mathrm{Leb}} = f^{\ast L}(\boldsymbol{\zeta}) \geq c_{K_{\mathsf{U}}},\]</span> <span class="math display">\[\therefore\quad \bigl|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\}\bigr|_{\mathrm{Leb}} \;\geq\; m_0 := \frac{b^{nL}\,c_{K_{\mathsf{U}}}}{|\det[\mathbf{Q}\ \mathbf{N}]|} \;&gt;\; 0 \qquad (\boldsymbol{\zeta}\in K_{\mathsf{U}}).\]</span> <strong><span class="math inline">\(K_3\)</span></strong>(유사역원 <span class="math inline">\(\mathbf{Q}\)</span>): <span class="math inline">\(m_0 = c_{K_{\mathsf{U}}}\cdot35\sqrt3\)</span> (<span class="math inline">\(b=1\)</span>).</p>
</section>
<section id="ii-2.-robust-core-mathcalr_deltasstar-비교퇴화튜브면" class="level2">
<h2 class="anchored" data-anchor-id="ii-2.-robust-core-mathcalr_deltasstar-비교퇴화튜브면">(ii)-2. Robust core <span class="math inline">\(\mathcal{R}_\delta(s^{\star})\)</span> — 비교·퇴화·튜브·면</h2>
<p>이제 robust core <span class="math inline">\(\mathcal{R}_\delta\subseteq[0,b]^{nL}\)</span>를 깎는다 — <span class="math inline">\(K_{\mathsf{U}}\)</span>의 모든 표적에서 <span class="math inline">\(\mathbf{w}\)</span>-slice 측도 <span class="math inline">\(\geq m_* := m_0/2\)</span>를 유지하면서, 그 slice가 <strong><span class="math inline">\(\mathbf{w}\)</span>는 그대로 둔 채</strong> 임의의 non-fall 잔차만큼 이동한 표적의 branch-일관 적립 집합 안으로 옮겨지도록.</p>
<p><strong>비교와 퇴화 (chamber가 일하는 곳).</strong> branch 데이터 <span class="math inline">\(\amalg\)</span>를 고정하면, 윈도우의 flow 스텝들은 유한 집합 <span class="math inline">\(\mathcal{A}\)</span>의 <strong>높이 비교</strong>로 결정된다: 각 <span class="math inline">\(a\in\mathcal{A}\)</span>는 어떤 스텝 <span class="math inline">\(t\)</span>에서 시험되는 높이차 <span class="math inline">\(\Delta_{ij}(\mathring{\mathbf{h}}(t))\)</span> (<span class="math inline">\(a\)</span>에 따른 노드쌍 <span class="math inline">\(i\neq j\)</span>), 적립들의 affine 함수다. fall-적립 계수를 <span class="math inline">\(\alpha_a\in\mathbb{R}^{nL}\)</span>, 적립 0에서의 값을 <span class="math inline">\(\gamma_a(s^{\star})\)</span>라 쓰면 <span class="math inline">\(\mathbf{b}^{\flat}=0\)</span>에서 비교는 <span class="math inline">\(\alpha_a\cdot\mathbf{b}^{\sharp}+\gamma_a(s^{\star})\)</span> (<span class="math inline">\(\mathbf{b}^{\flat}\)</span> 의존은 Lipschitz, 아래서 흡수). <span class="math inline">\(P_K\)</span>를 커널 <span class="math inline">\(K\)</span>로의 직교사영이라 하자 — <strong><span class="math inline">\(\mathbf{N}\)</span> 덕에 <span class="math inline">\(P_K = \mathbf{N}\mathbf{N}^{\top}\)</span></strong>. 만약 <span class="math inline">\(P_K\alpha_a = 0\)</span>이면 <span class="math inline">\(\alpha_a\in\operatorname{Range}((\boldsymbol{\Lambda}^{\sharp})^{\top})\)</span>, 즉 그룹상수+그룹합0; <span class="math inline">\(h_i-h_j\)</span> 비교의 fall 계수는 일어난 <span class="math inline">\(v_i\)</span>-fall에 <span class="math inline">\(+1\)</span>, <span class="math inline">\(v_j\)</span>-fall에 <span class="math inline">\(-1\)</span>, 나머지 <span class="math inline">\(0\)</span>이므로 그룹상수성은 <span class="math inline">\(i,j\)</span> 각각 “그 <span class="math inline">\(L\)</span>개 fall이 전부 일어났거나 전부 안 일어났거나”를 강제하고, 합0 조건이 남기는 건 둘뿐:</p>
<ul>
<li><span class="math inline">\(\alpha_a = 0\)</span> — <strong>결정론적 비교</strong> (branch가 이미 값을 고정), 또는</li>
<li><strong>final-equality 타입</strong> <span class="math inline">\(\alpha_a\cdot\mathbf{b}^{\sharp} = \sum_\ell b^{\sharp}_{i,\ell}-\sum_\ell b^{\sharp}_{j,\ell}\)</span>. 이 경우 fall shift가 <span class="math inline">\(\boldsymbol{\Lambda}^{\sharp}\mathbf{b}^{\sharp} = \boldsymbol{\zeta} = \mathbf{u}-\mathring{\mathbf{h}}(s^{\star})\)</span>인 임의의 적립에서 <span class="math display">\[\gamma_a(s^{\star}) + \alpha_a\cdot\mathbf{b}^{\sharp} \;=\; \Delta_{ij}\bigl(\mathring{\mathbf{h}}(s^{\star})+\boldsymbol{\zeta}\bigr) \;=\; \Delta_{ij}(\mathbf{u}), \qquad |\gamma_a(s^{\star}) + \alpha_a\cdot\mathbf{b}^{\sharp}| \;\geq\; \kappa_{\mathsf{U}}\]</span> — chamber 분리 <span class="math inline">\((\ast)\)</span> (1부 §3 ④)가 그대로 발동한다. <strong>퇴화 비교는 <span class="math inline">\(\delta\)</span>-튜브로 못 잡지만(적립을 움직여도 값이 안 변함), chamber가 등호에서 <span class="math inline">\(\kappa_{\mathsf{U}}\)</span>만큼 떼어놓아 자동으로 안전하다.</strong> <span class="math inline">\(K_3\)</span>: <span class="math inline">\(\kappa_{\mathsf{U}} = \tfrac1{768}\)</span>.</li>
</ul>
<p><strong>튜브·면 바운드 (<span class="math inline">\(\mathbf{w}\)</span>-공간 Fubini).</strong> 비퇴화 비교 <span class="math inline">\(\mathcal{A}_{\mathrm{nd}} := \{a\in\mathcal{A} : P_K\alpha_a\neq 0\}\)</span>. graph-data 상수 <span class="math inline">\(C_{\mathrm{tie}}, C_{\mathrm{bdry}}&lt;\infty\)</span>가 있어, 모든 shift <span class="math inline">\(\boldsymbol{\zeta}\)</span>·상태 <span class="math inline">\(s^{\star}\)</span>·<span class="math inline">\(\delta&gt;0\)</span>에 대해 (중괄호 안 <span class="math inline">\(\mathbf{b}^{\sharp} := \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span>): <span class="math display">\[\Bigl|\Bigl\{\mathbf{w} : \mathbf{b}^{\sharp}\in[0,b]^{nL},\ \min_{a\in\mathcal{A}_{\mathrm{nd}}}|\alpha_a\cdot\mathbf{b}^{\sharp}+\gamma_a(s^{\star})|\leq\delta\Bigr\}\Bigr|_{\mathrm{Leb}}\leq C_{\mathrm{tie}}\,\delta,\]</span> <span class="math display">\[\bigl|\bigl\{\mathbf{w} : \mathbf{b}^{\sharp}\in[0,b]^{nL},\ \textstyle\min_j b^{\sharp}_j\leq\delta\ \text{또는}\ \min_j(b-b^{\sharp}_j)\leq\delta\bigr\}\bigr|_{\mathrm{Leb}}\leq C_{\mathrm{bdry}}\,\delta.\]</span> 이유: <span class="math inline">\(\mathcal{A}_{\mathrm{nd}}\)</span> 유한이라 <span class="math inline">\(\lambda_\ast := \min_{a\in\mathcal{A}_{\mathrm{nd}}}\|P_K\alpha_a\|&gt;0\)</span>. <span class="math inline">\(\mathbf{w}\)</span>의 함수로 각 비교 <span class="math inline">\(\alpha_a\cdot(\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w})+\gamma_a(s^{\star})\)</span>는 affine, 기울기 <span class="math inline">\(\mathbf{N}^{\top}\alpha_a\)</span>이고 <span class="math inline">\(\|\mathbf{N}^{\top}\alpha_a\| = \|P_K\alpha_a\|\geq\lambda_\ast\)</span> (<span class="math inline">\(\because P_K=\mathbf{N}\mathbf{N}^{\top}\)</span>, <span class="math inline">\(\mathbf{N}\)</span> 열 정규직교). <span class="math inline">\(\mathbf{w}\)</span>-공간을 <span class="math inline">\(\mathbf{N}^{\top}\alpha_a/\|\mathbf{N}^{\top}\alpha_a\|\)</span> 방향으로 썰면 slice 좌표에 대해 기울기 <span class="math inline">\(\geq\lambda_\ast\)</span>의 affine — <span class="math inline">\(\{|\cdot|\leq\delta\}\)</span>는 길이 <span class="math inline">\(\leq 2\delta/\lambda_\ast\)</span>의 구간. 비지 않은 slice <span class="math inline">\(\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\}\)</span>는 지름 <span class="math inline">\(\leq b\sqrt{nL}\)</span> (<span class="math inline">\(\because\)</span> 두 점의 차 <span class="math inline">\(\mathbf{w}-\mathbf{w}'\)</span>가 <span class="math inline">\(\mathbf{N}(\mathbf{w}-\mathbf{w}')\in[-b,b]^{nL}\)</span>이고 <span class="math inline">\(\|\mathbf{w}-\mathbf{w}'\| = \|\mathbf{N}(\mathbf{w}-\mathbf{w}')\|\)</span> — <span class="math inline">\(K_3\)</span>: <span class="math inline">\(\sqrt{105}\approx10.25\)</span>). 유계 단면을 적분하고 유한 family를 합하면 첫째 바운드. 큐브 면 <span class="math inline">\(\{b^{\sharp}_j = 0\}\)</span>·<span class="math inline">\(\{b^{\sharp}_j = b\}\)</span>는 affine 함수 <span class="math inline">\(e_j\cdot(\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w})\)</span>, 기울기 <span class="math inline">\(\mathbf{N}^{\top}e_j\neq 0\)</span> (아니면 <span class="math inline">\(e_j\in\operatorname{Range}((\boldsymbol{\Lambda}^{\sharp})^{\top})\)</span> — 그룹상수·합0 특성에 모순)이라 같은 썰기를 <span class="math inline">\(2nL\)</span>개 면에 합하면 둘째 바운드. <span class="math inline">\(C := C_{\mathrm{tie}}+C_{\mathrm{bdry}}\)</span>로 쓴다.</p>
<p><strong>robust core.</strong> 오른쪽-역원 shift가 적립을 큐브 면 너머로 밀거나 tie 비교를 뒤집을 수 있으니, 그걸 흡수할 마진을 먼저 깎는다. 큐브-경계·비퇴화-tie 튜브(총 slice 측도 <span class="math inline">\(\leq C\delta\)</span>)를 도려내고, <span class="math inline">\(\delta&gt;0\)</span>를 <span class="math inline">\(C\delta\leq m_0/2\)</span>이며 <span class="math inline">\(\delta\leq\kappa_{\mathsf{U}}\)</span>이게 고정하면, robust core <span class="math display">\[\mathcal{R}_\delta(s^{\star}) := \{\delta\leq b^{\sharp}_j\leq b-\delta\ \forall j\}\;\cap\!\!\bigcap_{a:\,P_K\alpha_a\neq 0}\!\!\{|\alpha_a\cdot \mathbf{b}^{\sharp}+\gamma_a(s^{\star})|\geq\delta\} \;\subseteq\; [0,b]^{nL}\]</span> 는 slice 바닥을 유지한다: <span class="math inline">\(\bigl|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in\mathcal{R}_\delta(s^{\star})\}\bigr|_{\mathrm{Leb}}\geq m_* := m_0/2\)</span>, 모든 <span class="math inline">\(\boldsymbol{\zeta}\in K_{\mathsf{U}}\)</span>·<span class="math inline">\(s^{\star}\in C_0\)</span>에서.</p>
<blockquote class="blockquote">
<p><strong>옛 판본과의 차이 하나 더.</strong> 옛 <span class="math inline">\(\mathcal{R}_\delta(\boldsymbol{\zeta},s^{\star})\)</span>는 fibre <span class="math inline">\((\boldsymbol{\Lambda}^{\sharp})^{-1}(\boldsymbol{\zeta})\)</span>와의 교집합으로 정의돼 <strong>표적마다 다른 집합</strong>이었다. 새 <span class="math inline">\(\mathcal{R}_\delta(s^{\star})\)</span>는 fibre 제약이 빠진 <strong>큐브의 한 부분집합</strong> — 표적 의존이 사라지고, 표적은 오직 “<span class="math inline">\(\mathbf{w}\)</span>-slice를 어디서 뜨느냐”(<span class="math inline">\(\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span>)로만 들어온다. 인자도 <span class="math inline">\((\boldsymbol{\zeta},s^{\star})\)</span>에서 <span class="math inline">\((s^{\star})\)</span>로 줄었다.</p>
</blockquote>
<div id="383f03e4" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="260605_연구_HST_$C_0$는smallset이다—Doeblinminorization$K_3$예제_files/figure-html/cell-10-output-1.png" width="446" height="492" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>위 도식은 105차원 큐브의 2차원 만화 — 파란 점선이 한 표적의 slice(<span class="math inline">\(\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span>들의 자취), 분홍이 큐브-경계 튜브(<span class="math inline">\(b^{\sharp}_j\)</span>가 <span class="math inline">\(0\)</span>·<span class="math inline">\(b\)</span>에서 <span class="math inline">\(\delta\)</span> 이내), 주황이 tie 튜브(비퇴화 비교가 등호에서 <span class="math inline">\(\delta\)</span> 이내), <strong>보라 굵은 토막이 <span class="math inline">\(\mathcal{R}_\delta(s^{\star})\)</span>와 만나는 알짜 slice</strong>(<span class="math inline">\(m_*\)</span> 이상). 도려내기 전 slice 측도가 <span class="math inline">\(m_0\)</span>, 튜브가 최대 <span class="math inline">\(C\delta\leq m_0/2\)</span>를 먹어 절반 <span class="math inline">\(m_*\)</span>가 남는다.</p>
<p><strong>왜 굳이 도려내나 (반례).</strong> 도려내기 전 slice엔 가장자리(<span class="math inline">\(b^{\sharp}_j\approx0\)</span>) 점이 섞여 있다. transport가 적립을 <span class="math inline">\(-\mathbf{Q}\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\)</span>만큼 밀 때 그런 점은 <span class="math inline">\(b^{\sharp}_j&lt;0\)</span>이 돼 <strong>큐브 밖</strong> — 실현 불가능한 적립이 된다. tie 근처 점은 밀리면 비교 부호가 뒤집혀 <strong>branch <span class="math inline">\(\amalg\)</span>가 바뀌고</strong> slice가 다른 branch 조각으로 새어 측도 계산이 무너진다. <span class="math inline">\(\delta\)</span> 마진이 그 둘을 차단한다.</p>
</section>
<section id="ii-3.-transport-mathbfw는-그대로-표적만-이동" class="level2">
<h2 class="anchored" data-anchor-id="ii-3.-transport-mathbfw는-그대로-표적만-이동">(ii)-3. Transport — “<span class="math inline">\(\mathbf{w}\)</span>는 그대로, 표적만 이동”</h2>
<p>유한 윈도우 전체에서 단일 <span class="math inline">\(\ell^\infty\)</span>-Lipschitz 상수 <span class="math inline">\(\Gamma&lt;\infty\)</span> (graph·<span class="math inline">\(L\)</span> 의존)가, <span class="math inline">\(\mathcal{A}^{\flat}\)</span> 위 모든 잔차·오른쪽-역원 shift·비교의 <span class="math inline">\(\mathbf{b}^{\flat}\)</span>-민감도를 <span class="math inline">\(\Gamma\varepsilon_{\flat}\)</span>로 묶는다. standing setup의 단일 smallness 조건을 한 번 고정: <span class="math display">\[\varepsilon_{\flat} \;\leq\; \min\bigl\{\,b/(8nT_{\max}),\ \delta/(4\Gamma),\ \kappa_{\mathsf{U}}/(4\Gamma)\,\bigr\}.\]</span> 임의의 <span class="math inline">\(\mathbf{b}^{\flat}\in[0,\varepsilon_{\flat}]^{nLT_{\max}}\)</span>·<span class="math inline">\(\mathbf{u}\in \mathsf{U}\)</span>·<span class="math inline">\(\boldsymbol{\zeta} := \mathbf{u}-\mathring{\mathbf{h}}(s^{\star})\)</span>에 대해, <span class="math inline">\(\mathcal{R}_\delta(s^{\star}) = \bigsqcup_{\amalg}\mathcal{R}_{\delta,\amalg}\)</span>로 branch별 분할하고 각각을 <span class="math display">\[\mathbf{b}^{\sharp}\;\mapsto\;\widehat{\mathbf{b}}^{\sharp} := \mathbf{b}^{\sharp} - \mathbf{Q} \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}, \qquad \boldsymbol{\Lambda}^{\sharp}\widehat{\mathbf{b}}^{\sharp} = \boldsymbol{\zeta} - \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\]</span> 로 나른다. <strong><span class="math inline">\((\boldsymbol{\zeta},\mathbf{w})\)</span> 좌표에서 이 transport는 <span class="math inline">\(\mathbf{w}\)</span>를 건드리지 않는다</strong>: <span class="math inline">\(\mathbf{b}^{\sharp} = \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span>이면 <span class="math inline">\(\widehat{\mathbf{b}}^{\sharp} = \mathbf{Q}(\boldsymbol{\zeta}-\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat})+\mathbf{N}\mathbf{w}\)</span> — 표적 좌표만 <span class="math inline">\(\boldsymbol{\zeta}\to\boldsymbol{\zeta}-\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\)</span>로 미끄러진다. (옛 판본의 “측도 보존 평행이동” 논거가 “좌표 하나는 아예 불변”으로 더 투명해진 것.)</p>
<p><span class="math inline">\(\mathcal{R}_\delta(s^{\star})\)</span> 위에서:</p>
<ul>
<li>모든 비퇴화 비교가 등호에서 <span class="math inline">\(\geq\delta\)</span> — 각 스텝의 강하 집합이 <strong>모호하지 않고</strong>(tie 없음) 각 적립 벡터는 <span class="math inline">\(\mathcal{R}_{\delta,\amalg}\)</span>에 일관된 <strong>단일 branch <span class="math inline">\(\amalg\)</span></strong>를 따른다. 강하 이웃이 여럿일 때의 degree-weighted 픽은 discrete floor에서 이미 센 <span class="math inline">\(q_{\min}^{D}\)</span>가 나른다 — <strong>robust core가 없애는 건 tie 모호성이지 픽의 multiplicity가 아니다</strong>;</li>
<li>각 라운드의 강하 경로는 <span class="math inline">\(\leq n-1&lt;\Theta^{(r)}\)</span> flow로 소진 (threshold non-binding);</li>
<li>shift는 <span class="math inline">\(\mathbf{b}^{\sharp}\)</span>를 <span class="math inline">\(\leq\Gamma\varepsilon_{\flat}\leq\delta/4\)</span>만큼만 움직여 <span class="math inline">\(\widehat{\mathbf{b}}^{\sharp}\in[0,b]^{nL}\)</span> 유지; 비퇴화 비교는 <span class="math inline">\(\leq\delta/2\)</span> 움직여 <strong>부호 유지</strong>; 퇴화 final-equality 비교는 <span class="math inline">\((\ast)\)</span>로 <span class="math inline">\(\geq\kappa_{\mathsf{U}}/2\)</span> 유지.</li>
</ul>
<p>따라서 <span class="math inline">\(\widehat{\mathbf{b}}^{\sharp}\)</span>는 branch <span class="math inline">\(\amalg\)</span>에 머문다: slice <span class="math inline">\(\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in\mathcal{R}_{\delta,\amalg}\}\)</span>의 모든 <span class="math inline">\(\mathbf{w}\)</span>가 <span class="math inline">\(\mathbf{Q}(\boldsymbol{\zeta}-\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat})+\mathbf{N}\mathbf{w}\in[0,b]^{nL}\)</span>에 branch <span class="math inline">\(\amalg\)</span> 실현까지 만족하므로, <strong>이동된 표적 <span class="math inline">\(\boldsymbol{\zeta} - \boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\)</span>에서의 branch-<span class="math inline">\(\amalg\)</span> 적립 집합의 slice 측도는 <span class="math inline">\(\geq\bigl|\{\mathbf{w} : \mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\in\mathcal{R}_{\delta,\amalg}\}\bigr|_{\mathrm{Leb}}\)</span></strong>, <span class="math inline">\(\mathbf{b}^{\flat}\)</span>에 균일하게.</p>
</section>
<section id="ii-4.-조립-c_와-eta-그리고-detmathbfq-mathbfn의-상쇄" class="level2">
<h2 class="anchored" data-anchor-id="ii-4.-조립-c_와-eta-그리고-detmathbfq-mathbfn의-상쇄">(ii)-4. 조립 — <span class="math inline">\(c_*\)</span>와 <span class="math inline">\(\eta\)</span>, 그리고 <span class="math inline">\(|\det[\mathbf{Q}\ \mathbf{N}]|\)</span>의 상쇄</h2>
<p>branch-일관 적립 집합이 모든 이동된 표적에서 <span class="math inline">\(\mathbf{w}\)</span>-slice 측도 <span class="math inline">\(\geq m_* = m_0/2\)</span>를 유지하므로, <span class="math inline">\((\dagger)\)</span>가 <span class="math display">\[\rho_{\mathbf{b}^{\flat}} \;\geq\; c_* := \frac{m_*\,|\det[\mathbf{Q}\ \mathbf{N}]|}{b^{nL}} \;&gt;\; 0 \quad \text{on } \mathsf{U}, \qquad \text{균일하게 } s^{\star}\in C_0,\ \text{잔차 전부}.\]</span> 이것이 (ii)를 닫고, master 부등식과 합쳐 <span class="math inline">\((P^{\star})^{nL}(s^{\star},\cdot)\geq\eta\,\nu\)</span>가 선다. <span class="math inline">\(\blacksquare\)</span></p>
<p><strong>상쇄 확인 (<span class="math inline">\(K_3\)</span>).</strong> <span class="math inline">\(m_0 = b^{nL}c_{K_{\mathsf{U}}}/|\det[\mathbf{Q}\ \mathbf{N}]|\)</span>를 대입하면 <span class="math display">\[c_* \;=\; \frac{(m_0/2)\,|\det[\mathbf{Q}\ \mathbf{N}]|}{b^{nL}} \;=\; \frac{c_{K_{\mathsf{U}}}}{2}\]</span> — <span class="math inline">\(|\det[\mathbf{Q}\ \mathbf{N}]|\)</span>도 <span class="math inline">\(b^{nL}\)</span>도 사라진다. <strong>밀도 바닥의 최종 형태는 “합성곱 바닥의 절반”</strong>이고, <span class="math inline">\(\mathbf{Q}\)</span> 선택·옛 야코비안 <span class="math inline">\(35\sqrt3\)</span> 모두 최종 답에 안 남는다 (구조는 옛 <span class="math inline">\(c_* = m_*/(b^{nL}J)\)</span>와 동일하나 이제 그 사실이 식에서 투명하다).</p>
</section>
<section id="snowfall-a가-필수인-이유-snowfall-b-반례" class="level2">
<h2 class="anchored" data-anchor-id="snowfall-a가-필수인-이유-snowfall-b-반례">Snowfall A가 필수인 이유 (snowfall B 반례)</h2>
<p>fall 적립 하나하나가 Lebesgue 밀도를 갖기에 fall 밀도에 양의 바닥이 생긴다. <strong>Snowfall B</strong>(라운드 상수 적립)는 한 라운드의 모든 적립을 같게 만들어 <span class="math inline">\(nL\)</span>개 fall 좌표가 <strong>라운드당 스칼라 하나로 붕괴</strong> — fall 이미지가 저차원 집합에 갇혀 <span class="math inline">\(\mathbb{R}^{n-1}\)</span>에서 <strong>Lebesgue-null</strong>, 밀도 바닥이 무너진다.</p>
<hr>
</section>
<section id="결산-한-표로" class="level2">
<h2 class="anchored" data-anchor-id="결산-한-표로">결산 — 한 표로</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>station</th>
<th>산출물</th>
<th><span class="math inline">\(K_3\)</span> 값/정체</th>
<th>무엇을 보장</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Discrete floor</td>
<td><span class="math inline">\(\mu_{\min}^{nL}\,q_{\min}^{D}\,(\varepsilon_{\flat}/b)^{nLT_{\max}}\)</span></td>
<td><span class="math inline">\((\tfrac13)^{105}\cdot(\tfrac12)^{D}\cdot\varepsilon_{\flat}^{630}\)</span></td>
<td>시나리오의 이산 부분이 양의 확률</td>
</tr>
<tr class="even">
<td><span class="math inline">\((\dagger)\)</span> 치환적분</td>
<td><span class="math inline">\(\mathbf{b}^{\sharp}=\mathbf{Q}\boldsymbol{\zeta}+\mathbf{N}\mathbf{w}\)</span>, Tonelli</td>
<td><span class="math inline">\(105 = 2+103\)</span>, <span class="math inline">\(\mathbf{N}\in\mathbb{R}^{105\times103}\)</span></td>
<td>큐브 확률 ↔︎ <span class="math inline">\(\mathbf{w}\)</span>-slice Lebesgue 환전</td>
</tr>
<tr class="odd">
<td>Slice floor</td>
<td><span class="math inline">\(m_0 = b^{nL}c_{K_{\mathsf{U}}}/\lvert\det[\mathbf{Q}\ \mathbf{N}]\rvert\)</span></td>
<td><span class="math inline">\(c_{K_{\mathsf{U}}}\cdot35\sqrt3\)</span></td>
<td><span class="math inline">\(K_{\mathsf{U}}\)</span> 모든 표적서 full slice 양의 측도</td>
</tr>
<tr class="even">
<td>Robust core</td>
<td><span class="math inline">\(\mathcal{R}_\delta(s^{\star})\)</span>, <span class="math inline">\(m_* = m_0/2\)</span></td>
<td><span class="math inline">\(C\delta\leq m_0/2\)</span>, <span class="math inline">\(\delta\leq\kappa_{\mathsf{U}}=\tfrac1{768}\)</span></td>
<td>tie·경계 도려내고도 절반 생존</td>
</tr>
<tr class="odd">
<td>Transport</td>
<td><span class="math inline">\(\widehat{\mathbf{b}}^{\sharp} = \mathbf{b}^{\sharp}-\mathbf{Q}\boldsymbol{\Lambda}^{\flat}_{\amalg}\mathbf{b}^{\flat}\)</span></td>
<td><span class="math inline">\(\mathbf{w}\)</span> 불변, <span class="math inline">\(\Gamma\varepsilon_{\flat}\leq\delta/4\)</span></td>
<td>어떤 잔차든 같은 <span class="math inline">\(\mathbf{w}\)</span>로 흡수</td>
</tr>
<tr class="even">
<td>조립</td>
<td><span class="math inline">\(c_* = m_*\lvert\det[\mathbf{Q}\ \mathbf{N}]\rvert/b^{nL} = c_{K_{\mathsf{U}}}/2\)</span></td>
<td><span class="math inline">\(\det\)</span> 상쇄</td>
<td><span class="math inline">\(\rho_{\mathbf{b}^{\flat}}\geq c_*\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\eta \;=\; \mu_{\min}^{nL}\,q_{\min}^{D}\,(\varepsilon_{\flat}/b)^{nLT_{\max}}\,c_*\,|\mathsf{U}|_{\mathrm{Leb}} \;&gt;\;0\]</span> — “<span class="math inline">\(C_0\)</span> 안 모든 <span class="math inline">\(s^{\star}\)</span>에서 <span class="math inline">\(nL\)</span>라운드 뒤 공통 바닥 <span class="math inline">\(\eta\,\nu\)</span>”가 성립한다. 이것이 Lemma 8의 결론이고, <span class="math inline">\(C_0\)</span>는 small — 따라서 petite — 다.</p>
<p>여기까지가 <strong>H2(small set)</strong> 하나다. 에르고딕 정리 전체는 H1(<span class="math inline">\(\psi\)</span>-irreducibility·aperiodicity)·H3(Foster drift)까지 세 조건을 모두 채워야 한다.</p>
<hr>
<p><em>(1·2·3부 통합 해설 — 1부 무대, 2부 proof sketch(시나리오 1→4), 3부 full proof(Lebesgue-only). 정본: hst_AAA.tex Lemma 8, 2026-06-12판 — coarea/Hausdorff 폐지, <span class="math inline">\((\dagger)\)</span> 치환적분 + <span class="math inline">\(\mathbf{w}\)</span>-slice 체계.)</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>