<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="인연">
<meta name="dcterms.date" content="2026-07-22">

<title>연구 ▷ 호르무즈 ▷ 궤적으로 읽기 — 위기는 배들을 어떻게 바꿨나 (통합본) – 신록예찬’s Blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-7b59c39520e292c26c771bd4ab5cbcb0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">신록예찬’s Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DL2024/"> 
<span class="menu-text">DL2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/AP2023/"> 
<span class="menu-text">AP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/PP2024/"> 
<span class="menu-text">PP2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DV2023/"> 
<span class="menu-text">DV2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/MP2023/"> 
<span class="menu-text">MP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SC2024/"> 
<span class="menu-text">SC2024</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/DS2022/"> 
<span class="menu-text">DS2022</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/SP2023/"> 
<span class="menu-text">SP2023</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://guebin.github.io/IR2021/"> 
<span class="menu-text">IR2021</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan/"> 
<span class="menu-text">yechan</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://miruetoto.github.io/yechan2/"> 
<span class="menu-text">yechan2</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/miruetoto/yechan"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">연구 ▷ 호르무즈 ▷ 궤적으로 읽기 — 위기는 배들을 어떻게 바꿨나 (통합본)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>인연 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- 소유권자: 인연 | 사용자: 인연 -->
<!-- 판정: (B) 대중 해설 통합본 — 3-채널 분해 + 속도·정박 이론 + joint MFPCA + 표현 사전을 하나로 -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>이 글은 호르무즈 프로젝트의 네 편(3-채널 분해 · permutation 검정 해부 · 속도·정박 2-상태 이론 · joint MFPCA)을 <strong>하나의 완결된 이야기</strong>로 엮은 통합본입니다. 한 편이 길지만, 앞에서 세운 도구를 뒤에서 계속 씁니다.</p>
</div>
</div>
<blockquote class="blockquote">
<p><em>(스튜디오. 화면에 위성 지도 하나 — 호르무즈 해협 위로 파랗고 주황한 실타래 수천 가닥. H 가 마이크를 당긴다.)</em></p>
</blockquote>
<p><strong>H.</strong> 오늘 이야기는 배 1,174척의 이동 경로에서 시작해요. 2026년 봄, 호르무즈 해협. 전쟁이 나고, 봉쇄가 있었고, 뉴욕타임스가 그 전후의 선박 항적 데이터를 기사에 실었죠. 전쟁 전 열흘 동안 1,089척, 이란 보복 이후 열흘 동안 85척.</p>
<p><strong>G.</strong> 1,089에서 85로요? 12분의 1이 됐네요.</p>
<p><strong>H.</strong> 네, 그게 첫 번째 충격이고요. 오늘의 진짜 질문은 그 다음이에요 — <strong>살아남은 그 85척의 항해는, 전쟁 전과 무엇이 달라졌는가?</strong> 그리고 그 “달라짐”을 어떻게 하나의 숫자로 말할 것인가.</p>
<p><strong>G.</strong> 경로가 바뀌었다, 속도가 느려졌다, 이런 식으로 말하면 되는 거 아닌가요?</p>
<p><strong>H.</strong> 바로 그 지점에서 퍼즐이 터집니다.</p>
<hr>
<section id="에피소드-1-세-개의-검정이-따로-노는-미스터리" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-1-세-개의-검정이-따로-노는-미스터리">에피소드 1: 세 개의 검정이 따로 노는 미스터리</h2>
<p><strong>H.</strong> 같은 데이터에 표준적인 분석 세 가지를 돌렸어요. 결과가 이래요.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>물었던 질문</th>
<th>통계 검정의 대답 (p-value)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>궤적 전체가 달라졌나? (좌표 함수 그대로)</td>
<td><span class="math inline">\(p = 0.129\)</span> — 글쎄요?</td>
</tr>
<tr class="even">
<td>경로가 더 구불구불해졌나? (곡률)</td>
<td><span class="math inline">\(p = 0.349\)</span> — 전혀 아님</td>
</tr>
<tr class="odd">
<td>속도·정박이 달라졌나? (평균속도, 멈춤 비율)</td>
<td><span class="math inline">\(p &lt; 10^{-4}\)</span> — 압도적으로 그렇다</td>
</tr>
</tbody>
</table>
<p><strong>G.</strong> 잠깐만요, 그 p-value 라는 건 대체 어떻게 뽑은 거예요? 세 검정이 다른 방법인가요?</p>
<p><strong>H.</strong> 재료는 셋이 다 다른데, <strong>엔진은 하나</strong>예요 — permutation(치환) 검정. 원리가 아주 물리적이에요. 우리 데이터의 각 배에는 “전쟁 전” 또는 “위기 후”라는 이름표가 붙어 있잖아요. 만약 위기가 아무 효과도 없었다면, 이 이름표는 <strong>아무 의미 없는 스티커</strong>여야 해요. 그렇죠?</p>
<p><strong>G.</strong> 스티커를 떼서 아무 배에나 다시 붙여도 똑같아야 한다…</p>
<p><strong>H.</strong> 바로 그거예요. 그래서 실제로 그렇게 합니다. 이름표를 컴퓨터로 무작위로 섞어 붙이고 — 1,073장의 스티커를 섞되 “전쟁 전 1,006장, 위기 후 67장”이라는 장수는 유지하고 — 두 집단의 차이를 다시 계산해요. 이걸 수천 번 반복하면 <strong>“우연만으로 생길 수 있는 차이”의 분포</strong>가 만들어져요. 그 다음 진짜 이름표로 잰 차이를 그 분포 위에 올려놓고 물어요: 우연이 이만큼 큰 차이를 만들 확률이 얼마냐? 그게 p-value 예요.</p>
<p><strong>G.</strong> <span class="math inline">\(p &lt; 10^{-4}\)</span> 라는 건 만 번 섞어도 실제만 한 차이가 안 나왔다는 거고, <span class="math inline">\(p = 0.129\)</span> 는…</p>
<p><strong>H.</strong> 섞은 것 중 열에 하나 꼴로 실제보다 큰 차이가 그냥 나왔다는 뜻이에요. “우연과 구분이 안 된다”는 거죠. 이 방식의 장점은 정직함이에요 — 데이터가 정규분포라든가 하는 가정을 전혀 안 빌려요. 특히 우리처럼 1,006 대 67로 심하게 기운 표본에서는, 분포 가정에 기대는 공식보다 이름표를 실제로 섞어보는 쪽이 훨씬 안전해요.</p>
<p><strong>G.</strong> 좋아요, 원리는 알겠어요. 그런데 저라면 그 그림을 어떻게 그리죠? 처음부터 끝까지요.</p>
<p><strong>H.</strong> 칠판에 적어볼게요. 정확히 여섯 단계고, 이대로 하면 누구든 같은 그림이 나옵니다. (아래는 나중에 나올 3-수준 분해의 세 채널 기준이지만, 어떤 검정 통계량이든 뼈대는 동일해요.)</p>
<p><strong>Step 0 — 입력.</strong> 항적 <span class="math inline">\(N = 1073\)</span> 개 (전쟁 전 <span class="math inline">\(n_B = 1006\)</span>, 위기 후 <span class="math inline">\(n_A = 67\)</span>). 각 항적 <span class="math inline">\(i\)</span> 의 시기 이름표를 <span class="math inline">\(z_i \in \{0, 1\}\)</span> 로 적어요 (<span class="math inline">\(1\)</span> = 위기 후). 관측된 이름표 벡터가 <span class="math inline">\(z^{\mathrm{obs}}\)</span>.</p>
<p><strong>Step 1 — 각 항적을 세 좌표로.</strong> 여기가 제일 손이 많이 가는 단계니까 원자료부터 풀어서 적을게요. 항적 <span class="math inline">\(i\)</span> 의 원자료는 GPS 점열이에요:</p>
<p><span class="math display">\[\text{항적 } i \;=\; \bigl\{ (x_j, y_j, t_j) \bigr\}_{j = 1, \dots, n_i} \qquad (x, y \text{ 는 km 좌표, } t \text{ 는 초}).\]</span></p>
<p><strong>(1a) 시간을 버리고 “길 위의 눈금”을 만든다.</strong> 이웃한 두 점 사이의 거리와 시간을 재요:</p>
<p><span class="math display">\[\Delta s_j = \sqrt{(x_{j+1} - x_j)^2 + (y_{j+1} - y_j)^2}, \qquad \Delta t_j = t_{j+1} - t_j, \qquad L = \textstyle\sum_j \Delta s_j .\]</span></p>
<p>거리를 앞에서부터 누적해 전체 길이로 나누면, 각 점이 “경로의 몇 % 지점”인지가 나옵니다:</p>
<p><span class="math display">\[s_1 = 0, \qquad s_{j+1} = s_j + \Delta s_j / L \;\in\; [0, 1].\]</span></p>
<p>이 <span class="math inline">\(s\)</span> 가 새 눈금이에요 — 시계가 아니라 <strong>줄자</strong>. (동→서로 간 배는 <span class="math inline">\(s \mapsto 1 - s\)</span> 로 뒤집어 전부 서→동으로 통일.)</p>
<p><strong>G.</strong> 잠깐, 아래 도해의 (1a)를 보면 점 간격이 고르지 않잖아요. 그건 관측이 불규칙해서예요, 배 속도가 달라서예요?</p>
<p><strong>H.</strong> <strong>둘 다</strong>예요 — 점 사이 거리는 <span class="math inline">\(\Delta s = v \times \Delta t\)</span>, 두 인자가 다 흔들리거든요. 도해의 그 배로 실측해 보면: 관측 간격 <span class="math inline">\(\Delta t\)</span> 자체가 10분에서 92시간까지 제각각이에요. AIS 는 정해진 주기로 찍히는 게 아니라 수신 상황과 벤더 처리에 따라 듬성듬성 남거든요. 동시에 속도도 시속 0.02 km 에서 19 km 까지 변해요 — 서쪽 끝에 점이 뭉친 건 주로 이쪽, 배가 느려지고 멈추면서 같은 자리 근처에 점이 쌓인 거죠. 그리고 이 두 겹의 불규칙성이 바로 (1a)의 존재 이유예요: 시계 기준으로는 배끼리 비교가 안 되니 줄자로 갈아타는 것. 대신 시간 정보를 버리진 않아요 — (1c)의 <span class="math inline">\(\tau\)</span> 가 “시간이 어디에 몰렸나”를 고스란히 보관합니다.</p>
<p><strong>(1b) 위치와 모양.</strong> 줄자 눈금 위에 등간격 격자 <span class="math inline">\(s_k = (k - \tfrac12)/M\)</span>, <span class="math inline">\(k = 1, \dots, M{=}50\)</span> 을 놓고, 관측점들을 선형보간해서 격자 위 경로를 얻어요:</p>
<p><span class="math display">\[\beta_i(s_k) = \bigl( x_i(s_k), \, y_i(s_k) \bigr) \quad (\text{보간}), \qquad c_i = \tfrac{1}{M} \textstyle\sum_{k} \beta_i(s_k), \qquad \tilde\beta_i(s_k) = \beta_i(s_k) - c_i .\]</span></p>
<p>여기서 “보간”은 이렇게 합니다. 배가 격자 눈금 <span class="math inline">\(s_k\)</span> 에서 정확히 관측된 적은 없어요 — 관측점들의 눈금 <span class="math inline">\(s_j\)</span> 는 비균등하니까. 그래서 원하는 눈금 <span class="math inline">\(g\)</span> 가 이웃한 두 관측점 사이(<span class="math inline">\(s_j \le g \le s_{j+1}\)</span>)에 떨어지면, 두 점을 잇는 직선 위의 비례 지점을 취합니다:</p>
<p><span class="math display">\[w = \frac{g - s_j}{s_{j+1} - s_j}, \qquad \bigl( x(g), \, y(g) \bigr) = (1 - w)\,(x_j, y_j) + w\,(x_{j+1}, y_{j+1}).\]</span></p>
<p>“두 관측점 사이 60% 지점의 눈금이면, 지도에서도 그 두 점을 잇는 선분의 60% 지점에 찍는다” — 그게 전부예요. 아래 그림의 주황 줄자 눈금 11개도, <span class="math inline">\(M = 50\)</span> 격자 경로도 전부 이 한 줄(코드로는 <code>approx(s, x, xout = g)</code>)로 만든 겁니다.</p>
<p><strong>G.</strong> 그러니까 <span class="math inline">\(\beta\)</span> 는… 어디서 “추정”되어 나오는 게 아니라?</p>
<p><strong>H.</strong> 아니에요, 그게 핵심이에요. <span class="math inline">\(\beta\)</span> 는 <strong>추정이 아니라 결정</strong>입니다 — 모형 적합도, 스무딩도, 무작위성도 없어요. 절차를 한 번에 다시 적으면:</p>
<ol type="1">
<li>관측점들을 시간 순서대로 <strong>직선으로 잇는다.</strong> 이 꺾은선이 우리가 아는 이 배의 경로 전부예요.</li>
<li>꺾은선의 총 길이 <span class="math inline">\(L\)</span> 을 재고, 시작점에서 길이를 따라 <span class="math inline">\(g \cdot L\)</span> 만큼 <strong>걸어간 지점</strong>의 좌표가 <span class="math inline">\(\beta_i(g)\)</span>. 걷다가 관측점 <span class="math inline">\(j\)</span> 와 <span class="math inline">\(j{+}1\)</span> 사이에서 멈추면 그 선분 위의 비례 지점 — 방금의 보간 공식이 정확히 그 좌표를 줍니다.</li>
<li><span class="math inline">\(g = \tfrac{1}{100}, \tfrac{3}{100}, \dots, \tfrac{99}{100}\)</span> (<span class="math inline">\(M = 50\)</span> 개)에서 읽으면 끝. <span class="math inline">\(\beta_i\)</span> 는 <span class="math inline">\((x, y)\)</span> 쌍 50개, 즉 <strong>숫자 100개짜리 벡터</strong>예요.</li>
</ol>
<p>같은 입력이면 언제나 같은 출력이고, 자유롭게 고른 것은 <span class="math inline">\(M\)</span> 하나뿐입니다(그 선택이 결과를 안 흔든다는 건 본 논문의 민감도 분석에서 확인). 미니예제로 검산: 아래의 장난감 트랙 <span class="math inline">\(x = (0, 3, 7, 10)\)</span>, <span class="math inline">\(y = 0\)</span> 은 <span class="math inline">\(x = 10 s\)</span> 인 직선이라, <span class="math inline">\(M = 5\)</span> 격자 <span class="math inline">\(g = (0.1, 0.3, 0.5, 0.7, 0.9)\)</span> 에서 <span class="math inline">\(\beta\)</span> 의 <span class="math inline">\(x\)</span> 좌표는 정확히 <span class="math inline">\((1, 3, 5, 7, 9)\)</span> 가 나와야 하고 — 실제로 나옵니다.</p>
<p><span class="math inline">\(c_i\)</span> 는 경로의 무게중심(위치), <span class="math inline">\(\tilde\beta_i\)</span> 는 무게중심을 원점으로 옮겨 놓은 경로(모양)입니다.</p>
<p><strong>(1c) 운동학 — 시간을 줄자 위에 쏟아붓는다.</strong> 각 segment <span class="math inline">\(j\)</span> 는 “<strong>어디서</strong>(호길이 중점 <span class="math inline">\(m_j = \tfrac{s_j + s_{j+1}}{2}\)</span>) <strong>얼마나</strong>(<span class="math inline">\(\Delta t_j\)</span> 초)”의 기록이에요. 그 시간을 중점이 속한 칸에 넣습니다:</p>
<p><span class="math display">\[\mathrm{bin}(j) = \lceil m_j \cdot M \rceil, \qquad \mathrm{mass}_k = \sum_{j :\, \mathrm{bin}(j) = k} \Delta t_j, \qquad \tau_i(s_k) = \frac{\mathrm{mass}_k}{\sum_{k'} \mathrm{mass}_{k'}} .\]</span></p>
<p>말로 하면: <strong>시간의 히스토그램을 시간축이 아니라 경로축 위에 그리는 것.</strong> 정박한 배는 <span class="math inline">\(\Delta s \approx 0\)</span> 인데 <span class="math inline">\(\Delta t\)</span> 가 크죠 — 그 큰 시간이 통째로 한 칸에 떨어져서 봉우리가 됩니다.</p>
<p>지금까지의 (1a)→(1b)→(1c)를, 그리고 <strong>왜 그렇게 하는지</strong>를 실제 데이터의 배 두 척으로 보면 이렇습니다. 위기 이후의 gas 트랙 한 척과, 그 배와 모양이 가장 비슷한 전쟁 전 트랙 한 척을 짝지었어요:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_905.png" class="img-fluid figure-img"></p>
<figcaption>Step 1 해부 — 두 척으로 보는 “무엇을, 왜”. (1a) 시계로 찍힌 점열(간격 불균등)을 줄자 눈금으로 바꾼다. (1b) 왜 c 를 빼는가: 원좌표의 두 배는 39 km 떨어져 있지만(왼쪽), 각자의 중심을 빼고 겹치면 거의 포개진다(오른쪽) — 원좌표 거리에 섞여 있던 “이사”와 “모양”이 분리된다. (1c) 왜 τ 인가: 길이도 관측 시간도 다른 두 배가 같은 [0,1] 자 위에 올라온다 — 위기 후 배는 첫 칸에 시간의 79%(닷새 중 나흘 정박), 전쟁 전 배는 경로 전체에 고르게. 이 비교를 1,073척으로 확장한 것이 본편의 분석이다.</figcaption>
</figure>
</div>
<p><strong>G.</strong> 가운데 줄이 눈에 들어와요. 원좌표에선 서로 딴 동네에 있던 두 배가, 중심을 빼니까 거의 같은 모양이네요?</p>
<p><strong>H.</strong> 그게 “빼는 이유”의 전부예요. 빼기 전의 두 경로 사이 거리에는 이사(39 km)와 모양 차이가 <strong>섞여</strong> 있고, 뺀 후의 거리는 순수하게 모양이에요. 이걸 분리 안 하면 “위기의 몇 %가 이사고 몇 %가 변형인가”라는 질문 자체를 던질 수 없죠.</p>
<p><strong>G.</strong> 그리고 맨 아래 — 한 척만 보면 그냥 그 배 항해일지 요약인데, 두 척을 같은 자 위에 올리니까 비교가 되는군요.</p>
<p><strong>H.</strong> 바로 그거예요. <span class="math inline">\(\tau\)</span> 그림 한 장의 가치는 79% 막대 자체가 아니라, <strong>길이 300 km 짜리 배와 250 km 짜리 배, 닷새 관측과 이틀 관측을 같은 [0,1] 축 위에 포갤 수 있게 됐다</strong>는 데 있어요. 포갤 수 있으면 평균 낼 수 있고, 평균 낼 수 있으면 검정할 수 있죠. 이 두 척을 1,073척으로 늘린 게 에피소드 5의 τ profile 이에요. 이제 이걸 장난감 숫자로 손계산해 볼게요.</p>
<p><strong>미니 예제 (손계산용, <span class="math inline">\(M = 5\)</span>).</strong> 점 4개짜리 장난감 항적 — 중간 지점에서 10시간 정박한 배:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(j\)</span></th>
<th><span class="math inline">\((x_j, y_j)\)</span> km</th>
<th><span class="math inline">\(t_j\)</span></th>
<th><span class="math inline">\(\Delta s_j\)</span></th>
<th><span class="math inline">\(\Delta t_j\)</span></th>
<th>중점 <span class="math inline">\(m_j\)</span></th>
<th>bin <span class="math inline">\(= \lceil m_j \cdot 5 \rceil\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\((0, 0)\)</span></td>
<td>0h</td>
<td>3</td>
<td>1h</td>
<td><span class="math inline">\(0.15\)</span></td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\((3, 0)\)</span></td>
<td>1h</td>
<td>4</td>
<td>10h</td>
<td><span class="math inline">\(0.50\)</span></td>
<td>3</td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\((7, 0)\)</span></td>
<td>11h</td>
<td>3</td>
<td>1h</td>
<td><span class="math inline">\(0.85\)</span></td>
<td>5</td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\((10, 0)\)</span></td>
<td>12h</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(L = 10\)</span> km, <span class="math inline">\(s = (0, 0.3, 0.7, 1)\)</span>. 시간 질량은 칸 <span class="math inline">\((1, 3, 5)\)</span> 에 <span class="math inline">\((1, 10, 1)\)</span> 시간 →</p>
<p><span class="math display">\[\tau = \bigl( \tfrac{1}{12}, \; 0, \; \tfrac{10}{12}, \; 0, \; \tfrac{1}{12} \bigr) = (0.083, \; 0, \; 0.833, \; 0, \; 0.083).\]</span></p>
<p>“경로 가운데 칸에서 전체 시간의 83%” — 정박이 봉우리가 되는 걸 손으로 확인했어요. 위치는 <span class="math inline">\(c = (5, 0)\)</span>, 딱 경로 한가운데고요.</p>
<p>이 전부를 실행되는 R 함수 하나로 적으면:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>track_to_channels <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, t, <span class="at">M =</span> <span class="dv">50</span>) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  ds <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diff</span>(x)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">diff</span>(y)<span class="sc">^</span><span class="dv">2</span>)        <span class="co"># (1a) segment 길이 (km)</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  dt <span class="ot">&lt;-</span> <span class="fu">diff</span>(t)                            <span class="co">#      segment 시간 (초)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  s  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">cumsum</span>(ds)) <span class="sc">/</span> <span class="fu">sum</span>(ds)         <span class="co">#      정규화 호길이 [0,1]</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">tail</span>(x, <span class="dv">1</span>) <span class="sc">&lt;</span> x[<span class="dv">1</span>]) s <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> s        <span class="co">#      서→동 방향 통일</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  g  <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span>M <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">/</span> M                    <span class="co"># (1b) M점 격자</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  o  <span class="ot">&lt;-</span> <span class="fu">order</span>(s)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  beta  <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">approx</span>(s[o], x[o], <span class="at">xout =</span> g)<span class="sc">$</span>y,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">approx</span>(s[o], y[o], <span class="at">xout =</span> g)<span class="sc">$</span>y)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  c_i   <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(beta)                  <span class="co">#      ① 위치</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  shape <span class="ot">&lt;-</span> <span class="fu">sweep</span>(beta, <span class="dv">2</span>, c_i)             <span class="co">#      ② 모양</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  mid  <span class="ot">&lt;-</span> (s[<span class="sc">-</span><span class="fu">length</span>(s)] <span class="sc">+</span> s[<span class="sc">-</span><span class="dv">1</span>]) <span class="sc">/</span> <span class="dv">2</span>      <span class="co"># (1c) segment 중점</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  bin  <span class="ot">&lt;-</span> <span class="fu">pmin</span>(M, <span class="fu">pmax</span>(<span class="dv">1</span>, <span class="fu">ceiling</span>(mid <span class="sc">*</span> M)))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  mass <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dt, <span class="fu">factor</span>(bin, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span>M), sum)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  mass[<span class="fu">is.na</span>(mass)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  tau  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(mass <span class="sc">/</span> <span class="fu">sum</span>(mass))     <span class="co">#      ③ 운동학</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">position =</span> c_i, <span class="at">shape =</span> shape, <span class="at">tau =</span> tau)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 미니 예제 검증 — 위 표와 동일 (실행 확인됨)</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">track_to_channels</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">10</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>                  <span class="at">t =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">11</span>, <span class="dv">12</span>) <span class="sc">*</span> <span class="dv">3600</span>, <span class="at">M =</span> <span class="dv">5</span>)<span class="sc">$</span>tau</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.0833  0.0000  0.8333  0.0000  0.0833   (= 1/12, 0, 10/12, 0, 1/12)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Step 2 — 쌍별 거리 행렬.</strong> 채널마다 <span class="math inline">\(N \times N\)</span> 거리 행렬을 만들어요.</p>
<p><span class="math display">\[D^{\mathrm{pos}}_{ij} = \lVert c_i - c_j \rVert, \qquad D^{\mathrm{shp}}_{ij} = \tfrac{1}{\sqrt{M}} \lVert \tilde\beta_i - \tilde\beta_j \rVert, \qquad D^{\mathrm{kin}}_{ij} = \arccos\!\textstyle\sum_k \sqrt{\tau_i(s_k)\,\tau_j(s_k)}.\]</span></p>
<p>채널마다 단위(km, km, 라디안)가 다르니 각 행렬을 자기 평균으로 나눠 무차원화합니다: <span class="math inline">\(D \leftarrow D / \overline{D}\)</span>. <strong>여기까지가 비싼 계산이고, 딱 한 번만 합니다</strong> — 거리는 이름표와 무관하니까요.</p>
<p><strong>Step 3 — 검정 통계량.</strong> 이름표 벡터 <span class="math inline">\(z\)</span> 가 주어지면, “두 집단이 얼마나 다른 곳에 사나”를 energy distance 로 잽니다:</p>
<p><span class="math display">\[T(z) \;=\; \underbrace{\frac{2}{n_A n_B} \sum_{z_i = 1} \sum_{z_j = 0} D_{ij}}_{\text{집단 사이 평균거리} \times 2} \;-\; \underbrace{\frac{1}{n_A^2} \sum_{z_i = z_j = 1} D_{ij}}_{\text{위기 후 집단 안}} \;-\; \underbrace{\frac{1}{n_B^2} \sum_{z_i = z_j = 0} D_{ij}}_{\text{전쟁 전 집단 안}}.\]</span></p>
<p>직관: 두 집단이 같은 분포에서 나왔다면 “사이 거리”와 “안 거리”가 비슷해서 <span class="math inline">\(T \approx 0\)</span>. 다른 곳에 살수록 <span class="math inline">\(T\)</span> 가 커져요.</p>
<p><strong>Step 4 — 이름표 999번 섞기.</strong> <span class="math inline">\(b = 1, \dots, 999\)</span> 에 대해: <span class="math inline">\(z^{\mathrm{obs}}\)</span> 를 무작위로 재배열한 <span class="math inline">\(z^{(b)}\)</span> 를 뽑고 (1의 개수 67은 유지!) <span class="math inline">\(T(z^{(b)})\)</span> 를 계산해요. <span class="math inline">\(D\)</span> 는 이미 있으니 재배정 하나당 행렬-벡터 곱 한 번이면 끝나요. 이 999개가 그림의 <strong>회색 히스토그램</strong> — “위기가 무효라는 세계에서 나올 수 있는 <span class="math inline">\(T\)</span> 값들”이에요.</p>
<p><strong>Step 5 — 관측값과 p-value.</strong> 진짜 이름표의 <span class="math inline">\(T(z^{\mathrm{obs}})\)</span> 가 <strong>주황 세로선</strong>. p-value 는 등수 세기예요:</p>
<p><span class="math display">\[\hat{p} \;=\; \frac{1 + \#\{\, b : T(z^{(b)}) \ge T(z^{\mathrm{obs}}) \,\}}{999 + 1}.\]</span></p>
<p>우리 데이터에선 999개 전부가 관측값보다 작았으니 <span class="math inline">\(\hat p = \tfrac{1 + 0}{1000} = 0.001\)</span>.</p>
<p><strong>G.</strong> 분모가 999가 아니라 <span class="math inline">\(999+1\)</span> 이고 분자에도 <span class="math inline">\(1\)</span> 이 붙네요?</p>
<p><strong>H.</strong> 관측 이름표 <strong>자신도 후보 중 하나로 세는</strong> 거예요. 이렇게 하면 귀무가설 아래에서 <span class="math inline">\(T(z^{\mathrm{obs}})\)</span> 는 999개의 <span class="math inline">\(T(z^{(b)})\)</span> 와 완전히 같은 자격의 값이라 — 이름표가 무의미하면 1000개 중 등수가 균등 — <span class="math inline">\(\Pr(\hat p \le \alpha) \le \alpha\)</span> 가 <strong>유한한 반복 횟수에서도 정확히</strong> 보장돼요. B 를 늘리면 p 가 더 세밀해질 뿐, 정직함은 처음부터 보장이죠.</p>
<p>전체를 의사코드로 적으면 이게 다예요:</p>
<pre class="text"><code>입력: 거리행렬 D (N×N, 채널별), 이름표 z_obs (1이 n_A개), B = 999
D ← D / mean(D)                          # 채널 표준화
T_obs ← T(z_obs)                          # Step 3 의 공식
for b in 1..B:
    z_b ← z_obs 의 무작위 재배열          # 1의 개수 유지
    T_b ← T(z_b)
p̂ ← (1 + #{b : T_b ≥ T_obs}) / (B + 1)
그림 ← T_1..T_B 히스토그램(회색) + T_obs 세로선(주황)</code></pre>
<p>세 채널은 <strong>같은 재배열 <span class="math inline">\(z^{(b)}\)</span> 들을 공유</strong>해요 — 그래서 세 패널의 회색 산들이 “같은 우연”을 서로 다른 채널에서 본 것이 되고, 패널끼리 직접 비교할 수 있어요. 그 결과가 이 그림입니다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_904.png" class="img-fluid figure-img"></p>
<figcaption>이름표를 999번 섞은 결과 — 우연의 분포(회색) vs 실제 관측값(주황). 세 채널 모두 우연의 범위 바깥이라 p=0.001. 단, 벗어난 ’여유’는 제각각 — 위치는 우연 최댓값의 약 3배, 운동학은 간신히 바깥. 이 여유의 차이가 곧 효과 크기의 차이다.</figcaption>
</figure>
</div>
<p><strong>G.</strong> 셋 다 우연 바깥이라 “확실함”은 같은데, 벗어난 거리가 다르네요. 위치는 저 멀리 있고 운동학은 턱걸이고.</p>
<p><strong>H.</strong> 그 관찰을 기억해 두세요 — 에피소드 4의 복선이에요. “얼마나 확실한가”와 “얼마나 큰가”가 벌써 갈라지기 시작했죠.</p>
<p><strong>G.</strong> 그럼 세 줄의 “재료”는 각각 뭐였어요? 하나씩 뜯어봐 주세요.</p>
<p><strong>H.</strong> 좋아요, 한 줄씩 — 각각 스텝 → 그림 → 코드 → 결과 순서로요. 미리 하나만: 아래 코드는 특수 패키지 없이 그대로 돌아가는 <strong>단순화 재현판</strong>이에요. 원논문 스펙(B-spline 기저, GCV 평활 등)의 p 는 <span class="math inline">\(0.129 / 0.349 / {&lt;}10^{-4}\)</span> 이고, 이 단순화판을 실제로 돌리면 <span class="math inline">\(0.077 / 0.93 / 0.0002\)</span> — 숫자는 조금 다르지만 세 결론(<strong>애매 / 전혀 아님 / 압도적</strong>)은 정확히 같습니다.</p>
<section id="첫째-줄-궤적-전체가-달라졌나-함수형-pca" class="level4">
<h4 class="anchored" data-anchor-id="첫째-줄-궤적-전체가-달라졌나-함수형-pca">첫째 줄 — “궤적 전체가 달라졌나?” (함수형 PCA)</h4>
<ol type="1">
<li>모든 배를 Step 1b 의 <span class="math inline">\(\beta\)</span> 로 바꾼다 → 배 한 척 = 숫자 100개 (<span class="math inline">\(x\)</span> 50 + <span class="math inline">\(y\)</span> 50). 1,073척이면 <span class="math inline">\(1073 \times 100\)</span> 행렬.</li>
<li>이 행렬에 PCA — 1,073개의 점이 100차원 공간에 떠 있고, <strong>가장 크게 흩어진 방향</strong>이 PC1(제1 변동 모드). 그 방향이 무엇을 뜻하는지는 평균 경로를 그 방향으로 밀어보면 안다 (아래 그림 ①: 남북 lane 이동, 총분산의 57%).</li>
<li>배 한 척의 <strong>PC1 점수</strong> = 그 배가 그 방향으로 얼마나 가 있는가, 숫자 하나.</li>
<li>시기별 PC1 점수 평균의 차이를 통계량으로, 이름표 섞기에 올린다.</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_906.png" class="img-fluid figure-img"></p>
<figcaption>첫째 줄의 해부. ① PC1 방향으로 평균 경로를 ±2sd 밀면 남북 lane 이동이 나온다 — PC1 점수는 “어느 lane 쪽인가”를 재는 숫자. ② 시기별 PC1 점수 분포: 평균은 +69 이동했지만 두 분포가 워낙 넓게 겹쳐서, 이름표를 섞어도 이만한 차이는 흔하다 (p = 0.077) — 애매.</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pc  <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(Bgeo)                     <span class="co"># Bgeo: 1073 x 100, β 를 쌓은 행렬</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sc1 <span class="ot">&lt;-</span> pc<span class="sc">$</span>x[, <span class="dv">1</span>]                        <span class="co"># 배별 PC1 점수</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>obs  <span class="ot">&lt;-</span> <span class="fu">mean</span>(sc1[after]) <span class="sc">-</span> <span class="fu">mean</span>(sc1[<span class="sc">!</span>after])</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>null <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">4999</span>, { z <span class="ot">&lt;-</span> <span class="fu">sample</span>(after); <span class="fu">mean</span>(sc1[z]) <span class="sc">-</span> <span class="fu">mean</span>(sc1[<span class="sc">!</span>z]) })</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">sum</span>(<span class="fu">abs</span>(null) <span class="sc">&gt;=</span> <span class="fu">abs</span>(obs))) <span class="sc">/</span> <span class="dv">5000</span>   <span class="co">#&gt; 0.077 — 애매</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>G.</strong> 잠깐만요. PCA 를 두 시기 <strong>합쳐서 한 번</strong> 걸었네요? 두 시기 각각에 FPCA 를 걸어야 하는 거 아니에요?</p>
<p><strong>H.</strong> 좋은 의심인데, 비교가 목적이면 <strong>합쳐서 한 번이 맞아요.</strong> 이유가 세 겹이에요.</p>
<p>첫째, <strong>비교에는 공통 자(尺)가 필요해요.</strong> 시기별로 각각 걸면 Before 의 PC1 과 After 의 PC1 은 서로 다른 방향 — 100개 숫자의 서로 다른 선형결합 — 이에요. 그러면 “Before 점수 평균 vs After 점수 평균”은 서로 다른 질문에 대한 답 두 개를 빼는 셈이라 의미가 없어요. 키는 cm 자로 재고 몸무게는 kg 저울로 잰 다음 둘을 빼는 격이죠.</p>
<p>둘째, <strong>이름표 섞기와의 정합.</strong> 합친 PCA 는 이름표를 전혀 안 보고(비지도) 축을 만들어요. 그래서 이름표를 999번 섞는 동안 축은 그대로고, 검정의 정직함(에피소드 1의 randomization 보장)이 유지돼요. 시기별 축을 쓰면 검정 통계량 자체가 이름표의 함수가 되어서, 섞을 때마다 PCA 두 번을 다시 걸지 않는 한 검정이 망가집니다.</p>
<p>셋째, <strong>“각각 걸기”가 맞는 질문은 따로 있어요.</strong> “두 시기의 <strong>변동 구조 자체</strong>(모드의 방향, 분산의 스펙트럼)가 달라졌나?”를 묻는다면 시기별 FPCA 를 걸어 공분산을 비교하는 게 맞아요 — 그건 “분포가 이동했나”(우리 질문)와는 다른 질문이에요.</p>
<p><strong>G.</strong> 그래도 합친 축은 1,006척인 Before 가 지배할 텐데, 그게 결과를 왜곡하진 않아요?</p>
<p><strong>H.</strong> 그것도 실제로 확인해 봤어요. 세 가지 방식으로 축을 만들어 비교하면:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>축을 만든 방법</th>
<th>평균 이동</th>
<th>p</th>
<th>합친 축과의 방향 일치 <span class="math inline">\(\lvert\cos\rvert\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>두 시기 합침 (본문)</td>
<td><span class="math inline">\(+69.4\)</span></td>
<td><span class="math inline">\(0.077\)</span></td>
<td>—</td>
</tr>
<tr class="even">
<td>Before 만으로 축 → 전체 사영</td>
<td><span class="math inline">\(+67.4\)</span></td>
<td><span class="math inline">\(0.079\)</span></td>
<td><span class="math inline">\(0.999\)</span></td>
</tr>
<tr class="odd">
<td>After 67척만으로 축</td>
<td>—</td>
<td>—</td>
<td><span class="math inline">\(0.978\)</span></td>
</tr>
</tbody>
</table>
<p>세 축이 사실상 같은 방향(<span class="math inline">\(\lvert\cos\rvert \ge 0.97\)</span>)이고, Before-축으로 갈아타도 결과는 그대로예요. 게다가 After 쪽만으로 축을 만들면 67척으로 100차원 방향을 추정하는 셈이라 오히려 불안정하고요. 원칙(공통 자 + 이름표 불변)과 실증(어느 축이든 동일)이 같은 답을 줍니다.</p>
</section>
<section id="둘째-줄-경로가-더-구불구불해졌나-곡률" class="level4">
<h4 class="anchored" data-anchor-id="둘째-줄-경로가-더-구불구불해졌나-곡률">둘째 줄 — “경로가 더 구불구불해졌나?” (곡률)</h4>
<ol type="1">
<li><span class="math inline">\(\beta\)</span> 를 그대로 두 번 미분하면 관측 잡음이 폭발해요 (미분은 잡음 증폭기). 그래서 먼저 <strong>평활</strong>: 격자 경로에 부드러운 스플라인을 통과시킨다.</li>
<li>평활 곡선의 1·2차 도함수로 <strong>곡률</strong> <span class="math inline">\(\kappa(s) = \dfrac{x'y'' - y'x''}{(x'^2 + y'^2)^{3/2}}\)</span> — 지점별 “순간 굽음”(0 = 직진, 부호 = 좌/우회전).</li>
<li>배 한 척당 <span class="math inline">\(|\kappa(s)|\)</span> 를 경로 전체로 합쳐 <strong>총 굽음량(TAC)</strong> 하나로.</li>
<li>TAC(로그)의 시기 평균 차 → 이름표 섞기.</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_907.png" class="img-fluid figure-img"></p>
<figcaption>둘째 줄의 해부. ① 한 척의 κ(s): 두 번의 급회전이 봉우리로 잡힌다. ② 시기별 TAC 분포(로그): 두 바이올린이 사실상 판박이 — p = 0.93, 경로의 “거칠기”는 전혀 안 변했다.</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sx <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(g, bx, <span class="at">df =</span> <span class="dv">8</span>); sy <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(g, by, <span class="at">df =</span> <span class="dv">8</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>d1x <span class="ot">&lt;-</span> <span class="fu">predict</span>(sx, g, <span class="at">deriv=</span><span class="dv">1</span>)<span class="sc">$</span>y; d2x <span class="ot">&lt;-</span> <span class="fu">predict</span>(sx, g, <span class="at">deriv=</span><span class="dv">2</span>)<span class="sc">$</span>y</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>d1y <span class="ot">&lt;-</span> <span class="fu">predict</span>(sy, g, <span class="at">deriv=</span><span class="dv">1</span>)<span class="sc">$</span>y; d2y <span class="ot">&lt;-</span> <span class="fu">predict</span>(sy, g, <span class="at">deriv=</span><span class="dv">2</span>)<span class="sc">$</span>y</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>kap <span class="ot">&lt;-</span> (d1x<span class="sc">*</span>d2y <span class="sc">-</span> d1y<span class="sc">*</span>d2x) <span class="sc">/</span> (d1x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> d1y<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="fl">1.5</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>TAC <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(kap)) <span class="sc">*</span> L               <span class="co"># 한 척의 총 굽음량</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># → TAC 를 전 척에 계산, log(TAC) 평균차를 이름표 섞기:  p = 0.93 — 전혀 아님</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="셋째-줄-속도정박이-달라졌나-운동학-scalar" class="level4">
<h4 class="anchored" data-anchor-id="셋째-줄-속도정박이-달라졌나-운동학-scalar">셋째 줄 — “속도·정박이 달라졌나?” (운동학 scalar)</h4>
<ol type="1">
<li>연속된 두 관측점에서 <strong>segment 속도</strong> <span class="math inline">\(v_j = \Delta s_j / \Delta t_j\)</span>.</li>
<li>시속 60 km 초과 segment 는 위치 잡음으로 버린다.</li>
<li>배 한 척당 두 숫자: <strong>시간가중 평균속도</strong> <span class="math inline">\(\bar v = \sum v_j \Delta t_j / \sum \Delta t_j\)</span> 와 <strong>멈춤 비율</strong> = (<span class="math inline">\(v &lt; 5\)</span> km/h 인 시간)/(전체 시간).</li>
<li>각각 시기 평균 차 → 이름표 섞기.</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_908.png" class="img-fluid figure-img"></p>
<figcaption>셋째 줄의 해부. ① 도해의 그 gas 트랙의 segment 속도: 26시간 항해 후 92시간짜리 0 근처 막대 — 정박이 숫자로 보인다. ② 시기별 멈춤 비율 분포: Before 는 0 에 몰려 있고(멈춤 없이 통과) After 는 오른쪽으로 두껍다 — shift +0.14, p = 0.0024, 압도적.</figcaption>
</figure>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>v    <span class="ot">&lt;-</span> ds <span class="sc">/</span> (dt<span class="sc">/</span><span class="dv">3600</span>); keep <span class="ot">&lt;-</span> v <span class="sc">&lt;</span> <span class="dv">60</span>          <span class="co"># segment 속도, 잡음 컷</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>vbar <span class="ot">&lt;-</span> <span class="fu">sum</span>(v[keep]<span class="sc">*</span>dt[keep]) <span class="sc">/</span> <span class="fu">sum</span>(dt[keep])   <span class="co"># 시간가중 평균속도</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>stpf <span class="ot">&lt;-</span> <span class="fu">sum</span>(dt[v <span class="sc">&lt;</span> <span class="dv">5</span>]) <span class="sc">/</span> <span class="fu">sum</span>(dt)                <span class="co"># 멈춤·표류 시간 비율</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># → 두 지표의 시기 평균차를 이름표 섞기:  p = 0.0002 / 0.0024 — 압도적</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>H.</strong> 정리하면 — 세 검정 모두 재료를 “배 한 척 = 숫자 하나”로 줄인 뒤 같은 이름표 섞기에 올린 거예요. 그런데 첫째 줄은 100개 숫자를 PC1 하나로 줄이며 위치·모양·운동학이 뒤섞였고, 둘째 줄은 모양의 아주 좁은 단면(거칠기)만 봤고, 셋째 줄은 운동학만 정확히 겨눴죠. 이 비대칭이 다음 퍼즐로 이어집니다.</p>
<div class="callout callout-style-default callout-note callout-titled" title="상세 스펙 (재현용) — 세 검정의 정확한 설정">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>상세 스펙 (재현용) — 세 검정의 정확한 설정
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>공통: 시기 라벨 permutation, 양측, “전쟁 전/위기 후” 표본 크기 고정 재배정. 좌표는 경도·위도 → 중심위도 보정 equirectangular 로 km 변환.</p>
<ol type="1">
<li><strong>원좌표 MFPCA</strong> — 궤적별 호길이(arc-length) 재매개화 → 공통 격자 보간 → B-spline 기저 전개 → 다변량 FPCA (Ramsay–Silverman; Happ–Greven). 상위 2개 성분이 총분산 72.6% (상위 3개 81.1%). 통계량 = 제1주성분 점수의 시기 간 평균 차 (<span class="math inline">\(\Delta\xi_1 = -87.85\)</span>). Permutation <span class="math inline">\(B = 5000\)</span> → <span class="math inline">\(p = 0.129\)</span>.</li>
<li><strong>곡률 (TAC)</strong> — order-6 B-spline 평활 (기저 20개, 4계 도함수 벌점, GCV 로 <span class="math inline">\(\lambda\)</span> 선택), 점 6개 이상·경로 1 km 이상 트랙만. 곡률 <span class="math inline">\(\kappa(s) = (x'y'' - y'x'')/(x'^2+y'^2)^{3/2}\)</span> → 트랙별 총절대곡률(TAC)·최댓값·95백분위. 통계량 = TAC 시기 평균 차. Permutation → <span class="math inline">\(p = 0.349\)</span> (선종별 층화도 전부 null).</li>
<li><strong>속도·정박 scalar</strong> — segment 속도 = 거리/시간 (암시 속도 60 km/h 초과 segment 는 위치 잡음으로 폐기). 트랙별 시간가중 평균속도 (위기 후 <span class="math inline">\(-5.32\)</span> km/h) 와 멈춤·표류 시간비율 (속도 <span class="math inline">\(&lt;5\)</span> km/h 기준, <span class="math inline">\(+0.155\)</span>). 각각 permutation → 둘 다 <span class="math inline">\(p &lt; 10^{-4}\)</span>. 층화: cargo <span class="math inline">\(p&lt;10^{-4}\)</span>, gas <span class="math inline">\(p=0.0015\)</span>, tanker <span class="math inline">\(p=0.95\)</span>.</li>
</ol>
<p>전체 명세는 본 논문 부록 A 참조.</p>
</div>
</div>
</div>
<p><strong>G.</strong> 알겠어요. 그런데 그러니까 더 이상한데요. 속도가 그렇게 확실하게 바뀌었으면, 궤적 전체를 보는 첫 번째 검정도 잡아냈어야 하는 거 아니에요?</p>
<p><strong>H.</strong> 그렇죠! 그게 이 논문의 출발점이에요. 문제는 통계가 아니라 <strong>표현</strong>에 있었어요. 궤적을 <span class="math inline">\((x(t), y(t))\)</span> — “시각 <span class="math inline">\(t\)</span> 에 어디 있었다” — 로 적으면, 서로 다른 세 가지 정보가 한 그릇에 섞여요. <strong>어디로</strong> 갔는지, <strong>어떤 모양의 길</strong>이었는지, 그 길을 <strong>어떻게</strong> 지나갔는지.</p>
<p><strong>G.</strong> 섞이면 왜 문제죠?</p>
<p><strong>H.</strong> 강한 신호가 조용한 신호에 희석돼요. 라디오 세 채널을 한 스피커로 동시에 틀면, 제일 큰 방송도 웅웅거리는 소음이 되잖아요. <span class="math inline">\(p = 0.129\)</span> 라는 애매한 숫자가 바로 그 웅웅거림이에요.</p>
<hr>
</section>
</section>
<section id="에피소드-2-출근길의-세-가지-변화" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-2-출근길의-세-가지-변화">에피소드 2: 출근길의 세 가지 변화</h2>
<p><strong>H.</strong> 그래서 궤적을 딱 세 조각으로, 겹치지도 빠지지도 않게 분해합니다. 출근길로 비유해 볼게요. 어느 날 당신의 출근이 평소와 달라졌다면, 논리적으로 세 가지 경우예요.</p>
<p><strong>G.</strong> 음… 첫째, 아예 <strong>다른 동네 길</strong>로 갔다.</p>
<p><strong>H.</strong> 그게 <strong>위치(position)</strong> — 수학적으로는 경로의 중심점 <span class="math inline">\(c\)</span>. 둘째?</p>
<p><strong>G.</strong> 같은 동네인데 <strong>길의 생김새</strong>가 달랐다. 직진하던 걸 빙 둘러 갔다든가.</p>
<p><strong>H.</strong> <strong>모양(shape)</strong> — 중심을 빼고 남은 경로의 형태 <span class="math inline">\(\tilde\beta(s)\)</span>. 셋째가 제일 재밌어요.</p>
<p><strong>G.</strong> 완전히 같은 길인데… <strong>막혀서 서 있었다</strong>?</p>
<p><strong>H.</strong> 정확해요. <strong>운동학(kinematics)</strong> — 같은 길 위에서 시간을 어떻게 썼는가. 이 세 번째를 재는 도구가 이 논문의 심장인데, 이름이 <strong>점유밀도</strong> <span class="math inline">\(\tau(s)\)</span> 예요. 길을 100 구간으로 나누고, 각 구간에서 보낸 시간의 비율을 재는 거죠. 막힘 없이 일정한 속도로 지나가면 <span class="math inline">\(\tau\)</span> 는 어디서나 1로 평평해요. 어딘가에서 멈춰 서 있으면? 그 지점에 뾰족한 봉우리가 솟아요.</p>
<p><strong>G.</strong> 택배 트럭 GPS 로 “어디서 오래 서 있었나” 지도 그리는 느낌이네요.</p>
<p><strong>H.</strong> 딱 그거예요. 그리고 수학적으로 예쁜 게 두 가지 있어요. 하나 — 위치와 모양은 <strong>피타고라스 정리처럼 정확히 직교</strong>해요. 겹침이 0이라는 걸 증명할 수 있어요. 둘 — <span class="math inline">\(\tau\)</span> 는 확률밀도라서 <span class="math inline">\(\sqrt{\tau}\)</span> 를 취하면 <strong>구면 위의 점</strong>이 되고, 구면 기하학의 도구(평균, 거리, PCA)가 전부 공짜로 따라와요.</p>
<p><strong>G.</strong> “증명할 수 있다”고 하셨는데 — 진짜 증명이 논문에 있어요? 어렵나요?</p>
<p><strong>H.</strong> 본 논문의 <strong>명제 1</strong>이고, 증명이 세 줄이에요. 그대로 옮겨볼게요.</p>
<blockquote class="blockquote">
<p><strong>명제 (직교 분할).</strong> 두 배의 격자 경로를 <span class="math inline">\(\beta_1 = c_1 + \tilde\beta_1\)</span>, <span class="math inline">\(\beta_2 = c_2 + \tilde\beta_2\)</span> 로 분해하면, 경로 간 거리의 제곱은 정확히 두 조각의 합이다: <span class="math display">\[\underbrace{\tfrac{1}{M}\textstyle\sum_k \lVert \beta_1(s_k) - \beta_2(s_k) \rVert^2}_{\text{경로 간 거리}^2} \;=\; \underbrace{\lVert c_1 - c_2 \rVert^2}_{\text{위치 차}^2} \;+\; \underbrace{\tfrac{1}{M}\textstyle\sum_k \lVert \tilde\beta_1(s_k) - \tilde\beta_2(s_k) \rVert^2}_{\text{모양 차}^2}.\]</span></p>
<p><strong>증명.</strong> 좌변에 <span class="math inline">\(\beta_1 - \beta_2 = (c_1 - c_2) + (\tilde\beta_1 - \tilde\beta_2)\)</span> 를 넣고 제곱을 전개하면 <span class="math display">\[\lVert c_1 - c_2 \rVert^2 \;+\; 2\,\Bigl\langle c_1 - c_2, \; \tfrac{1}{M}\textstyle\sum_k \bigl( \tilde\beta_1(s_k) - \tilde\beta_2(s_k) \bigr) \Bigr\rangle \;+\; \tfrac{1}{M}\textstyle\sum_k \lVert \tilde\beta_1(s_k) - \tilde\beta_2(s_k) \rVert^2 .\]</span> 가운데 교차항의 <span class="math inline">\(\sum_k \tilde\beta_i(s_k)\)</span> 는 <strong>정의상 0</strong> 이다 — <span class="math inline">\(\tilde\beta\)</span> 는 평균(무게중심)을 빼서 만든 것이므로 평균이 0. 상수 벡터와 평균 0 벡터의 내적이 사라지니 교차항이 통째로 죽고, 남는 것이 우변. <span class="math inline">\(\blacksquare\)</span></p>
</blockquote>
<p><strong>G.</strong> 아, <span class="math inline">\((a+b)^2 = a^2 + b^2\)</span> 이 되려면 <span class="math inline">\(2ab\)</span> 가 죽어야 하는데, 중심을 뺐다는 사실 자체가 <span class="math inline">\(2ab\)</span> 를 죽이는군요.</p>
<p><strong>H.</strong> 그게 전부예요. 그래서 “겹침이 0”이라는 말이 은유가 아니라 등식이에요 — 위치로 잰 차이와 모양으로 잰 차이는 서로의 몫을 침범할 수 없어요. 아까 두 척 도해에서 39 km(위치)와 “포개진 뒤의 잔차”(모양)가 정확히 이 두 항입니다.</p>
<p><strong>G.</strong> 잠깐, 배가 완전히 멈추면요? 속도가 0이면 “시간 나누기 거리” 같은 계산이 터질 텐데.</p>
<p><strong>H.</strong> 좋은 지적이고, 실제로 초기 버전의 이론이 거기서 구멍이 났었어요. 그래서 밀도가 아니라 <strong>측도</strong>로 정의를 올렸어요 — 멈춤은 수학적으로 한 점에 질량이 뭉친 “atom”이 되고, 이론이 자연스럽게 품어요. 정박이 이 연구의 주인공인데, 주인공이 서는 자리에서 무대가 무너지면 안 되잖아요.</p>
<hr>
</section>
<section id="에피소드-3-저울을-믿을-수-있나-거짓말-탐지기-테스트" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-3-저울을-믿을-수-있나-거짓말-탐지기-테스트">에피소드 3: 저울을 믿을 수 있나 — 거짓말 탐지기 테스트</h2>
<p><strong>G.</strong> 세 조각으로 나눴다 치고, 이제 “위기 효과의 몇 %가 어느 조각인가”를 재는 거죠? 그 저울은 믿을 만해요?</p>
<p><strong>H.</strong> 그걸 확인하려고 <strong>답을 미리 아는 가짜 데이터</strong>를 만들었어요. 컴퓨터로 합성 항적을 수백 번 생성하는데, 어떤 실험에서는 위치만 옮기고, 어떤 실험에서는 모양만 바꾸고, 어떤 실험에서는 진입로에서 기다리게만 해요. 그리고 저울이 뭐라고 하는지 봐요.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>진실 (내가 만든 조작)</th>
<th>저울의 판정</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>위치만 옮김</td>
<td>위치 <strong>99%</strong>, 나머지 “변화 없음”</td>
</tr>
<tr class="even">
<td>모양만 바꿈</td>
<td>모양 <strong>98%</strong>, 나머지 “변화 없음”</td>
</tr>
<tr class="odd">
<td>기다리게만 함</td>
<td>운동학이 100번 중 100번 검출</td>
</tr>
<tr class="even">
<td><strong>아무것도 안 바꿈</strong></td>
<td>셋 다 “변화 없음” (오탐율 4~5%, 정확히 설계값)</td>
</tr>
</tbody>
</table>
<p><strong>G.</strong> 아무것도 안 바꿨을 때 오탐율이 5%라는 건…</p>
<p><strong>H.</strong> “유의수준 5%” 검정이 정말 5%로 작동한다는 뜻이에요. 광고와 실제가 일치하는 저울. 그리고 하나 더 — 실제 데이터는 1,006척 대 67척으로 심하게 기울어져 있잖아요? 그 <strong>15:1 불균형을 그대로 재현한 실험</strong>에서도 검출력 100%였어요. 이제 진짜 데이터에 올려놔도 됩니다.</p>
<hr>
</section>
<section id="에피소드-4-판결-63-31-6" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-4-판결-63-31-6">에피소드 4: 판결 — 63 / 31 / 6</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_901.png" class="img-fluid figure-img"></p>
<figcaption>위기 효과의 3-수준 귀속. 세 채널 모두 통계적으로 유의하지만, 크기는 위치 ≫ 모양 ≫ 운동학.</figcaption>
</figure>
</div>
<p><strong>H.</strong> 호르무즈 실데이터의 판결입니다. 위기가 관측된 항적에 남긴 변화 중 —</p>
<ul>
<li><strong>위치 63%</strong> — 배들이 다른 lane 으로 갔다. 물리량으로는 경로 중심이 평균 <strong>북쪽으로 18.6 km, 동쪽으로 12.7 km</strong> 이동. 오만 쪽 깊은 물길에서 이란 쪽 얕은 물길로 옮겨간 거예요. NYT 기사의 헤드라인이 숫자 하나로 정량화된 셈이죠.</li>
<li><strong>모양 31%</strong> — 위치를 빼고도 경로의 형태 자체가 달라졌다.</li>
<li><strong>운동학 6%</strong> — 그리고 시간을 쓰는 방식이 달라졌다. 작지만, 셋 중 어느 것도 우연이 아니에요(전부 <span class="math inline">\(p \le 0.003\)</span>).</li>
</ul>
<p><strong>G.</strong> 어라, 그런데 에피소드 1에서는 속도 쪽 검정이 제일 확실했잖아요(<span class="math inline">\(p &lt; 10^{-4}\)</span>). 막상 크기를 재보니 6%로 제일 작다고요?</p>
<p><strong>H.</strong> 그게 오늘의 펀치라인이에요. <strong>“가장 확실한 신호”와 “가장 큰 신호”는 다른 말입니다.</strong> p-value 는 “이게 우연일 리 없다”는 확신의 정도지, 효과의 크기가 아니에요. 아주 또렷하게 들리는 소리가 꼭 제일 큰 소리는 아닌 거죠. 세 채널을 같은 잣대(각자의 평소 변동 대비)로 재고 나서야 “얼마나”를 말할 수 있게 된 겁니다.</p>
<hr>
</section>
<section id="에피소드-5-시간이-고인-곳" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-5-시간이-고인-곳">에피소드 5: 시간이 고인 곳</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_902.png" class="img-fluid figure-img"></p>
<figcaption>시기별 평균 점유밀도. 점선(τ=1)이 등속 통과. 위기 이후(주황)는 경로의 서쪽 끝에서 τ≈7 — 등속의 7배에 달하는 시간이 그 구간에 쌓였다.</figcaption>
</figure>
</div>
<p><strong>H.</strong> 6%짜리 운동학 채널을 열어보면 이야기가 선명해요. 전쟁 전(파랑)의 <span class="math inline">\(\tau\)</span> 는 거의 평평 — 배들이 막힘 없이 흘렀다는 뜻. 위기 이후(주황)는 경로의 서쪽 끝, 그러니까 <strong>페르시아만 쪽 입구에 등속 대비 7배의 시간</strong>이 고여 있어요.</p>
<p><strong>G.</strong> 반론 하나요. 이 데이터는 관측된 구간만 있는 거잖아요. “경로의 시작점에 시간이 몰렸다”는 게 그냥 데이터가 거기서부터 기록되기 시작해서 생긴 착시일 수도 있지 않나요?</p>
<p><strong>H.</strong> 저자가 자기 결과에 던져야 할 바로 그 질문이고, 지리로 답할 수 있어요. 위기 이후 항적들의 서쪽 끝점이 데이터 커버리지 경계에서 <strong>중앙값 16.4 km 안쪽</strong>에 있어요. 전쟁 전엔 3.6 km — 즉 예전엔 경계에서 관측이 시작됐는데, 위기 후엔 <strong>내부의 정박지에서</strong> 시작돼요. 기록이 끊긴 자리가 아니라 배가 실제로 떠 있던 자리라는 거죠. “만 안에 900척이 발이 묶였다”던 당시 보도와도 맞아떨어지고요.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_903.png" class="img-fluid figure-img"></p>
<figcaption>시간이 고인 곳의 지도. 주황 점 = 각 배가 시간을 집중적으로 쓴 지점. 전쟁 전(왼쪽)은 항로 전반에 옅게, 위기 이후(오른쪽)는 이란 측 북쪽 arc 에 집중.</figcaption>
</figure>
</div>
<p><strong>H.</strong> 선종별로 갈라 보면 또 재밌어요. 유조선(tanker)은 거의 순수하게 “다른 길”만 택했어요 — 위치 71%, 기다림 신호는 없음. 그런데 <strong>LNG 운반선(gas)은 운동학이 20%</strong> — 다른 배들의 세 배예요. LNG 는 단순히 이사한 게 아니라, <strong>기다리는 항해</strong>가 된 겁니다.</p>
<p><strong>G.</strong> 카타르 LNG… 안 갈 수는 없고, 그렇다고 예전처럼 갈 수도 없고.</p>
<p><strong>H.</strong> 데이터가 그 딜레마를 그대로 보여주는 거죠.</p>
<hr>
</section>
<section id="에피소드-6-그-6를-파고들면-세웠나-늦췄나" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-6-그-6를-파고들면-세웠나-늦췄나">에피소드 6: 그 6%를 파고들면 — 세웠나, 늦췄나</h2>
<p><strong>G.</strong> 잠깐, 운동학 6% 로 넘어가기 전에요. 에피소드 1에서 “속도 −5 km/h”랑 “멈춤 비율 +0.14”를 따로 봤잖아요. 근데 그 둘은 사실 얽힌 거 아니에요? 배가 서 있으면 평균속도는 당연히 떨어질 텐데.</p>
<p><strong>H.</strong> 정확한 지적이고, 그게 이 에피소드 전체예요. 진짜 질문은 이거죠 — <strong>평균속도가 떨어진 게 전부 “세워놔서”인가, 아니면 움직일 때도 느려졌나?</strong> 이걸 가르는 항등식이 하나 있어요. 세 줄이면 유도돼요.</p>
<p>시간가중 평균속도의 정의에서, 항해 시간을 정박(<span class="math inline">\(v&lt;5\)</span>km/h)과 순항으로 나누면:</p>
<p><span class="math display">\[\bar v = \frac{\int v\, dt}{T} = \underbrace{\frac{\int_{\text{순항}} v\, dt}{T_{\text{순항}}}}_{\mu_c\;(\text{순항속력})} \times \underbrace{\frac{T_{\text{순항}}}{T}}_{1 - S}\]</span></p>
<p><strong>평균속도 = 순항속력 × 움직인 시간 비율.</strong> 배 한 척마다 이 셋을 재서 찍어보면:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_14.png" class="img-fluid figure-img"></p>
<figcaption>항등식의 실데이터 검증. 배 한 척이 점 하나 — 가로축 “움직인 시간 비율”, 세로축 평균속도. 점들이 원점 통과 직선에 정렬되고(cor = 0.999), 직선의 기울기가 곧 순항속력이다. 위기의 효과는 두 겹: 주황 점들이 왼쪽으로 몰리고(정박↑), 주황 직선의 기울기 자체가 낮다(순항 감속).</figcaption>
</figure>
</div>
<p><strong>G.</strong> 점들이 진짜 직선 위에 올라앉네요. 그리고 주황 직선이 파랑보다 <strong>기울기가 낮아요.</strong></p>
<p><strong>H.</strong> 그게 답이에요. 위기의 효과가 두 겹으로 보이죠 — 점들이 <strong>왼쪽으로</strong>(정박이 늘어 움직인 시간 비율이 줄고), 동시에 직선 <strong>기울기 자체가 아래로</strong>(순항속력이 떨어짐). 이 둘을 숫자로 가르면:</p>
<p><span class="math display">\[\Delta\bar v = -4.95 \;=\; \underbrace{-2.75}_{\text{정박 증가 }48\%} + \underbrace{-2.99}_{\text{순항 감속 }52\%}\]</span></p>
<p>솔직히 고백하면, 저는 분석 전에 “위기는 배를 <strong>세워놨을 뿐</strong>, 움직이는 배는 평소 속력일 것”이라 예측했어요. <strong>반증됐어요.</strong> 순항속력이 20.0 → 16.0 km/h, 움직이는 배도 <strong>20% 느려졌습니다.</strong> (긴 관측창이 정박과 순항을 평균내버린 착시 아니냐 — 관측창 1시간·2시간으로 잘라도, 정박 임계 3·5·8 km/h 어디로 잡아도 그대로예요.) 왜 느려졌는지는 데이터가 말 안 해줘요 — 전투해역 경계 항행, 이란 측 얕은 수로의 속도 제약, 전쟁보험 조건… 거기부턴 추측입니다.</p>
<p><strong>G.</strong> 근데 유조선은 아무것도 안 변했다면서요. 에피소드 5에서.</p>
<p><strong>H.</strong> 바로 그 유조선이 이 항등식의 백미예요. 선종별로 갈라 볼게요.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_15.png" class="img-fluid figure-img"></p>
<figcaption>평균속도 하락의 성분 분해, 전체와 선종별. cargo·gas 는 정박과 감속이 함께(정박 우세), tanker 는 정박이 오히려 줄어 감속과 상쇄 — 총량 Δv̄ 이 0 처럼 보였던 이유.</figcaption>
</figure>
</div>
<p>유조선은 총 평균속도로는 −0.7, 통계적으로 아무 일도 없었어요. <strong>그런데 분해하니</strong>: 유조선은 정박을 <strong>오히려 줄이면서</strong>(멈추지 않고 통과) 순항속력은 <strong>유의하게 낮췄어요</strong>(−2.0, p=0.003). 두 효과가 정반대라 총량에서 상쇄돼 사라져 있던 거예요.</p>
<p><strong>G.</strong> 합계가 0이라고 아무 일도 없었던 게 아니네요.</p>
<p><strong>H.</strong> 그게 이 에피소드의 교훈이에요. <strong>0은 “변화 없음”과 “상쇄” 두 가지 뜻이 있고, 항등식 분해가 그 둘을 갈라줍니다.</strong> cargo·gas 는 정박과 감속이 같은 방향(정박 우세)이라 총량에 그대로 나타났고, gas 는 여기서도 최대 타격 — 에피소드 5의 “gas 운동학 20%”와 정확히 교차 정합하죠.</p>
<hr>
</section>
<section id="에피소드-7-위기는-어느-방향으로-밀었나-영상처럼-보기" class="level2">
<h2 class="anchored" data-anchor-id="에피소드-7-위기는-어느-방향으로-밀었나-영상처럼-보기">에피소드 7: 위기는 어느 방향으로 밀었나 — 영상처럼 보기</h2>
<p><strong>G.</strong> 여기까지는 세 채널을 <strong>따로</strong> 봤잖아요. 위치 63, 모양 31, 운동학 6. 근데 궁금한 게 — 그 셋이 <strong>함께</strong> 움직였나요? 북쪽으로 옮긴 배가 동시에 더 기다렸나, 아니면 옮긴 배 따로 기다린 배 따로예요?</p>
<p><strong>H.</strong> 그게 “영상 자료”의 질문이에요. 배 한 척의 완전한 기록은 위치 목록이 아니라 <strong>움직이는 점의 동영상</strong>이니까. 그런데 따로 본 분해로는 이 질문에 답을 못 해요 — 채널을 직교로 갈라놨으니, 채널 <strong>사이</strong>의 상관은 설계상 버린 거거든요.</p>
<p><strong>G.</strong> 그럼 다시 붙여야겠네요.</p>
<p><strong>H.</strong> 붙이되 영리하게요. 동영상을 그냥 <span class="math inline">\((x(t), y(t))\)</span> 로 PCA 하면 에피소드 1의 그 표현 문제로 되돌아가요. 그래서 시간을 좌표로 <strong>뒤집어요</strong>: 매개변수를 줄자 <span class="math inline">\(s\)</span> 로 두고, 시간은 세 번째 좌표 <span class="math inline">\(F(s)\)</span> = “경로의 <span class="math inline">\(s\)</span> 지점까지 쓴 시간의 비율”로 올려요. (<span class="math inline">\(F\)</span> 는 에피소드 5의 <span class="math inline">\(\tau\)</span> 를 누적한 것 — 같은 정보인데 이제 위치·모양과 같은 [0,1] 위에 살죠.) 이 세 개를 한꺼번에 PCA 하면, 각 주성분(변동 모드)이 기하·시간에 걸쳐 있는지를 볼 수 있어요.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_10.png" class="img-fluid figure-img"></p>
<figcaption>Joint MFPCA 의 상위 8개 모드. 색 = 모드의 정체(초록 기하 / 분홍 결합), 진하기 = 시기분리 유의성. 변동의 대부분이 결합 모드이고, 위기와 유의하게 연관된 것은 PC2 와 PC5 뿐이다.</figcaption>
</figure>
</div>
<p><strong>H.</strong> 두 가지가 보여요. 하나 — 평시 배들의 변동은 대부분 <strong>결합 모드</strong>예요(분홍). “어디로 가는 배”와 “어디서 시간 쓰는 배”가 원래 얽혀 있다는 뜻이죠. 둘 — 그 많은 모드 중 <strong>위기와 연관된 건 딱 둘</strong>(PC2, PC5).</p>
<p><strong>G.</strong> 어? 제일 큰 모드(PC1, 38%)는 위기랑 상관없어요?</p>
<p><strong>H.</strong> 그게 반전이에요.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_11.png" class="img-fluid figure-img"></p>
<figcaption>PC1 (분산 38%) 의 해부. 왼쪽: 경로 성분. 오른쪽: 시간 성분 F(s) — +2sd 는 초반에 시간을 쓰는 배, −2sd 는 후반에 쓰는 배. 이 거대한 얽힘 축은 위기 전에도 후에도 존재한다 (p=0.22).</figcaption>
</figure>
</div>
<p><strong>H.</strong> 가장 큰 변동 축 PC1 은 “여정 초반에 시간 쓰는 배 vs 후반에 쓰는 배”인데 — 위기와 <strong>무관</strong>해요(p=0.22). 평시 해협 교통의 자연스러운 다양성이죠. 위기 이야기를 하려면 이 거대한 배경 변동을 걷어내야 하고, 그러고 나면 위기가 민 진짜 방향이 드러나요.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_12.png" class="img-fluid figure-img"></p>
<figcaption>PC2 (분산 25%, p=0.001) 의 해부. 위기 쪽(+2sd, 주황)은 경로가 동쪽으로 치우치고 동단이 남쪽으로 꺾이며(왼쪽), 동시에 여정 초반에 시간을 몰아 쓴다(오른쪽, 대각선 위 볼록). 기하와 시간이 한 방향으로 묶여 있다.</figcaption>
</figure>
</div>
<p><strong>H.</strong> 위기가 민 방향 PC2 는 기하 69% + 시간 31% 의 <strong>진짜 결합 모드</strong>예요. 위기 쪽으로 가면 경로가 옮겨가고(왼쪽), <strong>동시에</strong> 여정 초반에 시간을 몰아 써요(오른쪽, 대각선 위로 볼록 = 초반 대기). 즉 —</p>
<p><strong>G.</strong> 에피소드 4의 “경로 이동”이랑 에피소드 5의 “진입부 대기”가… 따로가 아니라 <strong>한 방향</strong>이었네요.</p>
<p><strong>H.</strong> 그거예요. 위기 이후 배들은 경로 바꾼 배 따로, 기다린 배 따로가 아니라, <strong>바뀐 경로로 다니면서 초반에 기다리는 항해</strong>를 했어요. 따로 본 두 결론이 같은 배들에서 묶여 일어났다는 걸, 붙여 봐야 알 수 있는 거죠.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="attachments/260722_a8979b_13.png" class="img-fluid figure-img"></p>
<figcaption>위기 평면. 위기(주황)는 전체 변동의 최대축(PC1)이 아니라 PC2×PC5 평면에서 분리된다.</figcaption>
</figure>
</div>
<p><strong>H.</strong> 한 줄로: <strong>따로 보기(에피소드 2–6)가 “회계”라면, 붙여 보기(이 에피소드)는 “스토리”예요.</strong> 회계는 몫을 정확히 나누고, 스토리는 그 몫들이 어떻게 한 사건으로 묶였는지 말해줘요.</p>
<hr>
</section>
<section id="맺음-결국-자료를-무엇으로-보느냐" class="level2">
<h2 class="anchored" data-anchor-id="맺음-결국-자료를-무엇으로-보느냐">맺음: 결국, 자료를 무엇으로 보느냐</h2>
<p><strong>G.</strong> 오늘 하루 종일 같은 데이터를 계속 다르게 봤잖아요. 정리하면요?</p>
<p><strong>H.</strong> 이 프로젝트 전체가 사실 한 문장이에요 — <strong>“같은 자료라도 무엇으로 표현하느냐가 답을 정한다.”</strong> 우리가 오늘 쓴 표현들을 늘어놓으면:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>표현</th>
<th>무엇으로 보나</th>
<th>답하는 질문</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>원좌표 <span class="math inline">\((x(t),y(t))\)</span></td>
<td>시간 위의 점</td>
<td>(섞여서 애매함 — 에피소드 1)</td>
</tr>
<tr class="even">
<td>3-채널 <span class="math inline">\((c, \tilde\beta, \tau)\)</span></td>
<td>위치 ⊕ 모양 ⊕ 시간배분</td>
<td>무엇이 얼마나? → 63/31/6</td>
</tr>
<tr class="odd">
<td>2-상태 항등식</td>
<td>순항 × 대기</td>
<td>세웠나 늦췄나? → 48/52</td>
</tr>
<tr class="even">
<td>joint <span class="math inline">\((x,y,F)\)</span></td>
<td>3변량 동영상</td>
<td>채널들이 어떻게 얽혔나? → PC2</td>
</tr>
</tbody>
</table>
<p>똑같은 배 1,073척인데, 물음을 바꿀 때마다 표현을 갈아탔고, 표현마다 다른 진실을 내줬어요. 원좌표에서는 웅웅거리던 신호가, 쪼개니 63/31/6 으로 또렷해지고, 다시 붙이니 “경로+대기가 한 방향”이라는 스토리가 나오고.</p>
<p><strong>G.</strong> 그럼 “정답 표현”이 있는 건 아니네요.</p>
<p><strong>H.</strong> 없어요. <strong>질문이 표현을 고르는</strong> 거지, 그 반대가 아니에요. 그게 이 연구의 진짜 교훈이고 — 데이터를 앞에 두고 제일 먼저 물어야 할 건 “무슨 검정을 돌릴까”가 아니라 “이걸 <strong>무엇으로 볼까</strong>”예요.</p>
<p><strong>G.</strong> 마지막 한 줄?</p>
<p><strong>H.</strong> 호르무즈 위기는 <strong>63% 이사였고, 31% 변형이었고, 6% 기다림이었다.</strong> 그 6% 안에서 배들은 세워지기도 했고 느려지기도 했고 — 유조선처럼 둘이 상쇄돼 안 보이기도 했고. 그리고 그 모든 변화는, 붙여 놓고 보면, <strong>같은 한 방향으로 묶여</strong> 있었어요. 다만 이 모든 건 <strong>보이는 배들</strong> 이야기예요. AIS 를 끄고 어둠으로 들어간 배는 여전히 표본 밖이고 — 그게 다음 이야기입니다.</p>
<blockquote class="blockquote">
<p><em>(화면의 실타래 지도가 천천히 어두워진다. 주황 점들만 남는다.)</em></p>
</blockquote>
<hr>
<p><strong>바탕 논문</strong>: 『Where Does the Signal Live? — A Three-Level Decomposition of Vessel Trajectory Ensembles in the Strait of Hormuz』 v0.5 (<code>COMPANY/</code> 등록) · <strong>코드</strong>: <code>260703</code>·<code>260708_인연_*_R.R</code> (분해·검정·2상태·joint MFPCA) · 본 통합본은 앞선 네 편의 연구 노트를 하나로 엮은 것.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>